### PR TITLE
Fixed: descendant combinator in `selector-descendant-combinator-no-non-space` and `selector-combinator-space-before/after`

### PR DESCRIPTION
**Pull request by evilebottnawi**
> Which issue, if any, is this issue related to?

#2506

> Is there anything in the PR that needs further explanation?

No, it's self explanatory.

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@jeddy3 I'm right now take their implementation (btw i think drop `styleSearch` in this rules and use `postcss-selector-parser`)

**Comment by jeddy3** [comment]
> (btw i think drop styleSearch in this rules and use postcss-selector-parser)

Let's only do that if it adds something e.g. clarity or performance etc.

If the `selector-combinator-space-*` rules work for `>>>` with a simple change the punctuation reference, then let's stick with that for now.

**Comment by evilebottnawi** [comment]
@jeddy3 not working as expected because we have `>` and `>>>` and `styleSearch` found `>` :sob:

**Comment by evilebottnawi** [comment]
Sorry for big commit, but i think it should be done together
One note: `selector-combinator-space-before/after` don't support `/deep/` (and other reference selectors) (because `postcss-selector-parse` don't works with their, theoretically we can write `isReferenceSelector`). I think we can leave this commit as it is and next commit i can see how handle `reference` selectors in this rules (maybe need see other rules).

/cc @jeddy3

**Comment by jeddy3** [comment]
> One note: selector-combinator-space-before/after don't support /deep/ (and other reference selectors) 

Yes, that's fine. Enforcing spacing around `/deep/` will need to be a separate issue as it's a breaking change - feel free to create a new issue for this. The changes in this PR are fixes so that `>>>` isn't mistaken for `>`.

**Comment by evilebottnawi** [comment]
@jeddy3 it think issue already created https://github.com/stylelint/stylelint/issues/2506, even the name it shows :smile:

**Comment by davidtheclark** [comment]
Added to changelog:

> -   Fixed: `selector-descendant-combinator-no-non-space` and `selector-combinator-space-before/after` now understand and check `>>>` shadow-piercing combinator ([#2509](https://github.com/stylelint/stylelint/pull/2509)).

**Pull request merged**
