### PR TITLE
Reconfigure ESLint with bumping eslint-config-stylelint to 20.0.0

### PR DESCRIPTION
**Pull request by ybiquitous**
> Which issue, if any, is this issue related to?

None.

> Is there anything in the PR that needs further explanation?

Summary:

- Remove redundant `globals`.
- Make `testRule*` globals [readonly](https://eslint.org/docs/latest/use/configure/language-options#using-configuration-files-1).
- Turn on `n/prefer-global/process` to disallow global `process` for consistency.
  See https://github.com/eslint-community/eslint-plugin-n/blob/v11.1.0/docs/rules/prefer-global/process.md

Note:

Global variables are often harmful. Unlike global variables defined in standard specs (ECMAScript or WHATWG etc.),
`process` is unique to Node.js. This may be a problem when running Stylelint on other platforms.

So, I prefer using `process` through the module system. But this is just my opinion. If anyone is against it, I'll withdraw this change.

### CODE REVIEW

**Comment by Mouvedia** [comment]
To be clear you just want to use `import process from 'node:process';`?

**Review by jeddy3 — COMMENTED** [review]
Having an explicit import SGTM.

**Comment by ybiquitous** [comment]
> To be clear, you just have to add `import process from 'node:process';`?

Yes, since there seem to be no objections, I'll add `import`. 👍🏼

**Comment by ybiquitous** [comment]
Fixed lint errors via 4aa84e418

**Comment by ybiquitous** [comment]
I've also opened upstream PR https://github.com/stylelint/eslint-config-stylelint/pull/233

**Review by jeddy3 — APPROVED** [review]
LGTM, thank you.

**Comment by ybiquitous** [comment]
> I'll update the shared config in this PR. 💪🏼

Done 141de20.

**Pull request merged**
