### PR TITLE
Add autofix to selector-max-empty-lines

### LINKED ISSUE #3611: Add autofix to selector-max-empty-lines
> What is the problem you're trying to solve?

Adds autofix of rules [defined in `stylelint-config-standard`](https://github.com/stylelint/stylelint-config-standard/blob/master/index.js) so that everyone can start using [`stylelint-config-standard`](https://github.com/stylelint/stylelint-config-standard) easily.

> What solution would you like to see?

Add autofix to [nselector-max-empty-lines](https://github.com/stylelint/stylelint/tree/master/lib/rules/selector-max-empty-lines)

### PR DESCRIPTION
**Pull request by Vizet**
> Which issue, if any, is this issue related to?

Closes #3611", added autofix to selector-max-empty-lines

> Is there anything in the PR that needs further explanation?

After fix number empty lines in a row <= max

### CODE REVIEW

**Comment by vankop** [comment]
@Vizet could you please add some tests with css comments? For instance,
```
.foo\r\n#this is comment\r\n{}
.foo\n#this is comment\n{}
.foo\n\n#this is comment\n\n#and this is comment too\n\n{}
```

**Comment by ntwb** [comment]
Some hints on how tests could be added to this PR can be taken from the `value-list-max-empty-lines` PR in #3814

**Comment by jeddy3** [comment]
Just a lint error to fix please:

> /home/travis/build/stylelint/stylelint/lib/rules/selector-max-empty-lines/index.js
> 71:13  error  Expected blank line before this statement  padding-line-between-statements

**Comment by Vizet** [comment]
> Just a lint error to fix please:
> 
> > /home/travis/build/stylelint/stylelint/lib/rules/selector-max-empty-lines/index.js
> > 71:13  error  Expected blank line before this statement  padding-line-between-statements

Sorry, i had old version repository. I rebased on master

**Comment by hudochenkov** [comment]
> -   Added: `selector-max-empty-lines` autofix ([#3717](https://github.com/stylelint/stylelint/pull/3717)).

**Pull request merged**
