### PR TITLE
Ignore color names in URLs in no-indistinguishable-colors

### PR DESCRIPTION
**Pull request by ntwb**
Ref #970

### CODE REVIEW

**Comment by ntwb** [comment]
The result of the failing test:

```shell
> rule: no-indistinguishable-colors
> config: true
> code: "a {\n  background-image: url(../images/white.png);\n  color: #fff;\n}"

not ok 7149 should be accepted
  ---
    operator: equal
    expected: 0
    actual:   1
    at: run (/Users/netweb/dev/stylelint/stylelint/node_modules/core-js/modules/es6.promise.js:104:47)
  ...
```

**Comment by evilebottnawi** [comment]
Look at the bug in css-colorguard
```js
const colorguard = require('colorguard');

colorguard.process('a {\n  background-image: url(../images/white.png);\n  color: #fff;\n}').then((result) => {
    console.log(result);
});
```

```shell
<input css 1>
  line 3  col 3  #fff collides with white  (2:34)

  ✖  1 collision found.
```

**Comment by evilebottnawi** [comment]
Created issue https://github.com/SlexAxton/css-colorguard/issues/39

**Comment by evilebottnawi** [comment]
@ntwb please rebase

**Comment by davidtheclark** [comment]
Patch released in colorguard 1.2.0. I updated the dependency here, so tests should pass, I think.

**Comment by ntwb** [comment]
Currently 4 tests failing with the `block-opening-brace-newline-before` rule:

```shell
ok 1683 should register one warning
ok 1684 should warn on line 2
ok 1685 should warn on column 3
ok 1686 should warn with message Expected newline before "{" (block-opening-brace-newline-before)
# 
> rule: block-opening-brace-newline-before
> config: "always"
> code: "a\n/* foo */{ a{ color: pink; } }"

not ok 1687 should register one warning
  ---
    operator: equal
    expected: 1
    actual:   2
  ...
ok 1688 should warn on line 2
not ok 1689 should warn on column 12
  ---
    operator: equal
    expected: 12
    actual:   9
  ...
ok 1690 should warn with message Expected newline before "{" (block-opening-brace-newline-before)
# 
> rule: block-opening-brace-newline-before
> config: "always"
> code: "a\r\n/* foo */{ a{ color: pink; } }"

not ok 1691 CRLF should register one warning
  ---
    operator: equal
    expected: 1
    actual:   2
  ...
ok 1692 CRLF should warn on line 2
not ok 1693 CRLF should warn on column 12
  ---
    operator: equal
    expected: 12
    actual:   9
  ...
ok 1694 CRLF should warn with message Expected newline before "{" (block-opening-brace-newline-before)
# 
> rule: block-opening-brace-newline-before
> config: "always-single-line"
> code: ""
```

Will take a closer look later today

**Comment by davidtheclark** [comment]
I must have messed up the commits. Will check again.

**Comment by ntwb** [comment]
> I must have messed up the commits. Will check again.

I'm actually getting this on `master`, not just this `bug-970` branch

Looking...

**Comment by ntwb** [comment]
So the last 4 builds / 4 pull requests have failed with the same errors:
• https://travis-ci.org/stylelint/stylelint/pull_requests
• https://travis-ci.org/stylelint/stylelint/builds

The last sucessful CI job was [stylelint/stylelint/builds/127029162](https://travis-ci.org/stylelint/stylelint/builds/127029162) which has related `block-opening-brace-newline-before/` tet changes seen here https://github.com/stylelint/stylelint/compare/423d6a17dede%5E...3050eb294e14

**Comment by davidtheclark** [comment]
Ok I will fix these PRs. Thanks and sorry.

**Comment by ntwb** [comment]
The 2 tests that _I think_ are failing are:

1. [block-opening-brace-newline-before/__tests__/index.js#L93](https://github.com/stylelint/stylelint/blob/master/src/rules/block-opening-brace-newline-before/__tests__/index.js#L93): `a\n/* foo */{ a{ color: pink; } }`
2. [block-opening-brace-newline-before/__tests__/index.js#L98](https://github.com/stylelint/stylelint/blob/master/src/rules/block-opening-brace-newline-before/__tests__/index.js#L98): `a\r\n/* foo */{ a{ color: pink; } }`

I'm off for some breakfast and ☕

**Comment by davidtheclark** [comment]
Oh I know what happened. The latest version of PostCSS, which Travis is getting, fixes a bug that we previously implicitly relied on.

**Comment by ntwb** [comment]
That fixed it, tests now passing in `master` and `bug-970` 👍

**Pull request merged**
