### PR TITLE
Add configFile option for postcss plugin API; closes #475

### LINKED ISSUE #475: Add configFile option to plugin options
With eslint, I can do this:
```
.pipe(eslint({configFile: '.eslintrc'}))
.pipe(eslint.format())
```

But with gulp I don't know what to do.
The only way I managed to do it, is giving a .json extension to the file and using require. But I would like to have the file without an extension, what can I do?
(if the file doesn't have an extension, the require function breaks..)
this works:
```
.pipe(postcss([
	stylelint(require('./stylelint.json'))
]))
```
this does not:
```
.pipe(postcss([
	stylelint(require('./stylelint'))
]))
```
neither this:
```
.pipe(postcss([
	stylelint({config: 'stylelint'))
]))
```

### PR DESCRIPTION
**Pull request by davidtheclark**
I'd appreciate help thoroughly testing that this works as anticipated and did not screw up anything else. @stylelint/owners, @luisfmsouza, @saviomd -- can any of you try it out in a few ways and see if you uncover any bugs?

### CODE REVIEW

**Comment by jeddy3** [comment]
Sorry, just got around to looking at this (was moving all my possessions from one place to another this weekend...). Thanks for tackling this one btw.

Is the expected behaviour to only load files with an `json` extension? Is this a limitation of the `require()` call? As it works a treat with relative and absolute json files, but throws a `configFile path "myconfig.js" corresponded to no file` error for relative and absolute `js` and `.stylelintrc` files.

**Comment by davidtheclark** [comment]
`require()` should load JSON and JS equally. Any chance the problem is just in your path? Did you try `./myconfig.js`? If your config prop is just `myconfig.js` with you `./` in front, `require()` won't know how to deal with it.

**Comment by jeddy3** [comment]
Digging a little deeper...

It looks like the require will only load json if it has an `.json` extension. So, I was able to get it to work by wrapping the config in the `myConfig.js` and `.stylelintrc` files in `module.exports`. That makes sense for the former file, but might be counter intuitive for a user if they create a json-based `.stylelintrc` which works during the look-up, but not if using `configFile`. Perhaps just something we can address in the docs?

**Comment by davidtheclark** [comment]
Ok I get it now. Yeah, .js files would need to be CommonJS; and I admittedly did not yet think about files without extensions. Will look into it soon.

**Comment by davidtheclark** [comment]
I think that because of `require()`'s expectation of extensions there are currently some limitations on using config files without extensions. I don't think it will work to load them via options or to load them via extends: it will only work to load them via rc as the initial config.

I'm willing to accept that this is a limitation of the config loading until #490 is done, and just document it. You?

**Comment by jeddy3** [comment]
>  I'm willing to accept that this is a limitation of the config loading until #490 is done, and just document it. You? 

Defo. Just a line in `docs/user-guide/postcss-plugin.md` will suffice :)

**Comment by jeddy3** [comment]
Lgtm!

**Pull request merged**
