### PR TITLE
Start on split documentation for different APIs

### PR DESCRIPTION
**Pull request by davidtheclark**
This is a start on split API documentation for #411.

@jeddy3 : This pretty much illustrates my idea about splitting the docs, though I didn't finish all the parts and didn't finish revising the user guide. If we wanted to follow through with this plan we'd need to:

- Put in `configuration.md` docs about how to create your configuration object (extends, plugins, quiet, rules -- is that it?)
- Keep the `user-guide.md` super simple and brief, giving a high-level overview and then linking out to various other, more detailed documents.
- Find another place to for the excellent rule convention explanations currently in the `user-guide.md` --- maybe `rules.md`, beneath the actual list? or in a new file, something like `about-rules.md`?

What do you think?

### CODE REVIEW

**Comment by jeddy3** [comment]
Splitting up the docs looks like a great idea to me. I'm not far off pushing up the continuation of that idea.

**Comment by jeddy3** [comment]
I continued to split apart the documentation in what will, hopefully, seem like a logical way. I've grouped things either under "User guide" or "Developer guide", and tried to continuity between the two.

Quick aside: I'll be the first to admit that the descriptions in the user guide and developer guide indexes could be much better written :) I kind of boshed those out right at the end.

> We need to find another place to for the excellent rule convention explanations

I realised that that section is actually two parts: rule naming conventions and configuring rules to work together. 

So, I've split the rule naming conventions into the rules.md. It proceeds the list of all the rules and I think makes for a nice introduction that will help new users decipher the list of rules that follows it i.e. by introducing and explaining the concept of everything being attached to a _thing_.

And I moved the "configuring rules to work together" bit into the configuration guide. Understanding how the rules can fit together seems like an essential part of learning how to configure the linter. Also, by splitting that section into two neither piece feels overwhelming now.

I'm done for the night. If you have time to feedback I'll try to incorporate it before you're able to work on this again. Otherwise, I'll catch up with you after Wednesday :)

**Comment by davidtheclark** [comment]
Cool, looking good. I tweaked a few things here and there ... the biggest of which was moving the list of rules to the top of the Rules doc, and the naming convention explanation to the bottom. Does all that seem ok to you?

I'm happy to let you take it from here and polish off the documentation however you see fit. I figure once this is done we'll be ready for the big release.

**Comment by jeddy3** [comment]
> Does all that seem ok to you?

Yep, it all looks great to me :) Your latest revision to the configuration page has made a big difference.

I've made a couple of tweaks:

* Added an example of a rules config early on in the configuration guide, to give context the next example in the guide - the `extends`.
* I'm not too sure about this next one... I've stripped back the README to just Features, Example output and then links off to the guides as I was struggling to summarise the usage and configuration. Is this alright, or do we need something here?

Besides that, I agree we're ready for the release :) Are you thinking `1.3.0` as I think you managed to add all this functionality without making a breaking change?

**Comment by davidtheclark** [comment]
One concern I just thought of: I think that any *repeat* user coming to look at the docs probably wants to look at the rule list. Because of that, we should make the rule list super easy to access. Could we throw a link to that directly on the README, and make sure it's available as a navigation link on the site?

And how about a kind of Quick Start guide for the README. I was thinking something like this:

With stylelint, it's easy to start linting your CSS to enforce your preferred conventions:

1. Install stylelint: `npm install stylelint`.
2. Learn about some rules (LINK to rules). No rules are turned on by default, so you only have to learn about the rules you *want* to enforce; and you can start small, growing your config over time as you have a chance to explore more of the rules.
3. Create your configuration, probably as a `.stylelintrc` file (LINK to config). 
4. Decide whether to use the CLI, Node API, or PostCSS plugin (LINKS).
5. Lint!

Feedback, ideas, criticism, and contributions more than welcome!

**Comment by davidtheclark** [comment]
And yes, I do not think there are any breaking changes despite all the additions.

**Comment by jeddy3** [comment]
> And how about a kind of Quick Start guide for the README

Sounds groovy to me. I'll drop that in now.

> Because of that, we should make the rule list super easy to access. 

Yep. We'll be including a link in the Quick Start guide and, ask it's such a short README, do you think that'll be enough?

> make sure it's available as a navigation link on the site?

Yep. It currently is (along with "plugins"), and I was thinking it keeping it that way for the reason you mentioned :)

**Comment by davidtheclark** [comment]
Great!

**Comment by davidtheclark** [comment]
I'll find some time today to test this branch in my real-world application.
Please hold off the release until I've managed to do that. (Have you been
able to do that yet?)

**Comment by davidtheclark** [comment]
@jeddy3 : Are you able to test this? Because of https://twitter.com/davidtheclark/status/654331567796432896 I have had problems. Once again makes me worry it was a mistake to use ES6 and babel.

**Comment by davidtheclark** [comment]
@jeddy3 : I was able to get around it by running `npm run prepublish` when I hit the error.

I think we need to wait for https://github.com/postcss/postcss-reporter/pull/14; otherwise seems to be going well for me.

**Comment by jeddy3** [comment]
I've been installing from my local filesystem e.g. `npm install ../stylelint`

> Once again makes me worry it was a mistake to use ES6 and babel.

It's so pretty though :) But yeah, it's caused a few issues with running from master.

**Comment by jeddy3** [comment]
I've run into two issues during my last round of testing... :cry: 

1. When running the CLI on a glob of passing CSS I get an "undefined" logged to the console for each file. Is this related to https://github.com/postcss/postcss-reporter/issues/13 and so do we need a release of that and a version bump in our dependencies?
2. When globally installing stylelint and using the CLI it doesn't seem to find `suitcss-config-suitcss` installed in the local `node_modules`: `Error: Cannot find module 'stylelint-config-suitcss'`. Is that intended behaviour?

Otherwise, everything looks great to me!

**Comment by davidtheclark** [comment]
Yes, problem  1 should be solved by the postcss-reporter PR.

As for 2 -- that's tricky. Hm. I might have to look into that some evening this week. Want to create a separate issue?

**Comment by jeddy3** [comment]
> As for 2 -- that's tricky. Hm. I might have to look into that some evening this week. Want to create a separate issue?

Will do.

**Comment by jeddy3** [comment]
Shall we merge this PR? 

We can handle #413 in another one.

**Comment by davidtheclark** [comment]
Yep. Let's keep this one to docs, so if it's done, merge away.

**Comment by jeddy3** [comment]
:tada:

**Pull request merged**
