### PR TITLE
fix: Fix --ignorePattern not working for the CLI.

### PR DESCRIPTION
**Pull request by satazor**
https://github.com/stylelint/stylelint/pull/2834 was incomplete.

I totally missed the CLI assignment.

### CODE REVIEW

**Comment by satazor** [comment]
//cc @ntwb @jeddy3

**Comment by andreffvalente** [comment]
I really need to use this option in my code. Any idea when you will release this fix?

**Comment by jeddy3** [comment]
Changelog: 

-   Fixed: `--ignore-pattern` in CLI ([#2851](https://github.com/stylelint/stylelint/issues/2851)).

> Any idea when you will release this fix?

I'll drop a patch release now.

**Comment by andreffvalente** [comment]
Thank you @jeddy3!

**Comment by jeddy3** [comment]
Released in `8.1.1`.

**Comment by ntwb** [comment]
It would be great if `lib/cli.js` had some system tests, @satazor @andreffvalente would either of you be interested in adding some tests for the cli?

If so please check out #2142 😄

**Comment by satazor** [comment]
Nobody ain't time for that. I'm joking obviously, but I'm currently overwhelmed by work and personal stuff which means that it would take some time for me to do them.

**Pull request merged**
