### PR TITLE
Add workaround for failing Windows environment

### PR DESCRIPTION
**Pull request by hudochenkov**
> Which issue, if any, is this issue related to?

Temporary workaround for https://github.com/stylelint/stylelint/issues/4337.

> Is there anything in the PR that needs further explanation?

Used [this](https://github.com/Microsoft/vscode/issues/9448#issuecomment-245024153) idea. Because for Windows case in a path is not important.

### CODE REVIEW

**Comment by hudochenkov** [comment]
Can't verify that workaround is working, because all environments were created with uppercase letter :)

**Comment by vankop** [comment]
may be handle this in our code?
we can use knowledge about `process.cwd` call result

**Comment by hudochenkov** [comment]
I think we shouldn't fix what is not broken. We have no reports from users on this regard.

**Comment by hudochenkov** [comment]
It worked! At checkout I see lowercase letter, then it changes to uppercase.

**Comment by vankop** [comment]
So we can remove extra comment?)

**Pull request merged**
