### PR TITLE
Add ignore blockless-group docs

### LINKED ISSUE #1461: Update `at-rule-empty-line-before` README with the `ignore: "blockless-group"` option
The [at-rule-empty-line-before/README.md](https://github.com/stylelint/stylelint/blob/master/src/rules/at-rule-empty-line-before/README.md) file was not updated to include the addition of the `ignore: "blockless-group"` option added via #1419.

@Nirazul would you be interested in fixing this up for us please?

### PR DESCRIPTION
**Pull request by jeddy3**
Closes #1461

### CODE REVIEW

**Comment by ntwb** [comment]
LGTM 👍

**Comment by fnwbr** [comment]
Correct me if I am wrong but this rule is not about

> at-rules within a blockless group

but more about at-rules **without a block**, right?

**Comment by jeddy3** [comment]
I'm a tad confused. Aren't "blockless" and "without a block" the same thing?

"_within_ a blockless _group_" is a bit unclear though, and that is being addressed within https://github.com/stylelint/stylelint/issues/1663

**Comment by fnwbr** [comment]
Sorry, yeah, I was confused by the "within" - basically what I read from

> at-rules within a blockless group

was

> at-rules at the root level

**Pull request merged**
