### PR TITLE
Fix order within no-descending-selector message

### LINKED ISSUE #1678: Inverted error message for no-descending-specificity rule?
Possible bug with the warning message. I've enabled the no-descending-specificity rule and after running it, I'm getting the following warning: 

`Expected selector ".container-overlay a:-webkit-any-link" to come before selector ".container-share-links a" (no-descending-specificity)`.

My CSS:

**Line 27**
```
.container-overlay a:-webkit-any-link {
  text-decoration: none;
}
```

**Line 238**

```
.container-share-links a {
  text-decoration: none;
}
```

The rule is correctly catching a specificity issue, however the warning message is inverted, right? The more specific selector should come **after** the more general one. Yet the warning message is advising the opposite, unless I'm getting my brain twisted into knots.

I'm using `version 7.0.3` of stylelint. Thanks!

### PR DESCRIPTION
**Pull request by jeddy3**
Closes #1678

### CODE REVIEW

**Comment by ntwb** [comment]
LGTM

**Comment by davidtheclark** [comment]
Should add a changelog note, right?

**Comment by jeddy3** [comment]
> Should add a changelog note, right?

Whoops, I was half asleep.

**Comment by davidtheclark** [comment]
LGTM

**Pull request merged**
