### PR TITLE
Refactor to remove `Number.isInteger` polyfill

### LINKED ISSUE #5219: Remove isInteger polyfill
Not required for Node 12.

Ref: https://github.com/stylelint/stylelint/pull/5215

### PR DESCRIPTION
**Pull request by ybiquitous**
We will no longer need the polyfill on the next major release (v14).

> Which issue, if any, is this issue related to?

Closes #5219

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

### CODE REVIEW

**Comment by jeddy3** [comment]
Thanks! It's great to see the ball rolling on the [`14.0.0` release list](https://github.com/stylelint/stylelint/issues/5205).

I was expecting the node 10 tests to fail. I guess `isInteger` is available later version of node 10, but probably not in the range stylelint@13 supports.

Let's do https://github.com/stylelint/stylelint/issues/5292 next, and get that merged so all the future `v14` pull requests are only testing against our new support range.

**Comment by ybiquitous** [comment]
Agree. I will tackle #5292 next. 💪🏼

**Review by hudochenkov — APPROVED** [review]

**Comment by ybiquitous** [comment]
I've opened PR #5302 to drop Node 10.

**Review by jeddy3 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
