### PR TITLE
add :is to pseudo-class list. fixes #4236.

### LINKED ISSUE #4236: Fix false positives for :is selector in selector-pseudo-class-no-unknown
> Clearly describe the bug

[`:is`](https://developer.mozilla.org/en-US/docs/Web/CSS/:is) selector is not known by this rule.

> Which rule, if any, is the bug related to?

`selector-pseudo-class-no-unknown`

> What CSS is needed to reproduce the bug?

e.g.

```css
*:is(*) { color: red; }
```

> What stylelint configuration is needed to reproduce the bug?

e.g.

```json
{
  "rules": {
    "selector-pseudo-class-no-unknown": "always"
  }
}
```

> Which version of stylelint are you using?

`10.1.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No

> What did you expect to happen?

`:is` to not trigger the rule

> What actually happened (e.g. what warnings or errors did you get)?

`:is` triggering the rule

```shell
 9011:3   ✖  Unexpected unknown pseudo-class selector ":is"   selector-pseudo-class-no-unknown
```

### PR DESCRIPTION
**Pull request by bkinnamon**
> Which issue, if any, is this issue related to?

Closes #4236 

> Is there anything in the PR that needs further explanation?

:is is still an experimental technology, but issue #4236 asked for a PR.

https://developer.mozilla.org/en-US/docs/Web/CSS/:is

### CODE REVIEW

**Comment by vankop** [comment]
Thanks for PR! Could you create test cases for that, please.

**Comment by bkinnamon** [comment]
I'm not sure I've done this right. I'm new to pull requests and trying to get the feel for things. Did the test case commit come through?

**Comment by hudochenkov** [comment]
I'll close and open this PR to try to kick in Github Actions. They didn't started for the last commit for some reason.

**Comment by hudochenkov** [comment]
> -   Fixed: `selector-pseudo-class-no-unknown` false positives for `:is` selector ([#4321](https://github.com/stylelint/stylelint/pull/4321)).

**Pull request merged**
