### PR TITLE
Disable Dependabot on default branch

### PR DESCRIPTION
**Pull request by ybiquitous**
> Which issue, if any, is this issue related to?

See #5439

> Is there anything in the PR that needs further explanation?

Currently, we have mainly developed on the `v14` branch.

See also:
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#open-pull-requests-limit

**Note: This PR's base branch should be `master`.**

### CODE REVIEW

**Comment by ybiquitous** [comment]
We should close the open dependabot PRs:

https://github.com/stylelint/stylelint/pulls?q=is%3Apr+is%3Aopen+label%3A%22pr%3A+dependencies%22+author%3Aapp%2Fdependabot

**Review by jeddy3 — APPROVED** [review]

**Comment by jeddy3** [comment]
I think the CI got overwhelmed. Let's merge this anyway.

I've cancelled and deleted all the other pending dependabot runs. There was a dozen or so languishing.

**Review by mattxwang — APPROVED** [review]

**Comment by ybiquitous** [comment]
Sorry for the inconvenience... 🙇🏼

**Comment by jeddy3** [comment]
> Sorry for the inconvenience... 🙇🏼

No worries at all! Updating all the dependencies is a job that needed doing as we'd fallen quite far behind, and by getting dependabot sorted on the `v14` branch we can ensure we stay up to date.

**Pull request merged**
