### PR TITLE
Add media-prefers-reduced-motion rule

### PR DESCRIPTION
**Pull request by YozhikM**
> Which issue, if any, is this issue related to?

Issue #3356 

> Is there anything in the PR that needs further explanation?

No.

### CODE REVIEW

**Comment by ai** [comment]
Also good rule for a11y

**Comment by jeddy3** [comment]
See https://github.com/stylelint/stylelint/pull/3355#issuecomment-394389845 about having this live in a plugin first.

> Also good rule for a11y

We can promote this plugin in the documentation e.g. 

* **Support for plugins**: It's easy to create your own rules and add them to the linter, or make use of plugins written by the community. For example, there are plugins for [Scss](..) and [a11y](..).

**Comment by evilebottnawi** [comment]
@jeddy3 looks like no one starting `a11y` plugin, i do not think that this can happen, maybe it is normal put this rules in core, if somebody starts working on `a11y` plugin, we can move this out of stylelint in 10 version. We should will be responsive to community, plugin system is awesome, but it is doesn't make sense when we have little community :disappointed:

**Comment by jeddy3** [comment]
Ported to a plugin in https://github.com/stylelint/stylelint/pull/3364

@YozhikM Thanks again.

**Pull request closed without merging**
