### PR TITLE
Add `ignorePatterns` config option

### LINKED ISSUE #5804: Integrate `ignoreFiles` configuration and `--ignore-pattern` CLI flag
### What is the problem you're trying to solve?

We have the following two options to ignore files from linting:

### `ignoreFiles` (.stylelintrc)

https://github.com/stylelint/stylelint/blob/dbbfe21e1c945c9d54b16ddd5c1570b4ae3f935e/docs/user-guide/configure.md#L368-L380

### `--ignore-pattern` (CLI)

https://github.com/stylelint/stylelint/blob/dbbfe21e1c945c9d54b16ddd5c1570b4ae3f935e/docs/user-guide/usage/cli.md#L63-L65

These options are similar but the usages are different: from Configuration and CLI.
I think this usability is not good. 😕 

### What solution would you like to see?

So I suggest the following:

- add `ignorePatterns` option to `.stylelintrc`
- deprecate `ignoreFiles` option of `.stylelintrc`

Thus, users can manage only one file `.stylelintrc` for stylelint configuration; that is, it is unnecessary to manage also `.stylelintignore`.

For example, `.stylelintignore`:

```diff
- dist/**/*.css
```

`.stylelintrc`:

```diff
{
+ "ignorePatterns": [
+   "dist/**/*.css"
+ ]
}
```

See also:
- [Ignoring Code - ESLint - Pluggable JavaScript linter](https://eslint.org/docs/user-guide/configuring/ignoring-code)

### PR DESCRIPTION
**Pull request by mattxwang**
> Which issue, if any, is this issue related to?

Closes #5804.

> Is there anything in the PR that needs further explanation?

Draft - I think I Need to improve some test coverage and nail down some of the behavioural changes.

In addition,

- need to add docs
- potentially add deprecation warning?
- changeset

### CODE REVIEW

**Comment by Mouvedia** [comment]
> potentially add deprecation warning?

see #7449

**Comment by ybiquitous** [comment]
@Mouvedia Thanks for the reminder. Right, this issue/PR duplicates with #7449 in our new config format. I'll close the original issue #5804 if @mattxwang agrees.

**Comment by mattxwang** [comment]
Ah! So sorry - to be frank, I've been way behind on many of my open-source obligations.

> I'll close the original issue https://github.com/stylelint/stylelint/issues/5804 if @mattxwang agrees.

Go for it!

Also, I know I've had a couple of PRs languishing (I haven't had the chance to really work on them) and I don't think I'll be able to push them over until at least March. Let me know if I should close #7194 or #7229 (needs more scoping out of what this will look like).

**Comment by ybiquitous** [comment]
@mattxwang Thanks for the quick response. I've just closed #6818, so I'm closing this PR too.

> Let me know if I should close #7194 or #7229 (needs more scoping out of what this will look like).

Let's close them since they need to be rewritten for ESM (`*.mjs`). You could restart with a new pull request if you want.

**Comment by Mouvedia** [comment]
> I'll close the original issue #5804 if @mattxwang agrees.

It should be reduced to

> add `ignorePatterns` option

i.e. it's only partially a duplicate.

**Comment by Mouvedia** [comment]
> I'll close the original issue #5804 if @mattxwang agrees.

It's only partially a duplicate; #7449 doesn't have a flag listed.
i.e. `--ignores` is missing
cf https://eslint.org/docs/latest/use/command-line-interface#--ignore-pattern

**Comment by ybiquitous** [comment]
> #7449 doesn't have a flag listed.

Right. But it's OK since we could revisit the flag after #7449 (and the new config format) is implemented. Leaving the original issue #5804 would be confusing.

**Pull request closed without merging**
