### PR TITLE
Add `eslint-plugin-you-dont-need-lodash-underscore`

### PR DESCRIPTION
**Pull request by ybiquitous**
https://www.npmjs.com/package/eslint-plugin-you-dont-need-lodash-underscore

> Which issue, if any, is this issue related to?

Related to #4412

> Is there anything in the PR that needs further explanation?

This PR aims to view the progress of replacement of `lodash`. **DO NOT MERGE**.
I will keep it up-to-date until the replacement will finish.

### CODE REVIEW

**Comment by alexander-akait** [comment]
I think too, time to remove `lodash`, we are on modern ECMA

**Comment by mattxwang** [comment]
After #5372 it looks like we can call it a day with removing lodash!

**Comment by jeddy3** [comment]
Shall we add the plugin to our standard eslint config, to advise contributors not to re-add lodash?

**Comment by ybiquitous** [comment]
@jeddy3 I have a concern for that `eslint-plugin-you-dont-need-lodash-underscore` cannot detect all usages of `lodash`, e.g. `_.merge`. Please see open feature requests: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/issues

But I will not block if anyone wants to include it into our sharable config.

**Comment by ybiquitous** [comment]
All lint errors now are resolved! 👍🏼

**Comment by jeddy3** [comment]
If it's not comprehensive, then let's leave it out of our sharable config.

**Pull request closed without merging**
