### PR TITLE
Added plugin in docs.

### PR DESCRIPTION
**Pull request by sh-waqar**
Added my personal plugin for stylelint `stylelint-declaration-use-variable` in the user documentation.

@davidtheclark Please review. Thanks.

### CODE REVIEW

**Comment by davidtheclark** [comment]
Awesome! I think this is our first request to add a plugin to the list. 

I'm looking at the code now and have a few suggestions that I'll file as issues. But I'm totally fine with adding it to our docs in whatever state it's in. @jeddy3?

Also, @kristerkari here's an SCSS-specific plugin --- any interest in using this in your stylelint-scss project?

**Comment by jeddy3** [comment]
> Awesome! I think this is our first request to add a plugin to the list.

Yep, it is :) Thanks @sh-waqar for contributing!

> I'm looking at the code now and have a few suggestions that I'll file as issues. 
Likewise.

> But I'm totally fine with adding it to our docs in whatever state it's in. @jeddy3?

Yep, I fine with that. One of my suggestions is going to be about the name, but happy to see this merged as-is and if the name changes then we an handle that in another PR.

**Comment by sh-waqar** [comment]
@davidtheclark @jeddy3 Thank you so much. I am taking a look at the suggestions you both have made. Will surely look into it and ping you guys for review ;)

**Comment by kristerkari** [comment]
> Also, @kristerkari here's an SCSS-specific plugin --- any interest in using this in your stylelint-scss project?

Yes, it looks like a good fit. I'm going to have more time to work on that project soon, so I have to keep this plugin in mind.

**Pull request merged**
