### PR TITLE
Proposal: Add configuration example at end of docs

### PR DESCRIPTION
**Pull request by schalkneethling**
A proposal to add configuration examples to the docs for the various rules. It is not often that I need to update or change the default shareable config, but when I do, oh boy 😄 I can never remember how the various rules are configured. As such, I think it would be useful to add little examples like this one to rules that are not a simple `true|false`.

Also, I believe in this case you set the rule to `null` to disable?

### CODE REVIEW

**Comment by ybiquitous** [comment]
@schalkneethling Thank you for your contribution. Does the following document satisfy your need already?

https://github.com/stylelint/stylelint/blob/0eaf3d456cdecdd698d5e4a9edc54d205d47d907/docs/user-guide/configure.md#rules

**Comment by schalkneethling** [comment]
> @schalkneethling Thank you for your contribution. Does the following document satisfy your need already?
> 
> https://github.com/stylelint/stylelint/blob/0eaf3d456cdecdd698d5e4a9edc54d205d47d907/docs/user-guide/configure.md#rules
> 
> EDIT: See also https://stylelint.io/user-guide/configure#rules

Wow! Indeed it does :) No idea how I missed that all this time. I wonder though. Perhaps one can add a link to this at the bottom of rule pages? Something like: Need help to configure rules? [Read the guide](https://stylelint.io/user-guide/configure#rules).

**Comment by ybiquitous** [comment]
> Perhaps one can add a link to this at the bottom of rule pages?

Umm..., it's difficult. Instead, we can easily add such a link to the page header like this: ⬇️ 

image

---

In any case, it seems better to open a new issue and discuss the difficulty of finding the rules document there.
Can you close this PR and open an issue with your detailed description, please?

**Comment by schalkneethling** [comment]
> Can you close this PR and open an issue with your detailed description, please?

Sure thing!

**Pull request closed without merging**
