### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by corysimmons**
Saving people time.

### CODE REVIEW

**Comment by MoOx** [comment]
Please stop being a dick.

**Comment by corysimmons** [comment]
I'm not the one wasting people's time for GitHub points.

**Comment by MoOx** [comment]
GitHub points?

**Comment by corysimmons** [comment]
image

**Comment by MoOx** [comment]
You should look at npm points.

screen shot 2016-02-11 at 07 36 08

**Comment by corysimmons** [comment]
Totally successful project. :100: Who needs semi-functional editor linters? :clap:

**Comment by MoOx** [comment]
Probably people that were used to have non-functional-at-all editor linters.

**Comment by corysimmons** [comment]
I want to disagree with you, but I can't. I just tried CSScomb for 5 minutes and realized what garbage it is.

Ah well, maybe in a few months you guys will have editor linting.

**Comment by davidtheclark** [comment]
@corysimmons, I would counterargue but you're just being ridiculous so I don't want to waste time typing. Sorry an open-source project hasn't fulfilled the dream of being Your Personal Everything.

**Pull request closed without merging**
