### PR TITLE
Migrate Coveralls to Codecov

### LINKED ISSUE #5748: Use codecov for coverage
## What is a problem

Builds on Coveralls have not worked for a while:
https://coveralls.io/github/stylelint/stylelint

Even when seeing the log of GitHub Actions, we cannot know anything... 🤷🏼 
https://github.com/stylelint/stylelint/runs/4336137130?check_suite_focus=true#step:8:8

I've resynced with the GitHub repository on the Coveralls repo settings, but errors still occur:
https://github.com/stylelint/stylelint/pull/5743#issuecomment-980070312

## How to solve

So, I think there are the following options:
1. Stop using Coveralls
2. Migrate to another service

For example, [Codecov](https://codecov.io/) is an option. When I've tried my forked repository, it works:
- https://codecov.io/gh/ybiquitous/stylelint/tree/401071d44695a610413a926fef873916ab66c102
- https://github.com/ybiquitous/stylelint/runs/4346303358?check_suite_focus=true#step:8:32
- https://github.com/ybiquitous/stylelint/pull/2

Does anyone have thoughts?

### PR DESCRIPTION
**Pull request by ybiquitous**
> Which issue, if any, is this issue related to?

Closes #5748

> Is there anything in the PR that needs further explanation?

This change aims to migrate Coveralls to Codecov as a test coverage SaaS.
See also:
- https://github.com/codecov/codecov-action
- https://github.com/apps/codecov

### CODE REVIEW

**Comment by ybiquitous** [comment]
## To-dos

- [x] Install the [Codecov GitHub App](https://github.com/apps/codecov)
- [x] Add the `stylelint/stylelint` repo to Codecov

**Comment by ybiquitous** [comment]
I think a comment from Codecove like [this](https://github.com/stylelint/stylelint/pull/5749#issuecomment-981120715) is a bit noisy. 🤔 

If we'd like to turn off the feature, we need to additionaly create `codecov.yml` as below:

```yaml
comment: false
```

What do you think? (see also the [doc](https://docs.codecov.com/docs/pull-request-comments))

**Comment by ybiquitous** [comment]
We can view the coverage data in all the files:
https://codecov.io/gh/stylelint/stylelint/tree/c138b21f24c591cf9a900a3a4d9000ff5a4b3424

**Comment by jeddy3** [comment]
> What do you think? (see also the doc)

Yes, let's turn the comment off.

**Comment by ybiquitous** [comment]
> Yes, let's turn the comment off.

Thanks. Done! 46123c27

**Review by jeddy3 — APPROVED** [review]
LGTM, thanks!

**Review by adalinesimonian — APPROVED** [review]
I use Codecov in another project, this looks good!

**Comment by ybiquitous** [comment]
I'll remove the project from Coveralls after I confirm Codecov has no problems:
https://coveralls.io/github/stylelint/stylelint

**Comment by ybiquitous** [comment]
I've removed it from Coveralls!

**Pull request merged**
