### PR TITLE
Chore: add `codeclimate` badge.

### PR DESCRIPTION
**Pull request by evilebottnawi**
> Which issue, if any, is this issue related to?

None, as it's a documentation fix.

> Is there anything in the PR that needs further explanation?

No, it's self explanatory.

@stylelint/core what do you think add new label? BTW perhaps we should pay attention to the report

### CODE REVIEW

**Comment by davidtheclark** [comment]
Honestly, I'm not interested in what CodeClimate has to say. I clicked through some of the reportrs, and did not find any criticisms that were accurate or suggestions that were helpful. Did you?

**Comment by evilebottnawi** [comment]
@davidtheclark I noticed a lot of duplicated code message, i think that some of the architectural highlights can be reviewed and processed in a more user-friendly and readable form

**Comment by davidtheclark** [comment]
> I noticed a lot of duplicated code message

Yes, but the ones I looked at were not actionable. They were for code that *should* be duplicated, for which an abstraction would be overkill. But, yeah, I'm sure there are some cases where this is not the case.

**Comment by evilebottnawi** [comment]
@davidtheclark I think it would be great if anyone has analyzed all the warnings, but I understand that we have little time for it. Also I think that `codeclimate` have configuration files and after analize maybe good create this file and take into account the subsequent warning

**Comment by evilebottnawi** [comment]
@davidtheclark I think it would be great if anyone has analyzed all the warnings, but I understand that we have little time for it. Also I think that `codeclimate` have configuration files and after analize maybe good create this file and take into account the subsequent warning

**Comment by ntwb** [comment]
I'm pretty sure it was myself who originally queued up the stylelint repo analysis at Code Climate. 

To have any kind of accurate analysis by Code Climate quite a few things need to happen, some of those are listed in #1341, whitelisting by Code Climate of our `eslint-config-stylelint` which was denied in https://github.com/codeclimate/codeclimate-eslint/issues/80, adding a `.codeclimate.yml` with a configuration suitable for stylelint to name but a few.

Per the above I'm going to close this, as adding the badge alone is *not* an accurate reflection of the status of the stylelint repo. 😄

**Pull request closed without merging**
