### PR TITLE
Prepare 14.0.0

### PR DESCRIPTION
**Pull request by jeddy3**
> Which issue, if any, is this issue related to?

Relates to https://github.com/stylelint/stylelint/issues/5205

> Is there anything in the PR that needs further explanation?

Of the 3 merge options, I assume we'll want to "create a merge commit" as that'll preserve the commits into `master`?

I'll merge this when we're ready to go. There are quite a few moving parts in this release, and I'll need to block out some time to do it. Tomorrow is a good day for me to do that (if the VS Code extension is OK).

In the meantime, I'm going to do some local testing on this branch. Pulling down this branch and checking it works with your project, would be helpful!

### CODE REVIEW

**Comment by ntwb** [comment]
I'm currently trying to test v14 with VS Code here https://github.com/stylelint/vscode-stylelint/pull/265#issuecomment-947536701

I'm struggling to get `npm link` to work to test v14

I was thinking we could publish to https://www.npmjs.com/package/stylelint a `next` pre-release release

- `./node_modules/.bin/np --preview --any-branch --no-release-draft`

Results look good, here's the full output of that command, note the `--preview` for a trial run:

```log
❯ ./node_modules/.bin/np --preview --any-branch --no-release-draft
? The following new files will not be part of your published package:
- types/normalize-selector/index.d.ts
- types/postcss-media-query-parser/index.d.ts
- types/postcss-resolve-nested-selector/index.d.ts
- types/stylelint/type-test.ts
The following new files will be published the first time:
- docs/migration-guide/to-14.md
- lib/__tests__/applyOverrides.test.js
- lib/__tests__/fixtures/config-overrides/extending-plugin-and-one-rule.json
- lib/__tests__/fixtures/config-overrides/extending-simple-rule.json
- lib/__tests__/fixtures/config-overrides/extends-in-overrides.json
- lib/__tests__/fixtures/config-overrides/plugin-and-one-rule.json
- lib/__tests__/fixtures/config-overrides/simple-rule.json
- lib/__tests__/fixtures/config-overrides/style.css
- lib/__tests__/fixtures/config-overrides/style.module.css
- lib/__tests__/fixtures/config-overrides/testPrintConfig/.stylelintrc
- lib/__tests__/fixtures/config-overrides/testPrintConfig/style.css
- lib/__tests__/overrides.test.js
- lib/rules/color-hex-alpha/__tests__/index.js
- lib/rules/color-hex-alpha/index.js
- lib/rules/custom-property-no-missing-var-function/__tests__/index.js
- lib/rules/custom-property-no-missing-var-function/index.js
- lib/testUtils/uniqueId.js
- lib/utils/__tests__/arrayEqual.test.js
- lib/utils/__tests__/isAutoprefixable.test.js
- lib/utils/__tests__/isStandardSyntaxComment.test.js
- lib/utils/arrayEqual.js
- lib/utils/isPathNotFoundError.js
- lib/utils/isStandardSyntaxComment.js
- lib/utils/validateTypes.js
Continue? Yes

Publish a new version of stylelint (current: 13.13.1)

Commits:
- Prepare 14.0.0  5dd7ec15
- Add support for `extends` in `overrides` config (#5603)  67313a38
- ** Truncated for readability **
- Refactor `lib/__tests__/extends.test.js` (#5280)  af6f858e
- Mention alternative integration with Emacs (#5275)  20dc873f

Commit Range:
13.13.1...master

Registry:
https://registry.npmjs.org/

? Select semver increment or specify new version premajor       14.0.0-0
? How should this pre-release version be tagged in npm? next

  ✔ Prerequisite check
  ✔ Git
  ✔ Installing dependencies using npm
  ✔ Running tests using npm
  ↓ Bumping version using npm [skipped]
    → [Preview] Command not executed: npm version 14.0.0-0.
  ↓ Publishing package using npm [skipped]
    → [Preview] Command not executed: npm publish --tag next.
  ↓ Pushing tags [skipped]
    → [Preview] Command not executed: git push --follow-tags.
~/Code/stylelint/stylelint v14 *2                                     
```

At the end of this process we would have a `next` tag at https://github.com/stylelint/stylelint/tree/next and a `next` release on npm https://www.npmjs.com/package/stylelint

And we could install this next version via `npm install --dev stylelint@next`

Thoughts @stylelint/owners ?

**Comment by ntwb** [comment]
🎉 Done

- Published `next` to https://www.npmjs.com/package/stylelint
- GitHub Tag https://github.com/stylelint/stylelint/tree/14.0.0-0

It's pushed the `14.0.0-0` tag to this PR, that wasn't expected

**Comment by jeddy3** [comment]
> Edit: Duplicate of https://github.com/stylelint-scss/stylelint-config-standard-scss/pull/1/files

Yep, you'll want to use that branch.

I think I'll publish prereleases for all the packages so that we can be confident everything works together.

**Comment by jeddy3** [comment]
> I believe glob "*.scss" would only match .scss files in a current folder:

That makes sense. 

The behaviour is in line with the [docs](https://deploy-preview-227--stylelint.netlify.app/user-guide/configure#overrides) (which I probably should have read first!):

> The patterns are applied against the file path relative to the directory of the config file. For example, if your config file has the path /Users/person/workspace/any-project/.stylelintrc.js and the file you want to lint has the path /Users/person/workspace/any-project/components/card.css, then the pattern provided in .stylelintrc.js will be executed against the relative path components/card.css.

I got my local test code to work by setting the glob to `../**/*.scss` when the config is in a sub folder. 

---

I've released prerelease versions of all the packages [in the release sequence](https://github.com/stylelint/stylelint/issues/5205#issue-837034702) under the `next` tag, e.g. `npm i --save-dev stylelint@next`. Hopefully, they'll make testing the VS Code extension easier.

Please give them a go in your projects.

**Pull request merged**
