### PR TITLE
Fixed: the `indentation` rule now correctly handles `_` hacks on property names.

### PR DESCRIPTION
**Pull request by evilebottnawi**
Close https://github.com/stylelint/stylelint/issues/1787.
/cc @davidtheclark @jeddy3

### CODE REVIEW

**Comment by davidtheclark** [comment]
LGTM — nice job @evilebottnawi.

**Comment by jeddy3** [comment]
LGTM.

@evilebottnawi Feel free to merge on a rebase.

**Comment by evilebottnawi** [comment]
CI green, merge

**Comment by yisibl** [comment]
Thanks!

**Pull request merged**
