### PR TITLE
`at-rule-name-case` rule

### PR DESCRIPTION
**Pull request by evilebottnawi**

### CODE REVIEW

**Comment by davidtheclark** [comment]
Seems pretty straightforward to me. I'm fine with a merge if others approve.

**Comment by evilebottnawi** [comment]
@davidtheclark one comment, if used less or sass(scss), it is possible to write only at-rule in `lower` case, `upper` is invalid and not compiled.

**Comment by davidtheclark** [comment]
Good to know. I'd say that should be added to the docs.

**Comment by jeddy3** [comment]
> I'd say that should be added to the docs.

Done in https://github.com/stylelint/stylelint/commit/a8275a2ae2c3a99b9596365f69c90de316993953

**Pull request merged**
