### PR TITLE
add missing rules.

### PR DESCRIPTION
**Pull request by evilebottnawi**

### CODE REVIEW

**Comment by ntwb** [comment]
Can we please always have a second person review pull requests before being merged please.

Its not formalized in writing anywhere but informally it is used with every pull request with the `PR: review needed` and `PR: review accepted` labels.

Maybe it should formalized in writing in [CONTRIBUTING.md](https://github.com/stylelint/stylelint/blob/master/CONTRIBUTING.md)?

**Comment by evilebottnawi** [comment]
@ntwb well, I just thought that this is a trivial issue.

**Comment by ntwb** [comment]
It was a simple change, and yes trivial, but a second set of eyes makes sure of no mistakes, hopefully :)

**Comment by evilebottnawi** [comment]
@ntwb well, I will follow the recommendation :smile:

**Pull request merged**
