### PR TITLE
fix: selector-max-universal

### PR DESCRIPTION
**Pull request by vankop**
> Which issue, if any, is this issue related to?

related to https://github.com/stylelint/stylelint/issues/4232

> Is there anything in the PR that needs further explanation?

Nothing. I have also updated some info in README

### CODE REVIEW

**Comment by hudochenkov** [comment]
What exactly did you do here? I need a commit message, but couldn't figure out myself.

**Comment by vankop** [comment]
Sorry for poor description.

This PR relates to "bug" with mismatching warnings count. Currently `stylelint` report extra warning for `:not(*)` (could be any logical combination).
It happens, because of `postcss-resolve-nested-selector` parses `:not(*)` to `[':not(*)', '*']`, so this produce extra warning

**Comment by ntwb** [comment]
How about:

> fixed: Logical combinations `:not` and `:has` pseudo-classes in `selector-max-universal` are now evaluated separately.

**Comment by vankop** [comment]
> How about:
> 
> > fixed: Logical combinations `:not` and `:has` pseudo-classes in `selector-max-universal` are now evaluated separately.

there are `:matches` as well, all typos fixes up to you (I am not native speaker 😆 )

**Comment by hudochenkov** [comment]
> -   Fixed: Logical combinations pseudo-classes in `selector-max-universal` are now evaluated separately ([#4263](https://github.com/stylelint/stylelint/pull/4263)).

**Pull request merged**
