### PR TITLE
Disable email notifications

### PR DESCRIPTION
**Pull request by jeddy3**
Ok with you guys?

### CODE REVIEW

**Comment by MoOx** [comment]
You are supposed to get a notification when you (commiter) break something (or fixes it).
Is this a problem ?

**Comment by jeddy3** [comment]
Is there anyway to disable the email notifications for just me? I keep email for just personal correspondence.

**Comment by MoOx** [comment]
You can try here

- http://docs.travis-ci.com/user/notifications/
- https://travis-ci.org/stylelint/stylelint/settings
- https://travis-ci.org/profile

If it's really a problem, we might change that. @davidtheclark do you find mail useful ?

**Comment by jeddy3** [comment]
I'm easy guys. Happy to just setup a email filter at my end until https://github.com/travis-ci/travis-ci/issues/3121 lets me disable the notifications via the website.

**Comment by MoOx** [comment]
Cool !

**Comment by jeddy3** [comment]
Closing in favour of filter at my end.

**Pull request closed without merging**
