### PR TITLE
Validate selectors consistently. Fixes #3130

### LINKED ISSUE #3130: Consistently check that selectors are standard before passing to the parser
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Updating to 8.4.0 breaks for us.

> What CSS is needed to reproduce this issue?

```scss
@mixin bpk-locale($locale) {
  html[lang=#{$locale}] &,
  html[lang=#{to_lower_case($locale)}] & {
    @content;
  }
}
```

https://github.com/Skyscanner/backpack/blob/3c53ec780ff922a727923b796be540637ce10e98/packages/bpk-mixins/src/mixins/_utils.scss#L165-L170

> Fails with the following error

```
 166:3  ✖  Cannot parse selector   parseError
```

> Which version of stylelint are you using?

8.4.0
> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

SCSS

> What did you expect to happen?

The linting not to fail

### PR DESCRIPTION
**Pull request by dom111**
> Which issue, if any, is this issue related to?

Closes #3130.

> Is there anything in the PR that needs further explanation?

No, it's self explanatory.

### CODE REVIEW

**Comment by dom111** [comment]
@hudochenkov

> Thanks for fixing this!

No problem, happy to help!

> I think we can use `isStandardSyntaxSelector` in `isStandardSyntaxRule`, because for standard syntax rule selector also should be in standard syntax.

This makes sense and I've stripped it out of most of the places that make sense. There are a few separate calls left but from what I gathered I think they're separate selector validations around nested and surrounding selectors.

Thanks!

**Comment by hudochenkov** [comment]
Please, as a new contributor, don't merge PRs just yet. Learn our [processes](https://stylelint.io/developer-guide/pull-requests), and observe.

**Comment by hudochenkov** [comment]
> -   Fixed: consistently check that selectors are standard before passing to the parser ([#4483](https://github.com/stylelint/stylelint/pull/4483)).

**Comment by dom111** [comment]
@hudochenkov Apologies, I didn't see the option to merge before, so when I saw the option existed I switched to following my usual process, (although the fact it's merging to master rather that an integration branch...) I'll refrain from merging in the future though, was just trying to save some work! :)

**Comment by hudochenkov** [comment]
No worries :)

**Pull request merged**
