### PR TITLE
Standardise badges

### PR DESCRIPTION
**Pull request by jeddy3**
To make them nice and neat :)

Ref #15

### CODE REVIEW

**Comment by MoOx** [comment]
Good initiative. I just found "winbuild" to be a bit weird. What about "windows build" or "win build" ?
I saw some people showing "OS X & Linux build" + "Windows build" as label.
Maybe "unix build" & "windows build" ?

**Comment by jeddy3** [comment]
"*nix build" and "windows build"?

**Comment by MoOx** [comment]
linux is a superset of unix right (like os x is) ?

**Comment by jeddy3** [comment]
Right you are. The asterisk looked weird as well :)

**Comment by MoOx** [comment]
It's nice like that

**Pull request merged**
