### PR TITLE
Add NPM Downloads label

### PR DESCRIPTION
**Pull request by evilebottnawi**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@jeddy3 @davidtheclark what do you think?

**Comment by davidtheclark** [comment]
SGMT

**Comment by jeddy3** [comment]
Normally adding a badge isn't an issue, but adding a forth means the badges will span two lines when viewing the website (http://stylelint.io/) on a mobile phone. Which ends up taking up a lot of space when you first land on the page. Unless this badge is a must-have, then I'd rather avoid a forth badge.

**Comment by evilebottnawi** [comment]
@jeddy3 it is normal on new line, badge strengthen the credibility of the product and it's good

**Pull request merged**
