### PR TITLE
Update code-scanning.yml

### PR DESCRIPTION
**Pull request by XhmikosR**
* added `workflow_dispatch`
* added `security-and-quality`

### CODE REVIEW

**Comment by XhmikosR** [comment]
BTW I can't push to the repo via my VM, I'm getting a 403 error. It seems PAT classic are not allowed anymore for this repo :/

**Review by ybiquitous — APPROVED** [review]
Thanks, LGTM 👍🏼 

We would appreciate it if you could fix the code-scanning alerts reported by this PR change.

**Comment by ybiquitous** [comment]
> BTW I can't push to this repo via CLI, I'm getting a 403 error. It seems PAT classic are not allowed anymore for this repo, and the granular token I tried didn't work

Umm. I have never heard about that. 🤔
Can you share your local error here? I might resolve the error.

**Comment by ybiquitous** [comment]
I've closed the following security alert due to a false positive. Let me know if you find a problem.
https://github.com/stylelint/stylelint/security/code-scanning/7

**Comment by ybiquitous** [comment]
Additionally, I've closed the alerts in `type-test.ts` due to a false positive like:
https://github.com/stylelint/stylelint/security/code-scanning/13

It seems we can address [other open alerts](https://github.com/stylelint/stylelint/security/code-scanning).

**Comment by XhmikosR** [comment]
It's hard to do anything in this repo since I'm getting 403 errors when pushing :/

I'm 100% sure it's a repo/organization setting that's preventing PAT from working. But I have no idea how to make things with granular token.

Anyway, the remaining issues look easy to fix :)

**Comment by ybiquitous** [comment]
Can you let me know if you create a PAT (fine-grained, not classic)? Maybe, we (admins) need to approve the token.

**Pull request merged**
