### PR TITLE
`position: static` and `z-index`.

### PR DESCRIPTION
**Pull request by evilebottnawi**
/cc @davidtheclark @jeddy3

### CODE REVIEW

**Comment by davidtheclark** [comment]
I think we need to consider any additions to this rule to be breaking changes (cf. #1236). Anybody disagree?

So this would need to be merged into v7. And we would definitely want to get all other such improvements merged into v7, right?

**Comment by evilebottnawi** [comment]
@davidtheclark agree, tomorrow i see specs and found all properties which should contain rule

**Comment by jeddy3** [comment]
> I think we need to consider any additions to this rule to be breaking changes (cf. #1236). Anybody disagree?

Nope. `v7` sounds good.

**Comment by evilebottnawi** [comment]
@jeddy3 now

**Comment by jeddy3** [comment]
And merge into `v7` branch please?

**Comment by evilebottnawi** [comment]
@jeddy3 i think we now working on v7, not right?

**Comment by evilebottnawi** [comment]
@jeddy3 some breaking changes already merged in master.

**Comment by jeddy3** [comment]
> some breaking changes already merged in master.

Oh, you're right. Looks like we're gearing up for `7.0` then :)

**Comment by evilebottnawi** [comment]
@jeddy3 merge? :)

**Comment by jeddy3** [comment]
Wait on @davidtheclark so we're all on the same page about `7.0`

**Comment by evilebottnawi** [comment]
Close. Now creating PR with more properties.

**Pull request closed without merging**
