### PR TITLE
Reconfigure CI

### PR DESCRIPTION
**Pull request by hudochenkov**
We need to run `npm run lint:md` on `*.md` files. I don't know how to configure Github Actions for this. At least we could use old approach and run all tests.

### CODE REVIEW

**Comment by vankop** [comment]
We can use different workflow for this =)

**Comment by hudochenkov** [comment]
@vankop is it possible to disable coveralls comment? It reports result to status checks, comment is redundant.

image

**Comment by hudochenkov** [comment]
> We can use different workflow for this =)

We could. But is it worth it to complicate CI for this?

**Comment by vankop** [comment]
> > We can use different workflow for this =)
> 
> We could. But is it worth it to complicate CI for this?

I can suggest another way - 2 flows:
1. tests
2. lint

So lint step will be always triggering

**Comment by vankop** [comment]
> is it possible to disable coveralls comment?

@hudochenkov As I understand from code and job output, this must be a coverall setting. All what code does just creating so called `job`, e.g. current job https://coveralls.io/jobs/53558061 . However, I did not figure out how coverall commit owner authenticated as `github-actions`

**Comment by hudochenkov** [comment]
I checked coveralls settings. And comments were disabled. I redisabled them just in case.

**Comment by ntwb** [comment]
Coveralls comments report as the same as “our” comments, as such Coveralls doesn’t currently comment, it reports status checks which is what we do want to continue, Coveralls will only leave a comment of the percentage test coverage changes by the threshold we have set, which is -5%

**Comment by ntwb** [comment]
This is a Coveralls comment example before we disabled them:
> https://github.com/stylelint/stylelint/pull/1392#issuecomment-223771324

**Comment by vankop** [comment]
Problem is that in your example comment authored by `coveralls`, now it authored by `github-actions`

**Comment by hudochenkov** [comment]
I extracted linting into separate workflow. Also renamed few things so now in statuses text is more concise and we see time for every item (almost).

**Comment by hudochenkov** [comment]
I see one flaw with two workflows. We can't enforce all tests for PR to be merged. Before Github Action we set Travis and Appveyor as a requirement. Github would not allow contributors to merge until tests are green. With two workflows we can't enabled requirements for every job (which we have 10 at the moment), because some of jobs (9 of them) just wouldn't run on PRs with `*.md` changes.

We have two choices:

1. Require only Lint job, and keep eye on build statuses when we merge.
2. Don't make exceptions for `*.md`and run all tests for all PRs.

I would go with the second option for more security. We don't have much PRs with just `*.md` changes. And kind of unnecessary 3-4 minutes of waiting for CI won't make any difference, because we do not react to a PR at the very moment it posted.

**Comment by evilebottnawi** [comment]
:+1: on second

**Comment by ntwb** [comment]
Agreed, on the second option, as we've such a large number of committers who can merge a PR lets ensure that we mitigate issues this may bring stylelint as best as possible 👍🏼

**Comment by hudochenkov** [comment]
Ready for a review.

**Comment by vankop** [comment]
@hudochenkov [fastify](https://github.com/fastify/fastify) faced with same `coveralls` problem, so I hope `coveralls` team will investigate this problem soon

**Comment by XhmikosR** [comment]
I contacted Coveralls via email about the comments issue, we'll see how it goes. It's quite annoying, especially for popular repos with many watchers.

**Pull request merged**
