### PR TITLE
Add linebreaks rule

### PR DESCRIPTION
**Pull request by saulotoledo**
> Which issue, if any, is this issue related to?

Closes https://github.com/stylelint/stylelint/issues/3114

> Is there anything in the PR that needs further explanation?

~It is a first draft. Needs some more test cases (e.g. newlines in the end of the file and empty newlines) and possibly some polishment. I will work on these as soon as possible this week. Any comments can be helpful. I will edit this description and title in the final version.~

First complete version available for review.

### CODE REVIEW

**Comment by saulotoledo** [comment]
@evilebottnawi Sure! I will add that test cases too.

**Comment by saulotoledo** [comment]
@evilebottnawi @jeddy3 Final version available.

I used a simple loop to iterate through the lines for reporting. I was using only the PostCSS API, but the code was getting very complicated because I had to calculate the proper lines and columns through the raw values. But there are too much situations to handle (newlines inside comments, comments with multiple lines, newlines between rules, values, after/before brackets and so on). I have a local copy of an (almost) finished version that works just by using the API, but it is difficult to read because of that. I can share if you want.

So, I decided to use the API only when fixing the code, a place where I do not have to worry about calculating the proper lines and columns. Let me know your opinion about.

**Comment by saulotoledo** [comment]
@evilebottnawi, @jeddy3 Also, note that I created a manual node for reporting. I had to do that because there is no node for empty lines or half comments, for example. Thus, it is impossible to report the correct lines by using the original nodes. If there is a better way to do that, please let me know and I will update the code.

**Comment by hudochenkov** [comment]
If you add changes based on my comment above, please don't rebase, so we can see what changed since the last review :)

**Comment by saulotoledo** [comment]
Hi @hudochenkov . I did not forget about the PR. I am traveling but I will read the request again as fast as possible. :)

**Comment by saulotoledo** [comment]
@hudochenkov I did some tentatives to use `line` and `index`, but no success. A good example are multiline comments (the "newlines" above are just examples):

```javascript
/**\n
 * This is a\n
 * multiline\r\n  <- there is an error here
 * comment\n
 */\n
```
I can just report the last line and do a lot of processing and "ifs" in the code to discover the line and index numbers for the problem in the middle of the comment.

There are also other situations. I am not sure about the exact cases because I was trying to test with comments. I was solving one by one, but the code was a bit complex with with many cases. The above version sounds better for me. If you want I can still share the unfinished solution in another branch.

**Comment by jeddy3** [comment]
> -   Added: `linebreaks` rule ([#3289](https://github.com/stylelint/stylelint/pull/3289)).

**Comment by ntwb** [comment]
Welcome to the @stylelint organisation @saulotoledo  🎉

**Comment by saulotoledo** [comment]
Thank you @ntwb! I'm happy with the invitation.

**Pull request merged**
