### PR TITLE
Add "/" as valid character after right parenthesis

### PR DESCRIPTION
**Pull request by dsine-de**
... to allow e.g. line-height shorthand value in "font" property:
font: calc(16px + .2vw)/1 sans-serif;

> Which issue, if any, is this issue related to?

#3132

> Is there anything in the PR that needs further explanation?

No, it's self explanatory.

### CODE REVIEW

**Comment by ntwb** [comment]
Thanks for the pull request @dsine-de 👍 

Could you update the _"This rule does not check for space immediately after `)` if the very next character is `,`,` )`, or` }`, allowing some of the patterns exemplified below."_ section of the `function-whitespace-after` rule docs [readme.md](https://github.com/stylelint/stylelint/blob/master/lib/rules/function-whitespace-after/README.md) please.

This will also [need some tests](https://github.com/stylelint/stylelint/blob/master/lib/rules/function-whitespace-after/__tests__/index.js) covering both the `always` and `never` rule options

**Comment by Arcanemagus** [comment]
A concern I had was that this may be valid for `font`, but this PR is making it valid for _any_ position after a `)`. Does that actually make sense? Or should this be limited to `font` somehow?

**Comment by ntwb** [comment]
@Arcanemagus I'm also adding some comments to the #3132 issue, we should probably discuss these there.

**Comment by jeddy3** [comment]
@dsine-de Are you able to add some tests to this PR so that we can merge it?

**Comment by dsine-de** [comment]
I'll do that in the next few days!

**Comment by evilebottnawi** [comment]
Closing due to inactivity in favor https://github.com/stylelint/stylelint/pull/3346

**Pull request closed without merging**
