### PR TITLE
Fix #309

### LINKED ISSUE #309: hierarchicalSelectors option
I just add `hierarchicalSelectors`option in https://github.com/stylelint/stylelint-config-cssrecipes

With this code it's work:

```css
.r-Grid {
  color: red;
}

  .r-Grid-cell {
    text-align: center;
  }
```

But not with this one:

```css
:root {
  --Grid: #fff;
}

.r-Grid {
  color: red;
}

  .r-Grid-cell {
    text-align: center;
  }
```

I have that error:

```
6:3     ⚠  Expected indentation of 4 spaces at line 6 (indentation) [stylelint]
```

Line 6 is ` color: red;` If I add 4 spaces before its value, there is no more error.

### PR DESCRIPTION
**Pull request by davidtheclark**

### CODE REVIEW

**Comment by magsout** [comment]
woot, works fine. Good job :+1:

**Comment by MoOx** [comment]
nice!

**Comment by MoOx** [comment]
When I push something, I like to prepare a release asap by adding the entry in the CHANGELOG. It helps to write a nice commit message because the line of the changelog needs to be explicit, so you get a nice commit message + a changelog already prepared.
The opposite (or complementary) approach is to directly use a smart commit message in order to generate changelog.
I am currently thinking about this https://github.com/semantic-release/semantic-release

**Comment by davidtheclark** [comment]
I can add note in changelog. I had been doing that after merges. But it makes sense to include it in the PR.

**Comment by MoOx** [comment]
It's also nice to include a link to an eventual issue or PR so curious people can take a look to the origin of the fix/add/change.

**Pull request merged**
