### PR TITLE
Add Node.js 10 to CIs

### PR DESCRIPTION
**Pull request by DanielRuf**
This PR adds Node.js to the builds to test against the current stable release of Node.js.

> Is there anything in the PR that needs further explanation?

"No, it's self explanatory."

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@DanielRuf Thanks again :smile: Please use 10 for `CI=pretest` and remove 9 node

**Comment by DanielRuf** [comment]
> @DanielRuf Thanks again 😄 Please use 10 for CI=pretest and remove 9 node

Done.

**Comment by DanielRuf** [comment]
It seems we caught some test failures. Will take a look at them in the next days, testa and fix them.

**Comment by hudochenkov** [comment]
This PR partially duplicates https://github.com/stylelint/stylelint/pull/3281.

**Comment by DanielRuf** [comment]
But tests both platforms (Ubuntu / Linux and Windows).

I will check the unit tests then and try to find solutions.

**Comment by ntwb** [comment]
It looks like the failures are still the same as documented on https://github.com/stylelint/stylelint/pull/3281#issuecomment-385133239

**Comment by jeddy3** [comment]
> I will check the unit tests then and try to find solutions.

That would be great! If nothing springs out at you though, then we could wait to see if it's something upstream that gets fixed.

**Comment by evilebottnawi** [comment]
Very strange i don't have problem with `nodejs@10` local testing :confused:

**Comment by DanielRuf** [comment]
> Very strange i don't have problem with nodejs@10 local testing 😕

On Windows?

**Comment by evilebottnawi** [comment]
@DanielRuf no linux, Ubuntu 18.04

**Comment by hudochenkov** [comment]
@evilebottnawi I've restarted Travis after your comment. Now the build is green, which leads to a conclusion that there were bugs in Node, which were fixed. I'll restart Appveyor.

**Comment by DanielRuf** [comment]
> @evilebottnawi I've restarted Travis after your comment. Now the build is green, which leads to a conclusion that there were bugs in Node, which were fixed. I'll restart Appveyor.

Or a depdenceny as we do not use a lockfile afaik.

**Comment by evilebottnawi** [comment]
@hudochenkov we have a lot of problem in `webpack` with Travis, sometimes looks node where CI running is overload and `jest` failed after standard timeout, maybe will be great increase standard value

**Comment by DanielRuf** [comment]
See https://github.com/facebook/jest/tree/master/packages/jest-jasmine2 as there were changes in the last days.

Travis not the issue afaik.

**Comment by DanielRuf** [comment]
Also check the table at https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System

**Comment by hudochenkov** [comment]
> Or a depdenceny as we do not use a lockfile afaik.

True. Either way, it works now :)

**Pull request merged**
