### PR TITLE
Stream, standalone, cli; addresses #288

### PR DESCRIPTION
**Pull request by davidtheclark**
This introduces a first draft of few things. I'll write up a little proto-documentation of what's in place to help explain. I made a lot of assumptions about APIs, etc., so please share feedback and I'll revise as we see fit.

There are two new exposed functions and a CLI. This also makes rule severity levels meaningful and means `.stylelintrc` files can be a reality.

**In everything below, if no `config` is explicitly provided, stylelint will use [rc](https://github.com/dominictarr/rc) (via [rc-loader](https://github.com/MoOx/rc-loader)) to find a `.stylelintrc` configuration file in the usual configuration-file places, in JSON, YML, or CommonJS format.**

---

## stylelint.lint(options)

Options:
- `files` (*required*): A file glob, ultimately passed to [node-glob](https://github.com/isaacs/node-glob) to figure out what files you're referencing
- `config` (optional): A stylelint configuration object
- `formatter` (optional): By default, [postcss-reporter](https://github.com/postcss/postcss-reporter)'s minimal formatter is used. Alternately, you can pass a function that
  - accepts an object containing a `messages` array and a `source` string
  - returns a string

Returns a Promise that resolves with an object containing the following properties:

- `output`: String. A string displaying the formatted warnings (using the default formatter or whichever you passed)
- `errored`: Boolean. If `true`, at least one rule with a severity of `2` registered a warning
- `results`: An array containing all the [PostCSS LazyResults](https://github.com/postcss/postcss/blob/master/docs/api.md#lazyresult-class) that were accumulated during processing

```js
var stylelint = require('stylelint');
var myConfig = require('./myConfig.js');

stylelint.lint({ files: 'all/my/stylesheets/*.css', config: myConfig })
  .then(function(data) {
      /* do things with data.output, data.errored, and data.results */
  });
```

## stylelint.lintStream([options])

Options:
- `files` (optional): A file glob, ultimately passed to [node-glob](https://github.com/isaacs/node-glob) to figure out what files you're referencing
- `config` (optional): A stylelint configuration object

Returns a Transform stream, which expects a readable stream of CSS or a file glob as input, runs each chunk (string or file) through stylelint, and for each chunk provides a [PostCSS LazyResult](https://github.com/postcss/postcss/blob/master/docs/api.md#lazyresult-class) object containing the messages logged by stylelint.

```js
// Using a file glob and a config object
var stylelint = require('stylelint');
var myConfig = require('./myConfig.js');

stylelint.lintStream({ files: 'myStyles.css', config: myConfig })
  .on('data', function(result) {
      /* do things with the result */ 
  });
```

```js
// Using an input stream and loading config from .stylelintrc
var stylelint = require('stylelint');

function createMyCssStream() { .. }

var myCssStream = createMyCssStream();

myCssStream
  .pipe(lintStream())
  .on('data', function(result) {
      /* do something with the result */ 
  });
```

---

Then there is also

## The CLI

`stylelint --help` should print the following:

```
  Modern CSS linter

  Usage
    stylelint [input] [options]

  By default, stylelint will look for a .stylelintrc file in JSON, YML, or CommonJS format,
  using rc to look in various places (cf. https://github.com/dominictarr/rc#standards).
  Alternatley, you can specify a configuration file with options.

  Input
    A file glob (passed to node-glob).
    You can also pass no input and use stdin.

  Options
    --config  Path to a configuration file in JSON, YML, or CommonJS format.
```

And you use it just like that. It outputs formatted results into `process.stdout` (`console.log`), which you could just read or pipe elsewhere.

```
stylelint path/to/things/*.css
```

```
echo "a { color: pink; }" | stylelint
```

```
stylelint path/to/things/*.css --config path/to/myConfig.yml > myTestReport.txt
```

**If at least one rule with a severity of 2 triggered a warning, the process will exit with code 2.**

(Once we have an alternate formatter, we'll want to add a `--formatter` CLI option.)

---

**So that's a lot of things.**

I imagine that very few people would use `stylelint.lintStream()`, but who knows? It's the backbone of `stylelint.lint()`, which is itself the backbone of the CLI, and a stream is always a good thing to have.

Please think about these APIs, review the code, if possible try it out, find my mistakes and typos ——this is first draft stuff, who knows if it will work.

Looking forward to feedback!

### CODE REVIEW

**Comment by davidtheclark** [comment]
Before finalizing anything we may want to do the following:

- Create at least one alternate formatter that people might want to use. Any suggestions? cf. https://github.com/CSSLint/csslint/wiki/Command-line-interface#--format
- More exit codes and additional errors anticipating common mistakes? cf. https://github.com/brigade/scss-lint#exit-status-codes
- More real-project testing to make sure the stuff works as anticipated
- Consider other CLI & standalone options, cf. https://github.com/CSSLint/csslint/wiki/Command-line-interface#options

At the same time, I don't want to delay the release indefinitely for features that could be added without breaking changes. My goal would be to add all the features that we need to ensure that we're happy with the API, don't plan to break it anytime soon, and can add other things we anticipate wanting to add (without breaking).

**Comment by jeddy3** [comment]
Oh wow! So much goodness.

@davidtheclark I'm off on holiday at the end of next week, so I've jumped back online now to try to contribute some thoughts to this before my hols.

I tried the JS Api (both streams and lint) and the CLI, and everything went really well :) It felt intuitive and familiar. I was able to run them all across multiple files with a simple config and with `stylelint-config-suitcss`.

I've read through the code and it all made sense to me. I'm afraid I can't offer useful critique of the design decisions though, as this is new territory for me.

> By default, postcss-reporter's minimal formatter is used + Create at least one alternate formatter that people might want to use. 

Would having a "stylish" reporter (e.g. `postcss-reporter` with icons etc turned on) as default be preferable? And then "minimal"/"compact" can be the first alternate formatter. There doesn't seem to be consistency between the other linters on this choice though: eslint seems to default to stylish, whereas scsslint keeps it simple. Either way, I think "stylish" and "compact"/"minimal" make good candidates for the first formatter.

> More exit codes and additional errors anticipating common mistakes?

This is nice and builds on what @codemakerlive was saying in https://github.com/stylelint/stylelint/issues/26#issuecomment-132153608 . "`66 - One or more files specified were not found`" and "` 80 - Files glob patterns specified did not match any files`" seem really useful to us. Also, I think "`78 - Invalid configuration file`" is a good candidate as it builds on the options-validator work?

> More real-project testing to make sure the stuff works as anticipated

@m-allanson You tend to use CLI tools in your build chain, right? If you have a mo, would you mind giving this branch a whirl?

> Consider other CLI & standalone options, cf.

Nothing really jumps out from that list, except maybe `exclude`/`ignore-path`.

> In everything below, if no config is explicitly provided, stylelint will use rc (via rc-loader) to find a .stylelintrc configuration file

It might be a nice user experience if we we're able to implement [this syntax](http://eslint.org/docs/developer-guide/shareable-configs.html#using-a-shareable-config), to extend shareable configs, for when we release this branch e.g.:

```js
extends: suitcss, 
rules: {
  indentation: [2, "tab"]
}
```

If only to make the process of using a shareable config, when using a `.stylelintrc` a little easier out of the box. Thoughts?

> My goal would be to add all the features that we need to ensure that we're happy with the API, don't plan to break it anytime soon, and can add other things we anticipate wanting to add (without breaking).

Sounds sensible to me :)

Finally, I'm going to shout out a mention to @kungfusheep and @1000ch, as authors of the sublime and atom plugins respectively, in case they have any input.

Thanks again for all your continued hard work on this project @davidtheclark ! It's amazing to see how much you've achieved in the last few months!

**Comment by davidtheclark** [comment]
I've thought about things a little more and propose:
- Remove `lintStream.js`, just have `standalone.js`
- Allow `standalone.js` to accept a `css` property that is a CSS string (as an alternative to the `files` glob)
- Create a JSON reporter, that returns an array of warning objects, e.g.
  ```json
  [
    { 
      "source": "path/to/file ...", 
      "line": 3, 
      "column": 23, 
      "message": "You can't ...", 
      "rule": "something-something" 
    },
    ..
  ]
  ```

I'm getting frustrated by `extends:`. They are definitely useful, but raise *a lot* of problems. I'll keep plugging away and see if I can come up with something that works.

**Comment by davidtheclark** [comment]
**Would there be any real downside to only allowing CommonJS configuration files?**

This would make a lot of things easier.

Just a thought.

**Comment by davidtheclark** [comment]
Running into a pretty significant problem with CommonJS configs: `rc` can't understand internal `require` calls (e.g. if you say `extends: require('other-config')`) — I think probably because of https://github.com/pierrec/node-eval/issues/3.

Ugh.

If anyone's curious, the big problem I'm having with extends is the resolution of relative paths in objects that are passed directly as configuration. For example, if you do `gulpPostcss([ stylelint(config) ])`, that `config` object might contain an `extends` prop with a relative path — but relative to what? Ideally it would be relative to wherever it is actually written down ... but I don't think we can know where that was, reliably. 

We could require that people use absolute paths if they are going to pass the config object directly, instead of relying on `rc` to find it. But while CommonJS configs could easily get the absolute path, JSON configs could not: they would have to be manually entered, which kind of sucks.

Additionally, `extends` are going to throw `rc` for a loop, because `rc` doesn't know how to interpret them itself, so we'd have to use a custom `rc` parser to interpret those. (But we'd still have the same relative path problem, I think.)

Can anybody see a nice way out of this?

**Comment by ismay** [comment]
> Would there be any real downside to only allowing CommonJS configuration files?

I wouldn't mind that. Also extending isn't crucial for my use case. Both extends and other syntax are nice to have, but I wouldn't really miss them.

Other than that I'm not sure whether I have anything meaningful to contribute to this disscusion. But I'll comment should I find anything.

**Comment by kungfusheep** [comment]
Moving away from a JSON format for the `rc` potentially causes a back-compat issue in my case - but it's not the end of the world if stylelint improves as a result.  

Did anything happen in regards to a `.postcssrc` file? I seem to remember this had been proposed at one point? It would be nice if the postcss eco-system had 'one `rc` to rule them all' in my opinion, though at the same time I don't see why supporting both would be an issue if it ever came to be. 

As for the formatter, the sublime plugin uses a custom formatter anyway so it will be unaffected by this change.

**Comment by davidtheclark** [comment]
# Second Draft

Thanks everyone for your input. Here's some updated proto-documentation to explain what I've done:

## Preliminaries

There is no more `stylelint.lintStream()`. I spoke to someone more knowledgeable about streams, who suggested that because of the size (small) of the files we deal with and the way that streams one (throttling), a stream probably wasn't actually more efficient than a synchronous glob analysis and some async file reading.

## Formatters

I made two two formatters: one that outputs straight JSON (`"json"`), another that uses `postcss-reporter`'s standard formatter without icons or plugin name (`"string"`). We or users can create other formatters with functions that output a string and accept *an array of these stylelint result objects**:

```js
{
  source:  "path/to/file.css", // The filepath or PostCSS identifier like <input css 1>
  errored: true, // This is `true` if at least one rule with a severity of 2 triggered a warning
  warnings: [ // Array of warning objects, each like the following ...
    {
      line: 3,
      column: 12,
      rule: "block-no-empty",
      severity: 2,
      text: "You should not have an empty block (block-no-empty)"
    },
    ..
  ]
}
```

So any function that accepts an array of these objects and outputs a string can be used as a formatter for the standalone or CLI interfaces.

## stylelint.lint(options)

Options:

Note: Though both `files` and `css` are "optional," you *must* have one and *cannot* have both.

- `files` (optional): A file glob, ultimately passed to node-glob to figure out what files you're referencing
- `css` (optional): A CSS string to be linted
- `formatter` (optional): Either `"json"`, `"string"`, or a function. Default is `"json"`. See above.
- `config` (optional): A stylelint configuration object
- `configBasedir` (optional): If the `config` object passed wants to use `extends` or `plugins`, it is going to have to pass a `configBasedir`, which is an absolute path to the directory that these `extends` and `plugins` are *relative to*. See the examples in `standalone-test.js`.

Returns a Promise that resolves with an object containing the following properties:

- `output`: String. A string displaying the formatted warnings (using the default formatter or whichever you passed)
- `errored`: Boolean. If true, at least one rule with a severity of 2 registered a warning
- `results`: An array containing all the stylelint result objects described above (the objects that formatters consume)
- `postcssResults`: An array containing all the PostCSS LazyResults that were accumulated during processing

Here are some examples:

```js
// If myConfig contains no extends or plugins, I do not have to use configBasedir
stylelint.lint({ 
  files: 'all/my/stylesheets/*.css', 
  config: myConfig 
}).then(function() { .. });

// If it does, I do
stylelint.lint({ 
  files: 'all/my/stylesheets/*.css', 
  config: myConfig, 
  configBasedir: path.join(__dirname, "configs")
}).then(function() { .. });

// Maybe I want to pass a string instead of a file glob, and I want to use the string formatter
stylelint.lint({ 
  css: 'a { color: pink; }', 
  config: myConfig, 
  formatter: "string"
}).then(function() { .. });
```

// This time I want to use my own custom formatter function
stylelint.lint({ 
  css: 'a { color: pink; }', 
  config: myConfig, 
  formatter: function(stylelintResults) { .. }
}).then(function() { .. });
```

## The CLI

`stylelint` --help should print the following:

```
  Modern CSS linter

  Usage
    stylelint [input] [options]

  By default, stylelint will look for a .stylelintrc file in JSON format,
  using rc to look in various places (cf. https://github.com/dominictarr/rc#standards).
  Alternately, you can specify a configuration file via --config.

  Input
    File glob(s) (passed to node-glob).
    You can also pass no input and use stdin.

  Options
    --config                    Path to a JSON configuration file.
    --version                  Get the currently installed version of stylelint.
    -f, --formatter           Specify a formatter: "json" or "string". Default is "string".
    --custom-formatter  Path to a JS file exporting a custom formatting function
```

And you use it just like that. It outputs formatted results into process.stdout (console.log), which you could just read or pipe elsewhere.

**Unlike `stylelint.lint()`, the CLI's default formatter is "string"`.**

The CLI still accepts stdin (if not file glob is passed) and outputs to stdout.

## Something Special

**Configuration files that are not directly passed to the function (because they are found via rc, extended, or referenced via `--config`) can always be in JSON format, sometimes in CommonJS format.**

## Plugins and Extends

Plugins and extends are paths that are ultimately `require()`d, so can fit whatever format works with node's `require.resolve()` algorithm. That means the paths can be:

- The names of modules in `node_modules` (e.g. `stylelint-config-wordpress`, if that module's `main` file is a valid JSON configuration)
- An absolute path to a file
- A relative path to a file, relative to the referencing configuration (e.g. if configA has `extends: "../configB"`, we'll look for `configB` relative to configA).

A configuration's `extends` value can be a single locator or an array of locators.

A configuration's `plugins` value is an object whose keys are rule names and values are locators for the actual plugin functions.

## Exit codes

Only the CLI actually exits the process with exit codes. The standalone `stylelint.lint()` is a promise, so people can `.catch()` errors; and the plugin needs to be handled within the plugin context.

For the CLI, here are the exit codes that might pop up:

- 1: Something just went wrong, who knows
- 2: At least one rule with a severity of 2 triggered at least one warning
- 78: There was some problem with the configuration file
- 80: A file glob was passed both it found no files

Note that rule-specific configuration mistakes (those checked by `validateOptions`) are being logged as PostCSS warnings, so are not in fact errors and therefore do not trigger exit codes.

## Enough!

That's enough typing. I hope this makes sense and at least a lot of it feels right. As I said above, please share feedback, test things out, criticize, etc., so we can get a functional API that pleases everyone!

**Comment by davidtheclark** [comment]
@jeddy3 : To respond to this:

> Would having a "stylish" reporter (e.g. postcss-reporter with icons etc turned on) as default be preferable?

I thought that having the icon turned off would be fine because these are *all* warnings. No need to repeat the icon for every one. But if you or others have other suggestions for prettying up the output, I'm open.

**Comment by ismay** [comment]
@davidtheclark Looks good, awesome work!

**Comment by jeddy3** [comment]
Thanks for persevering with extends!

> I thought that having the icon turned off would be fine because these are all warnings. 

Makes sense and sgtm.

> Note that rule-specific configuration mistakes (those checked by validateOptions) are being logged as PostCSS warnings, so are not in fact errors and therefore do not trigger exit codes.

Yep, I remembered that soon after posting the comment :)

> As I said above, please share feedback, test things out, criticize, etc., so we can get a functional API that pleases everyone!

This all looks great to me!

I'm away for the next couple of weeks, so feel free to merge and release at your discretion if you want to get this out there. And I'll help out where I can when I'm back :)

**Comment by davidtheclark** [comment]
Thanks @jeddy3. I'd actually prefer to wait until you're back to release anything because I could really use the help writing & polishing documentation, double-checking, etc. So let me know when you're back and ready to go. (I myself am away from computers Oct 3-11, so maybe this is bad timing ...)

**Comment by jeddy3** [comment]
I'm back on the 1st, so it looks like being after the 11th before we can both get stuck into this together. I'll try to make a start on the documentation while you're away though. Enjoy your trip, if I don't speak to you before then :)

**Comment by davidtheclark** [comment]
This is getting pretty huge, so I'm going to make a checklist of items that this branch contains that we need to make sure to document and test sufficiently before releasing:

- [ ] using `stylelint.lint()` (standalone)
- [ ] using the CLI
- [ ] using formatters
- [ ] writing custom formatters (incl. the stylelint result object format)
- [ ] existing JSON formatter
- [ ] existing string formatter
- [ ] different ways to load configuration (incl. all the places rc looks in)
- [ ] using plugins
- [ ] using extends
- [ ] quiet mode

That's all I can think of. Sorry that I did not go about this in the smartest way ... I let it balloon.

**Comment by efx** [comment]
+1 for creating this API and cli tool. This easier way to integrate stylelint will be most welcome.
Given these changes, if I wanted to adapt an existing rule would I create that as a plugin or use extends?
e.g. I decided to lint my LESS files and am seeing the indent rule give warnings  for 
```less
@myVar: {
  color: red;
}
```
This behavior is expected, but I would want to override or extend the indent rule setting for this particular syntax.

**Comment by davidtheclark** [comment]
@efx : You would create a plugin. Plugins are how we want to allow users to add their own non-standard rules. I've created one so far to enforce nesting levels, so you could use that as a starting point: https://github.com/davidtheclark/stylelint-statement-max-nesting-depth

**Comment by davidtheclark** [comment]
Also @efx : There's some documentation about making plugins here: https://github.com/stylelint/stylelint/blob/master/docs/developer-guide.md#plugin-rule-specific-guidelines

**Comment by efx** [comment]
@davidtheclark great thanks for the clarification! I'll use those links as a guide.

**Comment by colepeters** [comment]
@davidtheclark This looks awesome! I was just looking into the potential of bringing Stylelint checking to [neomake](https://github.com/benekastah/neomake) and realised I couldn’t do so without a CLI. +1million for putting this together! Looking forward to the release.

**Comment by jeddy3** [comment]
I'm back. 

> This is getting pretty huge,

Wow, so much good stuff.

Now that we have the nod from the atom and sublime guys, is it just further testing and the documentation that's left to do?

I'll try a first run at the documentation while you're away.

**Comment by davidtheclark** [comment]
Glad you're back! Yes, I think I've written in all the features I thought we wanted, so we just need to test and document before releasing. Of course, automated tests are there (though if you want to add to those, great); but I'm more concerned about end-to-end testing, I guess ---- ensuring it actually works as expected in a real workflow. Make sense?

**Comment by jeddy3** [comment]
> Yes, I think I've written in all the features I thought we wanted

Yep, it looks pretty amazing and feature complete to me!

> Make sense? 

Yep. Once the documentation is done (and I've tested what I can) we could solicit help from a few of the early adopters to see how they get on. Whether that's using this branch, or a release candidate approach. We can discuss this more when you're back from your hols though (after the 11th), so that we'll both be about to answer their questions. Sound good?

**Comment by TrySound** [comment]
@davidtheclark yaml for rc is pretty good. I use it for eslint and the same would be good for stylelint.

**Comment by jeddy3** [comment]
I've had 1st shot at the documentation. I've followed eslint's approach of keeping the main README for outlining the features and very the simplest way to get something, anything, working. I’ve then try to create a coherent whole in the user guide - explaining everything the user needs to know about using and configuring the linter.

I've been testing a bit too. A couple of issue have popped up. After a initial poke around, it looks like your last commit ("quiet mode") clobbered the config some how, which I think is causing at least one of the issues.

Things working a treat:

1. The Standalone JS API. 
    * + all its options: css, files, formatter and config.
    * + not specifying a config and it finding `.stylelintrc`
    * + beautifully handling `extends` within the  `.stylelintrc`
    * + correctly throwing an error when I didn't have `stylelint-config-suitcss` installed.

Issues:

1. The CLI throws an error: `Error: No rules found within configuration`. (I think this is connected to the quiet mode commit).
2. Using the linter as PostCSS plugin (both through the PostCSS JS API and though postcss-gulp) throws an error: `TypeError: Cannot read property 'hasOwnProperty' of undefined`.

Any ideas?

Also, while it's on my mind, what are you thoughts on including an `stylelint --init` command that'll write a `.stylelintrc` file to the current directory? Perhaps we bundle `styleguide-config-suitcss` in there as it seems to be the most unambiguously documented. It'll make the whole "getting started with stylelint" a tad easier.

**Comment by davidtheclark** [comment]
@jeddy3 : I am going to first look into fixing those problems, then read over the documentation you wrote (thanks!).

> Perhaps we bundle styleguide-config-suitcss in there as it seems to be the most unambiguously documented.

Bundle it in where?

**Comment by davidtheclark** [comment]
@MoOx, @TrySound: I went through a lot of iterations when trying to figure out how to get extends and plugins to work best. You know what, I probably just reduced to rc for simplicity's sake at some point then forgot to try switching back to rc-loader to enable YAML. I will try it out again and hopefully it will work well. Thanks for the reminder.

**Comment by davidtheclark** [comment]
BTW: Having just gotten back from a long backpacking trip, I'm surprised at how foreign and weird code feels to me. I might be a little slow for a few days as I get back into the swing of things.

**Comment by jeddy3** [comment]
> BTW: Having just gotten back from a long backpacking trip

Welcome back! :)

> I'm surprised at how foreign and weird code feels to me.

Ha, I know that feeling. I was driving around Utah in a campervan for that week I was away. Open skies and campfires every night, and not a computer for miles around. Don't worry, it'll be like it happened in a weeks' time... all you'll see is code and your backpacking trips will seem like a distant memory... unfortunately :)

**Comment by davidtheclark** [comment]
> I was driving around Utah in a campervan for that week I was away

Wow -- I was in Utah, too. Hiked in the Escalante area. Where did you go?

**Comment by davidtheclark** [comment]
@jeddy3 : Could you see if the latest commit allows you to use the CLI and plugin? It introduces new feature, too, which is `configOverrides`, available to the plugin and API (CLI will use this for `--quiet` and other similar future flags). 

The difference between `config` and `configOverrides` is this: If you pass a `config`, we'll assume that's what you want to use as config and we will not use rc to search for a `.stylelintrc` file. If instead you pass `configOverrides`, we will use rc to find `.stylelintrc` and then apply your overrides on top of that. Does this seem intuitive, and like a good solution?

**Comment by jeddy3** [comment]
> Wow -- I was in Utah, too. Hiked in the Escalante area

Nice! I hope you had an awesome time :)

> Where did you go?

On our last night on the road we camped in Dixie National Forest. So, just a stone's throw west from where you were! Beautiful part of the world. All the silver birch leaves were turning yellow too. Quite quite spectacular.

I flew to Vegas, and so we started and ended our campervan trip there. We loop around the Grand Canyon, taking in a bit of Nevada, Arizona and Southern Utah. We went as far East as Monument Valley, before looping back around the northern rim of the Grand Canyon. We did as much day-hiking as we could: Oak Creek near Flagstaff, in Monument Valley, and a bit of Buckskin Gulch slot canyon in Southern Utah. It was hot hot hot in desert :)

**Comment by davidtheclark** [comment]
Good choice for a US vacation! (Am I right in thinking that you live in England?) I've spent a lot of time hiking around Utah since I first bought a backpack, and I've lived in Arizona the past few years. On this trip our longest hike started high up in the fall colors of the Dixie National Forest and went down through an amazing canyon, called Death Hollow, to the Escalante River.

**Comment by jeddy3** [comment]
> Could you see if the latest commit allows you to use the CLI and plugin?

CLI now finds `.stylelintrc` :)

I'm not sure if the `extends` is working correctly though. I have the following in my `.stylelintrc`:

```json
{
  "extends": "stylelint-config-suitcss",
  "rules": {
    "indentation": [2, "tab"]
  }
}
```

But the CLI isn't picking up on the overriding `"indentation": [2, "tab"]`, and instead uses the 2 space `indentation` rule from `stylelint-config-suitcss`.

The postcss plugin (both via the JS API and `gulp-postcss`) now throw `Error: No rules found within configuration`. Should the plugin also search for `.stylelintrc`, or does it require the config to be passed in?

> If instead you pass configOverrides, we will use rc to find .stylelintrc and then apply your overrides on top of that. Does this seem intuitive, and like a good solution?

SGTM :)

**Comment by davidtheclark** [comment]
Ugh. I need to figure out how to write good tests for all these damned setups.

**Comment by jeddy3** [comment]
> our longest hike started high up in the fall colors of the Dixie National Forest and went down through an amazing canyon, called Death Hollow, to the Escalante River.

Oh wow. I just looked up the Death Hollow trail. Looks like an amazing hike!

> Am I right in thinking that you live in England?

That's right. I was in Vegas for a bachelor party. I figured I'd make the most of my trip over, and so me and friend rented a little campervan and took in as many sites and hikes as we could in the surrounding area for a week :)

It was my first time driving through Northern Arizona. You live in dramatically beautiful part of the world :)

**Comment by davidtheclark** [comment]
@jeddy3 : Please try again. I introduced a slight difference, also: before, if you had an array of extends the *bottommost* would take priority (overriding those above); now, the *topmost* will take priority (overriding those below).

**Comment by jeddy3** [comment]
Super nice, thanks!

CLI, JS API, PostCSS JS API, and postcss-gulp all work as expected. Successfully finding the `.stylelintrc`, correctly extending `stylelint-config-suitcss` by overriding `indentation` with the `tab` rule.

:tada:

FYI, it's getting late here and so I'm going to call it a night. I'll respond to anything new in the morning.

Welcome back again :)

**Comment by davidtheclark** [comment]
@MoOx, @TrySound, @jeddy3: I just remembered why I opted to stick with straight JSON configs instead of allow YAML. It's because I'm actually relying on the ability to use `require()` for the `extend` and `plugin` functionality. I can `require()` JSON and CommonJS but not YAML. If I use rc-loader, then your root configuration could be YAML, but you couldn't successfully `extend` a YAML config. Does this make sense?

**Comment by TrySound** [comment]
@davidtheclark Not sure I understand the problem. Did you look at eslint extending?

**Comment by davidtheclark** [comment]
@jeddy3 : I had a look over the revised documentation, and my main concern is that the user guide is way too long. It feels very intimidating and kind of confusing, even to me, at that length, with all those variations in the same place. I think it might help if we create separate documents for the following:

- CLI
- JS API
- PostCSS Plugin
- Configuration

Then the User Guide could be very compact, linking to those pages for more details.

What do you think about that?

**Comment by davidtheclark** [comment]
@jeddy3 : Also, I think that if the CLI and API and plugins are all working as expected, maybe we should merge the branch, close this ridiculous issue, and start another issue for documentation (and testing/refinement) of all the things. Seem good?

**Comment by davidtheclark** [comment]
cf https://github.com/stylelint/stylelint/issues/411

**Pull request merged**
