### PR TITLE
Fix #1022

### LINKED ISSUE #1022: Add support for end of line comments to function-comma-newline-after
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

I've got a scss list with comments at the end of the line. As with `block-closing-brace-newline-after`, this is not allowed by the rule. There are two things that struck me:
- The rule is triggered by the comment
- The scss list is handled as a function (although I'm not sure if that's intended behaviour)

I've prepared failing rules for those cases, but wanted to check first if they are regarded as errors.

> Which rule, if any, is this issue related to?

`function-comma-newline-after`

> What CSS is needed to reproduce this issue?

e.g.

```css
  $colors: (
    red, /* stylelint-disable-line color-named */
    #fff,
    #ddd,
  );
```

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
    "function-comma-newline-after": "always-multi-line"
  }
}
```

> Which version of stylelint are you using?

`4.3.2`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

gulp-stylelint

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Related to SCSS lists

> What did you expect to happen?

"No warnings to be flagged.

> What actually happened (e.g. what warnings or errors you are getting)?

"The following warnings were flagged:

```shell
error  Expected newline after "," in a multi-line function   function-comma-newline-after
```

### PR DESCRIPTION
**Pull request by Nirazul**
This PR should fix #1022 and following rule with it:
- `function-comma-newline-after`

Fix location:
- `functionCommaSpaceChecker`

As this method is also used in some other places, I've added some tests to ensure that nothing is broken in following rules:
- `function-comma-space-after`
- `function-comma-newline-before`
- `function-comma-space-before`

I've also extracted all tests related to syntax `scss` into separate testing blocks.

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@Nirazul use rebase

**Comment by evilebottnawi** [comment]
@Nirazul thanks for support project

**Comment by Nirazul** [comment]
@evilebottnawi 
Where do I need to use rebase? I've never used it before.

**Comment by evilebottnawi** [comment]
@Nirazul `revert` to commit before you start coding, then update `master` branch, checkout on you branch and run `git rebase master`

**Comment by evilebottnawi** [comment]
@Nirazul All we learn nothing wrong

**Comment by evilebottnawi** [comment]
@Nirazul i think best solution close this PR, get latest `master` branch, add code again and PR this

**Comment by Nirazul** [comment]
Okay, thanks for your help!

**Comment by jeddy3** [comment]
@Nirazul FYI, this is the tutorial I read on rebasing: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

Summarised as:

0. (if necessary) [squash your commits](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request#squash-your-changes).
1. `git fetch origin`
2. `git rebase master` (will complain about conflicts)
3. Use your editor to fix the conflicts.
4. `git add <fixed files>`
5. `git rebase --continue` (*don't use `git commit`, as it'll mess things up*)
6. `git push -f` (*you must use the `-f` flag, or it'll mess things up*).

If you look through the Pull Request history of the repo you'll see that we've all messed this process up on countless occasions, so don't worry about having to close this PR and create a new one :)

**Comment by Nirazul** [comment]
Thank you very much for your advice. It's encouraging to hear that you messed up at one point or another ^^

**Pull request closed without merging**
