### PR TITLE
Completely ignore files when using standalone

### LINKED ISSUE #1730: standalone.js should deal with ignored files
Right now we decide whether to ignore a file or not after PostCSS has parsed it: https://github.com/stylelint/stylelint/blob/master/src/postcssPlugin.js#L37. There are two problems with this:

1. We don't want to parse files we don't need to parse. That slows things down.
2. The user might not use a special syntax, thinking that her ignore pattern can be used to just ignore scattered SCSS files, for example. But in fact we are trying to parse them before ignoring them, so the user will get a syntax error. I think this is happening to @jacobmischka over at https://github.com/stylelint/stylelint/issues/1693#issuecomment-235761631. —— I don't really understand why you'd end up in this situation, but I'll accept that it can happen :)

We *do* need to apply ignore patterns within `postcssPlugin.js`, because ignoring needs to be applied when people use stylelint as a PostCSS plugin. But we *also* need to apply it in `standalone.js`, which will address the Node API and CLI. So that means any logic should be abstracted out and applied in both places.

Is anybody interested in taking this on? It's a little different than the usual rule-tweaking.

### PR DESCRIPTION
**Pull request by jacobmischka**
Fixes #1730

### CODE REVIEW

**Comment by davidtheclark** [comment]
@jacobmischka Great start! To preserve the current behavior, we'd like it if ignored files were still reported, as before, just not parsed and linted. Ideally the output of the CLI and the stylelint results that get produced do not need to change. We just need to ignore the file before it gets passed to PostCSS ...

**Comment by jacobmischka** [comment]
Oh ha, fair enough. I'll fix it tonight when I'm at a computer.

**Comment by jacobmischka** [comment]
I closed this intending to reopen because I wasn't sure why the CI builds were failing. They're failing because eslint was updated to 3.2.0 and that caused it to complain somewhere new. So that's solved.

However, my solution that I committed in `d96d945` is incorrect, so I'm just going to go ahead and leave it closed for the time being. I'll reopen when I fix it.

**Comment by davidtheclark** [comment]
@jacobmischka Does that fact that this re-opened mean you're ready for another look?

**Comment by jacobmischka** [comment]
Yes, sorry.

**Comment by davidtheclark** [comment]
@jacobmischka Ok, so it looks like you've preserved all the existing functionality, because you didn't have to delete any tests. Most of the way there. But we also need to *add new tests* that test the new functionality that this PR introduces. Does that make sense?

**Comment by davidtheclark** [comment]
@jacobmischka Any update on this?

**Comment by jacobmischka** [comment]
Sorry, I've been sightseeing on vacation this week and working to finish up projects before I left last week, so I haven't had any time to revisit this yet. I'll be able to on Monday once I've returned from my trip.

Sorry for the delay, if anyone else wants to complete this before I'm back I understand. Otherwise, I'll submit tests on Monday.

**Comment by davidtheclark** [comment]
Ok! I was just checking that the branch wasn't abandoned.

**Comment by jacobmischka** [comment]
I'm not entirely sure how you envisioned this being done. I don't see the need to add any additional tests, but I added some assertions. This is what I was doing when I altered the tests before, I wasn't just removing tests because they didn't pass. Though this way is less destructive.

I'm also not sure what appveyor's deal is, all I see is `AppVeyor was unable to...`. So please let me know what's wrong and I'll deal with it.

**Comment by davidtheclark** [comment]
> I wasn't just removing tests because they didn't pass

Haha, yeah I assumed that.

This looks great. There's one more test I think we should add that gets back to the root issue (#1730): let's create a standalone test where the syntax is standard CSS; the input file glob actually contains some SCSS files with `//` comments; and the `ignoreFiles` property causes those SCSS to be ignored. 

If you've solved that original issue, we should see no syntax errors because the SCSS will never be parsed. Make sense?

**Comment by jacobmischka** [comment]
To the best of my knowledge it's not possible to force the syntax to be standard CSS, I'm not sure if I understood what you meant correctly.

Instead I've just used front matter to create a syntax error instead, as that's what was causing the problem in the first place.

**Comment by davidtheclark** [comment]
@jacobmischka Great work! Let's merge.

**Pull request merged**
