### PR TITLE
Cleanup tests

### LINKED ISSUE #2164: Unhandled promise rejections are deprecated
Via https://travis-ci.org/stylelint/stylelint/jobs/181025542

```shell
...
 PASS  lib/utils/__tests__/report.test.js
(node:2404) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 27): Error: expect(received).toBeTruthy()
Expected value to be truthy, instead received
  false
(node:2404) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 PASS  lib/utils/__tests__/isStandardSyntaxRule.test.js
...
```

### PR DESCRIPTION
**Pull request by davidtheclark**
These corrections should fix #2164.

### CODE REVIEW

**Comment by jeddy3** [comment]
Awesome. Looks great to me. We can deal with node 4 elsewhere.

**Comment by ntwb** [comment]
Awesome, thanks 👍

**Comment by ntwb** [comment]
_Looks like v4 tests are now passing, maybe an isolated Travis CI explosion..._

**Comment by davidtheclark** [comment]
@ntwb: I think they were failing because of the memory leak, which is fixed with the latest version of cosmiconfig.

**Pull request merged**
