### PR TITLE
Fixed: false positives for some properties in `value-keyword-case`.

### PR DESCRIPTION
**Pull request by evilebottnawi**
> Which issue, if any, is this issue related to?

https://github.com/stylelint/stylelint/issues/1997

> Is there anything in the PR that needs further explanation?

No, it's self explanatory.

Ref to properties and their values:
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color-rendering
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/image-rendering
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/pointer-events

### CODE REVIEW

**Comment by jeddy3** [comment]
Nice! Thanks for supplying the references.

**Comment by davidtheclark** [comment]
Added not to changelog: 

> Fixed: false positives for some camel-case SVG keywords in `value-keyword-case`.

I should try to remember to add this comment every time, so it's easier to catch if I've forgotten.

**Comment by jeddy3** [comment]
> I should try to remember to add this comment every time, 

Sounds like a plan.

**Pull request merged**
