### PR TITLE
Add parameters to a release issue URL

### PR DESCRIPTION
**Pull request by ybiquitous**
> Which issue, if any, is this issue related to?

None, as it's a documentation fix.

> Is there anything in the PR that needs further explanation?

The following JS snippet can create the URL:

```js
const params = new URLSearchParams();
params.append('title', 'Release {version}');
params.append('labels', 'status: needs discussion');
console.log(`https://github.com/stylelint/stylelint/issues/new?${params}`);
```

https://github.com/stylelint/stylelint/issues/new?title=Release+%7Bversion%7D&labels=status%3A+needs+discussion

### CODE REVIEW

**Review by jeddy3 — APPROVED** [review]
Neat, thanks.

**Comment by ybiquitous** [comment]
@jeddy3 Thanks. Can I open an issue for the release v14.10.1? Maybe, I can have time to do it this weekend.

**Comment by jeddy3** [comment]
> @ybiquitous Thanks. Can I open an issue for the release v14.10.1? Maybe, I can have time to do it this weekend.

Yes, please do! I should be around until this coming Thursday (then I'll be offline for 10 days). So I can assist you or answer any queries if you put out a release before then.

**Comment by ybiquitous** [comment]
Thank you. Opened #6280

**Pull request merged**
