### PR TITLE
Start on color-no-almost-identical

### PR DESCRIPTION
**Pull request by davidtheclark**
This is a start. More documentation needs to be written. And I wonder if @jeddy3 has a better idea for the name.

If anybody has feedback on the implementation or ideas for tests and documentation please share!

cc/ @SlexAxton

### CODE REVIEW

**Comment by jeddy3** [comment]
> And I wonder if @jeddy3 has a better idea for the name.

I think what we're doing here is disallowing imperceptible differences in color. I think you're right to make it a `no` rule as it doesn’t make sense to enforce the opposite i.e. requiring that all colors be imperceptibly different. Also, we already have another rule based on human perception: `time-no-imperceptible`.

So, how's about `color-no-imperceptible-differences`?

**Comment by davidtheclark** [comment]
`color-no-imperceptible-differences` is like another name I was considering: `color-no-indistinguishable`. I wasn't sure about that because I am not really sure whether colorguard *only* flags colors that are pretty much indistinguishable to the human eye, or if it also (maybe at a higher threshold?) can flag colors that are distinguishable side-by-side but for all intents and purposes probably intended to be identical. @SlexAxton, could you clarify?

**Comment by jeddy3** [comment]
> or if it also (maybe at a higher threshold?) can flag colors that are distinguishable side-by-side

How's about `color-no-similar`? "Similar" feels like it has a broad enough definition. It's then the role of the `threshold` option to decide just how similar is too similar.

@SlexAxton In case you're wondering... there are [over a hundred rules](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#list-of-rules) in stylelint, and so we take time out to name them following a [set of conventions](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#about-rule-names) as to make them a little easier for new users to grok :)

**Comment by SlexAxton** [comment]
It's all based on the threshold you set and your personal eyes. By default
it's set to a threshold where I personally could just start to tell the
tiniest differences. So it's a bit of both, depending on the settings.

**Comment by davidtheclark** [comment]
Based on all the above I prefer `color-no-indistinguishable`.

**Comment by jeddy3** [comment]
> `color-no-indistinguishable`

Sgtm :)

**Comment by davidtheclark** [comment]
Ok, I added all the docs I knew to add. Read for review and merge if you like it.

**Comment by jeddy3** [comment]
Any idea why travis is failing? Is is the capitalisation of "R" in `'postcss/lib/Result'` (https://travis-ci.org/stylelint/stylelint/jobs/110817280#L987)?

**Comment by jeddy3** [comment]
Travis seems happier with a lowercase "r" :)

I've made two minor doc amends:

1. Added the rule to the example config. I didn't catch this with `string-no-newline` and so I just added now in `master`.
2. Aligned the arrows in the lead example. The other day I went through the rule READMEs and pointed all the arrows *at the beginning* of the thing they were highlighting as they were a bit all over the place.

It's awesome to see the first of the linter integration rules go in! Thanks for doing it.

I'm going to mark this PR as reviewed and call it a night. Are you OK to merge once appveyor goes green?

**Comment by davidtheclark** [comment]
> Added the rule to the example config. I didn't catch this with string-no-newline and so I just added now in master.

I kept looking for that but was looking for a JSON file, not a Markdown file. Will catch it next time.

Thanks.

**Pull request merged**
