### PR TITLE
Fix false positives for at-root in indentation

### LINKED ISSUE #3168: False positives for at-rules within selectors lists in indentation
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A feature where using SCSS's `@at-root` selector syntax breaks my `indentation` rule.
So I would like to be able to ignore custom keywords, like `@at-root`

> Which rule, if any, is this issue related to?

`indentation`

> What SCSS is needed to reproduce this issue?

````scss
.foo {
  text-align: center;

  @at-root .foo--left,
  .text-left & {
    text-align: left;
  }
}
````

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "extends": "stylelint-config-standard"
}
```

> Which version of stylelint are you using?

`8.2.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

NPM script with `"test-stylelint": "stylelint 'src/**/*.scss'",`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Yes, it's related to SCSS `@at-root` selector syntax.

> What did you expect to happen?

No errors to be thrown.

> What actually happened (e.g. what warnings or errors you are getting)?

The following errors were flagged:

```shell
src/components/m-header-navigation/index.scss
 59:3  ✖  Expected indentation of 4 spaces   indentation
```

**Note**
I also created an issue at `stylelint-scss`, but it wouldn't make much sense to basically copy the most of the `indentation` rule just for scss.
https://github.com/kristerkari/stylelint-scss/issues/206

### PR DESCRIPTION
**Pull request by AndyOGo**
> Which issue, if any, is this issue related to?

fixes #3168 

> Is there anything in the PR that needs further explanation?

No, it's self explanatory.

### CODE REVIEW

**Comment by kristerkari** [comment]
Looks good, but how about adding a test for `reject` too?

**Comment by AndyOGo** [comment]
@kristerkari Thanks for your quick feedback. I added the missing reject test for both `@at-root` and `@nest`.

Btw every time I try to commit, your setup git hook running `prettier` complains and aborts my commit. I have to force it by `--no-verify`. `Prettier` can't autofix either and I don't so what's wrong with the code 🤔

**Comment by jeddy3** [comment]
> Btw every time I try to commit, your setup git hook running prettier complains and aborts my commit.

That's odd. Hopefully, it's just a glitch that'll go away. At the moment the CI is green so there are no formatting revisions to make.

**Comment by hudochenkov** [comment]
> > Btw every time I try to commit, your setup git hook running prettier complains and aborts my commit.
>
> That's odd. Hopefully, it's just a glitch that'll go away. At the moment the CI is green so there are no formatting revisions to make.

@AndyOGo Sorry for inconvenience. It will be fixed by #3232.

@jeddy3 It wasn't caught by CI, because we don't run `npm run prettier:check` in CI :)

**Comment by jeddy3** [comment]
> @jeddy3 It wasn't caught by CI, because we don't run npm run prettier:check in CI :)

Oh wow. I just assumed we did as I have it set up that way for all my day-job projects. I guess we never got around to it. Let's remedy that in another PR.

**Comment by AndyOGo** [comment]
No problem, Good it turns out right :)
I really loved my dev experience 😃

**Comment by jeddy3** [comment]
> -   Fixed: `indentation` false positives for at-root ([#3225](https://github.com/stylelint/stylelint/pull/3225)).

**Pull request merged**
