### PR TITLE
Allow leading newlines for source map and copyright comments

### PR DESCRIPTION
**Pull request by jwilsson**
> Which issue, if any, is this issue related to?

#2120

> Is there anything in the PR that needs further explanation?

I opted for a regexp to check for any kind of whitespace so it will accept tabs as well. Let me know if you want tests for tabs too.

### CODE REVIEW

**Comment by jwilsson** [comment]
I've never worked with Jest before but when looking at the build failure, I'm guessing I need to update the snapshots for it?

**Comment by jeddy3** [comment]
> I'm guessing I need to update the snapshots for it?

The jest snapshots changes look good:

```console
Object {
             "column": 3,
    -        "line": 1,
    -        "rule": "comment-whitespace-inside",
    -        "severity": "error",
    -        "text": "Expected whitespace after "/*" (comment-whitespace-inside)",
    -      },
```

i.e. we are _loosing_ one `comment-whitespace-inside` warning at `1:3`. This is correct as top of the 001 stylesheet looks like so:

```css
/*!
 * Bootstrap v4.0.0-alpha.5 (https://getbootstrap.com)
 * Copyright 2011-2016 The Bootstrap Authors
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 */
/*! normalize.css v4.2.0 | MIT License | github.com/necolas/normalize.css */
```

Where the bootstrap copyright was erroneously triggering a warning (and the normalise one was not)

@jwilsson Yep, press `u` at the interactive menu to update the snapshot, and then commit&push the changes.

**Comment by jwilsson** [comment]
@jeddy3 Cool, thanks for the explanation!

Snapshots are updated.

**Comment by davidtheclark** [comment]
Thanks @jwilsson!

**Comment by davidtheclark** [comment]
Added note to changelog:

> -   Fixed: `comment-whitespace-inside` no longer complains about `/*!` comments with non-space whitespace (e.g. newlines) ([#2121](https://github.com/stylelint/stylelint/pull/2121))

**Pull request merged**
