### PR TITLE
Deprecate *-blacklist/*-requirelist/*-whitelist

### PR DESCRIPTION
**Pull request by kevindew**
> Which issue, if any, is this issue related to?

#4854

> Is there anything in the PR that needs further explanation?

This takes the action suggested in [@jeddy3's comment](https://github.com/stylelint/stylelint/issues/4854#issuecomment-670935654) of replacing the aliasing approach used in https://github.com/stylelint/stylelint/pull/4845 for `*-blacklist`/`*-requirelist`/`*-whitelist` rules with a deprecation approach. As suggested, this uses the copy and paste approach for rules rather than a [factory approach](https://github.com/stylelint/stylelint/commit/e93e44c938d77021eec4893fc20327337a60d49f) to reduce code duplication. This is with the expectation that these rules will be removed in a soon major release and thus won't remain duplicated for long.

As this was quite a manual task, the main issues to try catch in reviewing are copy+paste mistakes and anything that were missed. Given that this introduces a lot of copied and pasted code I've tried to make the reviewing easier by doing a bulk copy and paste in https://github.com/stylelint/stylelint/commit/4df7e92dffcfbbb6b46e4a1af1875474e742156c and then my actual edits in the later commits. When reviewing, it'd be easiest to focus attention on the changes after the first commit.

This change should mean that https://github.com/stylelint/stylelint.io/pull/159 no longer needs merging.

### CODE REVIEW

**Comment by kevindew** [comment]
Thanks @malsf21 - I just sorted the merge conflict.

> We used to add code that show to user that some rules are deprecated: https://github.com/stylelint/stylelint/pull/2679/files#diff-29bacdfdd2b7605922ec3355625a795aR30-R35
> 
> We also have this docs about deprecation: https://stylelint.io/developer-guide/rules#deprecate-a-rule
> 
> I think we need to add these warnings. What do you think?

Ack, I missed that documentation and copied a previous deprecation strategy.

Anyway, we've got the warnings in place, see: https://github.com/stylelint/stylelint/blob/99877b61d3de3606329db6caee0672376e6e2f7c/lib/rules/at-rule-blacklist/index.js#L32-L35 as an example (assuming I've understood you correctly)

However, what seems a bit less clear to me is how I achieve the permanent GitHub link that is suggested in this PR, do you have an example? I couldn't find one. My dilemma is that once this branch is merged, the commits will be squashed so if I link directly to a commit ([example](https://github.com/stylelint/stylelint/blob/99877b61d3de3606329db6caee0672376e6e2f7c/lib/rules/at-rule-blacklist/README.md)) then it'll be part of a tree [that is not a branch of this repository](https://github.com/stylelint/stylelint/commit/99877b61d3de3606329db6caee0672376e6e2f7c) and - if there are any further rebases - potentially not part of this PR. However once this is merged the links could be updated to reference a merged commit, so I could open up a follow-up PR for that. Do let me know if you share concern on this and how you'd like me to proceed.

**Comment by hudochenkov** [comment]
> Ack, I missed that documentation and copied a previous deprecation strategy.

No worries. Looks like we have to document it properly, because it's not documented.

> However, what seems a bit less clear to me is how I achieve the permanent GitHub link that is suggested in this PR, do you have an example?

It's not clear for me why it should be a link to Github, but in mentioned PR it's a lint to a our website ¯﻿\﻿_﻿(﻿ツ﻿)﻿_﻿/﻿¯

Anyway I came up with a solution — use tag view:

https://github.com/stylelint/stylelint/blob/13.6.1/lib/rules/at-rule-property-requirelist/README.md

We would need to use future version tag, which is not available now, but will be online when new version is released:

https://github.com/stylelint/stylelint/blob/13.7.0/lib/rules/at-rule-property-requirelist/README.md

**Comment by jeddy3** [comment]
> It's not clear for me why it should be a link to Github, 

If I remember correctly, it's because the website isn't versioned. When we remove the rules in the next major release, that will also remove the corresponding pages from the site because we build the website from the source files. The deprecation links will be 404ed.

It's pretty clunky, but we never had time to build anything better.

> Anyway I came up with a solution — use tag view:

Sounds good to me.

@kevindew We've not deprecated any rules for a couple of years, and we're finding our way with this. Thanks for bearing with us.  I've been busy with a new contract of late, but it's a Bank Holiday this weekend, and I should have time to get a release out. Will you have time to update the URLs to use the `https://github.com/stylelint/stylelint/blob/13.7.0/lib/rules/{ruleName}/README.md` before then?

**Comment by kevindew** [comment]
Thanks @hudochenkov and @jeddy3 that tag suggestion works and I've applied it in 2794d6f.

**Comment by jeddy3** [comment]
@kevindew Thanks for making the change. 

@hudochenkov The deprecation warnings look good to me know. Shall we merge?

**Pull request merged**
