### PR TITLE
Fix false positives for flex in length-zero-no-unit

### LINKED ISSUE #4831: Fix false positives for flex shorthand with 2 values in length-zero-no-unit
> Clearly describe the bug

There is false negative for `0px` in the flex shorthand rule:  
`flex: 1 0px;`

It is ambiguous situation for two values in flex shorthand property,
according to documentation:
https://developer.mozilla.org/en-US/docs/Web/CSS/flex

#### Two values: flex-grow | flex-basis:
`flex: 1 0px;`

#### Two values: flex-grow | flex-shrink:
`flex: 1 0;`

> Which rule, if any, is the bug related to?

e.g. `length-zero-no-unit`

> What code is needed to reproduce the bug?

```scss
.wrapper {
  flex: 1 0px;
}
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "length-zero-no-unit": true,
  }
}
```

> Which version of stylelint are you using?

`13.6.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

via `stylelint-webpack-plugin`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No

> What did you expect to happen?

No `length-zero-no-unit` error to be flagged.
Possibly it would be good to create another rule to disallow 2 values in flex shorthand property to avoid ambiguous situations, and make intentions evident

> What actually happened (e.g. what warnings or errors did you get)?

The following warnings were flagged:

```shell
Value.module.scss
 32:12  ✖  Unexpected unit   length-zero-no-unit
```

### PR DESCRIPTION
**Pull request by jeddy3**
> Which issue, if any, is this issue related to?

Closes #4831
Closes #5024

> Is there anything in the PR that needs further explanation?

Implements https://github.com/stylelint/stylelint/pull/5024#issuecomment-826058241

### CODE REVIEW

**Review by mattxwang — APPROVED** [review]
Similarly short and sweet, LGTM!

**Review by ybiquitous — APPROVED** [review]
LGTM! 👍🏼

**Review by darwintantuco — APPROVED** [review]
👍

**Comment by jeddy3** [comment]
> - Fixed: `length-zero-no-unit` false positives for `flex` property ([#5315](https://github.com/stylelint/stylelint/pull/5315)).

**Pull request merged**
