### PR TITLE
Test ESM rules

### PR DESCRIPTION
**Pull request by ybiquitous**
> Which issue, if any, is this issue related to?

Ref #5291
Follow-up to #7279

> Is there anything in the PR that needs further explanation?

~~Note that this change uses the unpublished version of `jest-preset-stylelint`:~~
~~https://github.com/stylelint/jest-preset-stylelint/pull/81~~
New version is published: https://github.com/stylelint/jest-preset-stylelint/releases/tag/6.3.2

This change should increase test coverage.

### CODE REVIEW

**Comment by ybiquitous** [comment]
> We need to fix `output` uses in the tests.

It's out of the scope of this PR. I'll open another PR for that.

**Comment by ybiquitous** [comment]
Published a new version: https://github.com/stylelint/jest-preset-stylelint/releases/tag/6.3.2

**Comment by ybiquitous** [comment]
Published a new version: https://github.com/stylelint/jest-preset-stylelint/releases/tag/6.3.2

I'll rebase this PR after #7279 is merged.

**Comment by ybiquitous** [comment]
FYI. #7286 has updated `jest-preset-stylelint` already.

**Review by jeddy3 — APPROVED** [review]
LGTM.

**Pull request merged**
