### PR TITLE
Ensure system fonts aren't quoted

### PR DESCRIPTION
**Pull request by ntwb**
See #1295

### CODE REVIEW

**Comment by jeddy3** [comment]
Tests look good.

**Comment by davidtheclark** [comment]
I rebased the PR and made tests pass. I decided not to create a generic util because we don't know if/when it would be used outside of this rule. Can always create it later.

Because this rule changed significantly recently, I had to change the tests a lot when rebased. @ntwb can you please look this over and confirm that this still should meet your expectations? Thanks!

**Comment by ntwb** [comment]
Thanks, I'll test it later today

**Comment by jeddy3** [comment]
Should this be merged into `v7` as it's a change in behaviour that could break builds?

**Comment by davidtheclark** [comment]
Probably right. I'll change the target branch and rebase.

**Comment by davidtheclark** [comment]
I guess I have to close PR to change the target branch.

**Pull request closed without merging**
