### PR TITLE
Deprecate emptyLineBefore option

### PR DESCRIPTION
**Pull request by jeddy3**

### CODE REVIEW

**Comment by davidtheclark** [comment]
LGTM

**Comment by jeddy3** [comment]
Good stuff. I'm just rebasing.

I figured it was worth being careful about which tests were commented out. I also added a test for the deprecation warning and to check that `emptyLineBefore` is still working.

I smoke tested both deprecation warnings on my local machine too.

**Comment by jeddy3** [comment]
After this is done, shall we get out `6.5.1`. Then I think that's everything we said we'd get done. Anything else we do before going away is a bonus :)

**Comment by davidtheclark** [comment]
Excellent. I'm pretty busy this weekend, so probably won't be able to put in much work besides reviewing things other people have done :) Thanks for taking care of this stuff.

**Comment by jeddy3** [comment]
> I'm pretty busy this weekend, so probably won't be able to put in much work besides reviewing things other people have done :)

Ditto. I'm ought to pack tomorrow :)

**Pull request merged**
