### PR TITLE
Fix `property-no-unknown` false positives for scroll-driven animations

### LINKED ISSUE #7088: Fix `property-no-unknown` false positives for scroll-driven animations
### What minimal example or steps are needed to reproduce the bug?

```css
.view-timeline-works {
	view-timeline: --my-name block;
	view-timeline-axis: block;
	view-timeline-inset: 200px;
	view-timeline-name: --my-name;
}

.animation-range-works {
	animation-range: contain 100px;
	animation-range-start: contain;
	animation-range-end: 100px;
}

.animation-timeline-does-not-work {
	animation-timeline: view();
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "extends": [
    "stylelint-config-standard"
  ]
}
```

### How did you run Stylelint?

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0A3AljA7gWgC5oFsYAbNAOxm0wgCcBrAZwAJgAdM13dLPQk8mPCbZsBAJ7YyAQyJMARsQhg6AbnaduOfEVIVsUgB5oGQhUtXquGLX12VyDGLiEAmAAxuADgbUcrPbX49aSIhEXFJGRhfAF91MiQpMkIpfAgybBokgHNKanpmNj8klLSMrLJcoUgyXClyJgBGD29fThKCVLR0zJzKBjqaZyYauvI2uuTOst7KyhgyKCFmrx92OI4Ejq6ewLtsKAgYBkkIXCpaOhZLbZm9gSFNAAoASlj2EAAaEAAzNGIYAA5KIIEAwAwyTwApBgBgML7gdJ-bKgopMJisMEGXALKAMTFCADa7HR6MxAzEAN05xqyOwAySUCkNCgmJJTAAuusEbS0NkAGK0aaggBWDHSCNgnnhiDRGJAFKp5FwBPlxFSxxVX3Z5NwlKCNKRfPpkyZLNVmPVOIGbLIMRAMSAA)

### Which Stylelint-related dependencies are you using?

```json
{
  "stylelint": "15.10.2",
  "stylelint-config-standard": "34.0.0"
}
```

### What did you expect to happen?

The `animation-timeline` property to not be unknown.

### What actually happened?

The following error gets thrown:

```
Unexpected unknown property "animation-timeline"  property-no-unknown
```

### Do you have a proposal to fix the bug?

Add `animation-timeline` to `lib/reference/properties.js`? Though I'm not familiar with the source for this library, so I don't understand why `view-timeline` and `animation-range` properties are not unknown if they don't seem to be defined there.

I also don't comprehend why the `view` function is not being flagged as unknown as I don't see it being declared in `lib/reference/functions.js`.

So maybe we should add those as well? If that's the case, I'm happy to open a PR.

### PR DESCRIPTION
**Pull request by renato-bohler**
> Which issue, if any, is this issue related to?

Closes #7088

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

### CODE REVIEW

**Comment by ybiquitous** [comment]
Ref:
- https://github.com/known-css/known-css-properties/releases/tag/v0.28.0
- https://github.com/known-css/known-css-properties/compare/v0.27.0...v0.28.0

**Review by ybiquitous — APPROVED** [review]
Thank you! LGTM 👍🏼

**Review by jeddy3 — APPROVED** [review]

**Comment by jeddy3** [comment]
@ybiquitous Am I right in thinking we'll need to add a changelog entry for this as it'll require a release because the semver (`^0.28.0`) range is below `1.0.0`?

**Comment by ybiquitous** [comment]
@jeddy3 Surely, leaving a changelog entry should be helpful for users. 👍🏼

**Pull request merged**
