### PR TITLE
Format arrays in rules

### PR DESCRIPTION
**Pull request by jeddy3**
Thanks to @ntwb research in https://github.com/stylelint/stylelint/pull/2160#issuecomment-264684797, I was able to use jscs to format the arrays.

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@jeddy3 we can help `eslint` https://github.com/eslint/eslint/issues/6075 and https://github.com/eslint/eslint/issues/6073, and have this rules in our config. I have long been interested in the implementation of these rules :smile:

**Comment by ntwb** [comment]
> I was able to use jscs to format the arrays

Ha, that didn't even occur to me, kind of obvious now though 😝

**Comment by ntwb** [comment]
I'm not sure about changing `}, {` to multiline:

```js
},
{
```

We use the same line for if/else, e.g:
```js
    if (typeof messageText === "string") {
      newMessages[messageId] = `${messageText} (${ruleName})`
    } else {
      newMessages[messageId] = function () {
        return `${messageText.apply(null, arguments)} (${ruleName})`
      }
    }
```

_That's my personal preference, but this preference is just the colour of my [bikeshed](https://en.wiktionary.org/wiki/bikeshedding)_ 🚲

**Comment by davidtheclark** [comment]
A+

**Comment by motnik** [comment]
@davidtheclark any idea when is this getting released?

**Comment by davidtheclark** [comment]
@motnik We will be releasing soonish. But this change shouldn't affect any users.

**Comment by jeddy3** [comment]
@davidtheclark I'm around this weekend if we want to try for a minor release then. 

@motnik You can help us prepare for a release by testing `master` against your project(s). We [recently made](https://github.com/stylelint/stylelint/pull/2134) this much easier to do and now simple `npm i -D stylelint/stylelint` will do. FYI, there's a issue (https://github.com/stylelint/stylelint/issues/2161) for discussions about the next release. So lets carry on any further chat there.

**Comment by davidtheclark** [comment]
@jeddy3 I am very busy for the next few weeks, so feel free to take the reins.

**Pull request merged**
