### PR TITLE
Refactor core functionality

### LINKED ISSUE #1810: Extended config path can only be in the config file path
> Which version of stylelint are you using?

`7.1.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint *.css`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

# Setup

Example folder structure

```
├ /components
│ └ /button
│   ├ /node_modules/stylelint-config-example
│   ├ index.js
│   ├ style.css
│   └ package.json
└ .stylelintrc
```

`.stylelintrc` is at the root level of the repository. My example button component is 2 levels deep.

Example `.stylelintrc`

```json
{
  "extends": "stylelint-config-example"
}
```

I'm using the CLI inside of the `/button` folder with the following command:

```sh
stylelint *.css
```

This results in the following error:

```
Error: Could not find "stylelint-config-example". Do you need a `configBasedir`?
```

> What did you expect to happen?

stylelint looks for `stylelint-config-example` in the `process.cwd()` path first, then looks where the configuration file lives.

In the above example, stylelint would look here:
* First path: `/components/button/node_modules/stylelint-config-example`
* Second path: `/node_modules/stylelint-config-example`

This is how ESLint works.

[L#75](https://github.com/stylelint/stylelint/blob/master/src/buildConfig.js#L75) in `src/buildConfig.js` is where the path is set in the above use-case.

### Why do this?

I'd like to store my stylelint configuration in one place further up the directory structure so that many modules can use the same one. This allows me to maintain only one configuration.

> What actually happened (e.g. what warnings or errors you are getting)?

stylelint only looks for configuration extensions in the same path as the configuration file be used.

In the above example, stylelint looks here: `/node_modules/stylelint-config-example`

# Next steps

Is the current behavior the intended behavior? If so, would the project be open to implement the above expected behavior?

I can submit a PR for this if it's wanted.

This is related to #1801, but I don't think it's the exact same issue. I think this is more about path resolution strategy.

### LINKED ISSUE #1881: Can't load configuration file by css file's path
My project files
```
~/myproject/css/.stylelintrc.json
~/myproject/css/test.css
~/myproject/js/.eslintrc.json
~/myproject/js/test.js
```

```bash
cd ~/myproject/
eslint js/*
stylelint css/*
```

When I Change the current working directory to `~/myproject/`, then executed `eslint js/*`, `stylelint` will throw a error: `No configuration found`.

In same case, `ESLint` is work fine.
I hope that, when I didn't set `--config`, stylelint can find configuration file by file path. Just like `ESLint`

### LINKED ISSUE #1882: API for configuration file
[stylefmt](https://github.com/morishitter/stylefmt) is a tool that automatically formats stylesheets.
[stylefmt](https://github.com/morishitter/stylefmt) can understand the formatting rules specified in your stylelint configuration file (.stylelintrc).
stylelint should provides api to load its configuration (e.g. stylelint.buildConfig).

@morishitter will use this to load configuration.

### PR DESCRIPTION
**Pull request by davidtheclark**
Work in progress! I just wanted to start a PR to make everybody aware of what I'm working on, because it's pretty big.

The goal here is to improve and clarify the core (non-rule) functionality, and what at it close #1882 and close #1881. And to do so *without breaking any public API*. This work runs in parallel to [v2 of cosmiconfig](https://github.com/davidtheclark/cosmiconfig).

Here's a checklist of my intentions:

- [x] Integrate [Flow](https://flowtype.org/) in place of JSDoc comments, since its types are actually enforced. It's pretty neat. (This involves the use of `babel-eslint` for ESLint.) I think this will be super helpful in clarifying the way that this functionality works.
- [x] Allow each file to have its own config (#1881). This requires some serious caching, to avoid conducting repeated cosmiconfig searches through the same file structures. That caching work will be built into cosmiconfig and added to here in stylelint. (This actually should be working now I think (??), but is not yet tested.)
- [x] Expose a `getConfigForFile()` function (#1882). Ties in with the above. 
- [x] Clarify responsibilities of different non-rule functions. A lot has been added and fixed over time, so responsibilities have often become kind of muddled.
- [x] Add more explanatory comments explaining edge cases, etc.
- [x] Try loading extends, plugins, processors from `process.cwd()`, to close #1810.

The refactoring in tests is not to alter their assertions (I want the same tests to pass), but to improve them. For example, the use of `catch(t.end)` instead of `catch(logError)` makes tape handle errors much better. I'm just making changes piecemeal as I'm working on getting tests to pass.

Any input welcome while I keep working on this.

### CODE REVIEW

**Comment by davidtheclark** [comment]
Another thing: If you have other ideas about ways to improve the code for the non-rule functionality, now would be a good time to voice them. I can work them into this PR.

**Comment by gucong3000** [comment]
One of my idea: 
I want to extends `EditorConfig`(http://editorconfig.org/).

This is my use case:
https://github.com/gucong3000/stylelint/blob/rclookup/src/__tests__/fixtures/lookupConfig/

**Comment by gucong3000** [comment]
My other suggestion is that when you look for a plugin or extend, you should lookup at 2 places.
1 configuration file directory
2 process current directory
The second directory is to allow `stylelint` run as a IDE package, or more then two project use a public build tool, without need NPM package installed in the project directory.

**Comment by davidtheclark** [comment]
@gucong3000 Could you open new issues for both of those ideas, and link them here? We can discuss them in those issues.

**Comment by jeddy3** [comment]
@davidtheclark This is looking great! The refactoring to clarify the responsibilities is fantastic, and things are a lot clearer now.

You've always been closer to the core than I (and no one knows the core code better than you), and if you feel these additions (e.g. flow) will help improve both the quality of the code and the developer experience then they have my full support.

I'm excited to see this PR come to fruition!

**Comment by davidtheclark** [comment]
@stylelint/core This is ready for some solid field testing. As mentioned above, existing APIs should not have changed: they all should work as before. Before we merge this I'd love it if we could already have tried it out on a bunch of projects.

Any non-core users who come across this, we'd also love it if you'd try this branch and give us your feedback!

Here are the *new* features:

## File-specific configs

A config is looked up for each individual file (#1881). Because of the caching in cosmiconfig v2, the performance hit on this should be minimal. If the linter slows down significantly, please let me know and we'll look into it. @gucong3000, can also you please try this branch against your own use-cases, since you are interested in this feature?

## `getConfigForFile` and `isPathIgnored` 

`getConfigForFile()` and `isPathIgnored()` are exposed in a slightly weird way and not documented. I would like to consider these experimental for a little while, to see how it goes. Then we can document. You use them like this (which you can see in the new `createLinter` tests):

```
import stylelint from "stylelint"
const linter = stylelint.createLinter(options)
linter.getConfigForFile(filepath).then((config) => { .. })
```

I'm thinking that in some future major release this `createLinter` function can release the "standalone" Node API. With it, you create a stylelint instance with its own caches and config.

@Arcanemagus: I was thinking you might want to try these out for the Atom plugin.

## Config modules (plugins, extends, processors) try loading from `process.cwd()`

Closes #1810. @gucong3000 and @rygine would you please try out this new feature, also, to see if it works for your use-case?

## Clarity

Let me know if anything is unclear, or if you have questions or concerns!

**Comment by jeddy3** [comment]
> This is ready for some solid field testing 

Very nice!

I've a quick bug to report before I crash.

```
Invalid Option: Invalid option value "import" for rule "at-rule-blacklist"
Invalid Option: Invalid option value "TODO" for rule "comment-word-blacklist"
Invalid Option: Invalid option value "a,b,color,cubic-bezier,gray,l,linear-gradient,rgb,rotate,scale,translate,url,var" for rule "function-whitelist"
Invalid Option: Invalid option value "float" for rule "property-blacklist"
Invalid Option: Invalid option value "top,bottom,color,width" for rule "property-whitelist"
Invalid Option: Invalid option value "^=" for rule "selector-attribute-operator-blacklist"
Invalid Option: Invalid option value "=" for rule "selector-attribute-operator-whitelist"
Invalid Option: Invalid option value "focus" for rule "selector-pseudo-class-blacklist"
Invalid Option: Invalid option value "hover" for rule "selector-pseudo-class-whitelist"
Invalid Option: Invalid option value "%,px,s,vh,deg" for rule "unit-whitelist"
Invalid Option: Invalid option value "em" for rule "unit-blacklist"
Invalid Option: Invalid option value "media,import,extends" for rule "at-rule-whitelist"
Invalid Option: Invalid option "[[[[[[[[[[[["custom-properties","declarations","rules","at-rules"]]]]]]]]]]]]" for rule plugin/declaration-block-order
```

- Present when using `/node_modules/.bin/stylelint sources/**/everything.css` i.e. cosmiconfig finds config at `.stylelintrc.json`
- *Not* present with using `/node_modules/.bin/stylelint sources/**/everything.css --config configs/everything.json` i.e. explicitly calling config file.

It appears to happen with any rule which uses an array for it's _primary option_.

Besides that, it ploughed through (via the CLI and Node API) my test files and the CSS files of my current project! :)

**Comment by davidtheclark** [comment]
> It appears to happen with any rule which uses an array for it's primary option.

Good job diagnosing. Curse those.

**Comment by davidtheclark** [comment]
@jeddy3 I think the bug you found should be fixed now, and I've added tests to help prevent regression in the future.

This PR is kind of a proving grounds for our tests. If the tests pass *and we don't have any further problems*, we win! If the tests pass but we still have problems, the tests need some more work.

**Comment by Arcanemagus** [comment]
I'll build up a branch utilizing this tomorrow and test things out!

**Comment by jeddy3** [comment]
> I think the bug you found should be fixed now, and I've added tests to help prevent regression in the future.

Your new code/tests LGTM, and have fixed the problem for me.

**Comment by m-allanson** [comment]
This sounds great! I'll be able to take the code for a spin in the next day or so.

**Comment by ntwb** [comment]
@davidtheclark I've tested this branch manually against a few of the repos I use daily, and all thumbs up, no issues surfaced.

That said, I hit upon [this issue](https://github.com/stylelint/stylelint/pull/1750#issuecomment-236507320) once again, not being able to easily test, in my case at least to use `grunt-stylelint` and use the projects own workflow in having to use `node dist/cli.js` is not ideal, we should find a way to eliminate this so that any branch or commit can easily be _dropped_ into any project for testing.

**Comment by davidtheclark** [comment]
@ntwb: Here's are two ways I do it:

Git clone into node_modules:

```
rm -rf node_modules/stylelint
cd node_modules
git clone [stylelint]
git checkout [branch]
```

Change package.json to use the GitHub URL (`stylelint/stylelint#branch-name`) and reinstall.

Do either of those work for you?

**Comment by Nirazul** [comment]
@davidtheclark 

I've struggled with the same problem as @ntwb. 
To your suggestions: At least with `gulp-stylelint` you don't have a dependency to plain stylelint. So this would be added, right?

The first option seems like a valid approach. Unfortunately, I'd have to generate the dist files manually, if I'm not mistaken.

**Comment by ntwb** [comment]
> @ntwb: Here's are two ways I do it:

Thanks @davidtheclark, here's some shell outputs of both methods you suggested:

In this first gist it is the "common" shell output of repo I've used to to test this, it's a fresh clone of my day to day repo I use every day, bbPress: [gist.github.com/ntwb/2868848b](https://gist.github.com/ntwb/2868848b7dd55bbab009fd4ec563c49a)

Next up is [gist.github.com/ntwb/49e768f7](https://gist.github.com/ntwb/49e768f70e7dfb1169e14304d89633ae) in which I manually remove `node_modules/stylelint` and replace it with a fresh Git clone of this repo.

Lastly is [gist.github.com/ntwb/f053f768](https://gist.github.com/ntwb/f053f768bc02a74a130d8fc08d8db19a) where I replace the semver version with `"stylelint": "git@github.com:stylelint/stylelint.git#one-config-per-file"` in the `package.json` file.

Both methods fail with identical errors relating to `/node_modules/stylelint/dist/cli.js`

Both methods above don't take into account the previously installed NPM binary symlink from the original `npm install`. The symlink is in `/node_modules/.bin` and is `stylelint -> ../stylelint/dist/cli.js`, yesterday I tried removing the symlink before trying the above methods, again no success.

The only workaround I've come up thus far is to use OS X's Finder app, and copy and paste a checkout of `stylelint`'s `one-config-per-file` branch and paste that into the repo I'm wanting to test against which is not ideal.

In my mind the ideal solution is to be able to replace the version in `package.json` per the second example above, i.e. `"git@github.com:stylelint/stylelint.git#some-branch-or-commit"` per the [NPM docs here](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies), this is the method I use the majority of the time with other repos.

**Comment by m-allanson** [comment]
@davidtheclark I've run this branch through a few projects here and all seems good 👍 .

I had similar problems to @ntwb in getting the branch running in different projects. @ntwb in your https://gist.github.com/ntwb/49e768f70e7dfb1169e14304d89633ae, can you fix it with `npm run build` to create the missing file, then a second `npm install` to get an error free install? That's what worked for me.

**Comment by davidtheclark** [comment]
@m-allanson @ntwb Have you tried using `npm link`?

**Comment by m-allanson** [comment]
@davidtheclark Ah, I'd completely forgotten about `npm link`, I'll do that next time.

**Comment by davidtheclark** [comment]
Just waiting for a 👍 from @evilebottnawi, whose codebase often finds bugs — then we can merge.

**Comment by jeddy3** [comment]
Appveyor is complaining that the following test (in `src/__tests__/postcssPlugin-test.js`) never ends:

```js
test("`config` option is `null`", t => {
  postcssPlugin.process("a {}")
    .then(t.threw)
    .catch((err) => {
      t.ok(err.message.indexOf("No configuration provided") !== -1)
      t.end()
    })
})
```

Any idea what's going on there?

**Comment by ntwb** [comment]
I'll try `npm run build` / ``npm install` and `npm link` later, though that still doesn't fix the issue  for users who want to "pin" stylelint to a custom commit, branch, or fork.

I don't think it is unreasonable for users to assume they can do do this per NPM's docs and just change the path/commit in their `package.json` file.

**Comment by davidtheclark** [comment]
@ntwb If you'd like to open an issue for further discussion, that'd be a good idea so the issue doesn't get dropped when this closes.

@jeddy3 I will try altering those tests and see what happens.

**Comment by davidtheclark** [comment]
Appveyor failed again, but I do not believe it. Does anybody run Windows so you could check the tests?

**Comment by ntwb** [comment]
Latest AppVeyor log: https://ci.appveyor.com/api/buildjobs/syv4gtf9q93yev7f/log

The start of the test failures:
```shell
[00:02:23] # `config` option is `null`
[00:02:23] not ok 173 test exited without ending
[00:02:23]   ---
[00:02:23]     operator: fail
[00:02:23]     at: processEmit [as emit] (C:\projects\stylelint\node_modules\nyc\node_modules\signal-exit\index.js:140:35)
[00:02:23]   ...
[00:02:23] not ok 174 test exited without ending
[00:02:23]   ---
[00:02:23]     operator: fail
[00:02:23]     at: processEmit [as emit] (C:\projects\stylelint\node_modules\nyc\node_modules\signal-exit\index.js:140:35)
[00:02:23]   ...
[00:02:23] not ok 175 test exited without ending
[00:02:23]   ---
[00:02:23]     operator: fail
[00:02:23]     at: processEmit [as emit] (C:\projects\stylelint\node_modules\nyc\node_modules\signal-exit\index.js:140:35)
[00:02:23]   ...
```

All tests following the above fail, the final logs are (skipping the ~12,000 failurs inbetween):
```shell
[00:02:29] not ok 12240 test exited without ending
[00:02:29]   ---
[00:02:29]     operator: fail
[00:02:29]     at: processEmit [as emit] (C:\projects\stylelint\node_modules\nyc\node_modules\signal-exit\index.js:140:35)
[00:02:29]   ...
[00:02:29] not ok 12241 test exited without ending
[00:02:29]   ---
[00:02:29]     operator: fail
[00:02:29]     at: processEmit [as emit] (C:\projects\stylelint\node_modules\nyc\node_modules\signal-exit\index.js:140:35)
[00:02:29]   ...
[00:02:29] 
[00:02:29] 1..12241
[00:02:29] # tests 12241
[00:02:29] # pass  172
[00:02:29] # fail  12069
[00:02:29] 
[00:02:29] File [C:\projects\stylelint\src\utils\index.js] ignored, nothing could be mapped
[00:02:29] File [C:\projects\stylelint\src\testUtils\basicChecks.js] ignored, nothing could be mapped
[00:02:29] File [C:\projects\stylelint\src\reference\namedColorData.js] ignored, nothing could be mapped
[00:02:29] File [C:\projects\stylelint\src\reference\shorthandData.js] ignored, nothing could be mapped
[00:02:30] File [C:\projects\stylelint\src\formatters\index.js] ignored, nothing could be mapped
[00:02:30] File [C:\projects\stylelint\src\testUtils\index.js] ignored, nothing could be mapped
[00:02:30] 
[00:02:30] npm ERR! Windows_NT 6.3.9600
[00:02:30] npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "tape"
[00:02:30] npm ERR! node v6.6.0
[00:02:30] npm ERR! npm  v3.10.3
[00:02:30] npm ERR! code ELIFECYCLE
[00:02:30] npm ERR! stylelint@7.3.1 tape: `babel-tape-runner "src/**/__tests__/**/*.js"`
[00:02:30] npm ERR! Exit status 1
[00:02:30] npm ERR! 
[00:02:30] npm ERR! Failed at the stylelint@7.3.1 tape script 'babel-tape-runner "src/**/__tests__/**/*.js"'.
[00:02:30] npm ERR! Make sure you have the latest version of node.js and npm installed.
[00:02:30] npm ERR! If you do, this is most likely a problem with the stylelint package,
[00:02:30] npm ERR! not with npm itself.
[00:02:30] npm ERR! Tell the author that this fails on your system:
[00:02:30] npm ERR!     babel-tape-runner "src/**/__tests__/**/*.js"
[00:02:30] npm ERR! You can get information on how to open an issue for this project with:
[00:02:30] npm ERR!     npm bugs stylelint
[00:02:30] npm ERR! Or if that isn't available, you can get their info via:
[00:02:30] npm ERR!     npm owner ls stylelint
[00:02:30] npm ERR! There is likely additional logging output above.
[00:02:30] 
[00:02:30] npm ERR! Please include the following file with any support request:
[00:02:30] npm ERR!     C:\projects\stylelint\npm-debug.log
```

**Comment by ntwb** [comment]
stylelint master on Windows 10, NodeJS v6.7.0 and npm 3.10.8: `npm test` successful:

```shell
1..23943
# tests 23943
# pass  23943

# ok
```

stylelint one-config-per-file branch:

• `npm install` works as expected, no errors updating to this PR's NPM
• `npm test` works as expected, all 23,943 tests pass, no errors

```shell
1..23943
# tests 23943
# pass  23943

# ok
```

It's not immediately obvious what is causing the AppVeyor failures, it works with Windows 10 here for me perfectly.

@davidtheclark Feel free to merge and I'll look further into the AppVeyor issue over the weekend

**Comment by evilebottnawi** [comment]
@ntwb i can tested today on env as appveyor machines if you can wait, maybe it is help in the understanding of the error

**Comment by evilebottnawi** [comment]
Started tests. It takes some time.

**Comment by evilebottnawi** [comment]
All windows machines builds:
- [x] Windows XP. Success.
- [x] Windows 7. Success.
- [ ] Window 8. Wait.
- [ ] Window 8.1 . Wait.
- [ ] Window Server 2012. Wait.

**Comment by evilebottnawi** [comment]
Windows :sob:

**Comment by evilebottnawi** [comment]
@britzkopf @FeodorFitsner @IlyaFinkelshteyn Can we help with problems guys?

**Comment by davidtheclark** [comment]
@evilebottnawi: If it's fine on all your tests maybe we can assume that it's an Appveyor cache issue or something and merge?

**Comment by IlyaFinkelshteyn** [comment]
Please check build log attached (I afraid UI is freezing with this long build, sorry). It seems that many tests failed...
[stylelint.txt](https://github.com/stylelint/stylelint/files/517217/stylelint.txt)

**Comment by IlyaFinkelshteyn** [comment]
FYI, you can always download build log here (see pic) if build it too long to work easily with UI

[cid:image001.png@01D220B2.37482C30]

**Comment by ntwb** [comment]
Thanks @IlyaFinkelshteyn, I also linked to the log in https://github.com/stylelint/stylelint/pull/1930#issuecomment-252192747

**Comment by ntwb** [comment]
Not that I expect any different results but I've restarted the AppVeyor job for this PR /shrug

I'm +1 on merging based on @evilebottnawi array of tests @davidtheclark

**Comment by evilebottnawi** [comment]
Merge, i don't know why we have build failed :sob: @IlyaFinkelshteyn (We know how to view the log, the request was to help understand why this happens, attempts to reproduce the error in similar environments failed)

**Comment by davidtheclark** [comment]
I will cut a real release of cosmiconfig v2 and then merge this.

**Comment by davidtheclark** [comment]
Changelog entries added:

> -   Added: each stylesheet lookups configuration from its own path. This different files can use different configurations during the same linting process.
-   Added: relative path extends, plugins, and processors try to load from `process.cwd()` if they aren't found relative to the invoking configuration.

**Comment by davidtheclark** [comment]
@jeddy3 Should we cut a release today? Whichever of us gets to it first ...

**Comment by jeddy3** [comment]
I'm going to try to squash a couple of bugs. We can release after that.

Congrats on an awesome refactor btw :)

**Comment by IlyaFinkelshteyn** [comment]
@evilebottnawi 
I opened your log and noticed that after the following trace all test went south.
```
# `config` option is `null`
[00:02:12] not ok 184 test exited without ending
``` 
I forked your repo and disabled sick test named `config option is null`
 in `src/__tests__/postcssPlugin-test.js` after which build went through OK.

Hope this helps to narrow down the issue.

--ilya.

**Comment by Arcanemagus** [comment]
@davidtheclark Thanks for putting `getConfigForFile()` together! Took advantage of it in https://github.com/AtomLinter/linter-stylelint/pull/285/commits/e3b00791575565d40063744a46c6c0fdec4128ce, which will be in the next version of `linter-stylelint` out as soon as CI finishes taking it's sweet time 😛.

**Pull request merged**
