### PR TITLE
Fix no longer needed workaround for Cosmiconfig segfault

### LINKED ISSUE #7322: Fix ERR_REQUIRE_ESM when importing ESM config with `.js`
### Describe the documentation issue

I don't know what the syntax for `stylelint.config.js` should be since all the examples are for `.stylelintrc` only. But ok, I found in the documentation of other linters that I can use `module.exports = {}` for CJS, but what is the syntax for ESM? I tried `export default {}` and `export config = {}` but it didn't work as there was always an `Error [ERR_REQUIRE_ESM]: require() of ES Module` error in the console even in [version 16](https://github.com/stylelint/stylelint/releases/tag/16.0.0-0).

### What solution would you like to see?

In https://stylelint.io/user-guide/configure it is worth adding at least one example of what the syntax of the `stylelint.config.js` file should look like for CJS and ESM.

### PR DESCRIPTION
**Pull request by ybiquitous**
> Which issue, if any, is this issue related to?

Closes #7322

> Is there anything in the PR that needs further explanation?

This workaround was introduced in #6902. See also #6898.

**Note**: This PR skips a few cases that failed due to segfault. See the source comment for details.

### CODE REVIEW

**Comment by ybiquitous** [comment]
Maybe related to https://github.com/nodejs/node/issues/35889. The patch was released in Node.js 20.

**Review by jeddy3 — COMMENTED** [review]
Were you able to test this locally on node@18 outside of Jest?

**Comment by ybiquitous** [comment]
Yes. [`scripts/visual-config.cjs`](https://github.com/stylelint/stylelint/blob/27f4f5bf4c1d4bdc2c52edca7d1c97f8e3cc8746/scripts/visual-config.cjs) is available within this repository. See the following:

```sh-session
$ node -v
v18.18.2

$ bin/stylelint.mjs --config scripts/visual-config.cjs scripts/*.css

scripts/visual.css
 1:1   ✖  Unknown rule unit-case                            unit-case
 1:1   ✖  Unknown rule string-quotes                        string-quotes
 1:9   ✖  Expected "url("foo.css")" to be ""foo.css""       import-notation
 4:9   ✖  Unexpected invalid hex color "#4f"                color-no-invalid-hex
 6:1   ✖  Expected ".foo.bar" to have no more than 1 class  selector-max-class
 7:10  ✖  Unexpected unit "px"                              unit-disallowed-list
 8:3   ⚠  Expected custom property name to be kebab-case    custom-property-pattern

7 problems (6 errors, 1 warning)
```

**Review by jeddy3 — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
