### PR TITLE
Prepare changelog

### PR DESCRIPTION
**Pull request by jeddy3**
I scanned through the closed issues and the commit logs  and found a couple we'd missed, mainly to do with `rule-properties-order`.

I also tweak the ordering to make it consistent with the rest of the changelog and so that related items are grouped together.

@davidtheclark @makotot Thanks again for all the new rules and for the fixes that went into this release! :tada: :)

### CODE REVIEW

**Comment by davidtheclark** [comment]
Thanks!

**Comment by jeddy3** [comment]
@davidtheclark Shall I release?

**Comment by davidtheclark** [comment]
Sure!

**Comment by jeddy3** [comment]
@davidtheclark Done! :)

Congratulations on the achievement of over 8000 tests too :tada: :)

**Comment by makotot** [comment]
:tada:

**Pull request merged**
