### PR TITLE
Add `jest:detectleaks` npm script for Jest memory leak testing.

### PR DESCRIPTION
**Pull request by ntwb**
Follow up to #3069/ #3121

### CODE REVIEW

**Comment by ntwb** [comment]
I've created #3124 to list, and seek help in fixing the current 17 tests that fail

**Comment by hudochenkov** [comment]
What `weak` for? Is it peer or optional dependency of Jest?

**Comment by ntwb** [comment]
My bad, I should have added a note about `weak`, Jest Leak Detector requires `weak`:
https://github.com/facebook/jest/blob/master/packages/jest-leak-detector/package.json#L14

**Comment by hudochenkov** [comment]
Found it https://github.com/facebook/jest/blob/19376c1e1e8a77717fbb7a216df92087eddbd277/packages/jest-leak-detector/src/index.js#L39-L51 Quite strange approach for dependencies.

**Comment by ntwb** [comment]
I think it's due to the _mono_ repo Facebook use:
• ~35 npm modules in a single repo https://github.com/facebook/jest/tree/master/packages
• Lerna is what's used to manage this repo setup https://lernajs.io/ - _"A tool for managing JavaScript projects with multiple packages."_

**Comment by hudochenkov** [comment]
It shouldn't be because of Lerna. I use it at work and any package could have whatever dependencies it wants.

**Comment by SimenB** [comment]
It's because of https://github.com/facebook/jest/issues/5169, fwiw

**Pull request merged**
