### PR TITLE
Ignore keyframe selectors in isStandardSelector; fixes #1383

### LINKED ISSUE #1383: selector-type-no-unknown returns false positives for keyframe selectors in mixins
With stylelint 6.5.1 and stylelint-config-standard 8.0.0, the `selector-type-no-unknown` appears to trigger a false-positive on keyframe % selectors inside of mixins. Admittedly, this is a super edge case.

Example code:
```
@include keyframes(identifier) {
    0% {
        opacity: 0;
        @include transform( 'scale(0.95)');
    }

    80% {
        opacity: 1;
    }

    100% {
        @include transform( 'scale(1)');
        opacity: 1;
    }
}
```

This triggers 3 errors, when I would expect 0.

### PR DESCRIPTION
**Pull request by davidtheclark**
I modified `isStandardSelector()` so it always ignores selectors that are just percentages, assuming (I think quite safely) that those are only used for keyframe selectors and therefore should be ignored all the time.

Because `isStandardSelector()` now ignored keyframe selectors I was able to remove the usage of `isKeyframeRule` from `selector-type-no-unknown`.

### CODE REVIEW

**Comment by jeddy3** [comment]
I think, maybe, the intent of the `isStandard` rules isn't clear and a rename is in order.

The `isStandard*` utils only deal with excluding *non-standard syntax*. The other `is*` rules can then be used to distinguish between *standard-syntax* difference e.g. `isCustomProperty`, `isKeyframeRule` and, in this case, `isKeyframeSelector`. Keyframe rules, keyframe selectors and custom properties are in the specs, but PostCSS doesn't distinguish between them.

I think we should rename the `isStandard*` utils to `isStandardSyntax*` e.g. `isStandardSyntaxRule` or `isStandardSyntaxSelector`. The intent it much clearer then.

Applying the above to this PR... if we continue to exclude [*keyframe selectors*](https://www.w3.org/TR/css3-animations/#keyframes) within `isStandardSyntaxSelector*` then we can no longer use the `isStandardSyntaxSelector` rule when we write some future rule specific to *keyframe selectors* e.g. `keyframe-selector-max-precision` would could be use to disallow decimal places in keyframe selector percentages. Such a rule would include:

```js
if (
  !isStandardSyntaxSelector(selector)
  || !isKeyframeSelector(selector) 
) { return }
```

Which would first allow us to exclude all *non-standard* syntax and then only include keyframe selectors.

Sound good?

**Comment by davidtheclark** [comment]
You're right: I should have made `isKeyframeSelector()` instead of doing what I did.

I don't understand, though, why you think adding `Syntax` to these util names will clarify them?

**Comment by jeddy3** [comment]
I think just "standard" is ambiguous.  "Standard Selector" as in it's a "normal"/standard selector and not a variant like *keyframe selector*. Or "Standard Selector" as in it conforms to standard CSS syntax. I think using `isStandardSyntax*` will remove any ambiguity and make the intent of the utils clearer.

**Comment by davidtheclark** [comment]
@jeddy3 That's fine by me. I will modify this PR, then the renaming of utils can be a separate issue.

**Comment by jeddy3** [comment]
Sgtm :)

**Comment by davidtheclark** [comment]
@jeddy3 Ready for another look.

**Comment by jeddy3** [comment]
Very nice. Good job accounting for the keyframe selector keywords.

**Pull request merged**
