### PR TITLE
Increase flow coverage

### PR DESCRIPTION
**Pull request by ivanzusko**
Increased flow coverage in:

- lib/lintSource.js from 74.59 to 79.61%
- lib/needlessDisables.js from 74.83 up to 97.26%;
- lib/cli.js from 52.73 up to 75.38%

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@ivanzusko Maybe your can help with https://github.com/stylelint/stylelint/pull/2675? Seems your are familiar with flow.

**Comment by ivanzusko** [comment]
@evilebottnawi I'll definitely do my best, but I'm in relocation process right now, so till weekends I want to dedicate the whole free time to my family. Give me, please, a few days.
Cheers!

**Comment by ivanzusko** [comment]
Hi, guys!

As far as my console is saying there is an issue with the amount of arguments:
image

the small fix of `blurInterpolation.js` should handle that problem. For example like this:

```javascript
module.exports = function (...source/*: Array<string>*/)/*: string*/ {
  const blurChar/*: string*/ = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : " "

  return source[0].replace(/[#@{}]+/g, blurChar)
}
```

image

**Comment by jeddy3** [comment]
Should we now set these flows PRs to merge into `v8`, rather than `master`, as there are structural adjusts in `v8` that might need to be accounted for?

**Comment by hudochenkov** [comment]
> Should we now set these flows PRs to merge into v8, rather than master, as there are structural adjusts in v8 that might need to be accounted for?

Yes, but I haven't finished `v8` tests, yet.

**Comment by evilebottnawi** [comment]
@jeddy3 i think we can marge this in master, many of these error or increasing coverage not related to v8 and structural changes

**Comment by jeddy3** [comment]
The [`decls`](https://github.com/stylelint/stylelint/tree/v8/decls) have been updated in `v8`. Does that not affect this flow work?

**Comment by evilebottnawi** [comment]
@jeddy3 oh, seems it is can be affect on flow work :disappointed: Why we will don't merge `master` with `v8`?

**Comment by m-allanson** [comment]
Could we rename the branches so that all new work goes towards version 8, but we can still publish publish version 7 patches?

Change `master` to `v7`
Change `v8` to `master`

**Comment by hudochenkov** [comment]
@m-allanson I think it could potentially mess with Github and open PRs pretty hard.

I think we could merge `v8` into `master` after tests are green in `v8`.  I'm [working](https://github.com/stylelint/stylelint/issues/2575#issuecomment-311494777) on it. Also we could have a new branch `v7` from current  `master` for v7 patch releases.

**Comment by jeddy3** [comment]
On second thoughts, I'm unsure how well our release process/script will play with this setup. It might prove tricky to do releases from a branch that isn't `master`. What's guaranteed to work is our usual approach of working off a branch until we're ready to release and then merging into `master`. As such, it might be best to point this PR (and the others we'd like to see in before `8.0.0`) to `v8`.

**Comment by hudochenkov** [comment]
@jeddy3 then it might may sense to set `v8` as default branch for now. What do you think?

**Comment by jeddy3** [comment]
Do you know if that'll have any impact on the release process? If we're not 100% sure, then we should probably leave it as is.

**Comment by hudochenkov** [comment]
@jeddy3 I have zero knowledge about stylelint release process ¯﻿\﻿_﻿(﻿ツ﻿)﻿_﻿/﻿¯

**Comment by ntwb** [comment]
I had a quick look at _npmpub_ and _release from changelog_ and neither specifically check or reference _branches_ or _master_, but I'm still not really sure if it would work though /shrug

**Comment by jeddy3** [comment]
> but I'm still not really sure if it would work though /shrug

I'm not 100% sure either. So, let's play it safe.

> @jeddy3 I have zero knowledge about stylelint release process ¯﻿\﻿_﻿(﻿ツ﻿)﻿_﻿/﻿¯

I really need to write this up... I'll create an issue.

**Comment by jeddy3** [comment]
@ivanzusko We've been busy prepping `8.0.0`, which unfortunately means this branch now has conflicts. Are you able to rebase of `master` so we can get this in at some point?

**Comment by ivanzusko** [comment]
@jeddy3 yes sure! I'll handle this in the nearest time.

**Comment by ntwb** [comment]
This doesn't look so good, 715 files changed 😝 

@ivanzusko Do you want to try rebasing again or just create a fresh PR with your commits?

p.s. Sorry about this 😄

**Comment by ivanzusko** [comment]
`715 files` yeap 😄 

I'll do fresh one

**Comment by ivanzusko** [comment]
@ntwb 
the fresh one: [https://github.com/stylelint/stylelint/pull/2823](https://github.com/stylelint/stylelint/pull/2823)

one more time my apologies for my slowness 😞

**Comment by ntwb** [comment]
Thanks @ivanzusko, likewise, sorry about this, I'll try to review #2823 soon :)

**Pull request closed without merging**
