### PR TITLE
Jest util tests (post-babel)

### PR DESCRIPTION
**Pull request by m-allanson**
> Which issue, if any, is this issue related to?

Replaces #2135, accounting for the changes in #2134.

> Is there anything in the PR that needs further explanation?

Both master and #2135 had renamed the same files in different ways, which is why I've created _another_ PR for this. Due to the file renaming in both branches, this is essentially #2135 with a sort of manual rebase applied. 

Some of the flow types have been ditched because it made this simpler to manage, they can be re-added at a later date.

I've just about run out of time, but I think it's looking ok.

### CODE REVIEW

**Comment by m-allanson** [comment]
The system tests are failing in node v4

**Comment by m-allanson** [comment]
I've removed the object destructuring from the system tests, but they're failing with a new error which I don't understand.

```
Test suite failed to run

    SyntaxError: Unexpected token =

      at transformAndBuildScript (node_modules/jest/node_modules/jest-cli/node_modules/jest-runtime/build/transform.js:316:10)
      at Object.<anonymous>.jest (system-tests/001/001.test.js:4:25)
```

Line 4 of `001.test.js` looks like this:

```js
const systemTestUtils = require("../systemTestUtils")
```

**Comment by davidtheclark** [comment]
Looking now ...

**Comment by davidtheclark** [comment]
@m-allanson `Unexpected token =` happened because there was a default parameter in there, which is not supported by Node 4. Not a very helpful stack trace.

**Comment by davidtheclark** [comment]
Thanks @m-allanson! Looks like it's working well now.

**Pull request merged**
