### PR TITLE
Fix testUtils and exposed createRuleTester

### PR DESCRIPTION
**Pull request by davidtheclark**
Relates to https://github.com/stylelint/stylelint-rule-tester/issues/9. Realized when trying to use `stylelint.createRuleTester` that I had flubbed it. While fixing that I fixed some apparent mistakes in the way we were exposing and using test utils.

### CODE REVIEW

**Comment by davidtheclark** [comment]
Once this is merged let's release it right away. Silly bug.

**Comment by jeddy3** [comment]
LGTM. 

Release as `6.2` because of the new `selector-no-qualifying-type` rule, right?

**Comment by davidtheclark** [comment]
Yep.

**Comment by davidtheclark** [comment]
I will release.

**Pull request merged**
