### PR TITLE
Add codeFilename option to Node API; closes #722

### LINKED ISSUE #722: Add to Node API ability to associate direct code input with a filename
This is particularly useful for editor plugins: https://github.com/AtomLinter/linter-stylelint/issues/84

### PR DESCRIPTION
**Pull request by davidtheclark**
@1000ch, @Arcanemagus: Does this look like it will work for the Atom linter plugin?

### CODE REVIEW

**Comment by 1000ch** [comment]
@davidtheclark I'll try this from now :+1:

**Comment by 1000ch** [comment]
It didn't work well... :cry: 

In workaround, I confirmed that `lintString()` gets `codeFilename` value as `filepath` (so `postcssProcessOptions` object has `from` value).

**Comment by davidtheclark** [comment]
> It didn't work well... 

What went wrong? How does your use-case differ from the test?

**Comment by 1000ch** [comment]
Ah, It seems to work well with glob, but not with file path.

```json
{
  "ignoreFiles": ["src/foo.css"],
  "rules": { "block-no-empty": true }
}
```

**Comment by davidtheclark** [comment]
Could you clarify? Where was the glob that didn't work --- in `codeFilename`? Because in the test that's an aboslute path, not a glob, and it seems to work.

**Comment by 1000ch** [comment]
A file path of CSS is passed to stylelint as `codeFilename` in linter-stylelint. I specified an absolute path to ignore In `.stylelintrc` (such as above comment).

**Comment by davidtheclark** [comment]
In the comment above you do not have an absolute path, because it doesn't start with `/`. That relative path will be evaluated according to:

- the config's filepath, if the config is a file that stylelint loaded,
- or `process.cwd()`

Is there a chance that because of the way Atom linter is using stylelint (loading the config independently with cosmiconfig), the `ignoreFiles` relative paths are not being evaluated as you'd expect?

**Comment by 1000ch** [comment]
>In the comment above you do not have an absolute path, because it doesn't start with /.

Sorry, that was my mistake. But an absolute path in `ignoreFiles` does not work well...:(

>That relative path will be evaluated according to:
>Is there a chance that because of the way Atom linter is using stylelint (loading the config independently with cosmiconfig), the ignoreFiles relative paths are not being evaluated as you'd expect?

Does it mean `configBasedir`? linter-stylelint pass a directory path of `.stylelintrc` as `configBasedir` to stylelint.

**Comment by davidtheclark** [comment]
> an absolute path in ignoreFiles does not work well

I will look into that, write a test or two and debug.

> Does it mean configBasedir? linter-stylelint pass a directory path of .stylelintrc as configBasedir to stylelint.

I think that `ignoreFiles` is not paying attention to `configBasedir` right now. It probably needs to. 

I can incorporate both of those into this PR later today or tomorrow. Then hopefully that will fix the problems. Thanks for being responsive, @1000ch!

**Comment by 1000ch** [comment]
:+1::+1::+1:

**Comment by davidtheclark** [comment]
@1000ch : I'm hoping that the latest two commits here found and fixed the mistakes that were causing your troubles. Can you please give it a another shot?

**Comment by 1000ch** [comment]
@davidtheclark Thank you for corresponding! I'll try it ASAP.

**Comment by 1000ch** [comment]
@davidtheclark It works well ! :+1:

**Comment by davidtheclark** [comment]
Ah, magnificent.

**Pull request merged**
