### PR TITLE
Fix tests and refactor

### PR DESCRIPTION
**Pull request by jeddy3**
Oops. At some in the past @evilebottnawi accidentally named his tests directory `__test__` when creating a new rule. I assume that error was duplicated each time a new rule was created. 

Long story short, quite a few of the recently created rules weren’t being tested when `npm test` was being run (locally and on the travis/appveyor).

Fortunately, most rules are passing. There were just three connected to the utils refactor that needed addressing.

They are fixed in this PR.

I think we dodged bullet spotting this now rather than later :)

### CODE REVIEW

**Comment by davidtheclark** [comment]
Feel free to merge and release as soon as the tests pass.

**Comment by evilebottnawi** [comment]
@jeddy3 oh sorry, did not notice this :cry:

**Comment by jeddy3** [comment]
> Feel free to merge and release as soon as the tests pass.

@davidtheclark We exposed `cssWordIsVariable` in [6.0.0](https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md#600).

So we can either release `7.0.0` and think for `7.1` which utils to expose going forward.

*Or* I can quickly re-add `cssWordIsVariable` back into the utils. Add a deprecated notice to the changelog and a `console.log` message. We can then remove it when `7.0.0` come around at the later date.

@evilebottnawi No worries, these things happen :)

**Comment by jeddy3** [comment]
On the plus side, the number of tests listed at the end of `npm test` just went over 15000 :) 🎉 

I'm going to grab some dinner now. I'll be back in a hour to do the release.

**Pull request merged**
