### PR TITLE
Deprecate e and extract CLI flags

### PR DESCRIPTION
**Pull request by jeddy3**
Ref: https://github.com/stylelint/stylelint/pull/1535

### CODE REVIEW

**Comment by ntwb** [comment]
LGTM

**Comment by davidtheclark** [comment]
Looks good. But we also need to deprecate the `extractStyleTagsFromHtml` option in the Node API: http://stylelint.io/user-guide/node-api/#extractstyletagsfromhtml

**Comment by jeddy3** [comment]
Whoops. Fixed.

**Comment by davidtheclark** [comment]
LGTM

**Pull request merged**
