### PR TITLE
Added cli flag "--disable-globbing"

### LINKED ISSUE #4193: Allow to use full file path without converting it to glob
> What is the problem you're trying to solve?

I have been trying to add stylelint to a project. However, when our build bot runs our tests, it runs them in a directory path that happens to contain parentheses. This causes problems with globby, and leads to stylelint not actually linting anything. I tried running globby with `noext` set, but that just caused it to produce some arcane-looking errors.
I might have been configuring globby wrong, I suppose; in the end, though, I found it easiest to (write a PR that) disables globbing altogether. We weren't using globbing anyway.

> What solution would you like to see?

A command that disables globbing, and just makes stylelint assume whatever paths you provided are literal paths. Ideally a cli option, since we are invoking stylelint through the command line rather than through the javascript interface.

### PR DESCRIPTION
**Pull request by theodab**
> Which issue, if any, is this issue related to?

Closes #4193

> Is there anything in the PR that needs further explanation?

Not really. I'm open to renaming the flag as you people see fit; I'm not attached to the specific name of "--disable-globbing".

### CODE REVIEW

**Comment by joeyparrish** [comment]
Looks like there is a minor style error reported by `npm run pretest`:

https://travis-ci.com/stylelint/stylelint/jobs/223657863

```
/home/travis/build/stylelint/stylelint/lib/standalone.js
  198:3  error  Expected blank line before this statement  padding-line-between-statements
```

**Comment by theodab** [comment]
Ok, I fixed that linter error, and ran the linter locally to make sure I didn't have any others.

**Comment by hudochenkov** [comment]
Labeling this as “blocked”, because we need to find another solution to the original issue.

**Comment by hudochenkov** [comment]
We decided that [this a bug](https://github.com/stylelint/stylelint/issues/4193) and we need it to fix it, rather create new flag.

**Pull request closed without merging**
