### PR TITLE
fix crash on nested selectors

### LINKED ISSUE #1209: declaration-block-no-ignored-properties falls at nested selectors
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Stylelint crashes on nested selector when `declaration-block-no-ignored-properties` enabled

> Which rule, if any, is this issue related to?

`declaration-block-no-ignored-properties`

> What CSS is needed to reproduce this issue?

```css
.root {
	display: block;

	&::before {
		content: '';
	}
}

```

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
    "declaration-block-no-ignored-properties": true
  }
}
```

> Which version of stylelint are you using?

`6.3.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Yes, it's related to nesting.

> What did you expect to happen?

No warnings to be flagged.

> What actually happened (e.g. what warnings or errors you are getting)?

Stylelint crashed.

```shell
TypeError: Cannot read property 'toLowerCase' of undefined
    at /Users/dzhiriki/Documents/csssr.ru/node_modules/stylelint/dist/rules/declaration-block-no-ignored-properties/index.js:34:50
    at Array.forEach (native)
    at /Users/dzhiriki/Documents/csssr.ru/node_modules/stylelint/dist/rules/declaration-block-no-ignored-properties/index.js:33:27
    at Array.forEach (native)
    at /Users/dzhiriki/Documents/csssr.ru/node_modules/stylelint/dist/rules/declaration-block-no-ignored-properties/index.js:23:15
    at /Users/dzhiriki/Documents/csssr.ru/node_modules/postcss/lib/container.js:94:28
    at /Users/dzhiriki/Documents/csssr.ru/node_modules/postcss/lib/container.js:81:26
    at Rule.each (/Users/dzhiriki/Documents/csssr.ru/node_modules/postcss/lib/container.js:68:22)
    at Rule.walk (/Users/dzhiriki/Documents/csssr.ru/node_modules/postcss/lib/container.js:80:21)
    at /Users/dzhiriki/Documents/csssr.ru/node_modules/postcss/lib/container.js:83:32
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/34011400-declaration-block-no-ignored-properties-falls-at-nested-selectors?utm_campaign=plugin&utm_content=tracker%2F9282518&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F9282518&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by dzhiriki**
Fix #1209

### CODE REVIEW

**Comment by dzhiriki** [comment]
Bug was created in 7ba84e9. 
Before:
`if (ignoredProperties.indexOf(node.prop) === -1 || index === nodeIndex) { return }`
After
`if (ignoredProperties.indexOf(node.prop.toLowerCase()) === -1 || index === nodeIndex) { return }`

When use nesting selectors, node can be selector, not a prop. And in this case node.props will be undefined.

**Comment by evilebottnawi** [comment]
@jeddy3 @davidtheclark release with critical bugs, ping ping ping

**Comment by jeddy3** [comment]
I'll add a test for this after the merge.

**Comment by evilebottnawi** [comment]
@jeddy3 need 6.3.1 :cat:

**Comment by evilebottnawi** [comment]
@jeddy3 sorry :crying_cat_face: it is my error

**Comment by jeddy3** [comment]
Yep, I'm on it. @evilebottnawi Don't worry, these things happen. Nobody died :)

**Comment by jeddy3** [comment]
Release is running. It'll take a minute or two.

**Comment by evilebottnawi** [comment]
@jeddy3 I try to do always better :cake:

**Comment by jeddy3** [comment]
`6.3.1` is out.

@dzhiriki Thanks for the quick fix. Sorry we broke your build.

@evilebottnawi I'm going to create another issue about maybe refactoring that rule to use the safer `walk` iterators, rather than `decl.parent.nodes.forEach`.

**Comment by evilebottnawi** [comment]
@jeddy3 yep

**Pull request merged**
