### PR TITLE
Much refactor

### PR DESCRIPTION
**Pull request by davidtheclark**
I decided it was time to run through all the rules quickly and see if there were obvious refactoring that could be done. I made a lot of changes. I made a couple of new utilities. And I even found some problems that I fixed. Sorry it's a beast of a commit -- I thought it would be even less efficient to split this up into a whole lot of different ones.

### CODE REVIEW

**Comment by davidtheclark** [comment]
Summary of changes I think:

- Rename `css` to `root` because I've found that that actually makes more sense
- Use arrow functions
- Use utility functions in new places
- Add some new utility functions, which even catch some errors in the way things were done before

**Comment by davidtheclark** [comment]
I think the rebase worked fine, so this should be good to go, unless you disagree with changes.

**Comment by jeddy3** [comment]
This is so good!

> unless you disagree with changes.

Nope, everything looks great! :)

**Comment by MoOx** [comment]
Wow, that's cool.

**Pull request merged**
