### PR TITLE
Remove extra column in some tables in Rules docs

### PR DESCRIPTION
**Pull request by germanfrelo**
> Which issue, if any, is this issue related to?

None, as it's a documentation fix.

> Is there anything in the PR that needs further explanation?

There is an extra column in some tables:
- [Max & min](https://stylelint.io/user-guide/rules#max--min)
- [Pattern](https://stylelint.io/user-guide/rules#pattern)

### CODE REVIEW

**Review by Mouvedia — APPROVED** [review]
@germanfrelo Thanks for the pull request.

**Comment by Mouvedia** [comment]
off-topic

@ybiquitous should we create an issue to add a [stylelint-config-recommended](https://github.com/stylelint/stylelint-config-recommended) column?

**Comment by germanfrelo** [comment]
> off-topic
> 
> @ybiquitous should we create an issue to add a [stylelint-config-recommended](https://github.com/stylelint/stylelint-config-recommended) column?

Maybe I'm wrong, but I think it was removed on purpose in PR https://github.com/stylelint/stylelint/pull/6960.

**Comment by ybiquitous** [comment]
@germanfrelo is right. `stylelint-config-standard` includes `stylelint-config-recommended`, so adding the recommended config is unneeded.

**Review by ybiquitous — APPROVED** [review]
@germanfrelo Thank you! LGTM 👍🏼

**Comment by Mouvedia** [comment]
> @germanfrelo is right. `stylelint-config-standard` includes `stylelint-config-recommended`, so adding the recommended config is unneeded.

For the users that extend `stylelint-config-recommended`, like me, it would be useful.
But it's not important, I agree.

**Pull request merged**
