### PR TITLE
Allow ordinary regular expressions anywhere a regex string is accepted in rule config

### LINKED ISSUE #3008: Support regex literals in all options that accept regexes
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Many of the Stylelint rule options supports regexes, but they require having the regexes in a string. For JS based configs, it would be much nicer to specify them as regex literals. Some rules supports this already, like the `selector-class-pattern` and `selector-id-pattern` rules, while the `declaration-property-value-blacklist` rule does not and require string `'/thin/'`.

> Which rule, if any, is this issue related to?

`declaration-property-value-blacklist`, but really any rule that supports regexes, should also support regex literals.

> What CSS is needed to reproduce this issue?

Does not apply.

> What stylelint configuration is needed to reproduce this issue?

Does not apply.

> Which version of stylelint are you using?

`8.2.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

`stylelint --config myconfig *.css`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

> What did you expect to happen?

I expected to be able to use regex literals in options.

> What actually happened (e.g. what warnings or errors you are getting)?

It didn't work.

### PR DESCRIPTION
**Pull request by CAYdenberg**
> Which issue, if any, is this issue related to?

Closes #3008 

> Is there anything in the PR that needs further explanation?

My goal is to do one of these per (working) day until it's done ... I can submit them as separate PRs or just keep a running branch.

### CODE REVIEW

**Comment by CAYdenberg** [comment]
This is ready for a review if anyone can manage it.

Mostly, this is pretty formulaic, so if you look at one commit you've seen them all. The only exception is:
https://github.com/stylelint/stylelint/pull/3799/commits/20ad77244b648df4cbf25ae9804124d00c7687dc

where I had to change the util validateObjectWithStringArrayProps.

**Comment by CAYdenberg** [comment]
Should probably tag this @stylelint/core 

Please review.

**Comment by CAYdenberg** [comment]
Thanks everyone! ❤️ 

I still can't edit the CHANGELOG directly, so if someone could do that for me, it'd be swell.

**Comment by jeddy3** [comment]
> I still can't edit the CHANGELOG directly, so if someone could do that for me, it'd be swell.

Strange... done:

-   Added: support for ordinary regular expressions anywhere a regex string is accepted in rule config ([#3799](https://github.com/stylelint/stylelint/pull/3799)).

@CAYdenberg Thanks again for all the work you put into this PR!

**Pull request merged**
