### PR TITLE
Add Coveralls coverage using NYC

### PR DESCRIPTION
**Pull request by ntwb**
See #1136 and #1237 

This is an alternate approach to that of Istanbul in #1237, and uses NYC instead:

> https://github.com/bcoe/nyc:
> > _"a code coverage tool built on istanbul that works for applications that spawn subprocesses"_

I've been using NYC over Istanbul as you need NYC when using AVA,:
https://github.com/sindresorhus/ava/#code-coverage

The results of NYC report: 

```
--------------------------------------------------------------|----------|----------|----------|----------|----------------|
File                                                          |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
--------------------------------------------------------------|----------|----------|----------|----------|----------------|
 src/                                                         |    96.08 |    90.91 |    97.01 |    95.97 |                |
  buildConfig.js                                              |    98.72 |    93.75 |      100 |    98.59 |            119 |
  createPlugin.js                                             |      100 |      100 |      100 |      100 |                |
  disableRanges.js                                            |    98.82 |    95.65 |      100 |    98.73 |             85 |
  index.js                                                    |      100 |      100 |      100 |      100 |                |
  normalizeRuleSettings.js                                    |      100 |      100 |      100 |      100 |                |
  postcssPlugin.js                                            |     93.1 |    81.25 |      100 |    92.59 |    27,31,53,81 |
  standalone.js                                               |    92.05 |    89.13 |     87.5 |    91.78 |... ,58,132,140 |
 src/formatters/                                              |    60.58 |    34.21 |    69.23 |    61.46 |                |
  index.js                                                    |      100 |      100 |      100 |      100 |                |
  jsonFormatter.js                                            |      100 |      100 |      100 |      100 |                |
  stringFormatter.js                                          |    76.62 |    46.43 |       85 |    77.46 |... 56,59,60,63 |
  verboseFormatter.js                                         |    11.54 |        0 |        0 |     12.5 |... 30,31,32,36 |
 src/rules/                                                   |      100 |      100 |      100 |      100 |                |
  index.js                                                    |      100 |      100 |      100 |      100 |                |
 src/rules/at-rule-empty-line-before/                         |    96.55 |     97.3 |      100 |      100 |                |
  index.js                                                    |    96.55 |     97.3 |      100 |      100 |                |
 src/rules/at-rule-name-case/                                 |    92.86 |    83.33 |      100 |      100 |                |
  index.js                                                    |    92.86 |    83.33 |      100 |      100 |                |
 src/rules/at-rule-name-space-after/                          |     91.3 |       75 |     87.5 |    94.12 |                |
  index.js                                                    |     91.3 |       75 |     87.5 |    94.12 |             13 |
 src/rules/at-rule-no-vendor-prefix/                          |    86.67 |    66.67 |      100 |      100 |                |
  index.js                                                    |    86.67 |    66.67 |      100 |      100 |                |
 src/rules/at-rule-semicolon-newline-after/                   |       95 |     87.5 |      100 |      100 |                |
  index.js                                                    |       95 |     87.5 |      100 |      100 |                |
 src/rules/block-closing-brace-newline-after/                 |    96.77 |    93.33 |      100 |      100 |                |
  index.js                                                    |    96.77 |    93.33 |      100 |      100 |                |
 src/rules/block-closing-brace-newline-before/                |    92.31 |     91.3 |      100 |      100 |                |
  index.js                                                    |    92.31 |     91.3 |      100 |      100 |                |
 src/rules/block-closing-brace-space-after/                   |    95.83 |    83.33 |      100 |      100 |                |
  index.js                                                    |    95.83 |    83.33 |      100 |      100 |                |
 src/rules/block-closing-brace-space-before/                  |    95.45 |    83.33 |      100 |      100 |                |
  index.js                                                    |    95.45 |    83.33 |      100 |      100 |                |
 src/rules/block-no-empty/                                    |    92.31 |       75 |      100 |      100 |                |
  index.js                                                    |    92.31 |       75 |      100 |      100 |                |
 src/rules/block-no-single-line/                              |    93.33 |    83.33 |      100 |      100 |                |
  index.js                                                    |    93.33 |    83.33 |      100 |      100 |                |
 src/rules/block-opening-brace-newline-after/                 |    90.48 |       75 |      100 |      100 |                |
  index.js                                                    |    90.48 |       75 |      100 |      100 |                |
 src/rules/block-opening-brace-newline-before/                |    95.24 |    83.33 |      100 |      100 |                |
  index.js                                                    |    95.24 |    83.33 |      100 |      100 |                |
 src/rules/block-opening-brace-space-after/                   |    95.24 |    83.33 |      100 |      100 |                |
  index.js                                                    |    95.24 |    83.33 |      100 |      100 |                |
 src/rules/block-opening-brace-space-before/                  |     96.3 |    91.67 |      100 |      100 |                |
  index.js                                                    |     96.3 |    91.67 |      100 |      100 |                |
 src/rules/color-hex-case/                                    |    95.24 |     87.5 |      100 |      100 |                |
  index.js                                                    |    95.24 |     87.5 |      100 |      100 |                |
 src/rules/color-hex-length/                                  |    97.06 |    95.45 |      100 |      100 |                |
  index.js                                                    |    97.06 |    95.45 |      100 |      100 |                |
 src/rules/color-named/                                       |    97.56 |    94.74 |      100 |      100 |                |
  index.js                                                    |    97.56 |    94.74 |      100 |      100 |                |
  representations.js                                          |      100 |      100 |      100 |      100 |                |
 src/rules/color-no-hex/                                      |    94.44 |    83.33 |      100 |      100 |                |
  index.js                                                    |    94.44 |    83.33 |      100 |      100 |                |
 src/rules/color-no-invalid-hex/                              |       95 |     87.5 |      100 |      100 |                |
  index.js                                                    |       95 |     87.5 |      100 |      100 |                |
 src/rules/comment-empty-line-before/                         |    96.67 |    96.77 |      100 |      100 |                |
  index.js                                                    |    96.67 |    96.77 |      100 |      100 |                |
 src/rules/comment-whitespace-inside/                         |    96.67 |    96.67 |      100 |      100 |                |
  index.js                                                    |    96.67 |    96.67 |      100 |      100 |                |
 src/rules/comment-word-blacklist/                            |    94.74 |     87.5 |      100 |      100 |                |
  index.js                                                    |    94.74 |     87.5 |      100 |      100 |                |
 src/rules/custom-media-pattern/                              |    93.75 |     87.5 |      100 |      100 |                |
  index.js                                                    |    93.75 |     87.5 |      100 |      100 |                |
 src/rules/custom-property-no-outside-root/                   |    92.86 |    83.33 |      100 |      100 |                |
  index.js                                                    |    92.86 |    83.33 |      100 |      100 |                |
 src/rules/custom-property-pattern/                           |     87.5 |       75 |      100 |      100 |                |
  index.js                                                    |     87.5 |       75 |      100 |      100 |                |
 src/rules/declaration-bang-space-after/                      |     96.3 |       75 |      100 |      100 |                |
  index.js                                                    |     96.3 |       75 |      100 |      100 |                |
 src/rules/declaration-bang-space-before/                     |    91.67 |       50 |      100 |      100 |                |
  index.js                                                    |    91.67 |       50 |      100 |      100 |                |
 src/rules/declaration-block-no-duplicate-properties/         |    96.77 |    91.67 |      100 |      100 |                |
  index.js                                                    |    96.77 |    91.67 |      100 |      100 |                |
 src/rules/declaration-block-no-ignored-properties/           |       96 |    90.91 |      100 |      100 |                |
  index.js                                                    |       96 |    90.91 |      100 |      100 |                |
 src/rules/declaration-block-no-shorthand-property-overrides/ |       96 |     87.5 |      100 |      100 |                |
  index.js                                                    |       96 |     87.5 |      100 |      100 |                |
  shorthands.js                                               |      100 |      100 |      100 |      100 |                |
 src/rules/declaration-block-properties-order/                |    90.38 |    90.28 |     91.3 |    92.13 |                |
  index.js                                                    |    90.38 |    90.28 |     91.3 |    92.13 |... 287,288,290 |
 src/rules/declaration-block-semicolon-newline-after/         |     91.3 |       80 |      100 |      100 |                |
  index.js                                                    |     91.3 |       80 |      100 |      100 |                |
 src/rules/declaration-block-semicolon-newline-before/        |    94.44 |    83.33 |      100 |      100 |                |
  index.js                                                    |    94.44 |    83.33 |      100 |      100 |                |
 src/rules/declaration-block-semicolon-space-after/           |    90.48 |     87.5 |     87.5 |    94.44 |                |
  index.js                                                    |    90.48 |     87.5 |     87.5 |    94.44 |             14 |
 src/rules/declaration-block-semicolon-space-before/          |    94.74 |    83.33 |      100 |      100 |                |
  index.js                                                    |    94.74 |    83.33 |      100 |      100 |                |
 src/rules/declaration-block-single-line-max-declarations/    |    94.74 |     87.5 |      100 |      100 |                |
  index.js                                                    |    94.74 |     87.5 |      100 |      100 |                |
 src/rules/declaration-block-trailing-semicolon/              |    93.33 |    88.89 |      100 |      100 |                |
  index.js                                                    |    93.33 |    88.89 |      100 |      100 |                |
 src/rules/declaration-colon-newline-after/                   |     93.1 |       80 |     87.5 |       95 |                |
  index.js                                                    |     93.1 |       80 |     87.5 |       95 |             14 |
 src/rules/declaration-colon-space-after/                     |    96.43 |    83.33 |      100 |      100 |                |
  index.js                                                    |    96.43 |    83.33 |      100 |      100 |                |
 src/rules/declaration-colon-space-before/                    |    91.67 |       50 |      100 |      100 |                |
  index.js                                                    |    91.67 |       50 |      100 |      100 |                |
 src/rules/declaration-no-important/                          |    90.91 |       75 |      100 |      100 |                |
  index.js                                                    |    90.91 |       75 |      100 |      100 |                |
 src/rules/font-family-name-quotes/                           |    94.03 |    93.65 |      100 |    95.16 |                |
  index.js                                                    |    94.03 |    93.65 |      100 |    95.16 |     93,114,125 |
 src/rules/font-weight-notation/                              |    89.39 |    90.91 |    88.89 |    96.08 |                |
  index.js                                                    |    89.39 |    90.91 |    88.89 |    96.08 |         17,102 |
 src/rules/function-blacklist/                                |    94.74 |    83.33 |      100 |      100 |                |
  index.js                                                    |    94.74 |    83.33 |      100 |      100 |                |
 src/rules/function-calc-no-unspaced-operator/                |    98.11 |    96.67 |      100 |      100 |                |
  index.js                                                    |    98.11 |    96.67 |      100 |      100 |                |
 src/rules/function-comma-newline-after/                      |    92.31 |       50 |      100 |      100 |                |
  index.js                                                    |    92.31 |       50 |      100 |      100 |                |
 src/rules/function-comma-newline-before/                     |    92.31 |       50 |      100 |      100 |                |
  index.js                                                    |    92.31 |       50 |      100 |      100 |                |
 src/rules/function-comma-space-after/                        |    97.44 |     87.5 |      100 |      100 |                |
  index.js                                                    |    97.44 |     87.5 |      100 |      100 |                |
 src/rules/function-comma-space-before/                       |    92.86 |       50 |      100 |      100 |                |
  index.js                                                    |    92.86 |       50 |      100 |      100 |                |
 src/rules/function-linear-gradient-no-nonstandard-direction/ |    93.55 |    88.89 |      100 |      100 |                |
  index.js                                                    |    93.55 |    88.89 |      100 |      100 |                |
 src/rules/function-max-empty-lines/                          |    95.24 |       90 |      100 |      100 |                |
  index.js                                                    |    95.24 |       90 |      100 |      100 |                |
 src/rules/function-name-case/                                |    96.15 |    91.67 |      100 |      100 |                |
  index.js                                                    |    96.15 |    91.67 |      100 |      100 |                |
 src/rules/function-parentheses-newline-inside/               |    94.44 |    94.44 |      100 |      100 |                |
  index.js                                                    |    94.44 |    94.44 |      100 |      100 |                |
 src/rules/function-parentheses-space-inside/                 |    94.74 |    95.45 |      100 |      100 |                |
  index.js                                                    |    94.74 |    95.45 |      100 |      100 |                |
 src/rules/function-url-data-uris/                            |    95.24 |       95 |      100 |      100 |                |
  index.js                                                    |    95.24 |       95 |      100 |      100 |                |
 src/rules/function-url-quotes/                               |    98.15 |    96.15 |      100 |      100 |                |
  index.js                                                    |    98.15 |    96.15 |      100 |      100 |                |
 src/rules/function-whitelist/                                |    95.45 |     87.5 |      100 |      100 |                |
  index.js                                                    |    95.45 |     87.5 |      100 |      100 |                |
 src/rules/function-whitespace-after/                         |    96.15 |     87.5 |      100 |      100 |                |
  index.js                                                    |    96.15 |     87.5 |      100 |      100 |                |
 src/rules/indentation/                                       |     94.7 |     92.8 |      100 |    95.08 |                |
  index.js                                                    |     94.7 |     92.8 |      100 |    95.08 |... 306,313,314 |
 src/rules/keyframe-declaration-no-important/                 |    91.67 |       75 |      100 |      100 |                |
  index.js                                                    |    91.67 |       75 |      100 |      100 |                |
 src/rules/max-empty-lines/                                   |    96.43 |    91.67 |      100 |      100 |                |
  index.js                                                    |    96.43 |    91.67 |      100 |      100 |                |
 src/rules/max-line-length/                                   |    96.97 |    93.75 |      100 |      100 |                |
  index.js                                                    |    96.97 |    93.75 |      100 |      100 |                |
 src/rules/max-nesting-depth/                                 |      100 |      100 |      100 |      100 |                |
  index.js                                                    |      100 |      100 |      100 |      100 |                |
 src/rules/media-feature-colon-space-after/                   |    96.15 |       75 |      100 |      100 |                |
  index.js                                                    |    96.15 |       75 |      100 |      100 |                |
 src/rules/media-feature-colon-space-before/                  |    91.67 |       50 |      100 |      100 |                |
  index.js                                                    |    91.67 |       50 |      100 |      100 |                |
 src/rules/media-feature-name-no-vendor-prefix/               |    92.86 |       75 |      100 |      100 |                |
  index.js                                                    |    92.86 |       75 |      100 |      100 |                |
 src/rules/media-feature-no-missing-punctuation/              |    96.88 |    93.75 |      100 |      100 |                |
  index.js                                                    |    96.88 |    93.75 |      100 |      100 |                |
 src/rules/media-feature-range-operator-space-after/          |    95.83 |       75 |      100 |      100 |                |
  index.js                                                    |    95.83 |       75 |      100 |      100 |                |
 src/rules/media-feature-range-operator-space-before/         |    93.75 |       50 |      100 |      100 |                |
  index.js                                                    |    93.75 |       50 |      100 |      100 |                |
 src/rules/media-query-list-comma-newline-after/              |    92.31 |       50 |      100 |      100 |                |
  index.js                                                    |    92.31 |       50 |      100 |      100 |                |
 src/rules/media-query-list-comma-newline-before/             |    92.31 |       50 |      100 |      100 |                |
  index.js                                                    |    92.31 |       50 |      100 |      100 |                |
 src/rules/media-query-list-comma-space-after/                |       96 |       50 |      100 |      100 |                |
  index.js                                                    |       96 |       50 |      100 |      100 |                |
 src/rules/media-query-list-comma-space-before/               |    92.86 |       50 |      100 |      100 |                |
  index.js                                                    |    92.86 |       50 |      100 |      100 |                |
 src/rules/media-query-parentheses-space-inside/              |    95.83 |       95 |      100 |      100 |                |
  index.js                                                    |    95.83 |       95 |      100 |      100 |                |
 src/rules/no-browser-hacks/                                  |    94.74 |    83.33 |      100 |      100 |                |
  index.js                                                    |    94.74 |    83.33 |      100 |      100 |                |
 src/rules/no-descending-specificity/                         |    97.56 |     87.5 |      100 |      100 |                |
  index.js                                                    |    97.56 |     87.5 |      100 |      100 |                |
 src/rules/no-duplicate-selectors/                            |    96.43 |       90 |      100 |      100 |                |
  index.js                                                    |    96.43 |       90 |      100 |      100 |                |
 src/rules/no-eol-whitespace/                                 |    91.67 |       75 |      100 |      100 |                |
  index.js                                                    |    91.67 |       75 |      100 |      100 |                |
 src/rules/no-extra-semicolons/                               |    97.62 |    92.86 |      100 |      100 |                |
  index.js                                                    |    97.62 |    92.86 |      100 |      100 |                |
 src/rules/no-indistinguishable-colors/                       |    94.44 |    85.71 |      100 |      100 |                |
  index.js                                                    |    94.44 |    85.71 |      100 |      100 |                |
 src/rules/no-invalid-double-slash-comments/                  |    92.86 |    83.33 |      100 |      100 |                |
  index.js                                                    |    92.86 |    83.33 |      100 |      100 |                |
 src/rules/no-missing-eof-newline/                            |    91.67 |    83.33 |      100 |      100 |                |
  index.js                                                    |    91.67 |    83.33 |      100 |      100 |                |
 src/rules/no-unknown-animations/                             |     89.8 |    86.67 |      100 |      100 |                |
  index.js                                                    |     89.8 |    86.67 |      100 |      100 |                |
 src/rules/no-unsupported-browser-features/                   |    95.45 |       90 |      100 |      100 |                |
  index.js                                                    |    95.45 |       90 |      100 |      100 |                |
 src/rules/number-leading-zero/                               |    97.14 |     87.5 |      100 |      100 |                |
  index.js                                                    |    97.14 |     87.5 |      100 |      100 |                |
 src/rules/number-max-precision/                              |    96.43 |    83.33 |      100 |      100 |                |
  index.js                                                    |    96.43 |    83.33 |      100 |      100 |                |
 src/rules/number-no-trailing-zeros/                          |    95.83 |       80 |      100 |      100 |                |
  index.js                                                    |    95.83 |       80 |      100 |      100 |                |
 src/rules/number-zero-length-no-unit/                        |     97.3 |    90.48 |      100 |      100 |                |
  index.js                                                    |     97.3 |    90.48 |      100 |      100 |                |
 src/rules/property-blacklist/                                |       95 |     87.5 |      100 |      100 |                |
  index.js                                                    |       95 |     87.5 |      100 |      100 |                |
 src/rules/property-case/                                     |    94.44 |       90 |      100 |      100 |                |
  index.js                                                    |    94.44 |       90 |      100 |      100 |                |
 src/rules/property-no-vendor-prefix/                         |    93.33 |     87.5 |      100 |      100 |                |
  index.js                                                    |    93.33 |     87.5 |      100 |      100 |                |
 src/rules/property-unit-blacklist/                           |    96.55 |    92.31 |      100 |      100 |                |
  index.js                                                    |    96.55 |    92.31 |      100 |      100 |                |
 src/rules/property-unit-whitelist/                           |    96.55 |    92.86 |      100 |      100 |                |
  index.js                                                    |    96.55 |    92.86 |      100 |      100 |                |
 src/rules/property-value-blacklist/                          |    95.24 |    83.33 |      100 |      100 |                |
  index.js                                                    |    95.24 |    83.33 |      100 |      100 |                |
 src/rules/property-value-whitelist/                          |    95.24 |    83.33 |      100 |      100 |                |
  index.js                                                    |    95.24 |    83.33 |      100 |      100 |                |
 src/rules/property-whitelist/                                |       95 |     87.5 |      100 |      100 |                |
  index.js                                                    |       95 |     87.5 |      100 |      100 |                |
 src/rules/root-no-standard-properties/                       |    96.43 |    93.75 |      100 |      100 |                |
  index.js                                                    |    96.43 |    93.75 |      100 |      100 |                |
 src/rules/rule-nested-empty-line-before/                     |    92.86 |    83.33 |      100 |      100 |                |
  index.js                                                    |    92.86 |    83.33 |      100 |      100 |                |
 src/rules/rule-non-nested-empty-line-before/                 |    97.14 |    96.77 |      100 |      100 |                |
  index.js                                                    |    97.14 |    96.77 |      100 |      100 |                |
 src/rules/selector-attribute-brackets-space-inside/          |    96.55 |       95 |      100 |      100 |                |
  index.js                                                    |    96.55 |       95 |      100 |      100 |                |
 src/rules/selector-attribute-operator-space-after/           |    93.75 |    83.33 |      100 |      100 |                |
  index.js                                                    |    93.75 |    83.33 |      100 |      100 |                |
 src/rules/selector-attribute-operator-space-before/          |    91.67 |       50 |      100 |      100 |                |
  index.js                                                    |    91.67 |       50 |      100 |      100 |                |
 src/rules/selector-class-pattern/                            |    95.24 |    91.67 |      100 |      100 |                |
  index.js                                                    |    95.24 |    91.67 |      100 |      100 |                |
 src/rules/selector-combinator-space-after/                   |    96.15 |    83.33 |      100 |      100 |                |
  index.js                                                    |    96.15 |    83.33 |      100 |      100 |                |
 src/rules/selector-combinator-space-before/                  |    91.67 |       50 |      100 |      100 |                |
  index.js                                                    |    91.67 |       50 |      100 |      100 |                |
 src/rules/selector-id-pattern/                               |       96 |    91.67 |      100 |      100 |                |
  index.js                                                    |       96 |    91.67 |      100 |      100 |                |
 src/rules/selector-list-comma-newline-after/                 |       95 |     87.5 |      100 |      100 |                |
  index.js                                                    |       95 |     87.5 |      100 |      100 |                |
 src/rules/selector-list-comma-newline-before/                |    92.31 |       50 |      100 |      100 |                |
  index.js                                                    |    92.31 |       50 |      100 |      100 |                |
 src/rules/selector-list-comma-space-after/                   |       96 |       50 |      100 |      100 |                |
  index.js                                                    |       96 |       50 |      100 |      100 |                |
 src/rules/selector-list-comma-space-before/                  |    92.86 |       50 |      100 |      100 |                |
  index.js                                                    |    92.86 |       50 |      100 |      100 |                |
 src/rules/selector-max-empty-lines/                          |    94.74 |       80 |      100 |      100 |                |
  index.js                                                    |    94.74 |       80 |      100 |      100 |                |
 src/rules/selector-max-specificity/                          |    90.91 |       75 |      100 |      100 |                |
  index.js                                                    |    90.91 |       75 |      100 |      100 |                |
 src/rules/selector-no-attribute/                             |     87.5 |    66.67 |      100 |      100 |                |
  index.js                                                    |     87.5 |    66.67 |      100 |      100 |                |
 src/rules/selector-no-combinator/                            |     87.5 |    66.67 |      100 |      100 |                |
  index.js                                                    |     87.5 |    66.67 |      100 |      100 |                |
 src/rules/selector-no-id/                                    |       90 |       80 |      100 |      100 |                |
  index.js                                                    |       90 |       80 |      100 |      100 |                |
 src/rules/selector-no-qualifying-type/                       |    90.16 |    76.32 |      100 |    94.34 |                |
  index.js                                                    |    90.16 |    76.32 |      100 |    94.34 |       33,36,38 |
 src/rules/selector-no-type/                                  |    89.74 |    85.71 |      100 |      100 |                |
  index.js                                                    |    89.74 |    85.71 |      100 |      100 |                |
 src/rules/selector-no-universal/                             |     87.5 |    66.67 |      100 |      100 |                |
  index.js                                                    |     87.5 |    66.67 |      100 |      100 |                |
 src/rules/selector-no-vendor-prefix/                         |    88.89 |       75 |      100 |      100 |                |
  index.js                                                    |    88.89 |       75 |      100 |      100 |                |
 src/rules/selector-pseudo-class-case/                        |    95.65 |    91.67 |      100 |      100 |                |
  index.js                                                    |    95.65 |    91.67 |      100 |      100 |                |
 src/rules/selector-pseudo-class-no-unknown/                  |    92.31 |     87.5 |      100 |      100 |                |
  index.js                                                    |    92.31 |     87.5 |      100 |      100 |                |
 src/rules/selector-pseudo-class-parentheses-space-inside/    |    96.88 |    95.45 |      100 |      100 |                |
  index.js                                                    |    96.88 |    95.45 |      100 |      100 |                |
 src/rules/selector-pseudo-element-case/                      |    95.65 |    91.67 |      100 |      100 |                |
  index.js                                                    |    95.65 |    91.67 |      100 |      100 |                |
 src/rules/selector-pseudo-element-colon-notation/            |    94.74 |    91.67 |      100 |      100 |                |
  index.js                                                    |    94.74 |    91.67 |      100 |      100 |                |
 src/rules/selector-pseudo-element-no-unknown/                |    96.15 |    93.33 |      100 |      100 |                |
  index.js                                                    |    96.15 |    93.33 |      100 |      100 |                |
 src/rules/selector-root-no-composition/                      |    90.91 |    83.33 |      100 |      100 |                |
  index.js                                                    |    90.91 |    83.33 |      100 |      100 |                |
 src/rules/selector-type-case/                                |    92.31 |    85.71 |      100 |      100 |                |
  index.js                                                    |    92.31 |    85.71 |      100 |      100 |                |
 src/rules/selector-type-no-unknown/                          |    95.65 |    90.91 |      100 |      100 |                |
  index.js                                                    |    95.65 |    90.91 |      100 |      100 |                |
 src/rules/shorthand-property-no-redundant-values/            |    98.21 |    97.73 |      100 |      100 |                |
  index.js                                                    |    98.21 |    97.73 |      100 |      100 |                |
 src/rules/string-no-newline/                                 |     87.5 |    66.67 |      100 |      100 |                |
  index.js                                                    |     87.5 |    66.67 |      100 |      100 |                |
 src/rules/string-quotes/                                     |    91.67 |       75 |      100 |      100 |                |
  index.js                                                    |    91.67 |       75 |      100 |      100 |                |
 src/rules/stylelint-disable-reason/                          |    97.06 |    92.86 |      100 |      100 |                |
  index.js                                                    |    97.06 |    92.86 |      100 |      100 |                |
 src/rules/time-no-imperceptible/                             |    89.13 |    86.67 |      100 |      100 |                |
  index.js                                                    |    89.13 |    86.67 |      100 |      100 |                |
 src/rules/unit-blacklist/                                    |    94.74 |    90.91 |      100 |      100 |                |
  index.js                                                    |    94.74 |    90.91 |      100 |      100 |                |
 src/rules/unit-case/                                         |       95 |    91.67 |      100 |      100 |                |
  index.js                                                    |       95 |    91.67 |      100 |      100 |                |
 src/rules/unit-no-unknown/                                   |    95.24 |    93.75 |      100 |      100 |                |
  index.js                                                    |    95.24 |    93.75 |      100 |      100 |                |
 src/rules/unit-whitelist/                                    |    94.74 |    90.91 |      100 |      100 |                |
  index.js                                                    |    94.74 |    90.91 |      100 |      100 |                |
 src/rules/value-keyword-case/                                |    97.62 |    97.37 |      100 |      100 |                |
  index.js                                                    |    97.62 |    97.37 |      100 |      100 |                |
 src/rules/value-list-comma-newline-after/                    |    92.31 |       50 |      100 |      100 |                |
  index.js                                                    |    92.31 |       50 |      100 |      100 |                |
 src/rules/value-list-comma-newline-before/                   |    92.31 |       50 |      100 |      100 |                |
  index.js                                                    |    92.31 |       50 |      100 |      100 |                |
 src/rules/value-list-comma-space-after/                      |    96.15 |    83.33 |      100 |      100 |                |
  index.js                                                    |    96.15 |    83.33 |      100 |      100 |                |
 src/rules/value-list-comma-space-before/                     |    92.86 |       50 |      100 |      100 |                |
  index.js                                                    |    92.86 |       50 |      100 |      100 |                |
 src/rules/value-no-vendor-prefix/                            |    89.47 |    66.67 |      100 |      100 |                |
  index.js                                                    |    89.47 |    66.67 |      100 |      100 |                |
 src/testUtils/                                               |    92.92 |    84.91 |       90 |     93.2 |                |
  basicChecks.js                                              |      100 |      100 |      100 |      100 |                |
  createRuleTester.js                                         |    91.49 |    85.71 |    85.71 |    92.05 |... 154,178,237 |
  index.js                                                    |      100 |      100 |      100 |      100 |                |
  mergeTestDescriptions.js                                    |      100 |      100 |      100 |      100 |                |
  testRule.js                                                 |      100 |       50 |      100 |      100 |                |
 src/utils/                                                   |    96.93 |    94.35 |      100 |    98.98 |                |
  atRuleParamIndex.js                                         |      100 |       50 |      100 |      100 |                |
  beforeBlockString.js                                        |      100 |      100 |      100 |      100 |                |
  blockString.js                                              |      100 |      100 |      100 |      100 |                |
  blurComments.js                                             |      100 |      100 |      100 |      100 |                |
  blurFunctionArguments.js                                    |      100 |      100 |      100 |      100 |                |
  blurInterpolation.js                                        |      100 |      100 |      100 |      100 |                |
  configurationError.js                                       |      100 |      100 |      100 |      100 |                |
  cssWordIsVariable.js                                        |      100 |      100 |      100 |      100 |                |
  declarationValueIndex.js                                    |      100 |      100 |      100 |      100 |                |
  findAtRuleContext.js                                        |      100 |      100 |      100 |      100 |                |
  functionArgumentsSearch.js                                  |      100 |      100 |      100 |      100 |                |
  getUnitFromValueNode.js                                     |    92.31 |    91.67 |      100 |      100 |                |
  hasBlock.js                                                 |      100 |      100 |      100 |      100 |                |
  hasEmptyBlock.js                                            |      100 |      100 |      100 |      100 |                |
  index.js                                                    |      100 |      100 |      100 |      100 |                |
  isAutoprefixable.js                                         |      100 |      100 |      100 |      100 |                |
  isCustomIdentPropertyAnimationName.js                       |      100 |      100 |      100 |      100 |                |
  isCustomIdentPropertyCounterIncrement.js                    |      100 |      100 |      100 |      100 |                |
  isCustomProperty.js                                         |      100 |      100 |      100 |      100 |                |
  isKeyframeRule.js                                           |      100 |      100 |      100 |      100 |                |
  isKnownPseudoClass.js                                       |      100 |      100 |      100 |      100 |                |
  isKnownPseudoElement.js                                     |      100 |      100 |      100 |      100 |                |
  isKnownUnit.js                                              |      100 |      100 |      100 |      100 |                |
  isLowerSpecificity.js                                       |      100 |      100 |      100 |      100 |                |
  isSingleLineString.js                                       |      100 |      100 |      100 |      100 |                |
  isStandardAtRule.js                                         |      100 |      100 |      100 |      100 |                |
  isStandardDeclaration.js                                    |      100 |      100 |      100 |      100 |                |
  isStandardFunction.js                                       |      100 |      100 |      100 |      100 |                |
  isStandardProperty.js                                       |      100 |      100 |      100 |      100 |                |
  isStandardRule.js                                           |      100 |      100 |      100 |      100 |                |
  isStandardSelector.js                                       |      100 |      100 |      100 |      100 |                |
  isStandardTypeSelector.js                                   |      100 |      100 |      100 |      100 |                |
  isStandardValue.js                                          |      100 |      100 |      100 |      100 |                |
  isValidHex.js                                               |      100 |      100 |      100 |      100 |                |
  isVariable.js                                               |      100 |      100 |      100 |      100 |                |
  isWhitespace.js                                             |      100 |      100 |      100 |      100 |                |
  matchesStringOrRegExp.js                                    |    82.61 |    85.71 |      100 |      100 |                |
  nextNonCommentNode.js                                       |      100 |      100 |      100 |      100 |                |
  nodeContextLookup.js                                        |      100 |      100 |      100 |      100 |                |
  optionsHaveException.js                                     |      100 |      100 |      100 |      100 |                |
  optionsHaveIgnored.js                                       |      100 |      100 |      100 |      100 |                |
  parseSelector.js                                            |      100 |      100 |      100 |      100 |                |
  rawNodeString.js                                            |      100 |      100 |      100 |      100 |                |
  report.js                                                   |    88.37 |    89.19 |      100 |    95.45 |             61 |
  ruleMessages.js                                             |      100 |      100 |      100 |      100 |                |
  styleSearch.js                                              |       99 |    99.02 |      100 |    98.84 |            151 |
  styleTagsFromHtmlExtracter.js                               |      100 |    92.86 |      100 |      100 |                |
  validateOptions.js                                          |    98.25 |     97.3 |      100 |      100 |                |
  whitespaceChecker.js                                        |    97.39 |     89.1 |      100 |    96.97 |    100,136,179 |
--------------------------------------------------------------|----------|----------|----------|----------|----------------|
All files                                                     |    94.24 |    89.39 |     98.4 |    97.93 |                |
--------------------------------------------------------------|----------|----------|----------|----------|----------------|
```

### CODE REVIEW

**Comment by ntwb** [comment]
So NYC reports 98.0% and Istanbul 98.7% https://coveralls.io/github/stylelint/stylelint

Either pull request would be fine to merge, I just happened to have coded it before I knew the other existed. I do like the fact NYC has the console report generated

**Comment by evilebottnawi** [comment]
@ntwb agree, NYC is better

**Comment by jeddy3** [comment]
> 98.0%

Hurrah! :)

Looks good to me!

**Comment by davidtheclark** [comment]
Thanks everybody!

**Pull request merged**
