### PR TITLE
Fix false positives for universal selector and disallowInList in no-duplicate-selectors

### LINKED ISSUE #4683: Fix false positives for universal selector and disallowInList in no-duplicate-selectors
> Clearly describe the bug

There are false positives for no-duplicate-selectors's `disallowInList: false`.

In summary, it's flagging some, but not all, selectors after a `*` declaration as a duplicate tag.

I've also created a [demo](https://stylelint.io/demo#N4Igxg9gJgpiBcICWBbADhATgFwATDExgENsYBxAGwgCNjKBlbAT0pgF9cAzTCFXAOQBnFmygBaSOggA7GDOxCBAbgA6M9ZBkjcVWvSasYuALy5CJMnrqNRMAAbrcz3AAtsKSvicvfNCAAe4kJIAF5IMgDm8Lj+mLCY4v4BajK+vj7puABUADSZ6dnw8DQwXFgw+WlZOcXEXGSY3tU1LsnBYRHRuBGuMJhI2Kmt7AWjGi24xM2tkNSYMQDuroMwwy7jGZNoMzVzWDFEUOvO4-ap6jABGDi4sFzEAK6UeNYGdqkguSBCzArEAQQ4CEQnEEXEACshF9wLIuEhIkDgD5VCBMM8YEJUTFkZNUTIIOIoI80JQkGBSDBgjA2GBsFgsQhcABtAq+bDoypsly41oZEBQJBCejURYASRkABkhdhsbgOY8YNzTgUALo+cbsEDsIA) of the issue.

> Which rule, if any, is the bug related to?

`no-duplicate-selectors`

> What code is needed to reproduce the bug?

```js
import {createGlobalStyle} from 'styled-components';

const GlobalStyle = createGlobalStyle`
    html {
        box-sizing: border-box;
        
        *,
        *::before,
        *::after {
            box-sizing: inherit;
        }
    }

    a {
        color: white;
    }
    
    p {
        color: red;
    }
`;

export default GlobalStyle;
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "no-duplicate-selectors": [
        true,
        {
            "disallowInList": true
        }
    ]
  }
}
```

> Which version of stylelint are you using?

13.2.1

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `stylelint "**/*.js" --report-needless-disables"`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Could just be a CSS-in-JS issue. Unknown.

> What did you expect to happen?

No errors / warnings to be flagged.

> What actually happened (e.g. what warnings or errors did you get)?

The following errors / warnings were flagged:

```shell
14:5 error Unexpected duplicate selector "a", first used at line 7 (no-duplicate-selectors)
```

### PR DESCRIPTION
**Pull request by srawlins**
> Which issue, if any, is this issue related to?

Fixes #4683
Closes #4795

> Is there anything in the PR that needs further explanation?

This code had a pretty big bug in it; it used `.includes` on a selector _string_, not a _list_, so it was just a substring match; the new code certainly takes more time, with more parsing, but is correct. Open to suggestions about how to do improve performance (perhaps cache parsed lists?).

### CODE REVIEW

**Comment by malsf21** [comment]
Just a note, looks like this collides with #4795, which has a more narrow approach to resolve the issue. Looks like these changes supersede #4795 though!

**Comment by jeddy3** [comment]
@srawlins Thanks for looking into this (and discovering the big bug behind this).

> Open to suggestions about how to do improve performance (perhaps cache parsed lists?).

Let's try caching the parsed lists.

You can use `npm run benchmark-rule -- no-duplicate-selectors "[true, {\"disallowInList\": true}]"` to benchmark the rule.

 At the moment `master` is:

```console
jeddy3@jeddy3 stylelint % npm run benchmark-rule -- no-duplicate-selectors "[true, {\"disallowInList\": true}]"

> stylelint@13.5.0 benchmark-rule /Users/jeddy3/Projects/stylelint
> node scripts/benchmark-rule.js "no-duplicate-selectors" "[true, {\"disallowInList\": true}]"

Warnings: 78
Mean: 91.46247921052631 ms
Deviation: 28.897587464632007 ms
```

And this branch is:

```console
jeddy3@jeddy3 stylelint % npm run benchmark-rule -- no-duplicate-selectors "[true, {\"disallowInList\": true}]" 

> stylelint@13.5.0 benchmark-rule /Users/jeddy3/Projects/stylelint
> node scripts/benchmark-rule.js "no-duplicate-selectors" "[true, {\"disallowInList\": true}]"

Warnings: 37
Mean: 10107.0616478 ms
Deviation: 508.2475623037317 ms
```

We don't need to make this branch comparable to `master` as correctness is better than speed, but it's worth seeing if caching will take a chunk out of this branch's numbers.

**Comment by srawlins** [comment]
> Let's try caching the parsed lists.

Thanks so much for the benchmarking tips! I read the code further and discovered what `nodeContextLookup` does and how the rule loop uses one giant tree anyhow, so I re-used that for a more proper fix. I also added another test that was failing before this refactor.

**Comment by jeddy3** [comment]
> - Fixed: `no-duplicate-selectors` false positives for universal selector and `disallowInList` ([#4809](https://github.com/stylelint/stylelint/pull/4809)).

**Pull request merged**
