### PR TITLE
Fix error "Cannot find module './testUtils/ruleTester'"

### LINKED ISSUE #736: 4.3.0 miss some files ? (Error: Cannot find module './testUtils/ruleTester')
https://travis-ci.org/MoOx/statinamic/jobs/109066672#L1038

### PR DESCRIPTION
**Pull request by MoOx**
Close #736
Ref #732 #702

### CODE REVIEW

**Comment by jeddy3** [comment]
Going to release 4.3.1 now

**Comment by MoOx** [comment]
<3

**Comment by jeddy3** [comment]
Done.

@MoOx Big thanks for tracking this one down so quickly and for the PR!

**Comment by jeddy3** [comment]
Missing `tape` dep... I'm on it.

**Comment by MoOx** [comment]
Oh sorry I opened a new issue, didn't see your message.

**Comment by MoOx** [comment]
Thanks for your time.

**Pull request merged**
