### PR TITLE
Add FAQ item about bundling configs

### LINKED ISSUE #1800: Allow `plugins` have multiple bundles.
I have some projects based on pure `css`, `less` and `scss`. Be good have multiple bundles in `plugin`. Useful example this https://github.com/itgalaxy/eslint-plugin-itgalaxy. Example (`eslint` support this http://eslint.org/docs/user-guide/configuring#using-the-configuration-from-a-plugin):
```json
{
  "stylelint": {
       "extends": [
            "plugin:itgalaxy/scss",
            "plugin:itgalaxy/sort"
        ]
  }
}
``` 
or
```json
{
  "stylelint": {
       "extends": [
            "plugin:itgalaxy/css",
            "plugin:itgalaxy/cssnext"
        ]
  }
}
```
It is allowed configure which need lint, quickly and easily add or remove plugins. Also it is allow prepare plugins bundles.
/cc @stylelint/core

### PR DESCRIPTION
**Pull request by jeddy3**
Closes #1800

### CODE REVIEW

**Comment by m-allanson** [comment]
LGTM

**Comment by evilebottnawi** [comment]
@jeddy3 Maybe create example inside `stylelint` orgs? package can removed or renamed

**Comment by jeddy3** [comment]
> package can removed or renamed

We can just update the FAQ if that happens.

**Comment by evilebottnawi** [comment]
@jeddy3 And we have to make this example repository again, it seems to me the right to do it straight away

**Comment by jeddy3** [comment]
If there's a resource we can point at that resolve this issue now, then I'd rather do that than make work for ourselves.

**Comment by evilebottnawi** [comment]
@jeddy3 let's wait what says @davidtheclark

**Comment by davidtheclark** [comment]
This is pretty basic Node knowledge. You can`require` any file in the package. How about just adding something like this:

> A user can `require()` any file in your npm package, so all you need to do is document which paths point to configs (e.g. `require('my-package/config-2')`)

**Comment by evilebottnawi** [comment]
@davidtheclark sgtm

**Comment by jeddy3** [comment]
> How about just adding something like this?

Sgtm. Updated the PR.

**Comment by davidtheclark** [comment]
👍

**Pull request merged**
