### PR TITLE
Add link to stylelint-scales plugin pack

### PR DESCRIPTION
**Pull request by digitaljohn**
> Which issue, if any, is this issue related to?

n/a

> Is there anything in the PR that needs further explanation?

Adding `stylelint-scales` to the list of stylelint plugins.

### CODE REVIEW

**Comment by vankop** [comment]
Looks like you need to add namespace `@signal-noise/stylelint-scales` or you going to take `stylelint-scales` package name?

**Comment by digitaljohn** [comment]
@vankop @jeddy3 This has been updated, thank you for pointing this out.

**Comment by vankop** [comment]
Why you don't want to take `stylelint-scales` ?

**Comment by jeddy3** [comment]
> Why you don't want to take stylelint-scales ?

I believe things are shifting towards scoped packages. For example, GitHub new [package registry](https://github.com/features/package-registry) only supports scoped packages at the moment.

I think we might as well go with the trend and start introducing scoped packages to stylelint plugins.

**Comment by vankop** [comment]
> we use [Lerna](https://lerna.js.org/) to manage everything in the single repo that has ~60 packages with deep dependencies on each other

Did you try [rush][https://rushjs.io/] - solution by Microsoft?

**Pull request merged**
