### PR TITLE
WIP: False positive for unit-no-unknown within calc function

### PR DESCRIPTION
**Pull request by CAYdenberg**
> Which issue, if any, is this issue related to?

#2551

> Is there anything in the PR that needs further explanation?

WIP. Wrote failing tests.

### CODE REVIEW

**Comment by jeddy3** [comment]
Tests look good.

Let's handle `calc()` as a special case.

**Comment by ntwb** [comment]
Resolved _prettier_ merge conflict in https://github.com/stylelint/stylelint/pull/2664/commits/1660eca11f89b20e9854842fdb0144c27d895388

**Comment by CAYdenberg** [comment]
I've been out-of-town and then swamped and haven't had time to finish this. If anyone wants to branch off my work that's absolutely fine with me, otherwise I'll get to it when I get to it :)

**Comment by CAYdenberg** [comment]
Whole bunch of weird stuff in the diff which I assume is due to prettier or some automated process. Will close and rebase from master.

**Pull request closed without merging**
