### PR TITLE
Part of issue 1101.

### PR DESCRIPTION
**Pull request by evilebottnawi**
/cc @davidtheclark 
All issue be contain little parts.

### CODE REVIEW

**Comment by davidtheclark** [comment]
Want to add a note to the changelog? Otherwise looks good.

**Comment by evilebottnawi** [comment]
@davidtheclark good?

**Comment by davidtheclark** [comment]
Yep, merge after CI turns green.

**Comment by evilebottnawi** [comment]
@davidtheclark good, i have time to resolve parts of this issue.

**Comment by evilebottnawi** [comment]
Ref issue: https://github.com/stylelint/stylelint/issues/1101

**Comment by evilebottnawi** [comment]
CI green. Merge.

**Pull request merged**
