### PR TITLE
Improved rule-properties-order

### PR DESCRIPTION
**Pull request by davidtheclark**
Addresses #393, #447, and #469.

Completely rewrote `rule-properties-order` in order to allow for the property groups. Here's what can be done:

Within a order array, you can include unprefixed property names, as before, or you can include objects with these properties:

- **strict** (boolean): If `true`, the properties in this group must come in the order specified. By default (or if `strict` is `false`), the group is flexible, and the properties can be in any order as long as they are grouped correctly.
- **emptyLineBefore** (boolean): If `true`, this group must be separated from other properties by an empty newline. By default (or if `emptyLineBefore` is `false), the rule doesn't care if there are empty newlines or not before properties.
- **properties** (array of strings): The properties in this group.

See the tests for details about how it works.

Despite @MadLittleMods's request for indefinitely nested groups, I decided that the code was already insanely complicated enough, so *you are not allowed to put more groups within a group's `properties` array.*

At the same time, I fixed the #469 bug.

*Please give me your feedback, help write more tests (if you think they're necessary), and help with the documentation (which I did not touch yet, except by writing the above).*

Thoughts?

cc/ @DanGamble89, @MadLittleMods

### CODE REVIEW

**Comment by DanGamble89** [comment]
Sounds pretty perfect to me, does the `emptyLineBefore` ignore the first declared group? I do agree nested groups might be a bit overkill, what would be the use case for them?

**Comment by davidtheclark** [comment]
> Sounds pretty perfect to me, does the emptyLineBefore ignore the first declared group

Yes. The tests are verifying this right now.

> I do agree nested groups might be a bit overkill, what would be the use case for them?

I can see the use, in some elaborate ordering schemas; but I do not think it's super important and don't want to spend the time myself figuring it out, adding further complexity to the code. Open to a PR --- maybe somebody with a CS degree or real experience or something can show me how this rule can be done better!

**Comment by DanGamble89** [comment]
Ah right cool, sorry i'm still quite new to JS so couldn't fully get my head around the committed files.

That's fair enough, my personal use is 6 or 7 split groups and then i just alphabetise in them! Will try and write a webpack loader for Stylelint this week so i can finally fully utilise it, thanks for the addition though. Was the only thing stopping me fully integrating it :)

**Comment by davidtheclark** [comment]
@DanGamble89 : Thanks for asking! It's not the easiest commit to read.

> Will try and write a webpack loader for Stylelint

That would be awesome.

**Comment by vlkosinov** [comment]
> Will try and write a webpack loader for Stylelint
@DanGamble89 why you can't use postccss loader with stylelint as processor?

**Comment by DanGamble89** [comment]
@vlkosinov honestly, because I don't know how! I was going to look at how eslint and csslint do their loaders so I can use it as a pre loader :)

**Comment by jeddy3** [comment]
Oh wow! That's a lot of stuff. When we first wrote this rule I was like "Lets _just_ do alphabetical sorting, because that's what everyone does right?!". Apparently that's not the case and, judging by the handful of shareable configs out there, people really [love](https://github.com/keithamus/stylelint-config-strict/blob/master/index.js#L345) [specifying](https://github.com/rtablada/stylelint-config-rtablada/blob/master/index.js#L166) their own properties order. Who knew hey?

I'll get stuck into the documentation, but before I do I have one query...

> strict (boolean): If true, the properties in this group must come in the order specified. By default (or if strict is false), the group is flexible, and the properties can be in any order as long as they are grouped correctly.

What do you think about swapping this around and having a `weak (boolean)` option, so that the default behaviour of the array is consistent (i.e. ordered exactly as specified) irrespective of whether it's nested or not? It feels like this might be a nicer experience for the user trying to just achieve #393. Likewise, it kind of feels like flexibly ordered groups are a special use case that should be opted into. What do you think?

> Despite @MadLittleMods's request for indefinitely nested groups, I decided that the code was already insanely complicated enough,

I think that was the right decision :)

So, besides that one question, this all looks fantastic to me. Thanks for putting in the leg work on this one!

**Comment by davidtheclark** [comment]
> What do you think about swapping this around and having a weak (boolean) option instead, so that the default behaviour of the array is consistent (i.e. ordered exactly as specified) irrespective of whether it's nested or not?

I'd be fine with switching the defaults. I think `weak` is kind of a ... weak word. How about a property called `order` with a keyword value `flexible` (and `strict` is default)?

As for postcss-bem-linter integration, have a look at https://github.com/davidtheclark/stylelint-selector-bem-pattern, which I just worked out yesterday and am currently experimenting with locally. Seems to be working great!

**Comment by MadLittleMods** [comment]
@davidtheclark @jeddy3 To expand on the flexible groupings and nested idea, [here is a full use-case](https://gist.github.com/MadLittleMods/929bcdefb2b29c9b97c3#file-stylelint-rule-properties-order-example-json) and [overview proposal of the syntax](https://gist.github.com/MadLittleMods/929bcdefb2b29c9b97c3#file-stylelint-rule-properties-order-use-case-syntax-overview-md)

**Comment by jeddy3** [comment]
> How about a property called order with a keyword value flexible (and strict is default)?

Much better!

> As for postcss-bem-linter integration, have a look at https://github.com/davidtheclark/stylelint-selector-bem-pattern

Oh wow. I totally hadn't seen this. That's ace! Great to see the options validator at work in the plugin! Also, so few lines of code to bring a CLI, `linter-stylelint` etc to `postcss-bem-linter`! :)

**Comment by vlkosinov** [comment]
Sorry for off-topic
> honestly, because I don't know how!

@DanGamble89 it is very simple, just two lines of code, see example: https://gist.github.com/vlkosinov/2d0497be4e9eece144d1

**Comment by davidtheclark** [comment]
@jeddy3, @MadLittleMods : I changed things so that groups have a property that is `order: "strict" | "flexible"`, and the default is `"strict"`.

@MadLittleMods: That is an interesting syntax you and your team came up with -- pretty cool. I think that because of its uniqueness and complexity it would be a good candidate for an external plugin, if you ever felt like developing an alternate ordering rule.

**Comment by davidtheclark** [comment]
@jeddy3 : Forgot to add -- so I think this PR needs documentation and then is ready to merge. Anybody disagree?

(Hope you're liking your new place! I was hungover on Sunday which meant I didn't feel like doing anything but sitting in the dark solving little code problems ... so bad for me = good for stylelint.)

**Comment by DanGamble89** [comment]
I like the `strict` as default change that would be the expected behaviour imo.

**Comment by jeddy3** [comment]
> I changed things so that groups have a property that is order: "strict" | "flexible", and the default is "strict".

Thanks for doing this.

> Forgot to add -- so I think this PR needs documentation and then is ready to merge. Anybody disagree?

Sounds good. I've added the docs. It wasn't much in the end as your proto-documentation worked a treat.

> Hope you're liking your new place!

Thanks :)

> which meant I didn't feel like doing anything but sitting in the dark solving little code problems

That's brilliant! Here's hoping for some more fruitful Sundays (and sore heads) :)

**Comment by satazor** [comment]
@MadLittleMods I loved your gist order preference. Could you share an up to date one with this new syntax?

**Comment by MadLittleMods** [comment]
@satazor Here ya go: https://gist.github.com/MadLittleMods/5dd03f1e8cb88ec1770e

**Pull request merged**
