### PR TITLE
Fix `function-no-unknown` `light-dark` false positive

### LINKED ISSUE #7226: `function-no-unknown`: fix `linear` `xywh` `light-dark` false positives
### What minimal example or steps are needed to reproduce the bug?

```css
:root {
  color-scheme: light dark;

  --text-color: light-dark(#777, #000);
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "function-no-unknown": true
  }
}
```

### How did you run Stylelint?

https://stylelint.io/demo

### See also

https://drafts.csswg.org/css-color-5/#light-dark
https://github.com/mdn/browser-compat-data/pull/20935

### Do you have a proposal to fix the bug?

1. <del>either update https://github.com/niksy/css-functions-list/blob/master/index.json</del>
2. or add an exception

### PR DESCRIPTION
**Pull request by mattxwang**
> Which issue, if any, is this issue related to?

Closes #7226.

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

### CODE REVIEW

**Review by Mouvedia — APPROVED** [review]

**Review by Mouvedia — COMMENTED** [review]
https://github.com/niksy/css-functions-list/commit/fec2bfea1be0f7663799d3b45aa0dc156ccf3d1f

**Comment by mattxwang** [comment]
Oh, good eye!

Should I make a PR updating the dep here, or update the dep itself (and treat this "bugfix" as a side effect)? Not sure how this normally works re: dep updates.

Also, [`webkit-gradient`](https://github.com/niksy/css-functions-list/commit/fec2bfea1be0f7663799d3b45aa0dc156ccf3d1f#diff-7aebb122a6ea8a2749d60cb05b7e103c9eae6e2e85e48d2d6cd9e20b63013975R162) has also been added.

**Comment by Mouvedia** [comment]
@mattxwang there's a bot that adds dependencies. Is there a way to trigger it?
The way to do it is to add a commit to that automatically created PR.

**Comment by Mouvedia** [comment]
@mattxwang there's a bot that adds dependencies. Is there a way to trigger it?
The way to do it is to add a commit to that automatically created PR.

**Comment by ybiquitous** [comment]
Ya, we can manually trigger Dependabot, or update PRs will come weekly on Monday.

**Comment by mattxwang** [comment]
Gotcha. I think I meant more, how do we want this to be reflected in the changeset/changelog: is the dep update accompanied by fixing this false positive?

(also, I'll add the test case to the dependabot PR)

**Comment by Mouvedia** [comment]
@mattxwang

```md
Fixed: `function-no-unknown` false positives for `light-dark`, `linear`and `xywh`
```

**Pull request closed without merging**
