### PR TITLE
Account for vendor prefixes when filtering on walk

### PR DESCRIPTION
**Pull request by evilebottnawi**
1. Should we check vendor prefixes (at-rules, properties and etc)? If should some rules need change to working with vendor prefixes. If yes i PR this.

/cc @davidtheclark @jeddy3

### CODE REVIEW

**Comment by jeddy3** [comment]
> Should we check vendor prefixes (at-rules, properties and etc)?

I think we should check vendor prefixed things *by default*. However, if this proves difficult to implement for a particular rule, then I think we simple ignore vendor prefixed things *in that rule* and add note saying so in that rule's README.

This is a breaking change btw.

**Comment by evilebottnawi** [comment]
@jeddy3 Agree. I create other change in rules in this PR and we may merge this in v7.

**Comment by jeddy3** [comment]
> Agree. I create other change in rules in this PR 

Good idea.

> and we may merge this in v7.

Definitely `v7` as these change could break builds.

**Comment by davidtheclark** [comment]
@evilebottnawi , @jeddy3 What still needs to be done for this PR?

**Comment by evilebottnawi** [comment]
@davidtheclark found time :smile: this saturday i will do it.

**Comment by evilebottnawi** [comment]
Close https://github.com/stylelint/stylelint/pull/1591

**Pull request closed without merging**
