### PR TITLE
Fix `at-rule-no-unknown` false positives for `@position-try`

### LINKED ISSUE #7965: Fix `at-rule-no-unknown` false positives for `@position-try`
### What minimal example or steps are needed to reproduce the bug?

```css
@position-try --foo {}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "at-rule-no-unknown": true
  }
}
```

### How did you run Stylelint?

https://stylelint.io/demo

### What did you expect to happen?

no error

### What actually happened?

`Unexpected unknown at-rule "@position-try"`

### Resources

https://developer.mozilla.org/en-US/docs/Web/CSS/@position-try#browser_compatibility

### PR DESCRIPTION
**Pull request by yelizsevinc**
> Which issue, if any, is this issue related to?

Closes #7965

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

I hope I didn't forget anything 🌸

### CODE REVIEW

**Comment by Mouvedia** [comment]
Hello @yelizsevinc,

Thank you for your first contribution.
Most of the false positives changes are often accompanied by a test.
It helps with the detection of regressions. 
e.g. `@position-try --foo {}`
i.e. simply add it to https://github.com/stylelint/stylelint/blob/78b1e837f1e4197034e52a2b33699cdc9f0821d3/lib/rules/at-rule-no-unknown/__tests__/index.mjs#L8

**Comment by yelizsevinc** [comment]
> Hello @yelizsevinc,
> 
> Thank you for your first contribution. Most of the false positive changes are often accompanied by a test. It helps with the detection of regressions. e.g. `@position-try --foo {}` i.e. simply add it to
> 
> https://github.com/stylelint/stylelint/blob/78b1e837f1e4197034e52a2b33699cdc9f0821d3/lib/rules/at-rule-no-unknown/__tests__/index.mjs#L8

Ah, thank you very much for your time to point out. Just added and will check the tests in the future.

**Review by Mouvedia — APPROVED** [review]
LGTM

**Review by ybiquitous — APPROVED** [review]
Thank you. LGTM 👍🏼

**Pull request merged**
