### PR TITLE
Upgrade colorguard

### LINKED ISSUE #911: Upgrade css-colorguard and use new warning props
[Version 1.1.0](https://github.com/SlexAxton/css-colorguard/blob/master/CHANGELOG.md#2016-03-11---110) puts `firstColor` and `secondColor` properties on the warning object, so we can use that instead of parsing the warning message text.

I am marking this as blocked because the rule is currently not implemented because of the `eval()` problem.

### PR DESCRIPTION
**Pull request by m-allanson**
Resolves #911

### CODE REVIEW

**Comment by davidtheclark** [comment]
Excellent @m-allanson! Really happy to see you picking up issues.

Let's just finish this one so that's ready for a new release with `color-no-indistinguishable`. Please make sure that that rule is included in these places: http://stylelint.io/developer-guide/rules/

Also, before we release this I'd like to make sure that it does indeed not crash Atom linter. You or I can try running this branch in our Atom linter and verify that the rule works.

**Comment by m-allanson** [comment]
Great! I've wired up the rule, but couldn't see how to use a local version of stylelint with Atom linter.

**Comment by davidtheclark** [comment]
The way that I would do it is to open up `~/.atom/packages/linter-stylelint` and replace it's locally installed version of stylelint with the one from your branch, and then try it out. If that makes sense and you have time to verify that today great; if not I'll try to get to it soon.

**Comment by m-allanson** [comment]
It looks good with Atom 1.4.2 on OSX.
screen shot 2016-03-18 at 16 51 47

**Comment by davidtheclark** [comment]
Thanks!

**Comment by Arcanemagus** [comment]
@m-allanson You should really update your Atom install :stuck_out_tongue:

v1.6.0 was just pushed to stable yesterday.

**Comment by m-allanson** [comment]
@Arcanemagus Thanks! The auto-update wasn't working for some reason, now I've manually switched to the latest, greatest version :)

**Pull request merged**
