### PR TITLE
Add rule: max-line-length

### PR DESCRIPTION
**Pull request by davidtheclark**
Addresses #423.

Here's a draft of the rule. While working out the tests I decided that the only long lines I thought should be accommodated were those with no whitespace except at the line's start. I think that in all the other situations you actually could make something multiline --- and the purpose of the rule is to force that, so I didn't want to make a limited set of punctuation marks that evaded the rule.

I did not write documentation. First I just wanted to see what @jeddy3 and @MadLittleMods thought of what's there. Thanks!

### CODE REVIEW

**Comment by jeddy3** [comment]
> I thought should be accommodated were those with no whitespace except at the line's start

Yep. That sounds good to me.

**Comment by MadLittleMods** [comment]
Sounds good, I can't think of a situation where this would be a problem.

**Comment by davidtheclark** [comment]
I did think of a kind of problem: What if one rule says you must put space inside your url parentheses, then this one sets your max-line-length, then you have a line like this:

```css
background: 
  url( somethingsomethingsomethingsomethingsomethingsomething );
```

... That will throw an error. The default solution would be to remove those spaces or to change them to newlines and have this:

```css
background: 
  url( 
    somethingsomethingsomethingsomethingsomethingsomething 
   );
```

... but your url parentheses spacing rule won't allow that.

Thoughts?

**Comment by jeddy3** [comment]
I think we always knew some rules would conflict (the most obvious example being the `*-blacklist` and `*-whitelist` rules). I think we decided it was down to the user to resolve the problem. e.g.

If a user enables `max-line-length`. Then then should either disabled the `function-parentheses-*-inside` rules, or enable the `function-parentheses-newline-inside`, with the option `"always-multiline"`, and change the `function-parentheses-space-inside` option to `always-single-line` - to give the authors more of a chance of conforming to the code style.

Is that what you're referring to?

**Comment by davidtheclark** [comment]
Yep, you're right: we've got it covered. That's good :)

**Comment by jeddy3** [comment]
@davidtheclark Add docs and wired up. Shall we merge?

**Comment by jeddy3** [comment]
If you're OK with the docs, are you able to rebase this one for me and merge in?

**Pull request merged**
