### PR TITLE
Fix case when raws.after/before could be undefined or null

### PR DESCRIPTION
**Pull request by vankop**
> Which issue, if any, is this issue related to?

fix https://github.com/stylelint/stylelint/issues/4309

> Is there anything in the PR that needs further explanation?

Nothing

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Can we add tests?

**Comment by vankop** [comment]
> Can we add tests?

Need to ask in issue for reproduction. As I understand it was `css-in-js`

**Comment by vankop** [comment]
looks like coverall have downtime..

**Comment by vankop** [comment]
I suggest to force this fix without tests. Looks like this is common problem when postcss returns `typeof root.raws.after !== 'string'`

**Comment by vankop** [comment]
@hudochenkov can you release this fix, please?

**Comment by hudochenkov** [comment]
I'll try to do release tomorrow.

**Comment by hudochenkov** [comment]
What changelog entry could be for this PR? Both PR title and issue title aren't suitable for changelog.

**Comment by evilebottnawi** [comment]
@hudochenkov fix crashing/stucking stylelint for css-in-js/other case name?

**Comment by hudochenkov** [comment]
> -   Fixed: `no-eol-whitespace` parsing problems for non-standard syntaxes ([#4313](https://github.com/stylelint/stylelint/pull/4313)).

**Comment by vankop** [comment]
@hudochenkov sorry for writing here, take a look on latest commit in `master`, CI build failed.

**Comment by hudochenkov** [comment]
Yeah, I see. Restarted it. Because CI 5 hours ago was successful.

**Pull request merged**
