### PR TITLE
A couple more selector-no rules

### PR DESCRIPTION
**Pull request by davidtheclark**
These ones are easy thanks to postcss-selector-parser.

### CODE REVIEW

**Comment by MoOx** [comment]
Now that we are close to cut a release, maybe you should add doc at the same time you add new rules ?

Otherwise it looks good.

**Comment by jeddy3** [comment]
Great to see more of these going in.

> maybe you should add doc at the same time you add new rules ?

That would be swell!

I'm back on the train, so I'm happy to do these ones now as it's the easiest thing for me to do with an intermittent net connection.

**Comment by jeddy3** [comment]
OK to merge?

**Comment by davidtheclark** [comment]
Yep, I should start doing that (adding docs).

**Pull request merged**
