### PR TITLE
Fix max-empty-lines before comments

### PR DESCRIPTION
**Pull request by yepninja**
> Which issue, if any, is this issue related to?

https://github.com/stylelint/stylelint/issues/4330

> Is there anything in the PR that needs further explanation?

e.g. "No, it's self-explanatory."

### CODE REVIEW

**Review by vankop — CHANGES_REQUESTED** [review]
need to update snapshots

**Comment by yepninja** [comment]
@vankop Updated

**Review by vankop — APPROVED** [review]

**Comment by ybiquitous** [comment]
@yepninja Thanks for creating this PR! Could you please change the base branch from `master` to [`v14`](https://github.com/stylelint/stylelint/tree/v14)?

**Comment by yepninja** [comment]
@ybiquitous Changed

**Comment by ybiquitous** [comment]
@yepninja Thank you! Can you also fix the conflict, please?

**Comment by yepninja** [comment]
@ybiquitous Resolved

**Comment by ybiquitous** [comment]
v14 changelog entry:

> Fixed: max-empty-lines autofix for Less comments (#5507).

**Pull request merged**
