### PR TITLE
Add no-unknown-animations; closes #596

### LINKED ISSUE #596: no-unknown-animations
What about having a rule to check that every animation in `animation-name` have correct `@keyframes`.

### PR DESCRIPTION
**Pull request by davidtheclark**

### CODE REVIEW

**Comment by jeddy3** [comment]
Looks spot on to me.

**Comment by davidtheclark** [comment]
@jeddy3 It's very annoying how this pattern of adding things to the changelog in the PRs means that you can only merge one at a time without rebasing all the others ...

**Comment by jeddy3** [comment]
Yep, I just realised that.

What's the best alternative? Update the changelog just before doing a release by looking back through the commits? It'll help with the rebasing, but it could be more error prone.

Ideas?

**Comment by davidtheclark** [comment]
I have no ideas right now. Will think about it.

**Comment by ntwb** [comment]
ESLint have a "release tool" https://github.com/eslint/eslint-release#what-it-does which updates the changelog based commits during the release process.

The relevant points:
> 3 Gathers the commit message for each commit since the last release
> 4 Calculates the next release version based on the commit message format of the changes since the last release
> 5 Updates CHANGELOG.md and commits the changes 

So two options here, stylelint could *roll its own* release script similar to ESLint or add this functionality to @MoOx's https://github.com/MoOx/npmpub

**Comment by MoOx** [comment]
Even better => https://github.com/semantic-release/semantic-release

**Comment by davidtheclark** [comment]
The problem with a tool that automatically builds a changelog based on commit messages is that then you have to spend a lot of time pruning commits and commit messages, which can be a huge pain. I would prefer to manually compose the changelog's entries.

**Comment by MoOx** [comment]
Same feeling. And when you see how to contribute to eslint, it's kind of a pain...

**Pull request merged**
