### PR TITLE
Regenerate package-lock.json

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes npm vulnerabilities

### CODE REVIEW

**Review by jeddy3 — APPROVED** [review]
LGTM, thanks!

This is connected to https://github.com/stylelint/stylelint/issues/5291.

Some of our older dependencies (which are now ESM-only) have vulnerabilities. Fortunately, these can currently be fixed using `npm audit fix`.

For example, `meow`:

```
jeddy3@mac stylelint % npm audit
# npm audit report

normalize-url  4.3.0 - 4.5.0 || 5.0.0 - 5.3.0 || 6.0.0
Severity: high
Regular Expression Denial of Service - https://npmjs.com/advisories/1755
fix available via `npm audit fix`
node_modules/normalize-url

path-parse  <1.0.7
Severity: moderate
Regular Expression Denial of Service in path-parse - https://npmjs.com/advisories/1773
fix available via `npm audit fix`
node_modules/path-parse

trim-newlines  <3.0.1 || =4.0.0
Severity: high
Regular Expression Denial of Service - https://npmjs.com/advisories/1753
fix available via `npm audit fix`
node_modules/trim-newlines

3 vulnerabilities (1 moderate, 2 high)

To address all issues, run:
  npm audit fix
jeddy3@mac stylelint % npm ls trim-newlines
stylelint@13.13.1 /Users/jeddy3/Projects/stylelint
├─┬ meow@9.0.0
│ └── trim-newlines@3.0.0
└─┬ np@7.5.0
  └─┬ meow@8.1.2
    └── trim-newlines@3.0.0 deduped
```

Hopefully, this stays true for a while longer so that we can deprioritise the migration to ESM.

**Comment by alexander-akait** [comment]
Some of these package can be dropped in favor build-in functions, for example - `trim-newlines`, not hard to implement using regexp, less deps - less problems

**Review by ybiquitous — APPROVED** [review]
Nice, LGTM! 👍🏼 

And, I also agree with @alexander-akait 😄

**Comment by jeddy3** [comment]
>  for example - trim-newlines, not hard to implement using regexp, less deps === less problems

`trim-newlines` is a dep of `meow`. 

But, yes, maybe some of our other ESM-only deps can be dropped:

```
execall            ^2.0.0  →   ^3.0.0     
 get-stdin          ^8.0.0  →   ^9.0.0     
 globby            ^11.0.3  →  ^12.0.2     
 log-symbols        ^4.1.0  →   ^5.0.0     
 mathml-tag-names   ^2.1.3  →   ^3.0.1     
 meow               ^9.0.0  →  ^10.1.1     
 slash              ^3.0.0  →   ^4.0.0     
 string-width       ^4.2.2  →   ^5.0.0     
 strip-ansi         ^6.0.0  →   ^7.0.1 
```

Fortunately, we only need to cross that bridge if there's a vulnerability in the package itself rather than one of its deps.

**Comment by ybiquitous** [comment]
@jeddy3 Thank you for listing up it! I try removing `slash` (#5544).

**Pull request merged**
