### PR TITLE
Process multiple spaces in media (#4509)

### LINKED ISSUE #4509: media-feature-parentheses-space-inside did not remove space
Hi

I have a problem with `media-feature-parentheses-space-inside`
(https://stylelint.io/user-guide/rules/media-feature-parentheses-space-inside) 

I set `"media-feature-parentheses-space-inside": "never",`

It's not working if there is more than **one space**

```
@media (  min-width: 700px     ) {
```

After fix i expect this:
```
@media (min-width: 700px) {
```

#### My settings (all from https://github.com/stylelint/stylelint-config-standard/blob/master/index.js):
```

			"at-rule-empty-line-before": [
				"always",
				{
					"except": [
						"blockless-after-same-name-blockless",
						"first-nested"
					],
					"ignore": [
						"after-comment"
					]
				}
			],
			"at-rule-name-case": "lower",
			"at-rule-name-space-after": "always-single-line",
			"at-rule-semicolon-newline-after": "always",
			"block-closing-brace-empty-line-before": "never",
			"block-closing-brace-newline-after": "always",
			"block-closing-brace-newline-before": "always-multi-line",
			"block-closing-brace-space-before": "always-single-line",
			"block-opening-brace-newline-after": "always-multi-line",
			"block-opening-brace-space-after": "always-single-line",
			"block-opening-brace-space-before": "always",
			"color-hex-case": "lower",
			"color-hex-length": "short",
			"comment-empty-line-before": [
				"always",
				{
					"except": [
						"first-nested"
					],
					"ignore": [
						"stylelint-commands"
					]
				}
			],
			"comment-whitespace-inside": "always",
			"custom-property-empty-line-before": [
				"always",
				{
					"except": [
						"after-custom-property",
						"first-nested"
					],
					"ignore": [
						"after-comment",
						"inside-single-line-block"
					]
				}
			],
			"declaration-bang-space-after": "never",
			"declaration-bang-space-before": "always",
			"declaration-block-semicolon-newline-after": "always-multi-line",
			"declaration-block-semicolon-space-after": "always-single-line",
			"declaration-block-semicolon-space-before": "never",
			"declaration-block-single-line-max-declarations": 1,
			"declaration-block-trailing-semicolon": "always",
			"declaration-colon-newline-after": "always-multi-line",
			"declaration-colon-space-after": "always-single-line",
			"declaration-colon-space-before": "never",
			"declaration-empty-line-before": [
				"always",
				{
					"except": [
						"after-declaration",
						"first-nested"
					],
					"ignore": [
						"after-comment",
						"inside-single-line-block"
					]
				}
			],
			"function-comma-newline-after": "always-multi-line",
			"function-comma-space-after": "always-single-line",
			"function-comma-space-before": "never",
			"function-max-empty-lines": 0,
			"function-name-case": "lower",
			"function-parentheses-newline-inside": "always-multi-line",
			"function-parentheses-space-inside": "never-single-line",
			"function-whitespace-after": "always",
			"indentation": 2,
			"length-zero-no-unit": true,
			"max-empty-lines": 1,
			"media-feature-colon-space-after": "always",
			"media-feature-colon-space-before": "never",
			"media-feature-name-case": "lower",
			"media-feature-parentheses-space-inside": "never",
			"media-feature-range-operator-space-after": "always",
			"media-feature-range-operator-space-before": "always",
			"media-query-list-comma-newline-after": "always-multi-line",
			"media-query-list-comma-space-after": "always-single-line",
			"media-query-list-comma-space-before": "never",
			"no-eol-whitespace": true,
			"no-missing-end-of-source-newline": true,
			"number-leading-zero": "always",
			"number-no-trailing-zeros": true,
			"property-case": "lower",
			"rule-empty-line-before": [
				"always-multi-line",
				{
					"except": [
						"first-nested"
					],
					"ignore": [
						"after-comment"
					]
				}
			],
			"selector-attribute-brackets-space-inside": "never",
			"selector-attribute-operator-space-after": "never",
			"selector-attribute-operator-space-before": "never",
			"selector-combinator-space-after": "always",
			"selector-combinator-space-before": "always",
			"selector-descendant-combinator-no-non-space": true,
			"selector-list-comma-newline-after": "always",
			"selector-list-comma-space-before": "never",
			"selector-max-empty-lines": 0,
			"selector-pseudo-class-case": "lower",
			"selector-pseudo-class-parentheses-space-inside": "never",
			"selector-pseudo-element-case": "lower",
			"selector-pseudo-element-colon-notation": "double",
			"selector-type-case": "lower",
			"unit-case": "lower",
			"value-list-comma-newline-after": "always-multi-line",
			"value-list-comma-space-after": "always-single-line",
			"value-list-comma-space-before": "never",
			"value-list-max-empty-lines": 0
		
```

#### Tested on
obraz

```
Version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
```

### PR DESCRIPTION
**Pull request by fanich37**
> Which issue, if any, is this issue related to?

It should close #4509 .

> Is there anything in the PR that needs further explanation?

No, it's self explanatory.

### CODE REVIEW

**Comment by hudochenkov** [comment]
Could you also add check for tabs `\t`, please? `/[ \t]/.test(node.before)`

**Comment by XhmikosR** [comment]
I wonder are newlines allowed here too?

**Comment by hudochenkov** [comment]
I believe we usually define whitespace as spaces and tabs in our rules, that's we we have rules like `function-comma-space-after` and `function-comma-newline-after`.

**Comment by hudochenkov** [comment]
> -   Fixed: `media-feature-parentheses-space-inside` false negatives for multiple spaces ([#4513](https://github.com/stylelint/stylelint/pull/4513)).

**Pull request merged**
