### PR TITLE
Revert adding Node.js 12 in AppVeyor

### PR DESCRIPTION
**Pull request by hudochenkov**
Before [the change](https://github.com/stylelint/stylelint/pull/4072) AppVeyor took 5-7 minutes to complete.

https://ci.appveyor.com/project/stylelint/stylelint/builds/24925881
https://ci.appveyor.com/project/stylelint/stylelint/builds/24825609

After change it takes 13-23 minutes:

https://ci.appveyor.com/project/stylelint/stylelint/builds/24976236 13 minutes.
https://ci.appveyor.com/project/stylelint/stylelint/builds/25120885 23 minutes and false fail.

### CODE REVIEW

**Comment by hudochenkov** [comment]
Windows builds failing. And when they are not — false error about passed tests.

**Comment by evilebottnawi** [comment]
> And when they are not — false error about passed tests.

It is wrong. It is visual bug. When tests failed they exit with code 1 and tests failed. When it is passed they exit with 0 code and tests passed. I can not understand why this is a problem. This is just a visual bug.

**Comment by evilebottnawi** [comment]
I will fix windows bugs and they ready to merge

**Comment by ntwb** [comment]
I’m currently mobile but will check this issue out an the Azure Pipelines issue, I’m not confident of Azure Pipelines current false reporting and would prefer we wait for node.js 12.x to stabilise on AppVeyor before switching to Azure as it stands right now

**Comment by evilebottnawi** [comment]
> refer we wait for node.js 12.x to stabilise on AppVeyor before switching to Azure as it stands right now

Why? :disappointed: AppVeyor always was very bad and looks as hack for windows tests

**Comment by ntwb** [comment]
AppVeyor has served us reliably for many years, at times it has been slow and they added us to a higher performance plan for free, and yes updates have also not been as fast as we would prefer, but right now the stability of AppVeyor without Node.js v12 is preferable than the unreliable and false reporting Azure Pipelines as. a “new” service is offering

**Comment by evilebottnawi** [comment]
> higher performance plan for free

Where? We still not have parallelism so it doesn't have sense, we still wait each build before run previously? 

> yes updates have also not been as fast as we would prefer

Because we don't have alternative for windows.

> right now the stability of AppVeyor without Node.js v12 is preferable than the unreliable and false reporting Azure Pipelines

Wrong, we have right reporting, it is bug in jest because they output invalid ansi code for windows console and will be fixed in next major release.

> Azure Pipelines as. a “new” service is offering IMHO

It is works since 2016/2017, it is not new service.

IMHO AppVeyor is not listen community, all feedback will be ignored, my emails often was unanswered and any bugs in their contains was ignore, this is not too good behavior for developers.

This is not a Microsoft advertisement, they just did it right and it works well.

**Pull request merged**
