### PR TITLE
Switch to GitHub Actions badge and remove Travis CI & AppVeyor badges

### PR DESCRIPTION
**Pull request by ntwb**
See https://help.github.com/en/articles/configuring-a-workflow

### CODE REVIEW

**Comment by hudochenkov** [comment]
The other question is do we really need this badge? What problem does it solve?

**Comment by evilebottnawi** [comment]
Shows that the project is maintained and developed

**Comment by hudochenkov** [comment]
Well, I could commit something and don't change anything for 5 years. And it will still show the last result :)

**Comment by evilebottnawi** [comment]
@hudochenkov yep, just common practice for many repositories (eslint has badges also). Don't think it is real problem

**Comment by hudochenkov** [comment]
I'm just questioning things that we were doing for a long time. If they still valid or we are doing them just because we were doing them before :)

**Comment by vankop** [comment]
Actually build status is pretty important. 

> Well, I could commit something and don't change anything for 5 years. And it will still show the last result :)

In real world you will look on the releases and commits activity as well

**Pull request merged**
