### PR TITLE
Start updating dependencies

### PR DESCRIPTION
**Pull request by davidtheclark**
Anyone feel like helping update Babel? I'm pretty damned annoyed about it. My next step will be to try to find a codemod or something to convert this codebase to ES5, because I've been regularly annoyed by the inconveniences that relying on compilation brings.

Babel 6 is more strict about module syntax, meaning that pre v6 tricked us into using named imports when we shouldn't have been able to ... which means a whole lot of garbage has to be slightly changed. I may have got those changes with regular expressions; but I can't get the tests to run. Anybody want to step in?

### CODE REVIEW

**Comment by davidtheclark** [comment]
I don't know if the problem is with our code or with babel-tape-runner or what, because the stack traces are not very helpful.

**Comment by TrySound** [comment]
I don't know. On my windows everything is okay.

**Comment by TrySound** [comment]
Again windows... @eventualbuddha did you get such problem before? Every dep has babel6
```
ReferenceError: [BABEL] src\buildConfig.js: Unknown option: C:\projects\stylelint\.babelrc.presets
```

**Comment by TrySound** [comment]
By the way, on my windows machines tests are passed

**Comment by davidtheclark** [comment]
Nice catch, @TrySound : I was tired, grumpy, and a little drunk last night and lost my cool :)

**Comment by davidtheclark** [comment]
If you want to go for extra bonus points and try out converting the tests to ava (if it makes any sense) I started a branch there: https://github.com/stylelint/stylelint-rule-tester/tree/ava But I'm hitting annoying errors including the `Unknown option` error you mentioned above, so I'm giving up for now.

**Comment by TrySound** [comment]
Will try today

**Comment by jeddy3** [comment]
> Babel 6 is more strict about module syntax, meaning that pre v6 tricked us into using named imports when we shouldn't have been able to...

Oh no, that sucks.  Any chance you could go into a few more details as I'm having a hard time understanding it? So we can use named imports from the likes of `lodash`, but not from our own code in?

```js
import { assign, merge, omit } from "lodash" // ok
import { configurationError } from "./utils" // not ok?
```

**Comment by davidtheclark** [comment]
If an es2015 module `default` exports an object, the properties on that object cannot be accessed via named imports.

So given ...

```js
// something.js
export default {
  foo: 1,
  bar: 2,
}
```

This won't work:

```js
import { foo } from 'something'
```

This will:

```js
import something from 'something';

const { foo } = something;
```

I'm guessing lodash works because Babel still permits interop -- the fact that it never pretend to be a es2015 module with a default export. But seems they stop permitting that erroneous syntax if the module is actually a compiled es2015.

Does look like maybe I got all the changes required for that, though. We just need those tests passing on Windows, and then double-check that the built version works as expected.

**Comment by jeddy3** [comment]
> Does look like maybe I got all the changes required for that, though. 

Groovy. I saw that. Thanks btw :)

I was just curious about the details behind it as I was having a hard time googling the named imports issue. Thanks for the explanation :)

**Comment by davidtheclark** [comment]
Got it: appveyor settings were causing node_modules to be cached too much. Changed them a little and it seems to be passing.

**Comment by TrySound** [comment]
Nice!

**Comment by TrySound** [comment]
@davidtheclark Why you made such utils exports? I think destructed modules are more readable.

**Comment by TrySound** [comment]
Btw there is better syntax to export from file
```js
export { foo as myFoo, bar } from 'src/other_module';
```

**Comment by davidtheclark** [comment]
> Btw there is better syntax to export from file

That only works with named exports, I believe. Not with default exports.

> I think destructed modules are more readable.

I disagree -- but my opinion is slight :) So if you want to take a crack at mass-changing this stuff so that utils use named exports and rules have named imports instead of the mass-change I had, feel free to take a crack at it.

**Comment by TrySound** [comment]
@davidtheclark `default` is name too, but with benefits
```
export { default } from 'src/other_module';
```

**Comment by davidtheclark** [comment]
Cool: I didn't know that would work!

**Comment by TrySound** [comment]
If we use babel we should use all modules features for simpler code.

**Comment by davidtheclark** [comment]
Sure. At this point I definitely wish we didn't use Babel, but I don't see a reasonable way to backpedal and get the codebase to ES5 without self-destruction. I'd appreciate help refactoring the modules. If you want to give it a shot, it may be easier to start a new branch from v3 to update the deps and refactor, I don't know.

**Comment by TrySound** [comment]
It would be cool to reduce count of testing iterations in CI. Maybe for only PR?

**Comment by davidtheclark** [comment]
> It would be cool to reduce count of testing iterations in CI. Maybe for only PR?

I don't understand the suggestion. Could you clarify?

**Comment by TrySound** [comment]
I mean that and travis and appveyor run tests twice. Is there a sense to run only once?

**Comment by davidtheclark** [comment]
> I mean that and travis and appveyor run tests twice. 

Oh, ok. I don't know why, would have to dig into it a little. If you can reduce it sounds good to me.

**Comment by TrySound** [comment]
I don't have an access to appveyor :)
/cc @MoOx

**Comment by MoOx** [comment]
Maybe you should create your project using appveyor so you don't rely on me ?
Otherwise what do you need from me ?

**Comment by davidtheclark** [comment]
@TrySound are you good to merge this branch now?

**Comment by TrySound** [comment]
@davidtheclark Maybe revert rules too? Caz pr still to big.

**Comment by TrySound** [comment]
I'm a little destroyed your commit :) Can you rebase and squash first five commits? Just like clean history.

**Comment by jeddy3** [comment]
> default is name too, but with benefits

I didn't know that either. That's nice :)

This PR lgtm. So, happy to see it merged.

**Comment by TrySound** [comment]
After @davidtheclark will squash first five commits

**Comment by davidtheclark** [comment]
@TrySound Is that what you were looking for? Or would you rather squash them all? Also ... can't you squash the branch locally, too?

**Comment by TrySound** [comment]
@davidtheclark Yeah, maybe in one. I just wanted to save source author of first commit :)

**Comment by TrySound** [comment]
By the way I divided commits to squash only big diffs :))

**Pull request merged**
