### PR TITLE
Fixed: False positives when triggering property is overriden in declaration-block-no-ignored-properties

### LINKED ISSUE #1790: False positives when triggering property is overriden in declaration-block-no-ignored-properties
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Without `declaration-block-no-duplicate-properties`, `declaration-block-no-ignored-properties`  triggers because I set a `height` and `width` after a duplicate display property.

> Which rule, if any, is this issue related to?

`declaration-block-no-ignored-properties`

> What CSS is needed to reproduce this issue?

```diff
.icon {
  border: 0;
- display: inline;
  fill: currentColor;
+  display: inline-block;
  width: 40px;
  height: 30px;
}
```

Even though that 2nd `display` declaration overrides the first, this stylelint rule still triggers because I set a `height` and `width`. 

> What stylelint configuration is needed to reproduce this issue?

```json
{
"extends": "stylelint-config-standard",
  "rules": {
    "number-leading-zero": "never",
    "custom-property-no-outside-root": true,
    "root-no-standard-properties": true,
    "selector-root-no-composition": true,
    "no-eol-whitespace": true
  }
}
```

> Which version of stylelint are you using?

`7.1.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No.

> What did you expect to happen?

What would be nice would be if stylelint saw the overridden declaration and warned me. 
I know there's this `"declaration-block-no-duplicate-properties": true,`, but I feel like it should be turned on in the `stylelint-config-standard` preset maybe. 

> What actually happened (e.g. what warnings or errors you are getting)?

The following warnings were flagged: 

```shell
 8:3  ✖  Unexpected "width" with "display: inline"    declaration-block-no-ignored-properties
 9:3  ✖  Unexpected "height" with "display: inline"   declaration-block-no-ignored-properties"
```

### PR DESCRIPTION
**Pull request by ideadapt**
Fixes #1790

### CODE REVIEW

**Comment by ntwb** [comment]
Thanks @ideadapt could you fix the ESLint errors please.

If you've previously run `npm install`, then running `npm test` will run all 20,000+ unit tests and also linting of JS with ESLint. Here's the ESLint warnings anyway:

```shell
/home/travis/build/stylelint/stylelint/src/rules/declaration-block-no-ignored-properties/__tests__/index.js
  95:7  error  Expected indentation of 4 space characters but found 6  indent
  97:7  error  Expected indentation of 4 space characters but found 6  indent
/home/travis/build/stylelint/stylelint/src/rules/declaration-block-no-ignored-properties/index.js
  134:27  error  'index' is defined but never used  no-unused-vars
  135:36  error  Trailing spaces not allowed        no-trailing-spaces
  137:1   error  Trailing spaces not allowed        no-trailing-spaces
```

**Comment by ideadapt** [comment]
@ntwb fixed the issues. ready to merge now

**Comment by evilebottnawi** [comment]
@ideadapt squash your commits in one for good history, need second eyes for merge. LGTM to me.

**Comment by jeddy3** [comment]
@ideadapt Thanks for this!

Can you please add a changelog item e.g. "Fixed: `declaration-block-no-ignored-properties` now uses the value of the last occurrence of triggering property."

**Comment by ideadapt** [comment]
@jeddy3 done

**Comment by jeddy3** [comment]
@ideadapt Thanks!

LGTM.

**Comment by ntwb** [comment]
LGTM

**Comment by evilebottnawi** [comment]
@ideadapt squash commits in one for pretty git history, LGTM

**Pull request closed without merging**
