### PR TITLE
Refactor mock custom formatter to rename to CJS

### PR DESCRIPTION
**Pull request by ybiquitous**
> Which issue, if any, is this issue related to?

Ref #5291

> Is there anything in the PR that needs further explanation?

Note that a custom formatter in ESM is unsupported.

### CODE REVIEW

**Comment by Mouvedia** [comment]
> Note that a custom formatter in ESM is unsupported.

https://github.com/stylelint/stylelint/blob/6d040b2d69ef691c8933b4a0e384f55539104523/lib/__tests__/standalone-formatter.test.mjs#L5
I guess it's different for [`formatter`](https://stylelint.io/user-guide/options#formatter).

**Comment by ybiquitous** [comment]
@Mouvedia We're currently using `require()`. But we should support ESM as well.

https://github.com/stylelint/stylelint/blob/958bf369127f867747c613ec9c7025344e220eed/lib/cli.mjs#L396-L400

**Comment by ybiquitous** [comment]
I've just opened an issue (#7267) for an ESM custom formatter.

**Review by Mouvedia — APPROVED** [review]
LGTM

offtopic
https://github.com/stylelint/stylelint/blob/v16/lib/__tests__/fixtures/custom-formatter.mjs
should probably be moved in the formatters directory

**Comment by ybiquitous** [comment]
Thanks for the review.

> offtopic
> [`v16`/lib/__tests__/fixtures/custom-formatter.mjs](https://github.com/stylelint/stylelint/blob/v16/lib/__tests__/fixtures/custom-formatter.mjs)
> should probably be moved in the formatters directory

This file is used only by `resolveCustomFormatter.test.js`:

https://github.com/stylelint/stylelint/blob/ca2109cbdd607fe1ac727b1ae370ab0bd0365c49/lib/__tests__/resolveCustomFormatter.test.mjs#L8

**Pull request merged**
