### PR TITLE
Avoid combining disable comments with a blank line

### LINKED ISSUE #4911: Fix double-slash disable comments followed by another comment
> Clearly describe the bug

When upgrading to 13.7.0, we found that double-slash disable comments:

`// stylelint-disable color-no-hex`

... stopped working (and started throwing errors) in 3 files out of several hundred.  Two of them were first-line, whole-file comments, the third was a disable-next-line for a specific rule.

Converting these comments to the other style fixed the issue:

`/* stylelint-disable color-no-hex */`

> Which rule, if any, is the bug related to?

N/A

> What code is needed to reproduce the bug?

Since this only occurred in a tiny sample of our files, I don't know of a specific repro path.

``

> Which version of stylelint are you using?

13.7.0

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

`CLI via npx stylelint \"{apps,libs}/**/*.scss\"`

### PR DESCRIPTION
**Pull request by jathak**
> Which issue, if any, is this issue related to?

Fixes #4911.

> Is there anything in the PR that needs further explanation?

This checks line numbers before combining adjacent `//` comments.

### CODE REVIEW

**Review by hudochenkov — APPROVED** [review]
Looks good!

Thank you for a quick fix!

**Review by jeddy3 — APPROVED** [review]

**Comment by jeddy3** [comment]
Thanks for the fix!

Changelog entry added:

> - Fixed: double-slash disable comments when followed by another comment ([#4913](https://github.com/stylelint/stylelint/pull/4913)).

**Comment by ThiefMaster** [comment]
Could this be released as 13.7.1? :)

**Comment by XhmikosR** [comment]
It seems we still get failures even with this patch: https://github.com/twbs/bootstrap/runs/1110881505.

I'll try to pinpoint the cause, but going back to 13.6.1 works fine again.

**Comment by stof** [comment]
This PR fixed it for cases where the `stylelint-disable` double-slash comment is on the first line of a group of commented lines, by avoiding merging it with previous lines. But Bootstrap has cases where such comment happens after other comment but without empty lines between them: https://github.com/twbs/bootstrap/blob/5c25ea647bdc463df5a322c8248460a78305a1f4/scss/bootstrap-grid.scss#L24-L27

Adding an empty line between the 2 comments should fix it with 13.7.1.

**Comment by XhmikosR** [comment]
Thanks for the reply. That does seem to be the case. Although, ideally, this should be handled too because it is a regression.

**Comment by stof** [comment]
@XhmikosR I created an new issue for the remaining regression

**Pull request merged**
