### PR TITLE
Do not try to write back ignored files after --fix.

### PR DESCRIPTION
**Pull request by subzey**
> Which issue, if any, is this issue related to?

Fixes issue #2627

> Is there anything in the PR that needs further explanation?

Accessing `opts.syntax` throws if the file is ignored. _I wonder why Flow didn't catch that?_

### CODE REVIEW

**Comment by hudochenkov** [comment]
Thank you for a fix! Would you mind adding test for this issue, please? You can add it to [`fix.test.js`](https://github.com/stylelint/stylelint/blob/master/system-tests/fix/fix.test.js).

**Comment by subzey** [comment]
@hudochenkov Looks like fix.test.js contains tests for lib version of stylelint (`lib/index`), and I need to test the standalone script (`lib/standalone`). I'm not really sure how to do that, in fact I can see no tests that contains `"standalone"` to start off from.

I definitely need help with tests.

**Comment by subzey** [comment]
Added a test. Not sure I did it right, but at least linters are okay, and it's green with the proposed fix code and red with the old one

**Comment by hudochenkov** [comment]
Thank you for thinking outside the box for test :)

I came up with this test:

```js
it("doesn't write to ignored file", () => {
  return stylelint.lint({
    files: [stylesheetPath],
    config: {
      ignoreFiles: stylesheetPath,
      rules: {
        "at-rule-name-case": "lower",
        "comment-empty-line-before": "always",
        "comment-no-empty": true,
      },
    },
    fix: true,
  }).then(() => {
    return pify(fs.readFile)(stylesheetPath, "utf8").then((newFile) => {
      return pify(fs.readFile)(path.join(__dirname, "stylesheet.css"), "utf8").then((oldFile) => {
        expect(newFile).toBe(oldFile)
      })
    })
  })
})
```

I still don't understand promises, so this why it's ugly as hell. If someone could improve code it would be much appreciated :)

**Comment by evilebottnawi** [comment]
@hudochenkov promise is very ugly if your don't use `async/await` :smile:

**Comment by subzey** [comment]
@hudochenkov Actually, I've almost copy-pasted the code chunk from https://github.com/stylelint/stylelint/blob/master/system-tests/004/004.test.js#L11-L14

**Comment by jeddy3** [comment]
@hudochenkov Is this good to go in for `7.12` or did you want to change the test? Is there any advantage to either approach over the other?

**Comment by hudochenkov** [comment]
@jeddy3 it's good to merge, if test looks ok.

> Is there any advantage to either approach over the other?

Test in this PR looks quite complicated. While my version might be improved. I didn't ask to use my test, because not sure if they are better than @subzey's test.

If you accept author's test, then feel free to merge.

**Comment by jeddy3** [comment]
Let's merge and then I'll drop in your test, if only because it's consistent with the other tests in the file.

**Comment by jeddy3** [comment]
Changelog:

> -   Fixed: `--fix` no longer crashes when used with ignored files ([#2652](https://github.com/stylelint/stylelint/pull/2652)).

**Pull request merged**
