### PR TITLE
Remove `syntax` option

### LINKED ISSUE #6414: Remove deprecated `syntax` option
When releasing v14.0.0, we deprecated the `syntax` option to require using the `customSyntax` option instead.

https://github.com/stylelint/stylelint/blob/d40288983161124d7b8a29be219835bf7ea6841d/docs/migration-guide/to-14.md?plain=1#L17

With the next major version, we can remove the deprecated option. See below:

https://github.com/stylelint/stylelint/blob/d40288983161124d7b8a29be219835bf7ea6841d/types/stylelint/index.d.ts#L243-L244

### PR DESCRIPTION
**Pull request by fpetrakov**
> Which issue, if any, is this issue related to?

Closes #6414.

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

### CODE REVIEW

**Comment by fpetrakov** [comment]
Is it everything I should have done?

**Comment by fpetrakov** [comment]
I will need some help as I haven't worked with these parts of the codebase yet.

**Review by ybiquitous — CHANGES_REQUESTED** [review]
@fpetrakov Thanks for working on the issue. This change should be a breaking change, so could you please change the base branch from `main` to [`v15`](https://github.com/stylelint/stylelint/tree/v15) (I've just created it)?

**Comment by ybiquitous** [comment]
@fpetrakov Let's fix all type errors caused by removing `syntax` from the `LinterOptions` type.

Also, we need to remove the code about `syntax` from `cli.js`. For example:

https://github.com/stylelint/stylelint/blob/e3585ed7d78d45145d9d83abba4066cd4201d8b5/lib/cli.js#L332-L335

It also looks like the following code could be removed (there may be more):

https://github.com/stylelint/stylelint/blob/e3585ed7d78d45145d9d83abba4066cd4201d8b5/types/stylelint/index.d.ts#L211

**Comment by fpetrakov** [comment]
@ybiquitous Thanks for the detailed explanation. I will work on this issue ASAP 🚀

**Comment by fpetrakov** [comment]
https://github.com/stylelint/stylelint/blob/e3585ed7d78d45145d9d83abba4066cd4201d8b5/lib/__tests__/standalone-syntax.test.js#L153-L183

Should I remove these 2 tests?

**Comment by fpetrakov** [comment]
I've also found these:

https://github.com/stylelint/stylelint/blob/e3585ed7d78d45145d9d83abba4066cd4201d8b5/lib/cli.js#L47

https://github.com/stylelint/stylelint/blob/e3585ed7d78d45145d9d83abba4066cd4201d8b5/lib/cli.js#L83

https://github.com/stylelint/stylelint/blob/e3585ed7d78d45145d9d83abba4066cd4201d8b5/lib/cli.js#L332-L335

https://github.com/stylelint/stylelint/blob/e3585ed7d78d45145d9d83abba4066cd4201d8b5/lib/cli.js#L374-L376

**Review by ybiquitous — COMMENTED** [review]
Thanks, all the changes look good! Is it possible to remove also `syntax` occurrences in the type definition?

https://github.com/stylelint/stylelint/blob/e3585ed7d78d45145d9d83abba4066cd4201d8b5/types/stylelint/index.d.ts#L211

https://github.com/stylelint/stylelint/blob/e3585ed7d78d45145d9d83abba4066cd4201d8b5/types/stylelint/index.d.ts#L536

**Comment by ybiquitous** [comment]
Could you add a changelog entry with the following content via `npx changeset add` (`major`)?

```
Removed: `syntax` option
```

**Review by ybiquitous — APPROVED** [review]
Thank you! LGTM 👍🏼

**Review by jeddy3 — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
