### PR TITLE
Synthesize option utils

### LINKED ISSUE #1715: Synthesize optionsHaveIgnored utils
I don't think we should be mass producing `optionHaveIgnored*` util functions the way we are. They are much too simple to justify the additional code and tests. Instead, how about a single function, `optionsHave`, that just does this: `optionsHave('ignore', 'walrus')`, `optionsHave('except', 'kendo')`, `optionsHave('ignoreProperties', 'color')`?

### PR DESCRIPTION
**Pull request by m-allanson**
Based on PR #1727, this incorporates the feedback from the discussion there. The `options*` utils are replaced with a single `optionsMatches` util.

I suspect `optionsMatches` could be sped up by inlining the basic string checking (`options[propertyName].indexOf(input) !== -1`) instead of handing it to `matchesStringOrRegExp`, but I haven't done any benchmarking around that.

Closes #1715

### CODE REVIEW

**Comment by ntwb** [comment]
More code removed than added 👍

**Comment by davidtheclark** [comment]
This looks *fantastic* to me. Thanks @m-allanson! My only feedback is that we should have some unit tests for the new function — and make sure to delete any existing unit tests for the function's you're deleting.

**Comment by jeddy3** [comment]
> This looks fantastic to me. 

Agreed. I didn't realise it'd involve writing a codemod! Thanks so much for doing this.

> My only feedback is that we should have some unit tests for the new function

Yep, that would be great.

**Comment by m-allanson** [comment]
Great! 

There were no tests for the removed utils, I've added some for the new `optionsMatches` util. Once everything looks good I can squash the commits. I'm assuming there doesn't need to be a changelog entry.

> I didn't realise it'd involve writing a codemod

Neither did I :) As it happens, it seems to be a really nice way of refactoring, especially when  combined with a project that has such comprehensive test coverage.

**Comment by davidtheclark** [comment]
Great work.

**Pull request merged**
