### PR TITLE
Refactor to replace chalk with nanocolors

### PR DESCRIPTION
**Pull request by ai**
The copy of https://github.com/stylelint/stylelint/pull/5559 but on top for `v14` branch

### CODE REVIEW

**Comment by hudochenkov** [comment]
For some reason CI didn't kicked in. Had to close and open PR.

**Review by hudochenkov — APPROVED** [review]
Looks good to me! Thanks, @ai!

**Review by ybiquitous — COMMENTED** [review]
@ai Thank you for creating this change! I like the package! 😄 

But, `--color`/`--no-color` flags don't seem to work. 🤔 

https://github.com/stylelint/stylelint/blob/7cac274fb42d923e759ce1af4149dbdd6d527515/lib/cli.js#L186-L187

Can you look into the problem?

**Comment by hudochenkov** [comment]
@ybiquitous I don't understand how it suppose to work, can't find any code, except `meow` configuration. Also seems like we don't have any tests. Is it even working `v14` at all with `chalk`?

**Comment by ybiquitous** [comment]
@hudochenkov When I look into this, it seems `chalk.supportsColor` and the `supports-color` package and handles the --color/--no-color flags. See below:

- https://github.com/chalk/chalk/blob/v4.1.2/readme.md#chalksupportscolor
- https://github.com/chalk/supports-color/blob/v7.2.0/index.js#L9-L19

**Comment by ai** [comment]
I will add CLI args support to be fully compatible with `chalk`.

**Comment by ai** [comment]
I can add CLI args support to be fully compatible with `chalk`.

Let'se research this problem.

**Comment by ai** [comment]
Done. I released Nano Colors 0.2 with `--color`/`--no-color` support and updated PR.

**Comment by alexander-akait** [comment]
@ai just idea - maybe in future better to start with `1.0.0` version? Why? Because now we use `^0.2.0`, when you release `^0.3.0` with new features we will need to update `nanocolors` in our package.json manually, it brings a slight inconvenience to maintenance

**Review by ybiquitous — APPROVED** [review]
@ai Thank you for the quick release! 🎉

**Review by jeddy3 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
