### PR TITLE
Fix `rule-selector-property-disallowed-list` secondary options

### LINKED ISSUE #6688: Fix `rule-selector-property-disallowed-list` secondary options
### What steps are needed to reproduce the bug?

Try to add a message parameter to `rule-selector-property-disallowed-list`.

See REPL: https://stylelint.io/demo#N4Igxg9gJgpiBcICGACYLIBsICd4pxigG4UBfAHQDtqQAaEAZwE8qAXJADwXEcfvAQqAMwCWAcx7BqKFBRA4ArphiN5+aVVmz5SlQFpGMFWDa59ABxwQLMHG2b6ooxkkzYA7kX2YXbdSgA2jLaspqhofJIAcGC2DjydHIgAPQAtkg44qJUKfIAunQhEckpwhAQeQiljKIAXjBVxdpkRVol4SXJaaqu4jAB8gByEGwobp5E8s2ylO2y+SFzZCBkQA

Removing the array (and the message) with an object works:

https://stylelint.io/demo#N4Igxg9gJgpiBcICGACYLIBsICd4pxigG4UBfAHQDtqQAaEAZwE8qAXJADwXEcfvAQqAMwCWAcx7BqKFBRA4ArphiN5+aVVmz5SlQFpGMFWDa59ABxwQLMHG2b6ooxkkzYA7kX2YXbdXJa2rKawcHySAEA2vJYuPJ0ciAA9AC2SDjiolTJ8gC6dDJhOinCEBC5CEnJjKIAXjCVRcGUQa1kIGRAA

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "rule-selector-property-disallowed-list": [
      {
        "a": ["color", "/margin/"],
        "/foo/": "/size/"
      },
       {
        "message": "Not allowed"
      }
    ]
  }
}
```

### How did you run Stylelint?

npx stylelint test.css

### Which version of Stylelint are you using?

15.2.0

### What did you expect to happen?

Should support messages

### What actually happened?

Rule is ignored

### Does the bug relate to non-standard syntax?

_No response_

### Proposal to fix the bug

Check code with `declaration-property-value-disallowed-list` which does work.

### PR DESCRIPTION
**Pull request by mattxwang**
> Which issue, if any, is this issue related to?

Closes #6688.

> Is there anything in the PR that needs further explanation?

I'm a bit confused why this wasn't caught by the test suite when the rule was first made/messages were added; presumably, I should write a regression test here. Any suggestions?

### CODE REVIEW

**Comment by mattxwang** [comment]
Thanks for the quick response, and sorry for the delay! I confirmed that the test case you suggested catches the bug, and that removing that one line resolves it. Have also updated the doc arrow to point at `color`!

**Comment by ybiquitous** [comment]
(off-topic) Hi @mattxwang,

Since @jeddy3 will be offline for a while (maybe a few months), could you please help me with the repository maintenance when you have time?

**Comment by mattxwang** [comment]
> could you please help me with the repository maintenance when you have time?

Of course! Didn't realize that @jeddy3 is offline. I can certainly review more PRs and help out with dependencies, etc.

**Comment by ybiquitous** [comment]
Thank you! 😊

**Pull request merged**
