### PR TITLE
docs: Update information about JetBrains IDEs.

### PR DESCRIPTION
**Pull request by vladsholokhov**
> Which issue, if any, is this issue related to?

Documentation fix.

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

### CODE REVIEW

**Review by ybiquitous — APPROVED** [review]
@vladsholokhov Thank you! LGTM 👍🏼

**Review by mattxwang — APPROVED** [review]
LGTM, thanks @vladsholokhov!

**Comment by mattxwang** [comment]
Huh - I'm not sure if there's a problem with GitHub Actions, but I'm seeing quite a few failures (not being able to get the LTS node version, not loading the host OS properly, etc.) which has caused `main` to fail. @ybiquitous @jeddy3 any insight here?

**Comment by ybiquitous** [comment]
@mattxwang Maybe it is a problem of `actions/setup-node`. But I'm not sure about the details... 🤷🏼 

https://github.com/stylelint/stylelint/blob/44145f117809f9f3dfd94d33e9438706c456a49d/.github/workflows/linting.yml#L24-L27

https://github.com/actions/setup-node/blob/04c56d2f954f1e4c69436aa54cfef261a018f458/src/installer.ts#L227-L231

**Comment by mattxwang** [comment]
@ybiquitous hm, I've re-ran the failed jobs on some other open PRs and they seem to resolve - it seems like GitHub actions/ `actions/setup-node` is flaky? I'll poke around, but in the meantime maybe something to keep in mind.

**Pull request merged**
