### PR TITLE
Remove Node.js 14 support

### LINKED ISSUE #6740: Remove Node.js 14 support
### What is the problem you're trying to solve?

Node.js 14 will [reach EOL on Apr 30, 2023](https://nodejs.dev/en/about/releases/) (in about a month).

The currently supported versions are the following:

https://github.com/stylelint/stylelint/blob/13efb8655c2fc8163596ace2b67635e9bea8e6b9/package.json#L203-L205

### What solution would you like to see?

We will remove the Node.js 14 support with the next major version.

The supported versions will be:

```json
{
  "engines": {
    "node": "^16.0.0 || >=18.0.0"
  }
}
```

### PR DESCRIPTION
**Pull request by ybiquitous**
> Which issue, if any, is this issue related to?

Closes #6740
Closes #6785
(Unfortunately, the PR's author doesn't respond)

> Is there anything in the PR that needs further explanation?

Node.js **16.13.0** is the first version of Node.js 16.x LTS series.
See https://nodejs.org/en/blog/release/v16.13.0

---

Here's a [`ls-engines`](https://www.npmjs.com/package/ls-engines) report:

```console
$ npx ls-engines@latest
`node_modules` found; loading tree from disk...
┌────────┬─────────────────────────────────────────────────────────────────┐
│ engine │ Currently available latest release of each valid major version: │
├────────┼─────────────────────────────────────────────────────────────────┤
│ node   │ v20.3.1, v19.9.0, v18.16.1, v17.9.1, v16.20.1                   │
└────────┴─────────────────────────────────────────────────────────────────┘

┌───────────────────────────────────┬───────────────────────────┐
│ package engines:                  │ dependency graph engines: │
├───────────────────────────────────┼───────────────────────────┤
│ "engines": {                      │ "engines": {              │
│   "node": "^16.13.0 || >= 18.0.0" │   "node": ">= 16.13"      │
│ }                                 │ }                         │
└───────────────────────────────────┴───────────────────────────┘


Your “engines” field allows fewer node versions than your dependency graph does.

If you want to widen your support, you can run `ls-engines --save`, or manually add the following to your `package.json`:
"engines": {
  "node": ">= 16.13"
}

┌────────┬─────────────────┬─────────────────┬──────────────────────────┐
│ engine │ current version │ valid (package) │ valid (dependency graph) │
├────────┼─────────────────┼─────────────────┼──────────────────────────┤
│ node   │ v20.3.0         │ yes!            │ yes!                     │
└────────┴─────────────────┴─────────────────┴──────────────────────────┘
```

### CODE REVIEW

**Review by mattxwang — APPROVED** [review]
LGTM!

**Comment by Mouvedia** [comment]
In the same way as
https://github.com/stylelint/stylelint/blob/21dfacb899e4b170e1c45ea09e97bb803c58b8b8/docs/migration-guide/to-15.md?plain=1#L186
we need a breaking change(s) section for [to-16](https://github.com/stylelint/stylelint/blob/v16/docs/migration-guide/to-16.md).

**Comment by ybiquitous** [comment]
@Mouvedia Good catch! Updated via f194ae7f.

**Review by jeddy3 — APPROVED** [review]
LGTM, thank you.

**Pull request merged**
