### PR TITLE
Add autofix to declaration-block-no-redundant-longhand-properties

### PR DESCRIPTION
**Pull request by imvetri**
WIP. 
As discussed [here](https://github.com/stylelint/stylelint/issues/3304) I have a initial version of autofix written. Before writing more, I would like to get feedback on the approach.

**Overview of the approach:**
On rule violation, it creates a shorthand value using references/shorthandFormats/resolveValue. For now I have created for padding.

### CODE REVIEW

**Comment by jeddy3** [comment]
I think adding tests for `padding` using the `fixed:` property of the schema (like [so](https://github.com/stylelint/stylelint/blob/master/lib/rules/rule-empty-line-before/__tests__/index.js#L46)) would be a good way of validating your approach so far.

**Comment by imvetri** [comment]
@jeddy3 Thanks for the pointer. Greatly helped.

**Comment by ntwb** [comment]
@imvetri Any chance you could update this PR please? We'd love to get this shipped :shipit:

**Comment by imvetri** [comment]
@ntwb Thanks for following up. I will have some updates in < 2 weeks.

**Comment by imvetri** [comment]
@ntwb  I m still working on this, I don't think so I will be able to complete by this weekend.

**Comment by ntwb** [comment]
Cool, thanks for the update @imvetri, let us know if we can help in any way :)

**Comment by imvetri** [comment]
@ntwb I continued working on this by adding unit test with context.fix as true ( refer to the [line](https://github.com/stylelint/stylelint/pull/3326/files#diff-28ddeca0d3df92ea11f69bc5a08b7570R9) ). While running the test what I found is that context.fix is not always as true. Sometimes it is true and sometimes it is undefined. Do you think you can guess what could be wrong? .

I have also pushed with vscode configuration in the latest commit to make debugging easier.

**Comment by hudochenkov** [comment]
Closing due inactivity. We can reopen if requested changes were made.

**Pull request closed without merging**
