### PR TITLE
Bump css-functions-list from 3.2.0 to 3.2.1

### LINKED ISSUE #7226: `function-no-unknown`: fix `linear` `xywh` `light-dark` false positives
### What minimal example or steps are needed to reproduce the bug?

```css
:root {
  color-scheme: light dark;

  --text-color: light-dark(#777, #000);
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "function-no-unknown": true
  }
}
```

### How did you run Stylelint?

https://stylelint.io/demo

### See also

https://drafts.csswg.org/css-color-5/#light-dark
https://github.com/mdn/browser-compat-data/pull/20935

### Do you have a proposal to fix the bug?

1. <del>either update https://github.com/niksy/css-functions-list/blob/master/index.json</del>
2. or add an exception

### PR DESCRIPTION
**Pull request by mattxwang**
> Which issue, if any, is this issue related to?

Closes #7236 and closes #7226 (and related to #7231).

> Is there anything in the PR that needs further explanation?

I intentionally broke this up into two commits so that you can see the failed test cases (false positives), and then showing how the version bump fixes them. 

Let me know if this PR's title should instead be the changeset entry!

### CODE REVIEW

**Comment by ybiquitous** [comment]
> Closes #7237

#7236 is correct instead, right?

**Review by ybiquitous — COMMENTED** [review]
[suggest] `-webkit-gradient` seems no longer needed:

https://github.com/stylelint/stylelint/blob/47f92a692a3cc7d3798e33c81f6f337e1f339a52/lib/rules/function-no-unknown/index.js#L54

**Comment by mattxwang** [comment]
Thanks for the quick turnaround! Slowly catching up to all of my Stylelint obligations 😓

**Review by ybiquitous — APPROVED** [review]
Thanks. LGTM 👍🏼

**Review by Mouvedia — APPROVED** [review]

**Pull request merged**
