### PR TITLE
fix(package): update table to version 4.0.1

### PR DESCRIPTION
**Pull request by ntwb**
Superseeds #2101

### CODE REVIEW

**Comment by ntwb** [comment]
I'm not sure what is going on with Table v4.x.x to be honest, there is no changelog and all 4.x.x [Table Travis CI build jobs have failed](https://travis-ci.org/gajus/table/builds).

Here's a compare of the last 3.x.x to 4.x.x branch: https://github.com/gajus/table/compare/v3.8.3...v4.0.1

Will need to look into that some more for further investigation

(If no one beats me to it I'll have more time tomorrow to investigate)

**Comment by evilebottnawi** [comment]
@ntwb maybe cache?

**Comment by ntwb** [comment]
@evilebottnawi I don't think so, cache maintenance for Travis CI was added back in https://github.com/stylelint/stylelint/commit/ebfec8a488f6f03e1383389e223bc8ef9a7af117 and not touched in AppVeyor. Also this PR is a fresh PR I created for Table v4.0.1, #2101 was for v4.0.0 and #2103 didn't have any issues.

**Comment by davidtheclark** [comment]
We need to expel Table from our dependencies. I don't like having a dependency that does not include a changelog. Let's find another library.

**Comment by evilebottnawi** [comment]
`eslint` use https://github.com/substack/text-table in `stylish` formatter, but it is seem old library and many tests failed

**Comment by evilebottnawi** [comment]
I am create issue let's wait what says contributors

**Comment by gajus** [comment]
> I create issue, let's wait what says contributors

The only breaking change is how you import table.

See https://github.com/gajus/table/issues/25#issuecomment-262209270

In your code base, you simply need to replace:

```js
import table from 'table';
// or
// const table = require('table').default;
```

with 

```js
import {table} from 'table';
// or
// const {table} = require('table');
```

**Comment by gajus** [comment]
Sorry about the lack of changelog. I don't like the https://github.com/semantic-release/semantic-release tool (because it uses github's releases instead of a static changelog file) and there isn't a feasible alternative at the moment.

Please suggest how to add automated changelog to the CI https://github.com/gajus/table/issues/27

**Comment by davidtheclark** [comment]
@gajus If you don't have an automated changelog you need to have a manual one. That's what we do.

**Comment by gajus** [comment]
> @gajus If you don't have an automated changelog you need to have a manual one. That's what we do.

You, personally, don't appear to maintain 50+ open-source projects. Therefore, we have different problems to solve.

In most of the projects I use semantic-release. However, I have learned that migrating to other repositories (e.g. gitlab) renders the release log useless.

On other projects I have started to use a custom script (https://github.com/gajus/gitinfo/blob/master/.scripts/release.sh), which is working great, but it is in experimental state. I am planning to abstract a variation of it and release it as a tool. As soon as thats out of the door, I will enforce it on table as well as all other packages.

**Comment by gajus** [comment]
> You, personally, don't appear to maintain 50+ open-source projects. Therefore, we have different problems to solve.

Dammit. Said this without looking at the profile. Well, kudos for not being sloppy. :-)

I will do my best to remedy table ASAP.

**Comment by ntwb** [comment]
I restarted the failing Travis CI job and all jobs now pass, thanks @evilebottnawi for the commit 👍

**Comment by davidtheclark** [comment]
@gajus I understand budgeting your energy! Consider mine a vote for changelog a even at the expense of something else. I personally consider it a priority in dependencies that are not super simple. It can save me (the user) a lot of headaches and uncertainty. Anyway, thanks for your work on these OSS projects!

**Pull request merged**
