### PR TITLE
Update babel-tape-runner to v2.0.0

### PR DESCRIPTION
**Pull request by ntwb**
Changelog: 
• https://github.com/wavded/babel-tape-runner/blob/master/changelog.md
• https://github.com/wavded/babel-tape-runner/compare/1.3.0...2.0.0

### CODE REVIEW

**Comment by ntwb** [comment]
It wasn't until after I hit go I realized I created the branch directly here rather than my fork, my bad, sorry.

**Comment by TrySound** [comment]
@ntwb Why is it bad?

**Comment by ntwb** [comment]
I suppose its not really, previously I couldn't, but with new permissions I now can :smile:

**Comment by davidtheclark** [comment]
Test still pass -- seems good.

**Pull request merged**
