### PR TITLE
Add autofix support to number-leading-zero

### PR DESCRIPTION
**Pull request by modosc**
> Which issue, if any, is this issue related to?

#2829 

> Is there anything in the PR that needs further explanation?

"No, it's self explanatory."

### CODE REVIEW

**Comment by modosc** [comment]
ugh, just saw #2917.

**Comment by modosc** [comment]
i think this should be good now?

**Comment by jeddy3** [comment]
> i think this should be good now?

Thanks, looking good.

@gucong3000 Does this address your concerns in https://github.com/stylelint/stylelint/pull/2917?

**Comment by gucong3000** [comment]
> Does this address your concerns in #2917?

Yes.
And this PR looking good.

**Comment by modosc** [comment]
> It doesn't seem to support multiple values. Like this:

fixed. i need to check the trailing zero code as well since i'm expecting it to fail in the same way.

**Comment by modosc** [comment]
> fixed. i need to check the trailing zero code as well since i'm expecting it to fail in the same way.

actually the `no-trailing-zeros` code did this right and is slightly cleaner - i copied that approach here. i also added tests for this case to `no-trailing-zeros` for completeness.

**Comment by jeddy3** [comment]
> -   Added: `number-leading-zero` autofix ([#2921](https://github.com/stylelint/stylelint/issues/2921)).

**Pull request merged**
