### PR TITLE
Add a notice about overtesting non-standard syntaxes

### PR DESCRIPTION
**Pull request by ybiquitous**
> Which issue, if any, is this issue related to?

See the discussion on PR #6556.

> Is there anything in the PR that needs further explanation?

This PR is just a document fix.

My English wording may be a little unnatural. Any advice is welcome.

### CODE REVIEW

**Review by hudochenkov — APPROVED** [review]

**Comment by jeddy3** [comment]
Let's hold off merging this until https://github.com/stylelint/stylelint/pull/6573 lands as it'll be easier to manage the conflict here than there.

**Comment by ybiquitous** [comment]
@ollie-iterators Thanks for the advice. I've changed it via 26a546e36.

@jeddy3 Thanks for writing the docs. If you don't mind, could you merge this PR change into PR #6573 and close this PR? (I'm not stuck on the current wording so that you could arrange it)

**Comment by jeddy3** [comment]
> If you don't mind, could you merge this PR change into PR https://github.com/stylelint/stylelint/pull/6573 and close this PR? (I'm not stuck on the current wording so that you could arrange it)

Sure thing. Done in https://github.com/stylelint/stylelint/pull/6573/commits/d7ef445436894462ddcf575e0c535ff71ff362b4

**Comment by ybiquitous** [comment]
Thank you!

**Pull request closed without merging**
