### PR TITLE
errorByDefault config option changes severity pattern

### PR DESCRIPTION
**Pull request by davidtheclark**
Addresses #382.

What I chose to do is make the new config pattern available behind a flag and keep the old pattern default. So now there's an `errorByDefault` option. 

We could follow one release strategy I myself have appreciated in the past: Release this new feature and put a deprecation notice on the feature it replaces (numbered severities); then in the next major version switch `errorByDefault` to be the standard pattern.

So here's a summary of how severities should work with `errorByDefault: true` in a config:

Any rule in the config has an "error" severity level unless:
- it has a secondary option `"warn": true`, or
- it's primary option is false.

So this ...

```js
"at-rule-no-vendor-prefix": 2,
"block-closing-brace-newline-after": [ 2, "always" ],
"block-closing-brace-newline-before": [ 2, "always-multi-line" ],
"block-closing-brace-space-before": [ 1, "always-single-line" ],
"block-no-empty": 1,
```

would become this ...

```js
"at-rule-no-vendor-prefix": true,
"block-closing-brace-newline-after": "always",
"block-closing-brace-newline-before": "always-multi-line",
"block-closing-brace-space-before": [ "always-single-line", { "warn": true } ],
"block-no-empty": [ true, { "warn": true } ],
```

### CODE REVIEW

**Comment by jeddy3** [comment]
Back from hols :) Great to see you've tackled this one!

> We could follow one release strategy I myself have appreciated in the past: Release this new feature and put a deprecation notice on the feature it replaces (numbered severities); then in the next major version switch errorByDefault to be the standard pattern.

Sounds good to me. Do we need to add the deprecation warning to this PR, along with the companion `explicitSeverities` option? So that a user can add `explicitSeverities: true` to their config to remove the deprecation warning, when using `3.0.0`, and also set themselves up for version `4.0.0` should they wish to continue using that style of config?

> So here's a summary of how severities should work with errorByDefault: true in a config:

Looks great to me. The terser config style is much nicer if you want to always error!

**Comment by davidtheclark** [comment]
Are we planning to retain the ability to use numbered severities? I was thinking that the deprecation notice would mean you can use numbered severities during 3.0, but at 4.0 they will be gone. 

What do you think of that? Personally, I would prefer it because I think it would be awkward to have two different config syntaxes when we only need to provide the one we think is best.

**Comment by jeddy3** [comment]
> Are we planning to retain the ability to use numbered severities?

Oh, I thought we concluded in #382 that there were good advantages raised for both approaches and that we'd be offering both going forward (with the old syntax always available behind a flag), but having re-read my post I now realise I didn't make this very clear.

> Personally, I would prefer [one approach] because I think it would be awkward to have two different config syntaxes when we only need to provide the one we think is best.

I agree that it could be awkward, but is it too awkward to warrant not offering the flexibility to the users? From a user experience (and documentation) perspective I think we can mitigate the awkwardness, what do you think? From a code perspective though, I totally trust your judgement and if you think it'll be too awkward (e.g. what happens if a user tries to extend one type of config with the other?) then lets roll with migrating to just a _error by default_ approach by the time we get to `4.0.0`.

**Comment by davidtheclark** [comment]
I am in favor of picking a config style that we think is best and going with it. It will be awkward in the code, the documentation, and the usage if we have multiple distinct configuration syntaxes. My vote is to go with the error-by-default pattern in this PR, deprecating the numbered-severities pattern and removing it in 4. I don't think that switching to the new syntax is hard enough for any users that we should bend over backwards to accommodate.

**Comment by jeddy3** [comment]
> I am in favor of picking a config style that we think is best and going with it.

Ok, lets do that :)

Shall we handle the documentation changes (config structure explanation and examples throughout) in this PR?

**Comment by davidtheclark** [comment]
> Ok, lets do that :)

Cool. I will modify the PR so there is a deprecation warning or something.

> Shall we handle the documentation changes (config structure explanation and examples throughout) in this PR?

Yep, I think so.

**Comment by jeddy3** [comment]
@davidtheclark I've change the documentation to reflect the new config style. Fortunately we consolidated all of the config examples in to the `configuration.md` for `2.0.0`, so it was an easy task.

It did highlight two things that I think it worth going over, just to make sure we're 100% positive this is the best approach:

1. Does using `false` to turn off rules that have options add an ambiguity to the config that wasn't there before e.g.

```json
"number-leading-zero": false
```

This is says "turn this rule off", but could it be also be construed as "no leading zeros"? 

2. By using `false` to turn rules off we are eliminating the option of using booleans for primary options in the future. We've so far always endeavoured to use keywords like "always" and "never" for primary options, so perhaps this isn't an issue. Worth keeping in mind that this a side-effect of this approach though.

What do you think? Worth reconsidering, or shall we merge into `3.0.0` and start prepping for a release?

**Comment by davidtheclark** [comment]
@jeddy3 I've been working hard on a talk that I just gave yesterday, so I plan to dig into all these issues starting this morning.

I think that's an ambiguity worth thinking about -- glad you caught it. Hmm...

`false` to turn off does have that problem. First, though, I'd point out that it's not more ambiguous than the 0-1-2 system, which makes no sense at all unless you've read documentation. This also might be briefly confusing until you've read the documentation.

> By using false to turn rules off we are eliminating the option of using booleans for primary options in the future.

I can't think of any situation in which it wouldn't be preferable for a rule to have the "always"/"never" dichotomy that we're always using rather than a true/false one. So I'm not particularly worried about that issue.

Considering those points, though, I wonder if we can come up with a better indicator for turning off plugins, one with no ambiguity at all?

- Null? `"number-leading-zero": null`
- Empty string? `"number-leading-zero": ""`
- A reserved keyword "off"? `"number-leading-zero": "off"`
- An additional config property (peer to `rules) that is `disabled`: an array of rules from some extended config that you want to turn off? `"disabled": ["number-leading-zero"]`

Any preferences for any of those? Or other ideas?

**Comment by jeddy3** [comment]
> I've been working hard on a talk that I just gave yesterday...

Oh! I hope it went well :) Will it be online somewhere as it'd be great to see it?

> First, though, I'd point out that it's not more ambiguous than the 0-1-2 system, which makes no sense at all unless you've read documentation.

I agree with that.

> Null? "number-leading-zero": null

I think that's as unambiguous at it gets - works equally well for `no` rules and those with primary options too. Shall we go with that?

**Comment by davidtheclark** [comment]
Sure: `null` sounds great.

I think the talk did go well. I have the slides up here: http://slides.com/davidclark/exploring-postcss The video recording is coming soon, not available yet, though.

**Comment by davidtheclark** [comment]
Here's the deprecation notice I'm putting in (s output by the string formatter). Any feedback?

```

>> Deprecation Warning: Numbered severities (0, 1, 2) have been deprecated, and in 4.0 they will be disabled. The new severity syntax can be turn on by setting `errorByDefault: true` in your config.  See: http://stylelint.io/?/docs/user-guide/configuration.md

src/__tests__/fixtures/empty-block.css
5:6	Unexpected empty block (block-no-empty)
```

**Comment by jeddy3** [comment]
Wording sounds spot on to me :)

**Comment by jeddy3** [comment]
P.S. Nice slides btw :)

**Comment by davidtheclark** [comment]
Ok, I think everything is in place now. I added a deprecation warning system so we can do similar things in the future and have them logged extra-special when user is using the Node.js API or CLI (when running as a PostCSS plugin, it's just another warning). I documented this in the formatter docs. I changed `false` to `null` for turning off rules; and I fixed tests. Please give everything a shot and if it seems to work right in your mind, we can merge, I'd say.

**Comment by jeddy3** [comment]
> Ok, I think everything is in place now.

Looking good :)

> I added a deprecation warning system

Nice!

Any chance we can display only one deprecation message pre run, as at the moment it's per file and quite loud?

> Please give everything a shot and if it seems to work right in your mind,

I've updated my local copy of `config-suitcss` to the new style and run that successfully :)

However, I wasn't able to get `extends` to work... either by setting a new option e.g. `indentation: "tab"` or by turning the `indentation` rule off with `indentation: null`.  e.g.

```json
{
  errorByDefault: true,
  "extends": "stylelint-config-suitcss",
  "rules": {
    "indentation": null
  }
}
```

Still produces indentation warnings.

Any ideas?

**Comment by davidtheclark** [comment]
> Any chance we can display only one deprecation message pre run, as at the moment it's per file and quite loud?

Probably no big deal, just hadn't thought of that. Good idea.

> However, I wasn't able to get extends to work

This is a tragedy. I will look into it if I have time today, after cleaning the bathroom :\

**Comment by davidtheclark** [comment]
@jeddy3 : Are you sure there's nothing going wrong in your local setup? We have tests passing for extends currently, and I am not having a problem myself using the CLI extends and our configs in fixtures that extend each other.

**Comment by davidtheclark** [comment]
There might be some problem with using extends where the old and new syntaxes are combined .... maybe we should just switch to the new syntax?

**Comment by davidtheclark** [comment]
@jeddy3 : Please try again. I think I figured out a way to handle the two syntaxes at the same time, which should fix the problem with extends that you noticed. If it works in your tests, I'll modify the warnings and documentation accordingly.

**Comment by davidtheclark** [comment]
This latest commit also tries out a method for not requiring users of the new syntax to set the `errorByDefault` option.

It requires an assumption, though. Without that settings we do still have to figure out some way of determining which syntax the config uses. I was thinking that maybe we could safely assume that if all the rules in the config start with a number, the config is using numbered severities ...

```js
const configHasNumberedSeverities = values(config.rules).every(ruleSettings => {
  return typeof [].concat(ruleSettings)[0] === "number"
})
```

The only place I could see this assumption fail would be if a user was using the new syntax (not numbered severities) but only had rules whose primary option is an integer. We have so few rules that take integers that I thought this might be safe ... but it's true that it's a hack. 

Unless someone has an idea for a more foolproof method of figuring out which syntax is in play, we either need to make this assumption or require users of the new syntax to add `errorByDefault: true` — and then remove it in v4 :\

**Comment by jeddy3** [comment]
Morning. Thanks for tacking this last night!

> Are you sure there's nothing going wrong in your local setup?

Nope, I'm not now as things still aren't working at my end, so, if the tests are passing, we should probably chalk it down to something in my local setup? The simple setup of:

```js
var stylelint = require('stylelint')
stylelint.lint({ files: "css/*.css" })
  .then(function(data) { console.log(data.output) })
  .catch(function(err) { console.error(err.stack) })
```

with a `.stylelintrc` of:

```json
{
  "rules": {
    "indentation": "tab"
  }
}
```

Throws this error:

```bash
jeddy3$ node standard-js-api.js
Error: EISDIR: illegal operation on a directory, read
    at Error (native)
```

In the meantime, I'll try to spring-clean a few things with my local setup.

> This latest commit also tries out a method for not requiring users of the new syntax to set the errorByDefault option.

This is so much better. I was just going to mention how odd it felt to add a flag to the suitcss config that would become redundant in `4.0`.

> We have so few rules that take integers that I thought this might be safe ...

Sgtm.

Shall we reduce the warning down to:

```bash
Deprecation Warning: Numbered severities (0, 1, 2) have been deprecated, and in 4.0 they will be disabled. See: http://stylelint.io/?/docs/user-guide/configuration.md
```

As the preference is to encourage users to user the new syntax without the flag right?

**Comment by davidtheclark** [comment]
Great. If that assumption to detect numbered severities seems fine not you, then I think this branch is ok to merge. Meanwhile, if the bugs persist on your end we'll find and fix them.

**Pull request merged**
