### PR TITLE
First draft of processors

### PR DESCRIPTION
**Pull request by davidtheclark**
This PR introduces a draft a of a `processors` interface that would enable things like extraction from HTML (or JavaScript, or whatever) to happen in external modules.

I removed the current extract-from-html functionality from stylelint itself and, for now, moved it into tests. From there, it would be trivial to move it into an external module.

(Much of the diff in `standalone.js` is just indentation, because I had to load the config within standalone itself, and that meant wrapping most of the lines in a `Promise.then()`.)

Please have a look and if you're able help by trying it out. Let me know if the documentation could be improved, too.

Question about the extract-from-html functionality: Do we want to create a stylelint repo for that? Or just state that we hope somebody picks it up, copying the code that's already there?

### CODE REVIEW

**Comment by jeddy3** [comment]
Wow, looking great!

I'll try to test locally in the morning.

> Question about the extract-from-html functionality: Do we want to create a stylelint repo for that? Or just state that we hope somebody picks it up, copying the code that's already there?

The latter I think.

**Comment by ntwb** [comment]
NIce, also agree on the latter, a repo can be created if needed in the future or decisions change

**Comment by jeddy3** [comment]
This is excellent. I was able to do a fair bit of testing locally and everything worked as expected.

Using this config:

```js
module.exports = {
	"processors": ["../processors/html.js"],
	"rules": {
		"block-no-empty": true
	}
}
```

Where `../processors/html.js` was an ES5 build of the HTML extractor, I was able to:

- Run the CLI against a bunch of HTML files containing `<style>` tags.
- Use the Node API against those same files.
- Run both the above against CSS files without any issues.
- Run both the above against a glob which targeted *both* HTML and CSS files - this was awesome to see, btw :)

I've no suggestions for the code or docs, as both appear spot-on.

I've [created a PR](https://github.com/stylelint/stylelint/pull/1539) for `master` that adds a deprecation note and briefly expands the "Release planning" doc. 

Thanks again for putting the legwork into this feature. It feels like we're really focusing-down the scope of the linter.

**Comment by davidtheclark** [comment]
Thanks for testing it out, @jeddy3. Glad it's working as expected.

**Comment by jeddy3** [comment]
@davidtheclark Is there more you want to do on this, or shall we merge?

**Comment by davidtheclark** [comment]
Merging!

**Pull request merged**
