### PR TITLE
Regenerate package-lock.json

### PR DESCRIPTION
**Pull request by XhmikosR**
This should be rebased after the other open dependabot PRs are merged.

Note that we should probably move with any dep updates in the eslint config too.

> 1 file changed, 667 insertions(+), 2047 deletions(-)

### CODE REVIEW

**Comment by XhmikosR** [comment]
This fixes the errors when doing `npm ci` on Windows CI, although they didn't fail the build

```
D:\a\stylelint\stylelint\node_modules\fsevents>if not defined npm_config_node_gyp (node "C:\npm\prefix\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\npm\prefix\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Traceback (most recent call last):
  File "C:\npm\prefix\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "C:\npm\prefix\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "C:\npm\prefix\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 547, in main
    return gyp_main(args)
  File "C:\npm\prefix\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 532, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\npm\prefix\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2034, in GenerateOutput
    sln_projects, project_objects, flat=msvs_version.FlatSolution())
  File "C:\npm\prefix\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1791, in _GatherSolutionFolders
    return _DictsToFolders('', root, flat)
  File "C:\npm\prefix\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1744, in _DictsToFolders
    for folder, contents in bucket.items():
AttributeError: 'MSVSProject' object has no attribute 'items'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\npm\prefix\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\hostedtoolcache\\windows\\node\\10.18.1\\x64\\node.exe" "C:\\npm\\prefix\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\a\stylelint\stylelint\node_modules\fsevents
gyp ERR! node -v v10.18.1
gyp ERR! node-gyp -v v
```

**Comment by XhmikosR** [comment]
This can be probably merged after #4557

**Comment by jeddy3** [comment]
Would we do a minor release when this is merged so that https://github.com/stylelint/stylelint/pull/4550 is fixed?

**Comment by XhmikosR** [comment]
SGTM but I think we need to retrigger dependabot before this PR is merged because I need to redo it with all deps updated, so it should be last.

**Comment by jeddy3** [comment]
> SGTM

I'd be great if we could get the new documentation (https://github.com/stylelint/stylelint/pull/4561) merged in before we do a patch release so that we can update the website using it.

**Comment by XhmikosR** [comment]
@hudochenkov is there any date planned to release a patch version? Or do we have an issue to track things?

**Comment by hudochenkov** [comment]
@XhmikosR no planned date. Usually we do releases on weekends. I'm not available this week. Maybe @jeddy3 will have time.

**Comment by jeddy3** [comment]
> Maybe @jeddy3 will have time.

I'll have time this week.

**Pull request merged**
