### PR TITLE
Ignore length-zero-no-unit violations found within var() functions if custom properties are ignored

### PR DESCRIPTION
**Pull request by lanthaler**
> Which issue, if any, is this issue related to?

Related to https://github.com/stylelint/stylelint/issues/4945, but limited to the var() function for now

> Is there anything in the PR that needs further explanation?

Should be self-explanatory. More than happy to answer questions if there are any

### CODE REVIEW

**Review by jeddy3 — CHANGES_REQUESTED** [review]
@lanthaler Thanks for the pull request.

Two related pull requests were recently merged (https://github.com/stylelint/stylelint/pull/5203 & https://github.com/stylelint/stylelint/pull/5245) which I think will address the problem most users are facing with this rule, i.e. using `var` within `calc` or some other math function. 

However, users may wish to ignore the contents of functions outright, whether that's `var` or something else. The [convention we use](https://stylelint.io/user-guide/rules/about#user-defined-ignore) is an `ignore*` secondary function, e.g. `ignoreFunctions`.

Rather than overloading the `custom-properties` keyword option, this option will allow users to make the rule more permissive on a granular scale.

Is it possible to rework this pull request to https://github.com/stylelint/stylelint/issues/4945#issuecomment-729069609?

**Comment by jeddy3** [comment]
I hadn't realised the rule was a mesh of style-search and the value parser. I've created an issue to refactor the rule to only use the value parser, which will make adding an `ignoreFunction` option easier.

**Comment by lanthaler** [comment]
I just discovered that there's already a lingering PR to add ignoreFunction #5082 and that you started refactoring this code altogether #5256. If this change isn't of interest as is, let's just close this PR. The reason I "overloaded" the custom-properties option is because the `var` function is exclusively about custom properties.

**Comment by jeddy3** [comment]
> If this change isn't of interest, let's just close this PR.

Yes, let's do that. With the recently merged #5203 & #5245 (which are in the refactoring of #5256), I think the most common problem of using `var` within `calc` is solved.

Thanks again for the pull request.

**Pull request closed without merging**
