### PR TITLE
Add Windows to Travis

### PR DESCRIPTION
**Pull request by hudochenkov**
Travis [added](https://blog.travis-ci.com/2018-10-11-windows-early-release) early Windows support.

Examples, how other projects added it:

https://github.com/docker-library/golang/pull/243
https://github.com/yargs/yargs/pull/1225
https://github.com/npm/node-semver/pull/257

Let's test it for a while. I don't think we need to replace Appveyor yet.

### CODE REVIEW

**Comment by hudochenkov** [comment]
Currently, there are issues with timeouts on Travis side. Will restart later.

**Comment by ntwb** [comment]
Neat 👌

Maybe to help mitigate the timeouts setting the Windows jobs to _allow to fail_ might be worthwhile?
> https://docs.travis-ci.com/user/customizing-the-build/#rows-that-are-allowed-to-fail

**Comment by hudochenkov** [comment]
@ntwb good idea! But first I want to make them work with at least manual restarts. Currently, it even fails by timeout on initial container creation.

**Comment by hudochenkov** [comment]
It's a known issue: https://travis-ci.community/t/windows-instances-hanging-before-install/250

Will wait for a resolution.

**Comment by ntwb** [comment]
I've just pinged Travis CI to seee about moving us from dotorg to dotcom Travis

https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures

We might get some benefits by switching sooner for this issue.

**Comment by ntwb** [comment]
Screen Shot 2019-04-08 at 12 14 17 pm

**Comment by ntwb** [comment]
Travis-CI have graciously activated the migration tool for stylelint to migrate from `.org` to `.com`, I'll take an initial look now at what that entails and report back.

**Comment by ntwb** [comment]
See also #4116

**Comment by ntwb** [comment]
See also #4116

**Comment by ntwb** [comment]
Updated PR via commit https://github.com/stylelint/stylelint/pull/3716/commits/d03806a5807101e07d8212df3012f87e51193a1a

**Comment by ntwb** [comment]
Latest CI jobs can be viewed at https://travis-ci.com/stylelint/stylelint/builds/115683987

**Comment by ntwb** [comment]
All 3 Windows builds are currently failing and will need further investigation:

https://travis-ci.com/stylelint/stylelint/builds/115683987

**Comment by ntwb** [comment]
Travis CI appears to be using `nvs` (rather than `nvm`), I'm taking a guess it is the following repo and this info suggests `npm install -g` should work as desired, so still not sure why the jobs are failing when attempting to `npm install -g npm@latest` :think

**Pull request closed without merging**
