### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by XhmikosR**
* postcss             ^8.3.11  →   ^8.4.1
* eslint-plugin-jest  ^25.2.4  →  ^25.3.0
* postcss-html         ^1.2.0  →   ^1.3.0

Testing the types changes. I kept getting those failures on my machine. I'm still getting one:

```
C:\Users\xmr\Desktop\stylelint>npm run lint:types

> stylelint@14.1.0 lint:types
> tsc

lib/lintPostcssResult.js:38:24 - error TS2345: Argument of type 'Document | Root' is not assignable to parameter of type 'Root'.
  Type 'Document' is not assignable to type 'Root'.
    Types of property 'type' are incompatible.
      Type '"document"' is not assignable to type '"root"'.

38   assignDisabledRanges(postcssDoc, postcssResult);
                          ~~~~~~~~~~


Found 1 error.
```

Unsure why this doesn't happen on CI too...

EDIT: It seems the types error happens on CI too, so we are all good. @ybiquitous feel free to push a fix or drop the PR :)
EDIT2: any ideas why Coveralls is dead?

### CODE REVIEW

**Comment by ybiquitous** [comment]
@XhmikosR Thanks for creating the PR! I've fixed the type error via b809e2a8. 👍🏼

**Comment by ybiquitous** [comment]
> EDIT2: any ideas why Coveralls is dead?

I'm not sure. 😕 
See also https://github.com/stylelint/stylelint/pull/5728#issuecomment-974791533

**Comment by ybiquitous** [comment]
I've just resynced with GitHub on the [Coveralls repo settings](https://coveralls.io/github/stylelint/stylelint/settings):

image

**Comment by adalinesimonian** [comment]
@XhmikosR I think I have a fix for the types error in #5725, you can probably just copy the changes from the relevant file.

**Comment by adalinesimonian** [comment]
Also, just a note that since PostCSS added range support in 8.4, any rule that only provides `warn` with a node will warn with a range for the entire node, which is in some cases undesirable.

**Comment by ybiquitous** [comment]
@adalinesimonian Thanks for the help. It seems good to update to postcss@8.4.x with PR #5725, instead of this PR.

Also, Dependabot will bump other outdated dependencies next week:

https://github.com/stylelint/stylelint/blob/a7d9c07441830e0b9777f29f510d6e7c6593d6c1/.github/dependabot.yml#L5-L6

**Comment by XhmikosR** [comment]
@ybiquitous now there are more failures. :/

As for dependabot, this is not the same as dependabot. From time to time, I regenerate the lock file to make sure we are getting all the latest fixes and that deps are deduplicated properly.

Anyway, feel free to drop this, I mostly opened it because I was getting various errors locally and not on CI and I wanted to see if we can make this consistent.

**Comment by ybiquitous** [comment]
@XhmikosR Thank you for sharing it! I'll look into this later.

**Comment by ybiquitous** [comment]
I've just updated some dependencies with other PRs, but some remain:

```console
$ npm outdated
Package               Current  Wanted  Latest  Location                           Depended by
execall                 2.0.0   2.0.0   3.0.0  node_modules/execall               stylelint
get-stdin               8.0.0   8.0.0   9.0.0  node_modules/get-stdin             stylelint
globby                 11.0.4  11.0.4  12.0.2  node_modules/globby                stylelint
mathml-tag-names        2.1.3   2.1.3   3.0.2  node_modules/mathml-tag-names      stylelint
meow                    9.0.0   9.0.0  10.1.2  node_modules/meow                  stylelint
postcss                8.3.11   8.4.4   8.4.4  node_modules/postcss               stylelint
postcss-html            1.2.0   1.3.0   1.3.0  node_modules/postcss-html          stylelint
postcss-value-parser    4.1.0   4.2.0   4.2.0  node_modules/postcss-value-parser  stylelint
string-width            4.2.3   4.2.3   5.0.1  node_modules/string-width          stylelint
strip-ansi              6.0.1   6.0.1   7.0.1  node_modules/strip-ansi            stylelint
```

The PostCSS packages above will be updated with PR #5725 (some errors are due to PostCSS 8.4).

@XhmikosR Thank you and sorry for taking your time. 😃

**Pull request closed without merging**
