### PR TITLE
Add functional support for `message` to rules with uneven arguments

### PR DESCRIPTION
**Pull request by mattxwang**
> Which issue, if any, is this issue related to?

Part of (but does not close) #6966; related to #7194.

> Is there anything in the PR that needs further explanation?

Still draft for now, but I'm choosing to split things up just to make things easier to review; I'm also still waiting on other opinions on how we should handle rules with no arguments & documentation.

### CODE REVIEW

**Comment by mattxwang** [comment]
Note for myself, list of rules left:

```
lib/rules/at-rule-empty-line-before/index.js
lib/rules/block-no-empty/index.js
lib/rules/comment-empty-line-before/index.js
lib/rules/comment-no-empty/index.js
lib/rules/comment-whitespace-inside/index.js
lib/rules/custom-property-empty-line-before/index.js
lib/rules/declaration-empty-line-before/index.js
lib/rules/declaration-no-important/index.js
lib/rules/declaration-property-value-no-unknown/index.js
lib/rules/font-family-name-quotes/index.js
lib/rules/font-family-no-duplicate-names/index.js
lib/rules/font-family-no-missing-generic-family-keyword/index.js
lib/rules/font-weight-notation/index.js
lib/rules/function-calc-no-unspaced-operator/index.js
lib/rules/function-linear-gradient-no-nonstandard-direction/index.js
lib/rules/function-url-no-scheme-relative/index.js
lib/rules/function-url-quotes/index.js
lib/rules/import-notation/index.js
lib/rules/keyframe-declaration-no-important/index.js
lib/rules/length-zero-no-unit/index.js
lib/rules/media-feature-name-no-vendor-prefix/index.js
lib/rules/media-feature-name-unit-allowed-list/index.js
lib/rules/named-grid-areas-no-invalid/index.js
lib/rules/no-empty-source/index.js
lib/rules/no-invalid-double-slash-comments/index.js
lib/rules/no-invalid-position-at-import-rule/index.js
lib/rules/no-irregular-whitespace/index.js
lib/rules/rule-empty-line-before/index.js
lib/rules/selector-attribute-quotes/index.js
lib/rules/selector-pseudo-element-colon-notation/index.js
lib/rules/string-no-newline/index.js

```

**Comment by mattxwang** [comment]
I'm going to keep on working on this PR for the next few days, but as a note to myself/others: I do think we'll need to change some of the underlying messages/APIs to make it easier for useres to use `messageArgs`; in particular, a way to disambiguate between the different functions that we call. I will have to go back and change some of these strategies.

**Comment by ybiquitous** [comment]
@mattxwang Can you restart this work?

**Comment by mattxwang** [comment]
> @mattxwang Can you restart this work?

Ah, sorry - have been falling behind on my OSS obligations. Yep, I can work on it again this week!

I will have to prototype out more details on _how_ the functions will work. Any suggestions welcome!

p.s. thank you for all your work in releasing v16!

**Comment by mattxwang** [comment]
Closing, ref https://github.com/stylelint/stylelint/pull/6818#issuecomment-1901779311.

**Comment by Mouvedia** [comment]
@mattxwang if you reduce the scope a bit for the next PR, it would not end up in limbo.
e.g. just add the ones you have done already for ones
i.e. color-named, font-weight-notation, function-calc-no-unspaced-operator and function-url-quotes

**Pull request closed without merging**
