### PR TITLE
Add selector-attribute-name-disallowed-list

### PR DESCRIPTION
**Pull request by rletsin**
Solution for Issue #4915 

> Is there anything in the PR that needs further explanation?

I think no, it's self-explanatory.

### CODE REVIEW

**Comment by rletsin** [comment]
I'll try to fix linting and test errors.
At the moment I have some trouble reproducing them locally.

**Review by jeddy3 — CHANGES_REQUESTED** [review]
@rletsin Thanks. It's looks great so far!

In [my original proposal](https://github.com/stylelint/stylelint/issues/4915#issuecomment-684843841), I should have said use both the:

- [`selector-attribute-operator-disallowed-list`](https://github.com/stylelint/stylelint/tree/master/lib/rules/selector-attribute-operator-disallowed-list)
- [`media-feature-name-disallowed-list`](https://github.com/stylelint/stylelint/blob/master/lib/rules/media-feature-name-disallowed-list/)

rules as a blueprints; taking the AST traversal from `selector-attribute-operator-disallowed-list` and the options from `media-feature-name-disallowed-list`. As this rule targets names, rather than operators, it'll need to accept regexes like the `media-feature-name-disallowed-list` rule does.

Can you update the options, docs and tests so they are more aligned with `media-feature-name-disallowed-list` rule, please?

**Comment by rletsin** [comment]
@jeddy3 Thanks for your suggestions!
I've added regex as possible input for this rule.

**Review by jeddy3 — APPROVED** [review]
Thanks for making the changes! 

Looks good to me.

**Review by ybiquitous — APPROVED** [review]
Looks nice! 👏

**Comment by jeddy3** [comment]
Changelog:

> - Added: `selector-attribute-name-disallowed-list` rule ([#4992](https://github.com/stylelint/stylelint/pull/4992)).

**Pull request merged**
