### PR TITLE
Fix no-unsupported-browser-features tests

### PR DESCRIPTION
**Pull request by hudochenkov**
> Which issue, if any, is this issue related to?

https://github.com/stylelint/stylelint/issues/2525

> Is there anything in the PR that needs further explanation?

Quick fixes to tests. Rule is deprecated anyway.

### CODE REVIEW

**Comment by hudochenkov** [comment]
Of course Travis is failing. Because node_modules is cached.

**Comment by evilebottnawi** [comment]
@hudochenkov you can remove cache build https://travis-ci.org/stylelint/stylelint/caches :smile:

**Comment by jeddy3** [comment]
@hudochenkov I think you're going to have to update the snapshots as well.

**Comment by hudochenkov** [comment]
@jeddy3 yes, I didn't saw them first. Just pushed commit with snapshots.

**Comment by hudochenkov** [comment]
@stylelint/core We should merge this PR in order to restore Travis.

**Comment by jeddy3** [comment]
@hudochenkov Thanks :)

**Pull request merged**
