### PR TITLE
Move Babel and ESLint configs to package.json

### PR DESCRIPTION
**Pull request by shinnn**
ESLint >= v1.10.0 supports [config file extension](http://eslint.org/docs/user-guide/configuring#configuration-file-formats).

According to the [ESLint release note](http://eslint.org/blog/2015/11/eslint-v1.10.0-released#configuration-file-formats):

> We are formally deprecating use of the `.eslintrc` extensionless configuration file format in favor the format-specific versions. Don't worry, we'll still support `.eslintrc` files for a long time, but we'd like to encourage everyone to move to the new file formats as you'll get advantages such as syntax highlighting and error detection with many editors.

Actually, Github [doesn't highlight `.eslintrc` contents](https://github.com/stylelint/stylelint/blob/59681635dc653a8d92cefa33e113438a0df73456/.eslintrc), but [does well for `.eslintrc.yml`](https://github.com/stylelint/stylelint/blob/72e007a88fc765194fc429467cade14680cdb0ac/.eslintrc.yml).

### CODE REVIEW

**Comment by jeddy3** [comment]
Thanks @shinnn!

@davidtheclark Should be take this opportunity to move the `babel` and `eslint` configs into our `package.json`? Is that a good idea?

@shinnn Do you have thoughts on that?

**Comment by shinnn** [comment]
> Should be take this opportunity to move the babel and eslint configs into our package.json? Is that a good idea?

I prefer `package.json` config and always use it on my own projects. In https://github.com/stylelint/stylelint/commit/72e007a88fc765194fc429467cade14680cdb0ac I tried to keep the existing code and file structure, but I'd happily update this PR to move configs to `package.json` if you want.

**Comment by davidtheclark** [comment]
@jeddy3 I'm fine with moving babel to package.json because it's small, but would like to keep eslint config in its own file. That's my personal preference.

**Comment by shinnn** [comment]
Moreover, if you keep ESLint config as an external file, I recommend to use `.js` extension because we can lint the ESLint config file by ESLint using the ESLint config described in the ESLint config file itself.

We have a lot of choice.

**Comment by jeddy3** [comment]
@davidtheclark The eslint config is tiny too, i.e. `extends: 'stylelint'`, as we use a shared eslint config.

So the `package.json` will be:

```
  "babel": {
    "presets": [
      "babel-preset-es2015"
    ],
  },
  "eslintConfig": {
    "extends": ["stylelint"]
  }
```

**Comment by davidtheclark** [comment]
@jeddy3: Oh yeah. That seems swell.

**Comment by jeddy3** [comment]
@shinnn Can you please update the PR to move `babel` and `eslint` configs into `package.json`, and we'll get the merged?

**Comment by shinnn** [comment]
@jeddy3 Sure.

**Comment by shinnn** [comment]
Done. https://github.com/stylelint/stylelint/commit/df198e8df93fed980c8ef2456de53acba1e519e4

**Comment by jeddy3** [comment]
Thanks @shinnn !

Lgtm.  Lets wait for a greenlight from the CI before merging this one.

**Comment by shinnn** [comment]
Passed all the tests.

**Comment by jeddy3** [comment]
Thanks again :)

**Pull request merged**
