### PR TITLE
Stylelint pre-commit plugin

### PR DESCRIPTION
**Pull request by awebdeveloper**
An Pre-commit plugin for style-lint 

https://github.com/stylelint/stylelint.io/issues/41

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@awebdeveloper 
Need fix
> docs/user-guide/complementary-tools.md
  34:3  warning  Incorrect list-item indent: add 2 spaces  list-item-indent  remark-lint

**Comment by hudochenkov** [comment]
To be honest, I don't see a value for this “tool”. It's not clear what is it, why is it needed, and how to use it.

**Comment by awebdeveloper** [comment]
@hudochenkov its a plugin for yelp's pre-commit git tool. 

This prevents commits unless it passes the stylelint check. I guess the link in the repo are self explanatory but if you still fell so I could update the readme of my repo

**Comment by awebdeveloper** [comment]
@hudochenkov  I have updated the realm to contain a bit more info

**Comment by ntwb** [comment]
I think we should keep our list of _complemetary tools_ to tools that have some widespread usage

**Comment by awebdeveloper** [comment]
@ntwb having a pre-commit hook is a common use-case, don't you think so

**Comment by ntwb** [comment]
I think I've been swayed to change my mind here...

I think there is merit in promoting some tools for stylelint and _version control_

Another tool that fits this category is https://github.com/okonet/lint-staged, it's similar, but different

**Comment by jeddy3** [comment]
@awebdeveloper Thanks!

**Pull request merged**
