### PR TITLE
Add rule : unit-whitelist

### PR DESCRIPTION
**Pull request by makotot**
Ref: #429

### CODE REVIEW

**Comment by jeddy3** [comment]
@makotot Thanks! :) This one looks perfect from the go to me.

@davidtheclark Do you have any suggestions or shall I merge?

**Comment by davidtheclark** [comment]
Great! I just have one question: This applies to *all* units, right, now just length units? It might help people understand the scope of the rule if we mention that and add an example or two with non-length units (e.g. `30deg` or `5s`). Other than that, code looks good.

**Comment by makotot** [comment]
Thanks :) Added exampls with non-length units to README.

**Comment by davidtheclark** [comment]
I'm good with this now -- ready to merge. @jeddy3 did you want more documentation or something? Noticed you added the label.

**Comment by jeddy3** [comment]
Looks great to me now :)

Thanks again @makotot !

**Comment by makotot** [comment]
Thanks! :)

**Pull request merged**
