### PR TITLE
Account for windows carriage returns in parens in indentation

### PR DESCRIPTION
**Pull request by m-allanson**
Demonstrates the problem discussed in #1708

### CODE REVIEW

**Comment by jeddy3** [comment]
Thanks everyone for helping get to the bottom of this issue.

It's a head-scratcher to why this bug was initially only reproducible in some environments. That really threw the investigation off. We've dealt with windows line ending bugs before and tracking down the source of the problem was usually a breeze. All I can think of is that git was normalising the line endings *in the test repos* to `\n`. I think, when faced with a similar bug in the future, we need to remember that reproducible tests repos *aren't* a reliable way of demonstrating whitespace bugs. Instead we should encourage PRs of failing tests (using carriage returns and line feed *characters*). 

Hopefully, this PR resolves the issue.

Thanks again everyone for mucking in on this one. It was a real team effort :)

**Comment by m-allanson** [comment]
Those tests look nice and comprehensive. LGTM.

**Comment by evilebottnawi** [comment]
@jeddy3 LGTM, nice work :tada:

**Comment by davidtheclark** [comment]
Fantastic, everybody.

**Comment by davidtheclark** [comment]
Just realized this PR did not contain a changelog note. Anybody want to add one quick?

**Comment by jeddy3** [comment]
> Just realized this PR did not contain a changelog note.

My bad. Done in https://github.com/stylelint/stylelint/commit/b9280093a1df8f042385d3dfe31eef03aa8998cf.

**Comment by ntwb** [comment]
Yeah, head scratcher indeed, thanks everyone 😄

**Pull request merged**
