### PR TITLE
Expose cssWordIsVariable in utils

### PR DESCRIPTION
**Pull request by kangax**

### CODE REVIEW

**Comment by davidtheclark** [comment]
Sure!

**Comment by kangax** [comment]
Thanks, David! 

Btw, do you have skype/slack/fleep/fb messenger/gitter/other similar medium where I can quickly ask you smth?

**Comment by davidtheclark** [comment]
Forgot to ask for a changelog entry. 

Yeah, you can DM me on Twitter or on Gitter and I should get the nofication.

**Comment by davidtheclark** [comment]
Also, feel free to [email me](https://github.com/davidtheclark).

**Comment by davidtheclark** [comment]
Added changelog note in 3d9ffa29e7bdbcf2fce5b56aa7dcafd49566aa04

**Pull request merged**
