### PR TITLE
System tests

### PR DESCRIPTION
**Pull request by davidtheclark**
Definitely not ready to merge yet. But I'm opening a PR so I can see how Travis responds ...

### CODE REVIEW

**Comment by davidtheclark** [comment]
Ref #2016.

This is actually looking ok ...

Here's the idea so far:
- `system-tests/` holds everything relevant to this.
- `system-tests/.eslintrc` simply adds the Jest env to the config.
- We add a subfolder for each test case, containing a `stylesheet.*`, a `config.*`, and a `[case number].test.js`. The test file checks stylelint's output against the snapshot.

Case 002 experiments with a config with dependencies — in this case, `stylelint-scss`. What I have going here works but it feels wrong and ugly to me. There's a separate `package.json` and `node_modules` inside `system-tests/` to manage these config dependencies, in order to avoid circular dependency problems when one of those plugins depends on `stylelint` (as `stylelint-scss` does). This means that we need to `cd system-tests && npm install` before we run the system tests. **If anybody has another idea about how to accomplish this, I'd love to hear it.**

**Comment by ntwb** [comment]
A couple of notes/questions regarding `system-tests/001/stylesheet.css` if I may:

• The file is Bootstrap v4.0.0-alpha.5
• I believe Bootstrap v4 is still currently using `scss_lint`
• I believe Bootstrap v4 does not currently use CSSLint.

Firstly, is is that entire file valid CSS? (I presume it is, but lets for a moment assume it isn't)

What I'm curious about in regard to validity of that CSS file is as these Jest tests are to _protect against regressions_ if there are any issues with that Bootstrap CSS file then stylelint will be perpetually testing against _possible_ invalid CSS.

If in a future not too far from now stylelint v8.2.5 fixes "a bug of some sort" then how would that affect the above config-stylesheet pair as the `001.test.js` and `001.test.js.snap` are not using a specific semantic version of stylelint and the returned `.snap` object results would now be different to that of the original commit.

1. Rather than large libraries of CSS such as Bootstrap, should these test pairs be smaller succinct examples of 10, 50, 100 lines of CSS rather than thousands?

2. Should, which leads to can each of these tests be against a specific version of stylelint? ( I'm already envisaging even more circular dependency problems with this if that were the case)

p.s. Will think and research some ideas regarding the extra `package.json` NPM implementation

**Comment by davidtheclark** [comment]
@ntwb Thanks for putting some thought into this!

The file is built from Bootstrap's SCSS, so I think it is valid CSS. But regardless, I'm not sure it matters. The point of the snapshot tests is to ensure that stylelint's output remains consistent, even if that output is a syntax error. If stylelint changes such that this Bootstrap CSS file no longer produces the same results, we want to know.

The snapshots will update as stylelint updates, but only if the result changes are *deliberate*. You can see here that the snapshot is committed to the repo: so if we *update* the snapshots, because a bug was fixed and some test case's output changed *in a good way*, that update will be included in a PR, diffed and reviewed.

Because of this, I think we always want the snapshot tests to run against the stylelint code under development, not against fixed versions of stylelint. We want to make sure that the code that we are about to commit does not break the expected output from these test cases.

**Comment by evilebottnawi** [comment]
@davidtheclark what about install all packages for tests from `package.json` for latest snapshot of code?

**Comment by davidtheclark** [comment]
> what about install all packages for tests from package.json for latest snapshot of code?
@evilebottnawi if what you're suggesting is use the project's `package.json` and add plugins etc. as devDependencies, I believe the problem is that some of those plugins etc. will have a dependency on stylelint, in which case we'll have a problem.

**Comment by ntwb** [comment]
I think `peerDependencies` could work here, I still don't fully grok `peerDependencies` so I'll continue researching this, currently reading:
https://stackoverflow.com/questions/26737819/why-use-peer-dependencies-in-npm-for-plugins

**Comment by m-allanson** [comment]
@davidtheclark this is looking great.

> If anybody has another idea about how to accomplish this, I'd love to hear it.

Would adding a `postinstall` npm script be enough to handle the `cd system-tests && npm install` command?

Another option could be to install the `system-test` dependencies as devDependencies in stylelint's main `package.json`. Then use [Jest's manual mocks](https://facebook.github.io/jest/docs/manual-mocks.html#content) to override any nested stylelint dependencies.

This means that, with an npm dependency structure like this:

```
@stylelint@(development version)
└─┬ @stylelint-scss
  └── @stylelint@(released version)
```

any `stylelint-scss`references to the released version of `stylelint` would be replaced with the development version of `stylelint`. Does that sound crazy? Note that I've not tried it and I don't know if it would actually work.

**Comment by davidtheclark** [comment]
> I think peerDependencies could work here

@ntwb Don't think `peerDependencies` would work in this situation. We'd still end up in `stylelint` having a `node_modules/stylelint` directory, which is problematic.

> Would adding a postinstall npm script be enough to handle the cd system-tests && npm install command?

@m-allanson I don't think we want to do `postinstall` because we don't want these installing all the time, not for end users.

```
@stylelint@(development version)
└─┬ @stylelint-scss
  └── @stylelint@(released version)
```

^^ Seems kind of crazy to me, more crazy than having an install-within-in-install.

**Comment by davidtheclark** [comment]
Well, I think this is ready for more trials. @stylelint/core can you please point me to some code, in repos or gists, that you think we should add to this system test suite?

**Comment by ntwb** [comment]
One config-stylesheet pair I thought would be beneficial, though artificial in that it would more than likely need to be created specifically for this would be for [custom messages](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#custom-messages). 

I was thinking the config-stylesheet pair would only require basic CSS but a thorough configuration with a custom message for all stylelint rules that support them.

Is this the type of config-stylesheet pair that would be a good fit here?

**Comment by davidtheclark** [comment]
@ntwb That couldn't hurt! I don't think, though, you'd need to include a custom message for *every* rule, because the logic to apply custom messages lives outside the rules — therefore, if a few work, we're pretty assuming they'll all work.

**Comment by davidtheclark** [comment]
If these tests pass, I'm going to merge what I have. I think we can best avoid the double-install mess by just *not testing external tools*. It is not the responsibility of this library to test, for example, that `stylelint-scss` works as expected. So I think we just don't include test cases that rely on plugins, etc., that in turn depend on stylelint.

**Pull request merged**
