### PR TITLE
Cosmiconfig

### LINKED ISSUE #490: New configuration loader
Here's the spec:

- Look for `.stylelintrc`, `stylelint.config.js`, and `stylelint` properties in `package.json` files.
- Starting from `process.cwd()`, look for these files in `./ ../ ../../ ../../../` etc., all the way to `~` (user home directory), checking first for `stylelint` in `package.json`, second for `.stylelintrc`, third for `stylelint.config.js`.
- *Stop looking at the first one that is found*, and use that one as the config.
- Built-in YAML support for `.stylelintrc`.
- The config can have an extends property, whose value is a single string or an array of strings. Each string must be a lookup that require() would understand, so either:
  - A npm module name
  - An absolute path
  - A relative path, relative to the config file that is extending
- If config A extends config B, the result is config A's properties merged into config B, with config A taking priority.

The plan right now is to build these features into a standalone module and integrate that module into stylelint.

cc/ #442, #418

### PR DESCRIPTION
**Pull request by davidtheclark**
This PR integrates [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) into a new v3 branch, where I figured we could start integrating our breaking changes for 3.0.0.

Although I haven't yet released 1.0 of cosmiconfig, I think that the API isn't going to change for stylelint's needs.

I did some other miscellaneous tweaking while looking around and fixing problems, so I'm afraid it's not the cleanest PR ever.

I think I captured all the configuration-loading effects that cosmiconfig has in the changelog, but have not yet documented them in the user guide.

Closes #490.

### CODE REVIEW

**Comment by TrySound** [comment]
@davidtheclark Again just return a promised result instead of wrap in Promise constructor

**Comment by TrySound** [comment]
@davidtheclark If you want give me access, I will fix

**Comment by davidtheclark** [comment]
Sure, contributions welcome!

**Comment by TrySound** [comment]
Accept me in your boyband?

**Comment by davidtheclark** [comment]
Very nice, thanks. ♩ ♪ ♫ ♬

**Comment by TrySound** [comment]
I mean org

**Comment by TrySound** [comment]
Also I have plan to remove Q. :)

**Comment by davidtheclark** [comment]
Ah -- I haven't done that before. I think you did get an invite, though.

**Comment by TrySound** [comment]
@davidtheclark Yay, cool :) Thanks

**Comment by davidtheclark** [comment]
Yeah, I was thinking https://github.com/stylelint/stylelint/blob/master/src/standalone.js could use some refactoring. The codebase has gotten really large ... the more eyes on the code the better.

**Comment by TrySound** [comment]
@davidtheclark The most cool in promises is that simpler api covers more needs

**Comment by davidtheclark** [comment]
Great work on the standalone refactor.

**Comment by TrySound** [comment]
Done

**Comment by davidtheclark** [comment]
To finish off this PR, I think we need one:

- @jeddy3's approval and testing (you've always been good at finding issues that we missed writing tests for)

That right?

**Comment by jeddy3** [comment]
> @jeddy3's approval and testing

I've made a start on this. 

Are the options [here](https://github.com/stylelint/stylelint/blob/v3/docs/user-guide/node-api.md#options) correct?

In the meantime, using `--config` to a relative config which has an `"extends"` seems to max out my processor. Perhaps an infinite loop?

**Comment by davidtheclark** [comment]
> Are the options here correct?

Yeah, those shouldn't have changed.

**Comment by jeddy3** [comment]
Ok, one more then:

---
```js
stylelint.lint({ files: "css/*.css", configFile: "config/myconfig.json"})
```

Run as:

```bash
node standard-js-api.js
```

Gives:

```bash
TypeError: Cannot read property 'config' of null
    at /Users/jeddy3/Projects/stylelint-test/node_modules/stylelint/dist/buildConfig.js:42:32
```

Whereas the following works:

```bash
node standard-js-api.js --config config/myconfig.json
```

**Comment by davidtheclark** [comment]
@jeddy3: When you pass a `configFile` path it either needs to be absolute or relative to `process.cwd()`. Is that the case with what you're running?

**Comment by jeddy3** [comment]
> relative to process.cwd()

It is this.

**Comment by jeddy3** [comment]
Same error with absolute path too.

**Comment by davidtheclark** [comment]
Well boo.

**Comment by jeddy3** [comment]
> Well boo.

Yep. Otherwise though, everything else looks hunky dory :)

**Comment by davidtheclark** [comment]
@jeddy3 I fixed the infinite loop, but could not reproduce the other one. Are you sure your CSS files are at the equivalent of `path.join(process.cwd(), 'config/config.json'`?

If in one of our tests that I run from the project root use `files: src/__tests__/fixtures/empty-block.css`, the test passes.

In any case, if you're using the Node.js API I don't think there's any reason not to use absolute paths. We could make it a requirement, even.

**Comment by davidtheclark** [comment]
Oh sorry, I misread: It's the `config` file that wasn't loading. Let me look again.

**Comment by davidtheclark** [comment]
Figured it out. `configFile` wasn't actually an option in the Node.js API. So I added it and made it work same as in the plugin.

**Comment by davidtheclark** [comment]
So I think that's it. @jeddy3 if the problems you found are fixed, please merge into v3.

**Comment by jeddy3** [comment]
> Figured it out. 

Good stuff.

> if the problems you found are fixed, please merge into v3.

All looks good now :)

**Comment by davidtheclark** [comment]
:balloon: That was a big one.

**Comment by jeddy3** [comment]
:tada: Thanks for this one @davidtheclark (and everyone else for their input and help)! :)

**Pull request merged**
