### PR TITLE
Update to PostCSS@6

### PR DESCRIPTION
**Pull request by ntwb**
Updates postcss to the latest 6.x version 

Supersedes #2548

### CODE REVIEW

**Comment by ntwb** [comment]
Related PRs, I didn't create new PRs for these as they'll need rebasing once this PR is merged, theoretically they all also require and are dependant on this PR also:

• #2555 postcss-scss
• #2553 sugarss
• #2554 postcss-safe-parser
• #2550 autoprefixer

**Comment by jeddy3** [comment]
I suggest we just update everything related to `postcss@6` in this PR for the sake of simplicity.

**Comment by hudochenkov** [comment]
I think we could delay this until `8.0`. This way we won't have much merge conflicts with `master`. And by that time other dependencies (and PostCSS) fix their bugs, if any :)

**Comment by jeddy3** [comment]
> I think we could delay this until 8.0

Yep, it's pointing to the `v8` branch. We can merge `master` into `v8` before working on this PR.

**Comment by jeddy3** [comment]
I've rebased this on `v8`.

**Comment by jeddy3** [comment]
Summary:

```shell
Test Suites: 5 failed, 267 passed, 272 total
Tests:       26 failed, 13042 passed, 13068 total
Snapshots:   7 passed, 7 total
Time:        108.692s
Ran all test suites.
```

`26 failed, 13042 passed` is a pretty decent ratio :)

The failing suites are:

- [ ] `lib/rules/no-extra-semicolons/__tests__/index.js`
- [ ] `lib/rules/block-closing-brace-newline-after/__tests__/index.js`
- [ ] `lib/__tests__/ignoreDisables.test.js`
- [ ] `lib/__tests__/defaultSeverity.test.js`
- [ ] `lib/__tests__/postcssPlugin.test.js`

I suggest we tackle them individually as PRs into this branch `v8-postcss-six`. Drop a note in here if you've about to start on one. 

I'm going to give `lib/rules/block-closing-brace-newline-after/__tests__/index.js` a go now.

**Comment by jeddy3** [comment]
Going to look at `lib/__tests__/postcssPlugin.test.js`

**Comment by jeddy3** [comment]
Going to look at `lib/__tests__/defaultSeverity.test.js` and commit directly here.

**Comment by jeddy3** [comment]
I've got in down to 4 failing tests in `lib/rules/no-extra-semicolons/__tests__/index.js`. All four are extra semicolons after custom property sets blocks, e.g.:

```css
:root { --bar-foo: { color: red };; }
```

I'm out of time for tonight. @evilebottnawi If you have a moment, feel free to look into these last 4 tests as you're very familar with the `no-extra-semicolons` rule. Or anyone else can dive in if they've an idea about what's going on here.

**Comment by evilebottnawi** [comment]
@jeddy3 because postcss v6 have better support this, try to fix this today

**Comment by evilebottnawi** [comment]
@jeddy3 strange
```shell
Test Suites: 1 passed, 1 total
Tests:       126 passed, 126 total
Snapshots:   0 total
Time:        1.569s
Ran all test suites matching "lib/rules/no-extra-semicolons/__tests__/index.js".
```

**Comment by evilebottnawi** [comment]
In `rules` only two errors in `block-closing-brace-newline-after`

**Comment by evilebottnawi** [comment]
seems `npm@5` output incorrect `node_modules` where `postcss` v5 on top

**Comment by evilebottnawi** [comment]
Seems need resolve too https://github.com/davidtheclark/postcss-resolve-nested-selector/issues/3

**Comment by evilebottnawi** [comment]
@ai seems bug in postcss
Input:
```css
:root { --foo: { color: red };; }
```
Output for `--foo`:
```
Rule {
      raws: 
       { before: ' ',
         between: ' ',
         semicolon: false,
         after: ' ',
         ownSemicolon: ';' },
      type: 'rule',
      nodes: 
       [ Declaration {
           raws: [Object],
           type: 'decl',
           parent: [Circular],
           source: [Object],
           prop: 'color',
           value: 'red' } ],
      parent: 
       Rule {
         raws: { before: '', between: ' ', semicolon: false, after: ' ' },
         type: 'rule',
         nodes: [ [Circular] ],
         parent: 
          Root {
            raws: [Object],
            type: 'root',
            nodes: [Object],
            source: [Object],
            lastEach: 4,
            indexes: [Object] },
         source: { start: [Object], input: [Object], end: [Object] },
         selector: ':root',
         lastEach: 4,
         indexes: { '4': 0 } },
      source: 
       { start: { line: 1, column: 9 },
         input: 
          Input {
            css: ':root { --foo: { color: red };; }',
            id: '<input css 1>' },
         end: { line: 1, column: 29 } },
      selector: '--foo:',
      lastEach: 3,
      indexes: {} }
```
No information about extra semicolon, stringify this node output: `--foo: { color: red };` (without extra semicolon). Also no information in docs about `ownSemicolon: ';'`

**Comment by ai** [comment]
@evilebottnawi fixed https://github.com/postcss/postcss/commit/dde28082bb0ca4d24109038dbe7da24a3684a868

**Comment by evilebottnawi** [comment]
@ai btw in my example we lose extra semicolon in `Rule`, no information about this :disappointed:

**Comment by ai** [comment]
@evilebottnawi what is expected output?

**Comment by evilebottnawi** [comment]
@ai To tell the truth I do not know, but try `:root { --foo: { color: red };; }` parse and stringify (output `--foo: { color: red };` without extra semicolon)

**Comment by ai** [comment]
Yeap, it is a bug. Please create issue, I will try to fix it tomorrow.

**Comment by evilebottnawi** [comment]
Done: https://github.com/postcss/postcss/issues/1045

**Comment by evilebottnawi** [comment]
wip

**Comment by evilebottnawi** [comment]
@jeddy3 seems bug in npm@5 :disappointed:

**Comment by evilebottnawi** [comment]
restarting and clearing caches do not solve problem :disappointed: maybe before npm@5 become stable add allow failure

**Comment by jeddy3** [comment]
Green after purging all the caches.

@evilebottnawi Thanks for following up on the `no-extra-semicolon` rule. Thanks @ai for addressing the custom property set semicolon so quickly!

This looks good to me.

**Comment by jeddy3** [comment]
`8.0.0` changelog:

> -   Changed: compatibility with `postcss` from `@5` to `@6` ([#2561](https://github.com/stylelint/stylelint/issues/2561)).

**Pull request merged**
