### PR TITLE
Linkify changelog releases

### PR DESCRIPTION
**Pull request by ntwb**
A PR looking to standardize our changelog along the lines of http://keepachangelog.com

@stylelint/core What's the teams thoughts on "standardising" our changelog per keepachangelog?

### CODE REVIEW

**Comment by jeddy3** [comment]
Are these changes compatible with our release script, which generates a GitHub release from the CHANGELOG? I think the current release process is working well and I'd be reluctant to revisit it unless these changes add a lot of benefits for users.

**Comment by ntwb** [comment]
> Are these changes compatible with our release script, which generates a GitHub release from the CHANGELOG? I think the current release process is working well and, if it isn't compatible, I'd be reluctant to revisit it unless these changes add a lot of benefits for users.

Agreed, I shall confirm this doesn't break that 👍

**Comment by ntwb** [comment]
Closing, will revisit maybe later

**Comment by ntwb** [comment]
"Keep a Changelog" support was added in https://github.com/MoOx/github-release-from-changelog/pull/11

**Pull request closed without merging**
