### PR TITLE
Property regexes

### LINKED ISSUE #733: Allow regexes in all `property-*` rules for identifying properties
That will make it easier to, say, target all the `background*` rules, instead of having to specify each individually.

### PR DESCRIPTION
**Pull request by davidtheclark**
Closes #733.

Adds a new util, `matchesStringOrRegExp()`, to make this easy.

Also adds automatic prefix trimming to property-unit-whitelist/blacklist, because I think that was just an oversight when the rules were created.

### CODE REVIEW

**Comment by davidtheclark** [comment]
I added to this PR the the new property-value-whitelist (instead of making a second PR because that rule relied on this PR's other stuff).

So now the PR also closes #689.

**Comment by jeddy3** [comment]
Oh wow, this is fantastic!

It drastically makes all the property rules less long-winded to config.

Thanks for putting the time into implementing this!

**Comment by davidtheclark** [comment]
Actually didn't take as long as it looks like it did :)

**Comment by davidtheclark** [comment]
@jeddy3 I think I'm done working on stylelint for the weekend. Do you have a few minutes to double-check the changelog etc. and publish a magnificent release?

**Comment by jeddy3** [comment]
> Do you have a few minutes to double-check the changelog etc. and publish a magnificent release?

Absolutely!

P.S. Once we have completed the release, I'll be able to push an update to the website that, at long last, adds proper urls :)

**Comment by ntwb** [comment]
Awesome work, awesome release :+1:

**Comment by jeddy3** [comment]
:tada:  :)

**Pull request merged**
