### PR TITLE
Create and test declaration-comma-space

### PR DESCRIPTION
**Pull request by davidtheclark**
Very similar to `function-comma-space`.

### CODE REVIEW

**Comment by MoOx** [comment]
Could you provide doc with the rule ?
I guess if you get ton of undocumented rule it will become a pain to document everything :/

**Comment by MoOx** [comment]
Except that, this looks good.

**Comment by davidtheclark** [comment]
I think there's at least as much value at this early stage in plowing through rules and working out the kinks, figuring out the hard parts, etc. Time invested in documentation is equivalent whether it's done now or later. But if the kinks have been worked out already the docs are less likely to have to be rewritten :)

**Comment by MoOx** [comment]
As you wish. Feel free to merge so :)

**Pull request merged**
