### PR TITLE
Use unambiguous terminology for what a linter reports on

### PR DESCRIPTION
**Pull request by ZacharyRSmith**
The current text "The following patterns are considered warnings" is misleading because rules default to throwing errors instead of warnings.  So, this update shows how to set severity to warning.

If this is considered a valuable change, then we should change similar READMEs.

> Which issue, if any, is this issue related to?

e.g. "#000" or "None, as it's a documentation fix."

> Is there anything in the PR that needs further explanation?

e.g. "No, it's self explanatory."

### CODE REVIEW

**Comment by jeddy3** [comment]
> is misleading because rules default to throwing errors instead of warnings. 

"The following patterns are (not) considered warnings:" is a standardised string that appears before all examples.

We use "warning(s)" throughout the documentation as a generic word to describe when the linter finds something it doesn't like.

The choice of terminology predates the introduction of severities into stylelint. I can see how it can be confusing now that we have severities.

> If this is considered a valuable change, then we should change similar READMEs.

Thanks for the offer :) Perhaps we can replace the word "warning" with something generic to "errors" and "warnings", e.g. "infraction" or "violation".  Do you think this would be clearer? This approach also takes into account the [`defaultSeverity` configuration option](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#defaultseverity) i.e. it's not just a rules' `"severity"` secondary option that determines if a rule will warn or error.

**Comment by ZacharyRSmith** [comment]
Ah, I did not know about the defaultSeverity opt.  Thanks for pointing it out!

Yes, I think "violation" would be clearer.

**Comment by jeddy3** [comment]
> Yes, I think "violation" would be clearer.

Cool.

@stylelint/core, any objections to changing "warning(s)" to "violation(s)" and "warn" to "complain" (which we [already use in a few places](https://github.com/stylelint/stylelint/search?utf8=%E2%9C%93&q=complains&type=))?

**Comment by evilebottnawi** [comment]
@jeddy3 sounds good

**Comment by davidtheclark** [comment]
@jeddy3: I like those word-replacements.

**Comment by jeddy3** [comment]
> "warning(s)" to "violation(s)" and "warn" to "complain" 

@ZacharyRSmith Would you like to make those changes, across the board, in this PR?

**Comment by ZacharyRSmith** [comment]
@jeddy3 I made those changes for lib/rules/*.md

**Comment by ZacharyRSmith** [comment]
eh i'll check on the failing build

**Comment by ZacharyRSmith** [comment]
i just double-checked, and my changes are not related to the fail.  i need to bounce, sorry i can't fix it

**Comment by hudochenkov** [comment]
@ZacharyRSmith thank you for your work! Indeed build fails not because of your changes. Don't worry.

**Comment by jeddy3** [comment]
FYI, PR to update stylelint.io in prep for this change is at https://github.com/stylelint/stylelint.io/pull/36

**Pull request merged**
