### PR TITLE
Allow for both primary and secondary options

### PR DESCRIPTION
**Pull request by davidtheclark**
@jeddy3 I found a minute to try taking care of this. I think this does what we want. If you start building a rule with secondary options give it a shot and let me know if it doesn't :)

### CODE REVIEW

**Comment by jeddy3** [comment]
Thanks! :)

I'll push a rule to this branch.

**Comment by jeddy3** [comment]
Maybe it's just my terribly written conditional first time around, but the expect=reverse and optional object approach seems to simplify the logic of the rule some what :)

One thing... is there a nicer way to do check the `ignore` and `expect` options than doing?:

```js
if (options === Object(options)) {
  if ("except" in options && options.except.indexOf("blockless-group") !== -1) {
    if (isInBlocklessGroup(atRule)) { }
  }
}
```

**Comment by davidtheclark** [comment]
How about

```js
if (options && options.except && options.except.indexOf("blockless-group") !== -1) { .. }
```

??

We could write a `hasExcept()` function at some point that could handle that second two parts, so

```js
if (options && options.hasExcept('blockless-group')) { .. }
```

And then the same for ignore.

What do you think?

**Comment by jeddy3** [comment]
> We could write a hasExcept() function at some point that could handle that second two parts, so

Sweet. That's the one I was thinking of :)

**Comment by davidtheclark** [comment]
@jeddy3 I just made a commit that added `optionsHaveException()` and `optionsHaveIgnored()` utils and used applied them to `at-rule-empty-line-before`. Have a look and maybe apply it to your other work?

**Comment by jeddy3** [comment]
Sweet. Thanks for this!

**Comment by jeddy3** [comment]
I had a change of heart about the ignore functionality. I'm not sure we should be adding that functionality *by default*. Instead, I think we should only add it if it's ever requested.

I started adding the ignore functionality to the `indentation` rule but it seemed, arguably, to unnecessarily increase the workload (more conditionals, more tests etc...).

I also think some of the ignore stuff should be implicit (although documented in the rule README.md, like I've done). For example, it makes sense to me that `comment-empty-line-before` implicitly ignores inline comments. Likewise, all the `*-empty-line-before` rules implicity ignore the very first node in stylesheet.

I think the exception stuff is more powerful (you are *checking* the reverse, rather than just ignoring) so I have coded that up.

There might be a case for the `ignore` stuff in some upcoming rules though.

Whatcha think? Ok to merge this in?

**Comment by davidtheclark** [comment]
I agree that we should only add ignore functionality as requested. I didn't know you were going to systematically apply it to everything, I guess. I'm glad you caught yourself before that.

If I understand right, then, you are going to change all of our `-except-` keywords to `except` options in a secondary options object (third item in a rule's settings array). We will build `ignore` options as needed. Is that accurate?

I have a request myself :) --- which is that for `rule-empty-line-before` I can `ignore` `after-comment`, so that in my CSS I could have either:

```css
/* comment */

a {
  color: pink;
}
```

Or

```css
/* comment */
a {
  color: pink;
}
```

I'll file a separate issue for that.

**Comment by jeddy3** [comment]
> If I understand right, then, you are going to change all of our -except- keywords to except options in a secondary options object (third item in a rule's settings array). We will build ignore options as needed. Is that accurate?

That's exactly right.

> I have a request myself :) --- which is that for rule-empty-line-before I can ignore after-comment, so that in my CSS I could have either:

Ha, fair enough.. that sounds legit :)

> I'll file a separate issue for that.

Sweet. I'll tackle tackle it later.

So, good to merge?

**Comment by davidtheclark** [comment]
Sure

**Pull request merged**
