### PR TITLE
Fix `selector-type-case` end positions and refactor to use `fix` callback instead of `context.fix`

### PR DESCRIPTION
**Pull request by Mouvedia**
> Which issue, if any, is this issue related to?

#2643, #5694

> Is there anything in the PR that needs further explanation?

N/A

### CODE REVIEW

**Review by ybiquitous — APPROVED** [review]
Thanks, LGTM 👍🏼

**Comment by Mouvedia** [comment]
@ybiquitous what's the objective concerning the release which will have the documentation update?
i.e. should the refactors be scattered between several releases ?

I can't really do all the refactors myself.
If we were to split the work between the maintainers we could probably aim for the next release.
That's roughly 8 rules per person if I only count you and @romainmenke.

**Comment by ybiquitous** [comment]
@Mouvedia I recommend creating a new umbrella issue to list all the rules to be refactored. This issue would be helpful for contributors other than the three of us.

Also, I think it's not a problem to release the refactors gradually.

**Comment by Mouvedia** [comment]
> @Mouvedia I recommend creating a new umbrella issue to list all the rules to be refactored. This issue would be helpful for contributors other than the three of us.

Do you want me to remove the task list from #2643?
 
> Also, I think it's not a problem to release the refactors gradually.

👍

**Comment by ybiquitous** [comment]
> Do you want me to remove the task list from #2643?

Ah, sorry. #2643 is enough. Let's use the issue. 👍🏼 

It might be nice to add the "good first issue" label to attract the attention of many contributors.

**Comment by Mouvedia** [comment]
> It might be nice to add the "good first issue" label to attract the attention of many contributors.

Ill do that once we have done one clean PR; to use as a reference.
Right now I concentrate on tricky ones or more challenging ones for that very reasons.
i.e. I leave the easy ones last so that they can be picked-up by newcomers

**Comment by ybiquitous** [comment]
Sounds good. It's up to you. 👍🏼

**Pull request merged**
