### PR TITLE
Fix ESLint `no-shadow` violations

### LINKED ISSUE #5013: Refactor to address suppressed ESLint no-shadow violations
Ref: https://github.com/stylelint/stylelint/issues/4985

Our remained task is to fix all `// TODO: Issue #4985`, for example:

https://github.com/stylelint/stylelint/blob/6ad94ac7253a01c31b69c1a183eeb9d4daa5f104/lib/assignDisabledRanges.js#L110-L112

### PR DESCRIPTION
**Pull request by ybiquitous**
This change closes #5013 by fixing all the ESLint `no-shadow` rule violations.

> Which issue, if any, is this issue related to?

Closes #5013

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

### CODE REVIEW

**Review by mattxwang — APPROVED** [review]
Gave it a medium-thoroughness read through and this looks quite solid! Slightly relying on tests passing as well, but it seems like everything is in order. More than happy to retract the approval if needed!

I'm curious, did you do all of these by hand, or did you use some sort of automated tool? I was resolving some of these other violations in other stylelint repos (and personal projects) and it's definitely a bit of a grind.

Thanks for your work on this 🚀

**Comment by ybiquitous** [comment]
@mattxwang Thank you so much for the review! This PR may be a little too big, but I thought to resolve `no-shadow` violations anyway. 😅 

> I'm curious, did you do all of these by hand, or did you use some sort of automated tool?

Unfortunately, the answer is "no". It would be nice if such a tool would exist!

If anyone feel this PR is too big, I can also split this to multiple PRs.

**Review by jeddy3 — APPROVED** [review]
Thank you for working through all these!

LGTM.

**Comment by ybiquitous** [comment]
Thanks a lot for reviewing so many diffs! 😊 👌

**Pull request merged**
