### PR TITLE
Remove explicit gray color and use dim instead

### LINKED ISSUE #1996: Use dim instead of gray in formatters for compatibility with color chaining
When using iterm2 solarized theme, string formatter is displaying line number so light we can barely see it.

Currently, it uses `chalk.gray`, but I think that `chalk.dim.white` would be better. What do you think?

screenshot

### PR DESCRIPTION
**Pull request by kriansa**
Closes #1996

### CODE REVIEW

**Comment by jeddy3** [comment]
@kriansa Thanks for another contribution!

I believe `gray` is used a couple of times in the [`verboseFormatter`](https://github.com/stylelint/stylelint/blob/master/src/formatters/verboseFormatter.js) as well. Can you please, for the sake of consistency, update those to use `dim` too?

**Comment by kriansa** [comment]
Done. Could you review it?

**Comment by davidtheclark** [comment]
👍 from me

**Comment by evilebottnawi** [comment]
@kriansa squash your commit in one for best commit history, thanks

**Comment by jeddy3** [comment]
> squash your commit in one for best commit history, thanks

We can do this ourselves via github's "squash and merge" feature :)

**Comment by jeddy3** [comment]
@kriansa Thanks! LGTM i.e. exactly the same in iTerm2's default color scheme :)

**Comment by jeddy3** [comment]
> -   Fixed: the `string` and `verbose` formatters now use `dim` instead of `gray` for greater compatibility with different terminal color schemes.

**Pull request merged**
