### PR TITLE
Fix inconsistent behaviour for escaped characters in selector-class-pattern

### PR DESCRIPTION
**Pull request by davidtheclark**
Ref #2263.

cc @hudochenkov

### CODE REVIEW

**Comment by hudochenkov** [comment]
@evilebottnawi feel free to jump on it :)

**Comment by hudochenkov** [comment]
I have a feeling that there is nothing we can do code-wise. I think amount of developers who uses this rule and writes escaped selectors is pretty small. We can add a note in docs that escaped selectors (`.u-size-11\/12\@sm`) parsed as escaped one more time (`.u-size-11\\/12\\@sm`), so RegExp should account for that.

**Comment by davidtheclark** [comment]
@hudochenkov: Your plan sounds good to me!

**Comment by jeddy3** [comment]
Let's update the docs in this PR and close the issue.

**Comment by jeddy3** [comment]
@hudochenkov Updated docs.

**Pull request merged**
