### PR TITLE
Close issue 1101.

### PR DESCRIPTION
**Pull request by evilebottnawi**
/cc @davidtheclark @jeddy3

### CODE REVIEW

**Comment by davidtheclark** [comment]
Looks great. Awesome work, @evilebottnawi, building up these utils. 

Only thing I can see the PR needing is a CHANGELOG entry.

**Comment by jeddy3** [comment]
> Looks great. Awesome work, @evilebottnawi, building up these utils.

Agreed. This was excellent work @evilebottnawi !

**Comment by davidtheclark** [comment]
LGTM

**Comment by jeddy3** [comment]
Good stuff.

Lets wait for green lights for completeness and then I'll merge this in with a custom commit message.

**Comment by ntwb** [comment]
> ...then I'll merge this in with a custom commit message.

Missed out on updating the commit message here, `Close issue 1101` is meaningless 😞 

cc @stylelint/core ^^

**Comment by jeddy3** [comment]
Yep, it was merged before I could fix it.

Can we try to use meaningful commit messages going forward i.e. describe what the commit does, rather than solely what issue it closes.

**Comment by davidtheclark** [comment]
Ok. I haven't been reviewing commit messages routinely but can start.

**Pull request merged**
