### PR TITLE
ES6-style rule imports. Closes #154

### LINKED ISSUE #154: Rules import/export approach
As per https://github.com/stylelint/stylelint/commit/c9befe50e54f95a56891366a6f72c30beecbfbad

Currently uses `.default` syntax, but should use ES6 imports.

```js
import declarationNoImportant from "./declaration-no-important"

export default {
  "declaration-no-important": declarationNoImportant,
}
```

### PR DESCRIPTION
**Pull request by jeddy3**
@stylelint/owners Is this the correct syntax?

### CODE REVIEW

**Comment by davidtheclark** [comment]
Looks good to me. Does it work when you try this as a postcss plugin?

**Comment by jeddy3** [comment]
Yeap :) I tested it before I made the pull request.

**Comment by davidtheclark** [comment]
Then looks great. Merge away I say.

**Comment by MoOx** [comment]
:+1:

**Pull request merged**
