### PR TITLE
Support overlapping disabled ranges; closes #840

### LINKED ISSUE #840: Allow overlapping stylelint-disable ranges
Currently it is not possible to use `stylelint-disable` comments with nested selectors. That limits the usage of the feature in cases where you are using nesting and want to disable certain rules inside the nested selectors.

After adding support for `stylelint-disable` and nesting, this should be possible:

```scss
/* stylelint-disable any-rule */
.foo {
  /* stylelint-disable selector-no-id */
  .bar,
  #bar {
  /* stylelint-enable selector-no-id */
   color: black;
  }
}
```

### PR DESCRIPTION
**Pull request by davidtheclark**
Interesting, tricky one here. Any additional help with integration and regression testing would be much appreciated.

### CODE REVIEW

**Comment by kristerkari** [comment]
I can try to run this against my project and see if it works correctly.

**Comment by kristerkari** [comment]
I ran these changes against my project and it fixes the problem that I had with #840.

**Comment by davidtheclark** [comment]
Excellent.

**Comment by kristerkari** [comment]
It also correctly throws `"selector-no-id" has not been disabled` if I remove `/* stylelint-disable selector-no-id */` but leave the `/* stylelint-enable selector-no-id */` that comes after it.

**Comment by davidtheclark** [comment]
@ntwb Did you accidentally add the "needs revision" label? Or was there something you wanted revised on this PR?

**Comment by jeddy3** [comment]
Shall we get this merged? I think that label was added by accident.

**Comment by davidtheclark** [comment]
I think it's good to go.

**Comment by jeddy3** [comment]
Groovy. Do you want to merge in #872 and #873 before doing a rebase, otherwise I think we'll run into some changelog clashes again?

Feel free to release `4.6.0` afterward merging those and this PR in. I'm calling it a night now :)

**Comment by ntwb** [comment]
> @ntwb Did you accidentally add the "needs revision" label? Or was there something you wanted revised on this PR?

This was deliberate.

What was not deliberate was my not adding a comment about the merge conflict via https://github.com/stylelint/stylelint/commit/23da4af16344439d039fcc66aa569d35a021af3a, sorry.

**Pull request merged**
