### PR TITLE
Ignore scss maps within function-* rules

### LINKED ISSUE #983: Ignore scss maps within function-* rules
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Bug (?): Sass Maps are throwing errors due to rules targeted for functions.

> Which rule, if any, is this issue related to?

`function-*` type rules

> What SCSS is needed to reproduce this issue?

e.g.

```scss
$media-expressions: (
    res2x: ('(min-resolution: 2dppx)'),
    res3x: ('(min-resolution: 3dppx)'),
);
```

> What stylelint configuration is needed to reproduce this issue?

e.g.

```json
{
  "rules": {
        "function-calc-no-unspaced-operator": true,
        "function-comma-newline-after": "always-multi-line",
        "function-comma-newline-before": "never-multi-line",
        "function-comma-space-after": "always",
        "function-comma-space-before": "never",
        "function-parentheses-newline-inside": "never-multi-line",
        "function-parentheses-space-inside": "never-single-line",
        "function-url-quotes": "single",
        "function-whitespace-after": "always",
  }
}
```

> Which version of stylelint are you using?

e.g. `5.2.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

PostCSS with stylelint plugin.

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Yes, it's related to SCSS maps.

> What did you expect to happen?

No warnings to be flagged.

> What actually happened (e.g. what warnings or errors you are getting)?

The following warnings were flagged:

```shell
_test.scss
1:22	⚠  Unexpected whitespace after "(" in a multi-line function (function-parentheses-newline-inside) [stylelint]
2:39	⚠  Expected single space after "," (function-comma-space-after) [stylelint]
2:40	⚠  Unexpected whitespace before ")" in a multi-line function (function-parentheses-newline-inside) [stylelint]
```

### PR DESCRIPTION
**Pull request by Nirazul**
Closes #983

### CODE REVIEW

**Comment by jeddy3** [comment]
Thanks @Nirazul ! 

This looks excellent and every one of the new tests looks ideal to me. Thanks for taking the time to tweak each of the tests to account for the subtle differences between the `*-space-*` and `*-newline-*` rules and for the subtle differences between different primary options.

I'll let @davidtheclark give it a second look over and he'll merge it if he's happy with it.

**Comment by davidtheclark** [comment]
Looks good, thanks.

**Comment by Nirazul** [comment]
I've forgotten to update the changelog. Will you guys do it?

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint/commit/8f5210d8a04a686b1e7d4edac0be3682aca640d9

Thanks again for patching up these rules :)

**Comment by Nirazul** [comment]
You're welcome :)

**Pull request merged**
