### PR TITLE
8.0.0

### PR DESCRIPTION
**Pull request by jeddy3**
Merge `v8` into `master`.

Once this is merged I'll do the following in order:

1. Create a new PR that pretty-prints the code.
2. Release a major version of [`eslint-config-stylelint`](https://github.com/stylelint/eslint-config-stylelint).
3. Create a new PR that uses that release and updates eslint.
4. Merge https://github.com/stylelint/stylelint/pull/2706 for automatic pretty-printing going forward.

We should then all try `master` against our code bases.

Then we release `8.0.0`! 

Ref: https://github.com/stylelint/stylelint/issues/2575

### CODE REVIEW

**Comment by hudochenkov** [comment]
@jeddy3 Would you mind fixing changelog order, please?

**Comment by jeddy3** [comment]
> @jeddy3 Would you mind fixing changelog order, please?

Done

**Comment by jeddy3** [comment]
Actually, I need to tweak again...

**Comment by ntwb** [comment]
One concern, the proposed task list:

> 1. Create a new PR that pretty-prints the code.
> 2. Release a major version of [`eslint-config-stylelint`](https://github.com/stylelint/eslint-config-stylelint).
> 3. Create a new PR that uses that release and updates eslint.
> 4. Merge https://github.com/stylelint/stylelint/pull/2706 for automatic pretty-printing going forward.

Should that be in _this_ order:

1. Release a major version of [`eslint-config-stylelint`](https://github.com/stylelint/eslint-config-stylelint).
2. Create a new PR that uses that release and updates eslint.
3. Create a new PR that pretty-prints the code.
4. Merge https://github.com/stylelint/stylelint/pull/2706 for automatic pretty-printing going forward.

The new eslint config changes should be committed before pretty printing the code should it not?

Or doesn't it matter? (I think I'm confusing myself of the workflow in my head)

**Comment by jeddy3** [comment]
> The new eslint config changes should be committed before pretty printing the code should it not?

You're right :)

**Comment by ntwb** [comment]
SGTM 👍 

(I'll be back around in ~30 mins, relocating from co-work space to home)

**Comment by jeddy3** [comment]
I think we're ready to merge this into `master` on green.

**Comment by ntwb** [comment]
Woot 💥

**Pull request merged**
