### PR TITLE
Fix false positives for variables and color functions in color-function-notation

### LINKED ISSUE #5671: Fix false positives for variables and color functions in `color-function-notation`
> Clearly describe the bug

A follow-up from #5638, where the original issue was fixed correctly in my tests but more advanced scenarios still result in false positives, e.g. when using Sass' `color.mix` within `rgba()`.

> Which rule, if any, is the bug related to?

`color-function-notation`

> What code is needed to reproduce the bug?

```scss
@use 'sass:color';

$color: rgba(color.mix(#000, #fff, 35%), 0.6);
```

> What Stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "color-function-notation": "modern"
  }
}
```

> Which version of Stylelint are you using?

`14.0.1` as well as `main` from commit e2c3473.

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

```
stylelint \"src/**/*.scss\"
```

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, SCSS color functions

> What did you expect to happen?

No errors

> What actually happened (e.g. what warnings or errors did you get)?

```shell
 25:27  ✖  Expected legacy color-function notation  color-function-notation
```

### PR DESCRIPTION
**Pull request by lachieh**
Fixes #5671

### CODE REVIEW

**Comment by lachieh** [comment]
Question here for maintainers. The rules that are failing now from the scss syntax section:   
https://github.com/stylelint/stylelint/blob/d630d96ae75a8f983db310ad086ed6872149048f/lib/rules/color-function-notation/__tests__/index.js#L407-L413
https://github.com/stylelint/stylelint/blob/d630d96ae75a8f983db310ad086ed6872149048f/lib/rules/color-function-notation/__tests__/index.js#L441-L446

Are these rules valid tests cases here? Should this be something that is handled by [stylelint-scss](https://github.com/stylelint-scss/stylelint-scss)? It seems like part of the problem is that the contents of the variable is what needs to be checked first and that's not a responsibility of stylelint.

**Comment by jeddy3** [comment]
Thanks for the pull request!

> Are these rules valid tests cases here?

Nope. Those should be accepted now, rather than rejected. 

> Should this be something that is handled by stylelint-scss?

Yes, exactly.

**Comment by lachieh** [comment]
Looking closer at theses tests, is the scss section necessary at all or should I merge those test cases with the main syntax rules?

**Comment by jeddy3** [comment]
> Looking closer at theses tests, is the scss section necessary at all or should I merge those test cases with the main syntax rules?

They should be in a separate `testRule` (that uses the `postcss-scss` syntax) so that we signal that we're testing non-standard constructs (which, in this case, are dollar variables - both defined and used).  It helps us maintain the line between CSS and non-standard stuff more clearly.

**Comment by lachieh** [comment]
Got it, thanks. This one is ready for review now.

**Review by ybiquitous — COMMENTED** [review]
@lachieh Thank you for creating this pull request!

It would seem better to me if you could add some test cases to `isStandardSyntaxColorFunction.test.js`.

**Comment by lachieh** [comment]
@ybiquitous Thanks, added some test cases. Let me know if it needs any more.

**Review by ybiquitous — APPROVED** [review]
@lachieh Thank you! LGTM 👍🏼

**Review by jeddy3 — APPROVED** [review]
LGTM, thank you!

**Comment by ybiquitous** [comment]
@jeddy3 Will you update the changelog?

**Comment by jeddy3** [comment]
Whoops, good catch. Thanks @ybiquitous !

Added now:

> - Fixed: `color-function-notation` false positives for variables and color functions ([#5793](https://github.com/stylelint/stylelint/pull/5793))

**Pull request merged**
