### PR TITLE
Create and test block-opening-brace-space

### PR DESCRIPTION
**Pull request by davidtheclark**
One half of the refactor for https://github.com/stylelint/stylelint/issues/47 (other half will be `-newline` rule).

I made an important change to the test framework. I've found after writing a bunch of these rules now that one of the most time-consuming parts is writing descriptions for the tests. From my perspective, printing the CSS is sufficient, and that makes the tests much faster to write. I understand @MoOx that the descriptions do serve some purpose; but I couldn't stand to write them again :) So I refactored the ruleTester so that descriptions are optional, changed existing tests accordingly, and did not include descriptions in tests for this new rule. If we feel the need to add descriptions later we can do that later. I don't want it to discourage me from writing more code, thinking that I'll have to do all those descriptions.

Are you okay with that?

### CODE REVIEW

**Comment by MoOx** [comment]
let say i am ok :)
Don't have too much to say since I didn't write any rule :)

**Comment by davidtheclark** [comment]
Cool. Functionality is still there to create the extended descriptions --- it's just secondary.

**Comment by jeddy3** [comment]
SGTM! Those descriptions were sucking my time for easily understood css code.

**Comment by jeddy3** [comment]
I'll need to shift around the parameters in the `declaration-no-important` and `declaration-colon-space` tests won't I?

**Comment by davidtheclark** [comment]
Anything that wasn't in there when I just committed will need the change, yea. Just get latest master and see if anything needs adjusting.

**Comment by jeddy3** [comment]
Shall I add it to this PR?

**Comment by davidtheclark** [comment]
Add to it or merge this and then make the corrections -- either way fine by me.

**Comment by jeddy3** [comment]
Pushing to this PR now :)

**Comment by jeddy3** [comment]
Done. Gotta love multiple cursors :)

Merging into master.

**Comment by MoOx** [comment]
Remember to delete branch when you merge PR ;)

**Comment by jeddy3** [comment]
Oops, will do :)

**Pull request merged**
