### PR TITLE
docs: Add "New Release Issue Template" to releases.md

### PR DESCRIPTION
**Pull request by ntwb**
FYI: I'm not sure I got the #anchor format correct for `template-checklist`, it's hard getting the correct link in a not yet deployed change 😏

### CODE REVIEW

**Comment by ntwb** [comment]
p.s. Reviewing this PR in [_markdown diff view_](https://github.com/stylelint/stylelint/pull/2728/files?short_path=500d18f#diff-500d18f84d682aae104d171bb1976264) is much simpler 😄

**Comment by ntwb** [comment]
I think my questionable link should probably be:
• `docs/developer-guide/releases.md#new-release-issue-template`

**Comment by ntwb** [comment]
I'm trying to debug we the Node.js 8.x Travis CI job has failed now...

Initial thoughts are a new _minor_ or _patch_ semantic version of a dependency has been updated

**Comment by jeddy3** [comment]
> I think my questionable link should probably be `docs/developer-guide/releases.md#new-release-issue-template`

Links are relative, so what you have at the moment `#new-release-issue-template` should work well.

Links are [also checked](https://github.com/stylelint/stylelint/blob/master/package.json#L160) by remark, so we know it's right.

Rebase of `v8` to get the CHANGELOG lint fixes.

**Comment by ntwb** [comment]
> Rebase of v8 to get the CHANGELOG lint fixes.
There's nothing to rebase from v8 (I think) 🤔 

> The 8.x stuff is quite temperamental...

It is, I'd already planned today to make a bunch of PRs updating the npm version and Travis CI configs to _hopefully_ improve this somewhat.

**Comment by jeddy3** [comment]
I rebased and it's green now. Merging.

**Pull request merged**
