### PR TITLE
chore: clone only last commit

### PR DESCRIPTION
**Pull request by DanielRuf**
This PR uses shallow clones like it is the case for Travis CI.

> Is there anything in the PR that needs further explanation?

"No, it's self explanatory."

### CODE REVIEW

**Comment by hudochenkov** [comment]
Can you provide more description or a link to this feature description, please?

**Comment by DanielRuf** [comment]
> Can you provide more description or a link to this feature description, please?

Sure.

https://www.appveyor.com/blog/2014/06/04/shallow-clone-for-git-repositories/
https://docs.travis-ci.com/user/customizing-the-build#Git-Clone-Depth
https://www.perforce.com/blog/git-beyond-basics-using-shallow-clones

This basically improves the performance of the builds.

**Comment by ntwb** [comment]
As per the Travis CI docs linked above:

> _"Please note that if you use a depth of `1` and have a queue of jobs, Travis CI won’t build commits that are in the queue when you push a new commit."_

@DanielRuf I'm happy for the value to be `10`, but **not** `1`, could you create a follow up pull request for this please

**Comment by DanielRuf** [comment]
> @DanielRuf I'm happy for the value to be 10, but not 1, could you create a follow up pull request for this please

Ok, but then we have to change also the appveyor config or how do you see that?

**Comment by ntwb** [comment]
Let's set both to `10` @DanielRuf 👍

**Comment by DanielRuf** [comment]
> Let's set both to 10 @DanielRuf 👍

Normally I would set 5 but 10 is also ok =)

**Pull request merged**
