### PR TITLE
Use write-file-atomic for writing fixed styles to filesystem

### LINKED ISSUE #2991: Fix invalid command line parameter with --fix destroys all styles
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Bug, probably caused by incorrect interaction between the arg parser and autofix

> Which rule, if any, is this issue related to?

None

> What CSS is needed to reproduce this issue?

I have a repo here: https://github.com/ZhangYiJiang/stylelint-autofix-cli-bug

> What stylelint configuration is needed to reproduce this issue?

`stylelint-config-standard` is used, although I do not think it is relevant. 

> Which version of stylelint are you using?

8.2.0 (Latest from npm)

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI - `stylelint src/*.css --fix src/` (notice the extraneous incorrect parameter `src/`) 

For a more realistic setup (which is how I discovered this bug), a user would add `stylelint src/*.css` to their `package.json`'s script section as a shortcut which they can run using `yarn lint` (or `npm run lint`, although this bug doesn't seem to repro with npm, maybe due to how npm handles parameters). If they then try to run `--fix` and accidentally add an incorrect parameter, the bug is triggered. 

``` shell 
$ cat src/app.css 
#app {
  background: orange;
}

$ yarn lint --fix src/
yarn run v1.2.1
$ stylelint 'src/*.css' --fix src/
Error: EISDIR: illegal operation on a directory, read
    at Error (native)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

$ git diff 
diff --git a/src/app.css b/src/app.css
index 52950c1..e69de29 100644
--- a/src/app.css
+++ b/src/app.css
@@ -1,3 +0,0 @@
-#app {
-  background: orange;
-}
``` 

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

> What did you expect to happen?

Error about invalid command line options 

> What actually happened (e.g. what warnings or errors you are getting)?

Error about invalid command line options, *and* all linted styles are destroyed

### PR DESCRIPTION
**Pull request by ZhangYiJiang**
> Which issue, if any, is this issue related to?

Fixes #2991 

> Is there anything in the PR that needs further explanation?

This makes writing back the linted results when `--fix` is used atomic - previously if the operation was cancelled or crashed while the styles were been written, the sources could be left in an inconsistent state. 

The correct way to write file is to write it to a temp file first, then replace the original. As it turns out the nice folks at npm has written a package to do just that, and hey, if it's good enough for npm then it's probably good enough for Stylelint :wink:

### CODE REVIEW

**Comment by ZhangYiJiang** [comment]
>  if it's good enough for npm then it's probably good enough for Stylelint :wink:

Huh, looks I spoke too soon - this small change causes Stylelint to use a *lot* more memory than before, at least when running tests. On my laptop master uses ~450MB, while on this branch it ballooned to 1.4GB then crashed with an out of memory error :scream: I'm not entirely sure what is happening here, so I'll try to dig deeper.

**Comment by ZhangYiJiang** [comment]
So... erm, it seems that the culprit is `graceful-fs`, which is a transitive dependency of `atomic-write-file` - in fact this has actually came up before - https://github.com/facebook/jest/issues/2179#issuecomment-265448617 and https://github.com/stylelint/stylelint/issues/2168 

I guess we *could* fork `write-atomic-file` and simply replace `require('graceful-fs')` with `require('fs')`...

**Comment by ZhangYiJiang** [comment]
Okay, yes, I can verify that a simple `/s/graceful-fs/fs/g` on `write-file-atomic/index.js` works. It does mean keeping a fork of the `write-file-atomic` package, which is, well, not ideal, but it works. The tests still leak a bit of memory, but at least they finish running without crashing. 

Using the [`tmp`](https://www.npmjs.com/package/tmp) module causes the same memory leak - see https://github.com/raszi/node-tmp/issues/129 - this is what happens when I try to use that lib: 

```
 PASS  system-tests/001/001.test.js (52 MB heap size)
 PASS  system-tests/004/004.test.js (62 MB heap size)
 PASS  lib/rules/at-rule-empty-line-before/__tests__/index.js (84 MB heap size)
 PASS  lib/rules/selector-no-qualifying-type/__tests__/index.js (106 MB heap size)
 PASS  lib/rules/value-keyword-case/__tests__/index.js (128 MB heap size)
 PASS  system-tests/005/005.test.js (140 MB heap size)
 PASS  lib/rules/selector-max-empty-lines/__tests__/index.js (162 MB heap size)
 PASS  lib/rules/selector-attribute-operator-space-before/__tests__/index.js (179 MB heap size)
 PASS  lib/rules/selector-attribute-operator-space-after/__tests__/index.js (195 MB heap size)
 PASS  lib/rules/declaration-empty-line-before/__tests__/index.js (210 MB heap size)
(node:15714) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
 PASS  lib/rules/color-named/__tests__/index.js (222 MB heap size)
 PASS  lib/rules/rule-empty-line-before/__tests__/index.js (236 MB heap size)
 PASS  lib/rules/selector-attribute-brackets-space-inside/__tests__/index.js (249 MB heap size)
 PASS  lib/rules/selector-pseudo-class-case/__tests__/index.js (263 MB heap size)
 PASS  lib/rules/custom-property-empty-line-before/__tests__/index.js (276 MB heap size)
 PASS  lib/rules/selector-class-pattern/__tests__/index.js (289 MB heap size)
 PASS  lib/rules/indentation/__tests__/rules.js (301 MB heap size)
 PASS  lib/rules/property-case/__tests__/index.js (315 MB heap size)
 PASS  lib/rules/function-url-quotes/__tests__/index.js (329 MB heap size)
 PASS  lib/__tests__/standalone-syntax.test.js (343 MB heap size)
 PASS  lib/rules/unit-case/__tests__/index.js (356 MB heap size)
 PASS  lib/rules/comment-empty-line-before/__tests__/index.js (369 MB heap size)
 PASS  lib/rules/selector-list-comma-space-before/__tests__/index.js (380 MB heap size)
 PASS  lib/rules/no-extra-semicolons/__tests__/index.js (393 MB heap size)
 PASS  lib/rules/selector-attribute-quotes/__tests__/index.js (404 MB heap size)
 PASS  lib/rules/shorthand-property-no-redundant-values/__tests__/index.js (416 MB heap size)
 PASS  lib/rules/selector-pseudo-element-case/__tests__/index.js (429 MB heap size)
 PASS  lib/rules/media-feature-name-case/__tests__/index.js (442 MB heap size)
 PASS  lib/__tests__/processors.test.js (452 MB heap size)
 PASS  lib/__tests__/ignore.test.js (464 MB heap size)
 PASS  lib/rules/selector-max-specificity/__tests__/index.js (477 MB heap size)
 PASS  lib/rules/block-closing-brace-space-after/__tests__/index.js (489 MB heap size)
```

**Comment by jeddy3** [comment]
> Huh, looks I spoke too soon - this small change causes Stylelint to use a lot more memory than before, at least when running tests.

FYI, we had a memory leak with `graceful-fs` [before](https://github.com/stylelint/stylelint/issues/2168). Forking `write-atomic-file` might be our only option.

**Comment by ZhangYiJiang** [comment]
@jeddy3 I believe this PR is ready for review

**Comment by ntwb** [comment]
Linking to https://github.com/isaacs/node-graceful-fs/issues/102 for if/when the issue is resolved

**Comment by ntwb** [comment]
Going to merge this in the hope it will fix the _out of memory_ testing issues in #3069

**Comment by ntwb** [comment]
Once again, thanks @ZhangYiJiang, sorry it took us so long to merge 😄

**Pull request merged**
