### PR TITLE
Create reference dir; closes #1071

### LINKED ISSUE #1071: Put lists of keywords in a single place
Scattered throughout the rules are lists of keywords. Units, properties, values, etc. I was thinking it might be a good idea to pull these out and put them in one place. A `keywordLists` directory or something. And we make them maximally reusable. 

I just want to avoid the situation where a list gets updated in one place and should have been but wasn't updated in another.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/32990212-put-lists-of-keywords-in-a-single-place?utm_campaign=plugin&utm_content=tracker%2F9282518&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F9282518&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by davidtheclark**
What do you think @stylelint/core?

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@davidtheclark LGTM, but i think we should tested this array

**Comment by davidtheclark** [comment]
> i think we should tested this array

What does that mean?

**Comment by evilebottnawi** [comment]
@davidtheclark create tests
```js
test("isKnownUnitSets", t => {
  // Login for testing array `knownUnits`
})
```
and etc

**Comment by davidtheclark** [comment]
I disagree. Because they are just Sets, those tests would be redundant: we can safely assume that the Set is going to contain whatever we put in it, and that its native methods will work. That's one of the advantages of having simple Sets!

**Comment by evilebottnawi** [comment]
@davidtheclark good,  what about yesterday utils `isCustomIdentPropertyAnimationName` and `isCustomIdentPropertyCounterIncrement`, should they be in sets? So I continued to solve issue.

**Comment by davidtheclark** [comment]
Yeah, I think those could be keyword sets, too.

**Comment by evilebottnawi** [comment]
@davidtheclark be cool if you did this in this PR.

**Comment by davidtheclark** [comment]
Yes, doing now.

**Comment by evilebottnawi** [comment]
@davidtheclark wait merge, after continue work on issue in `value-keyword-case`.

**Comment by evilebottnawi** [comment]
@davidtheclark I'm sorry for importunity, but i wait, i have time to work on this issue ;)

**Comment by jeddy3** [comment]
This is a great initiative!  LGTM. 

@evilebottnawi Is there more to do here? Or can we rebase and merge?

**Comment by evilebottnawi** [comment]
@jeddy3 yep

**Comment by jeddy3** [comment]
> @jeddy3 yep

Is there more to do? *Or* can we rebase and merge? :)

**Comment by evilebottnawi** [comment]
@jeddy3 rebase and merge, after i continue work on this issue

**Comment by davidtheclark** [comment]
Rebsaed. Let's merge on green light.

**Comment by ntwb** [comment]
Sweet 👍

**Comment by evilebottnawi** [comment]
CI green. Merge.

**Pull request merged**
