### PR TITLE
Move pify from devDependencies to dependencies

### PR DESCRIPTION
**Pull request by m-allanson**
> Which issue, if any, is this issue related to?

#2607

### CODE REVIEW

**Comment by m-allanson** [comment]
@hudochenkov Maybe this will work? I haven't tested it in all scenarios from your issue

**Comment by hudochenkov** [comment]
Hm... why it's a devDependency if it's regular dependency? https://github.com/stylelint/stylelint/blob/e1700b47d3a284393723d52f3d3786d6bc7eeb4d/lib/standalone.js#L3

I don't think we should remove it, because we need this dependency.

**Comment by jeddy3** [comment]
> I don't think we should remove it, because we need this dependency.

@m-allanson Good spot. It looks like `pify` was accidentally added as a `devDependency`, rather than a `dependency`. This PR moves it into `dependency`.

**Comment by hudochenkov** [comment]
Looks like I was looking in some other place while was writing a comment above. Sorry ¯﻿\﻿_﻿(﻿ツ﻿)﻿_﻿/﻿¯ I'll test this change in a few hours.

**Comment by hudochenkov** [comment]
I believe we shouldn't add anything to chagelog? Or should we? This problem was introduced in `7.10.0` in this [commit](https://github.com/stylelint/stylelint/blob/43b18fe4c56e9f177644b50354fb8efe9fb34a84/package.json#L91). And as I understand it only affects npm@2 users.

**Comment by jeddy3** [comment]
It's a fix of a regression, right? Best add it to the changelog so that it's discoverable if someone runs into the issue when using `7.10.0`

> - Fixed: "Cannot find module 'pify'" regression in node@4 with npm@2.

**Comment by hudochenkov** [comment]
Thanks. Done.

**Pull request merged**
