### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by xdamman**
This pull request adds backers and sponsors from your Open Collective https://opencollective.com/stylelint ❤️
  
  It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [[more info](https://github.com/opencollective/opencollective/wiki/Github-banner)]. See how it looks on [this repo](https://github.com/apex/apex#backers).
We have also added a `postinstall` script to let people know after `npm|yarn install` that you are welcoming donations (optional). [[More info](https://github.com/OpenCollective/opencollective-cli)]
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets

  P.S: As with any pull request, feel free to comment or suggest changes. The only thing "required" are the placeholders on the README because we believe it's important to acknowledge the people in your community that are contributing (financially or with code!).

  Thank you for your great contribution to the open source community. You are awesome! 🙌
  And welcome to the open collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other open source sustainers!

### CODE REVIEW

**Comment by ntwb** [comment]
1. Why would we want to do this?

2. Why should we promote Open Collective?

3. What percentage of monies collected by Open Collective is kept by and for Open Collective and not passed onto the stylelint team?

---- 

What are your thoughts on this @stylelint/core?

Me, myself, I'm conflicted, I do a lot of open source work and don't get paid for any of it and I'm fine with that. 

I don't think open source and money in the way Open Collective work is the answer either, or at least from what I've seen and read thus far. 

For example if we get $5 per month and a team member makes a request for reimbursement that the rest of the team are hesitant to agree to the payout that causes friction within the team, on a larger scale if we're getting $1000 per month deciding on how that money is divided up between the team members and contributors is a nightmare waiting to happen.

For these reasons I like the concept behind Bounty Source over Open Collective, if a company or individual is seeking a feature or fix for stylelint then for the most part the awarding of the bounty is between the whomever put up the cash for the bounty and the contributor who met the requirements of the proposed feature or fix.

**Comment by xdamman** [comment]
Open Collective as a fiscal sponsor takes 10% (classic rate for fiscal sponsorship).
If you bring your own bank account / legal entity, then Open Collective only takes 5% (like any other crowdfunding platform).

The questions that you are raising are good questions.
Here are some blog posts that may answer them:
- Money and Open Source Communities https://medium.com/open-collective/money-and-open-source-communities-64b1c2f6aec4
- Preact: Shattering the Perception that Open Source Must be Free https://medium.com/open-collective/why-and-how-to-fund-the-open-source-projects-you-depend-on-da62a582307

You may also find this one interesting to get some context:
- A New Way to Fund Open Source Projects https://medium.com/open-collective/a-new-way-to-fund-open-source-projects-91a51b1b7aac

It's really up to you whether or not you want to create an open collective for your community. You are absolutely not obliged.

No matter what, keep up the great work!

**Comment by ntwb** [comment]
Thanks for the follow up @xdamman, I'm quite familiar, and probably personally grapple with this issue myself more than I wish I had to but nothing much more to add to what I've already said.

**Comment by jeddy3** [comment]
Thank you for following up on [my request](https://github.com/stylelint/stylelint/issues/2544#issuecomment-312444328) so quickly, and for your time @xdamman.

I might of jumped the gun in requesting stylelint's inclusion in the Open Collective. I respect @ntwb's concerns as he has a wealth of open source experience.  There is clearly more for us to discuss as an open source organisation and group of individuals. 

Thank you for sharing those blog posts. It's a very exciting thing you've created. To me, the posts give the impression that this approach can work, but only if done thoughtfully and with some upfront planning by the collective. Unfortunately, and I'm aware of the irony in this, what little time we have is currently being spent on getting our next major release (`8.0.0`) out the door.

I'd like all contibutors to feel they have the time to weigh into this discussion and share their thoughts on if and how the double-edged sword nature of this is managable for our specific circumstances. As such, in the interim, would it be at all possible to hide the https://opencollective.com/stylelint page, until we've had time to revisit this issue @xdamman?

Many thanks again accepting us into the collective and for taking the time to prepare this PR.

@stylelint/core Feel free to share your thoughts on this. I'm going to be mostly off-line for a month from mid-July, and so there's plenty of time before I'll be able to revisit the discussion myself.

**Comment by xdamman** [comment]
Sure thing. I just deactivated your collective. I understand the concerns. They are not new. But we believe that it is by experimenting and trying that we will learn. That said, this is definitely not for everybody. So no stress! 

But if you feel adventurous and if you are willing to experiment with all this in full transparency so that we can all learn from each other, the door of the [Open Source Collective](https://opencollective.com/opensource) is always open!

Take care!

**Comment by alannallama** [comment]
I completely understand the questions @ntwb is raising, and I definitely agree with @jeddy3 that taking some time to talk it through as a community is the way to go. However, I just want to put out there that if you've got supporters wanting to financially support stylelint, spinning up an Open Collective and letting funds build up while you take time to have those community discussions is actually pretty low risk. Essentially, you'd end up sitting on money you're not sure how to spend - not a bad problem to have! If you ever want to close down the Open Collective or move to another platform, you can just transfer the funds out.

Collectives spend money according to their own needs, cultures, and policies. Some fund specific feature development. Others print stickers and t-shirts. Some pay for pizza at local meetups, or cover costs for people to attend and speak and conferences where they talk about the project. Some fund a person full time to code. Others pay for community moderation and documentation work. I wrote an article with lots of examples: [Has Your Open Source Community Raised Money? Here’s How to Spend It.](https://medium.com/open-collective/has-your-open-source-community-raised-money-heres-how-to-spend-it-3e9dd957dad), which might be of interest.

There absolutely are important concerns like "How will people feel if some contributors are paid and some aren't?" or "How might money affect our culture?" But I believe the benefits of financial resources outweigh the costs of answering these questions as a community, and in fact the process of considering these topics is very healthy, regardless of the answers you arrive at. Handling money together requires another level of collaboration and collective decision-making, but that's a great direction to evolve in. I've helped invent some open source tools to help groups do this effectively, like [Loomio](http://www.loomio.org) and [CoBudget](http://cobudget.co), but the truth is there are as many methods as there are communities because each one is different.

Anyway, that's just my unsolicited two cents! Seems like hitting the brakes is the right thing for you right now, but I'd encourage you to keep talking about it :)

**Comment by ntwb** [comment]
Thanks @alannallama, all great ideas and more food for thought 👍 

I'm quite sure my option would be different, possibly even swayed if we had people lining up to donate money, we don't though, we've had a single bounty of $15 via Bountysource and thats it. I believe the vast majority of open source projects would be in a similar position.

Away from stylelint I'm very active in the WordPress community, both globally, and locally here in Australia and we've had a couple of discussions on the idea of following [WordPress SFO](https://opencollective.com/wordpress-sf) Open Collective model for our ~20 or so local [WordPress Australia Meetups](https://www.meetup.com/topics/wordpress/au/) as a way to pool sponsorship payments to then be distributed as required to each meetup. We already have quite a few sponsors that each month pickup the tab for each meetups venue hire, pizza, drinks etc and we'd love to pool this money for a multitude of reasons.

My point is here that I see Open Collective is great for some things, such as this above, others not so much IMHO at this stage. Monetary payments in the world of Open Source are new, it's also for the most part untested, I'm glad, thankful even that sites such as Bountysource and Open Collective now exist to try and change this, it's a significant change of mindset that @xdamman pointed out above to address the belief that _Open Source must be Free_

Anyway, more to think about, I'm sure I'll continue to add more thoughts on the subject here 😄 

p.s. I'd love to get myself some stylelint swag, t-shirt & stickers would be very cool 😎
_(I'm also happy to pay for that swag myself, though me donating cash back on top of time to stylelint is not really the goal behind all this, if I was getting monetary compensation to contribute to open source directly then sure, I'd happily donate cash back to stylelint myself.)_

**Comment by ntwb** [comment]
Let's do this @asood123 @xdamman 

It's crossed my mind numerous times recently and @hzoo's tweet finally convinced me

• https://twitter.com/left_pad/status/927721908078104576

Let's get this PR updated and/or replaced like #2955 if that's easier.

**Comment by asood123** [comment]
@ntwb Easiest to pick up the other PR, that still looks correct. I'll activate your collective on our system, so you can start raising money.

**Comment by CAYdenberg** [comment]
Closing as dupe in that case. If that's wrong, just reopen.

**Pull request closed without merging**
