### PR TITLE
Fix false negatives on second run for cache and `severity` option

### LINKED ISSUE #4715: Fix false negatives on second run for cache and plugins
> Clearly describe the bug

Stylelint doesn't report warning of plugins on second run if cache activated

> What stylelint configuration is needed to reproduce the bug?

Install:
`npm install stylelint-no-unsupported-browser-features`

And add in .stylelintrc:
```
  "plugins": [
    "stylelint-no-unsupported-browser-features"
  ],
  "rules": {
    "plugin/no-unsupported-browser-features": [true, {
      "severity": "warning"
    }],
```

And active styelint `cache` to `true`

> Which version of stylelint are you using?

13.3.2

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

Node.js API

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No

> What did you expect to happen?

On second run, see the same warning than in the first run

> What actually happened (e.g. what warnings or errors did you get)?

On the second run only warning on files having errors are reported

### PR DESCRIPTION
**Pull request by kimulaco**
> Which issue, if any, is this issue related to?

Closes #4715

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

### CODE REVIEW

**Comment by ybiquitous** [comment]
@kimulaco Thanks for creating the PR.

I am looking into this bug. So, the bug seems related to not plugins but *severity*. See the code below.

If `stylelintError` is `true`, a cache is discarded here: ⬇️ 

https://github.com/stylelint/stylelint/blob/751acda06a0755ddf0a0603013681173c70bf2c3/lib/standalone.js#L219-L222

Then, `stylelintError` is set to `true` here (only if the severity is `error`): ⬇️ 

https://github.com/stylelint/stylelint/blob/751acda06a0755ddf0a0603013681173c70bf2c3/lib/utils/report.js#L79-L81

The following is a production: ⬇️ 

```console
$ cat a.css
a { colo: red; }

$ cat package.json
{
  "dependencies": {
    "stylelint": "14.13.0"
  },
  "stylelint": {
    "rules": {
      "property-no-unknown": [true, { "severity": "warning" }]
    }
  }
}

$ rm -f .stylelintcache

$ npx stylelint *.css --cache -f json | jq -c '.[0].warnings'
[{"line":1,"column":5,"endLine":1,"endColumn":9,"rule":"property-no-unknown","severity":"warning","text":"Unexpected unknown property \"colo\" (property-no-unknown)"}]

$ npx stylelint *.css --cache -f json | jq -c '.[0].warnings'
[]
```

We can see the second run emits no warnings.

On the other hand, the second run emits warnings after changing the severity from `warning` to `error` in the `package.json` file above.

```console
$ npx stylelint *.css --cache -f json | jq -c '.[0].warnings'
[{"line":1,"column":5,"endLine":1,"endColumn":9,"rule":"property-no-unknown","severity":"error","text":"Unexpected unknown property \"colo\" (property-no-unknown)"}]

$ npx stylelint *.css --cache -f json | jq -c '.[0].warnings'
[{"line":1,"column":5,"endLine":1,"endColumn":9,"rule":"property-no-unknown","severity":"error","text":"Unexpected unknown property \"colo\" (property-no-unknown)"}]
```

**Comment by kimulaco** [comment]
@ybiquitous Thanks. I thought I needed to cache the result. But I could understand that it was caused by a condition to remove the cache.
Please give me some time to fix it. 🙏

**Comment by ybiquitous** [comment]
@kimulaco I hope you don't mind. I appreciate your contribution to this project. 😊

**Comment by kimulaco** [comment]
@ybiquitous I fixed. It contains a new approach, so I would like your opinion.

First, I reverted all codes that cache the `postcssResult`. (https://github.com/stylelint/stylelint/pull/6384/commits/aa28b1af1a85acc6123a91b89507b0df66415c15, https://github.com/stylelint/stylelint/pull/6384/commits/db190028f17a2283e1f4d9ac53ea28559dfc1701)

Then, I added `stylelintWarning` to `StylelintPostcssResult`. The cache is discarded also when `stylelintWarning` is `true`.
Because, `stylelintError` is equal to `errored`, so to prevent breaking spec of `errored`. 

https://github.com/stylelint/stylelint/blob/59d6a3f174dc6787202db388763cb36da516d5f2/docs/user-guide/usage/node-api.md?plain=1#L53-L55

**Review by ybiquitous — COMMENTED** [review]
@kimulaco Thank you, LGTM! 👍🏼 

In addition, could you please add a changelog entry? The entry line should be like this (from the PR title): ⬇️ 

```
Fixed: false negatives on second run for cache and `severity` option
```

**Comment by kimulaco** [comment]
@ybiquitous Thanks for the review! I added a changelog.

**Pull request merged**
