### PR TITLE
Add postcss-sass as dependency, because postcss-html needs it

### PR DESCRIPTION
**Pull request by hudochenkov**
> Which issue, if any, is this issue related to?

https://github.com/stylelint/stylelint/issues/3035

> Is there anything in the PR that needs further explanation?

We don't use `postcss-sass` in our codebase, but it's a peer dependency of `postcss-html`, which we use. Luckily `postcss-html` doesn't fail if not every its dependency installed. But it might change theoretically, and we'll have a problem. Also we don't want annoy people by unmeet dependency messages.

### CODE REVIEW

**Comment by GreenGremlin** [comment]
Will this change be published soon? The peerDependency warnings are getting a bit annoying.

**Comment by jeddy3** [comment]
@stylelint/core If no one beats me to it, I can do a minor release this evening.

**Comment by jeddy3** [comment]
@GreenGremlin A regression delayed the release, but `8.4` is out now and should remove the peerDependency warning.

**Comment by GreenGremlin** [comment]
Thanks!

**Pull request merged**
