### PR TITLE
Add negation at-media tests

### PR DESCRIPTION
**Pull request by jeddy3**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@jeddy3 i think we try test:
```css
@media not (all and (min-width: 1200)) { ... }
```
Parenthesis after not, if tests OK, LGTM

**Comment by jeddy3** [comment]
It looks like we both got a little carried away with our parens in our media queries. Only:

```css
@media not screen and (min-width: 100px) {}
```

[Is valid](https://www.w3.org/TR/mediaqueries-4/#mq-not) as I think parens are only allowed around media features.

I've updated the tests accordingly.

**Comment by evilebottnawi** [comment]
@jeddy3 https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries in example i see this code, hm

**Comment by jeddy3** [comment]
I can see how [those examples](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#not) can be confusing because most of them are showing how the media queries *are evaluated*, rather than what the actual syntax is. Only the following two examples are valid CSS:

```css
@media not all and (monochrome) { ... }
@media not screen and (color), print and (color) { ... }
```

**Comment by evilebottnawi** [comment]
@jeddy3 exactly, I'm sorry for the carelessness of the documentation, LGTM

**Comment by ntwb** [comment]
LGTH

**Pull request merged**
