### PR TITLE
Bump jest from 28.1.3 to 29.0.2, jest-preset-stylelint from 5.0.4 to 6.0.0

### PR DESCRIPTION
**Pull request by mattxwang**
> Which issue, if any, is this issue related to?

Supersedes #6321.

> Is there anything in the PR that needs further explanation?

CI currently fails due to this change in jest-preset-stylelint, version 6:

> - Removed: support for Node.js less than 14.15.0.

Not sure how we want to handle merging this, etc. - can also just close this PR if we'd like to wait!

Related to - #6311

### CODE REVIEW

**Comment by jeddy3** [comment]
> Not sure how we want to handle merging this, etc. - can also just close this PR if we'd like to wait!

We can keep it open. I'll label as blocked by https://github.com/stylelint/stylelint/issues/6311.

**Comment by ybiquitous** [comment]
The [`v15`](https://github.com/stylelint/stylelint/tree/v15) branch is now available as a destination to push this commit. So we can go forward with this PR.

**Comment by jeddy3** [comment]
It looks like it's just the snapshots that need updating:

```
npm run jest -- -u
```

Because of this [breaking change in 29.0.0](https://github.com/facebook/jest/blob/main/CHANGELOG.md#features-6):

> [jest-config] [BREAKING] Make snapshotFormat default to escapeString: false and printBasicPrototype: false (https://github.com/facebook/jest/pull/13036)

**Review by jeddy3 — APPROVED** [review]
Thanks. LGTM.

**Comment by mattxwang** [comment]
I've been a bit behind on contributing - @ybiquitous did you want me to also edit `CHANGELOG`, or does the Changesets automation do that for us now?

**Comment by ybiquitous** [comment]
@mattxwang I'm not sure, but probably the Changeset GitHub App doesn't work on branches except for `main`. We can run `npx changeset add` locally to add a changelog entry instead.

**Comment by jeddy3** [comment]
> did you want me to also edit CHANGELOG

Let's not add an entry for this pull request as it's not a user-facing change.

**Pull request merged**
