### PR TITLE
Fix false negatives for SVG properties in alpha-value-notation

### PR DESCRIPTION
**Pull request by Mouvedia**
> Which issue, if any, is this issue related to?

see stylelint/stylelint-config-standard#257

> Is there anything in the PR that needs further explanation?

- a PR has been opened on stylelint-config-standard: stylelint/stylelint-config-standard#258
- ensure that stylelint and stylelint-config-standard are synced

### CODE REVIEW

**Comment by Mouvedia** [comment]
Dunno if its _changeset_ fault but we have a "Startup failure" on the PR checks.

**Review by jeddy3 — COMMENTED** [review]
Thanks, LGTM.

We don't need to merge this before the next release if we want to keep the new changeset workflow trial simple as this pull request requires a new release of the `standard` config.

(It'll be a `"minor"` changeset entry if we follow our [semver policy](https://stylelint.io/about/semantic-versioning/).)

**Review by ybiquitous — DISMISSED** [review]
@Mouvedia Thank you. LGTM 👍🏼

**Review by ybiquitous — APPROVED** [review]
We'll use the existing workflow in the next release (see #6287), so we can merge this PR.

**Comment by ybiquitous** [comment]
Changelog entry added:

> - Fixed: `alpha-value-notation` false negatives for SVG properties ([#6284](https://github.com/stylelint/stylelint/pull/6284)).

**Pull request merged**
