### PR TITLE
types: add types to requireRule, reportUnknownRuleNames

### PR DESCRIPTION
**Pull request by vankop**
> Which issue, if any, is this issue related to?

add types to requireRule, reportUnknownRuleNames

> Is there anything in the PR that needs further explanation?

nothing

Blocked by:  https://github.com/stylelint/stylelint/pull/4354

### CODE REVIEW

**Comment by evilebottnawi** [comment]
/cc @vankop @hudochenkov Can we create types in one PR (one commit - one types)? Pros:
- no extra notifications
- good git history
- non blocking PRs (when one types require other types and etc)
- easy to review

**Comment by vankop** [comment]
@evilebottnawi After this PRs I will create 3 more, they will be bigger since all types depends on each other. Types for utility we can create in one PR.

**Comment by evilebottnawi** [comment]
@vankop 

> they will be bigger since all types depends on each other

So should be easy it to do in one PR to avoid blocking better PRs, because if you fix something in an one PR you have to fix it in another PRs and it can be inconvenient and increase work time

> Types for utilities we can create in one PR.

Agree

**Comment by vankop** [comment]
> So should be easy it to do in one PR to avoid blocking better PRs, because if you fix something in an one PR you have to fix it in another PRs and it can be inconvenient and increase work time

@evilebottnawi I will try to make PR with types in such ways:
- to cover as much code as possible
- but keep them relatively easy to review

Obviously, it is hard to find "golden" middle between this points (some reviewers prefer small PRs), so I think to put this on my own vision will be a better decision 👮🏼😁

**Pull request merged**
