### PR TITLE
Reduce cyclomatic complexity in getPostcssResult.js

### PR DESCRIPTION
**Pull request by gucong3000**
> Which issue, if any, is this issue related to?

no

> Is there anything in the PR that needs further explanation?

Reduce cyclomatic complexity for  `lib/getPostcssResult.js`

### CODE REVIEW

**Comment by jeddy3** [comment]
What's the relationship of this PR with https://github.com/stylelint/stylelint/pull/2855 -> will they not conflict?

**Comment by gucong3000** [comment]
I think PR #2855 changes too big, should be separated into smaller PRs.
If you think so, you can close #2855.

**Comment by gucong3000** [comment]
Previous code branches: 3753 
https://travis-ci.org/stylelint/stylelint/jobs/273956924#L2234

After code branches: 3740 
https://travis-ci.org/stylelint/stylelint/jobs/274079241#L2248

**Comment by jeddy3** [comment]
> I think PR #2855 changes too big, should be separated into 3 smaller PRs.

If you think that's best then yes, close #2855 and split into 3 smaller PRs.

> Previous code branches: 3753...

Thanks for linking to these stats. It clearly shows you've reduced the cyclomatic complexity.

**Pull request merged**
