### PR TITLE
Add stylelint-scss to plugins list

### PR DESCRIPTION
**Pull request by kristerkari**
I wasn't sure what name to use for the header, so I used "Multiple rules".

### CODE REVIEW

**Comment by ntwb** [comment]
Wondering if each of the SCSS rules included in `stylelint-scss` should be included in the list or just linking to `stylelint-scss` to enough?

**Comment by Nirazul** [comment]
Why not use the term `Collections`

**Comment by kristerkari** [comment]
> Wondering if each of the SCSS rules included in stylelint-scss should be included in the list or just linking to stylelint-scss to enough?

It would be really painful to maintain that list since you'd have to keep it in sync with all the new rules in `stylelint-scss´.

> Why not use the term Collections

That does sound better, so maybe I should change it?

**Comment by jeddy3** [comment]
Lets go with "packs" as that what PostCSS [uses](https://github.com/postcss/postcss/blob/master/docs/plugins.md#packs) and stylelint rules are a superset of PostCSS plugins. I'll merge and do it.

@kristerkari BTW, congratulations to you and the other contributors on releasing `1.0.0` of `stylelint-scss`. It looks great! :)

**Comment by kristerkari** [comment]
@jeddy3 Thanks! I've had some awesome people helping out with it.

**Pull request merged**
