### PR TITLE
Fix level 5 media queries in media-feature-name-no-unknown

### LINKED ISSUE #3396: Fix false positives for prefers-reduced-motion media in media-feature-name-no-unknown
> Clearly describe the bug

`media-feature-name-no-unknown` reports an error when `prefers-reduced-motion` is used. This conflicts with this rule: https://github.com/YozhikM/stylelint-a11y/blob/master/src/rules/media-prefers-reduced-motion/README.md

> Which rule, if any, is the bug related to?

`media-feature-name-no-unknown`

> What CSS is needed to reproduce the bug?

e.g.

```css
@media screen and (prefers-reduced-motion) {
  div {
    animation: none;
  }
}
```

> What stylelint configuration is needed to reproduce the bug?

e.g.

```json
{
  "rules": {
    "'media-feature-name-no-unknown": "true"
  }
}
```

> Which version of stylelint are you using?

`9.2.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

`stylelint --syntax scss  './src/**/*.scss'`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No

> What did you expect to happen?

No warnings to be flagged

> What actually happened (e.g. what warnings or errors did you get)?

"The following warnings were flagged:"

```shell
test.scss
 19:20  ✖  Unexpected unknown media feature name "prefers-reduced-motion"   media-feature-name-no-unknown
```

### PR DESCRIPTION
**Pull request by pkuczynski**
Fixes #3396

### CODE REVIEW

**Comment by pkuczynski** [comment]
I added `prefers-reduced-transparency`, but note that it's only a Draft and no browser seems to support it yet, while `prefers-reduced-motion` is supported in Safari https://caniuse.com/#search=prefers-reduced-motion

**Comment by evilebottnawi** [comment]
@pkuczynski we have a lot of draft stuff right now, it is allow to avoid problem in future and fix compatobility with `postcss` plugins which polyfills this properties

**Comment by pkuczynski** [comment]
Sure, no probs. `inverted-colors` and `light-level` added. This PR is now complete, right?

**Comment by jeddy3** [comment]
> Sure, no probs. inverted-colors and light-level added.

Thanks!

> This PR is now complete, right?

LGTM

**Comment by jeddy3** [comment]
> -   Fixed: `media-feature-name-no-unknown` false positives for level 5 names ([#3397](https://github.com/stylelint/stylelint/pull/3397)).

**Comment by ntwb** [comment]
p.s. A bit late, but welcome to the @stylelint organisation @pkuczynski 🎉

**Pull request merged**
