### PR TITLE
rework scss comments in comments-no-empty rule

### LINKED ISSUE #4037: Fix false negatives for double slash comments in no-empty-comment
> Clearly describe the bug

`comment-no-empty` doesn't report on SCSS empty comment

> Which rule, if any, is the bug related to?

`comment-no-empty`

> What CSS is needed to reproduce the bug?

e.g.

```scss
//

a {
  width: 00.10em;
}
```

> What stylelint configuration is needed to reproduce the bug?

e.g.

```json
{
  "rules": {
    "comment-no-empty: true
  }
}
```

> Which version of stylelint are you using?

e.g. `10.0.1`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

SCSS

> What did you expect to happen?

warning

> What actually happened (e.g. what warnings or errors did you get)?

No warning

### PR DESCRIPTION
**Pull request by vankop**
> Which issue, if any, is this issue related to?

closes #4037

> Is there anything in the PR that needs further explanation?

nothing

### CODE REVIEW

**Comment by evilebottnawi** [comment]
I think it should be in `styleint-scss` as rule, not here

**Comment by vankop** [comment]
@evilebottnawi close issue?

**Comment by evilebottnawi** [comment]
@vankop let's wait answers from other developers, maybe we need only add docs about this limitation for rule

**Comment by jeddy3** [comment]
> I think it should be in styleint-scss as rule, not here

Agreed. I think this should be handled within a `scss/comment-no-empty` plugin as [with other SCSS-like comment rules](https://github.com/kristerkari/stylelint-scss#-comment).

The built-in rules are geared towards standard syntax. They ignore non-standard constructs rather than include code to handle this.

> maybe we need only add docs about this limitation for rule

Yes, I think that is best:

"This rule ignores SCSS-like comments."

**Comment by vankop** [comment]
@jeddy3 @evilebottnawi Please consider to make remarks if needed within editing file

**Pull request merged**
