### PR TITLE
Fix false positives for valueless attribute selectors in selector-attribute-name-disallowed-list

### LINKED ISSUE #5059: Fix false positives for valueless attribute selectors in selector-attribute-name-disallowed-list
> Clearly describe the bug

`selector-attribute-name-disallowed-list` doesn't handle valueless attribute selectors correctly.

> Which rule, if any, is the bug related to?

`selector-attribute-name-disallowed-list`.

> What code is needed to reproduce the bug?

```css
[disabled] { }
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "selector-attribute-name-disallowed-list": ["disabled"]
  }
}
```

> Which version of stylelint are you using?

`13.8.0`.

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `stylelint "**/*.css" --config myconfig.json`.

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No.

> What did you expect to happen?

The warning was flagged.

> What actually happened (e.g. what warnings or errors did you get)?

No warnings were flagged.

/cc @rletsin

### PR DESCRIPTION
**Pull request by vkrol**
> Which issue, if any, is this issue related to?

Closes #5059.

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

/cc @rletsin

### CODE REVIEW

**Review by jeddy3 — APPROVED** [review]
LGTM, thanks!

**Review by malsf21 — APPROVED** [review]
LGTM! 🚀

**Comment by vkrol** [comment]
Can I merge this PR myself?

**Comment by hudochenkov** [comment]
@vkrol I'm not sure if you have rights to edit CHANGELOG via website https://stylelint.io/maintainer-guide/pull-requests

**Comment by vkrol** [comment]
@hudochenkov thank you very much! I missed this guide :( I updated `CHANGELOG.md`.

**Comment by vkrol** [comment]
@hudochenkov could you please review the change in `CHANGELOG.md`?

**Comment by hudochenkov** [comment]
@vkrol I don't need to update changelog in a PR. After PR is merged we update changelog via webinterface. You might not have right to change changelog via web-interface, because it's a commit directly to `master`, and `master` is a protected branch.

Anyway, I'll merge this PR as it looks good :)

**Comment by vkrol** [comment]
@hudochenkov 
> After PR is merged we update changelog via webinterface.

Oh, sorry. This is not my best day ever :(

**Comment by hudochenkov** [comment]
Don't worry! It's alright :)

**Pull request merged**
