### PR TITLE
Update to PostCSS 8

### LINKED ISSUE #4942: Migrate to PostCSS 8
Steps:

- [x] Update to latest PostCSS dependencies
- [x] Fix failing tests 
- [x] Fix failing TypeScript errors
- [x] Migrate to built-in rules to visitor API to remove deprecation warnings
- [x] Investigate impact on executing order

[Release notes](https://github.com/postcss/postcss/releases/tag/8.0.0).
[Migration guide](https://evilmartians.com/chronicles/postcss-8-plugin-migration).

---

Before we migrate we need all our dependencies be on PostCSS 8.

`dependencies` are ready:

- [x] [`@stylelint/postcss-css-in-js`](https://github.com/stylelint/postcss-css-in-js) — https://github.com/stylelint/postcss-css-in-js/pull/74 (removed)
- [x] [`@stylelint/postcss-markdown`](https://github.com/stylelint/postcss-markdown) (removed)
- [x] [`autoprefixer`](https://github.com/postcss/autoprefixer)
- [x] [`postcss`](https://github.com/postcss/postcss)
- [x] [`postcss-html`](https://github.com/stylelint/postcss-html) — https://github.com/stylelint/postcss-html/pull/1. (removed)
- [x] [`postcss-less`](https://github.com/shellscape/postcss-less)
- [x] [`postcss-media-query-parser`](https://github.com/dryoma/postcss-media-query-parser) — it doesn't use PostCSS.
- [x] [`postcss-resolve-nested-selector`](https://github.com/davidtheclark/postcss-resolve-nested-selector) — doesn't depend on PostCSS.
- [x] [`postcss-safe-parser`](https://github.com/postcss/postcss-safe-parser)
- [x] [`postcss-sass`](https://github.com/AleshaOleg/postcss-sass)
- [x] [`postcss-scss`](https://github.com/postcss/postcss-scss)
- [x] [`postcss-selector-parser`](https://github.com/postcss/postcss-selector-parser) — doesn't have PostCSS as peer or regular dependency.
- [x] [`postcss-syntax`](https://github.com/stylelint/postcss-syntax) — https://github.com/stylelint/postcss-syntax/pull/2. (removed)
- [x] [`postcss-value-parser`](https://github.com/TrySound/postcss-value-parser) — doesn't depend on PostCSS.
- [x] [`sugarss`](https://github.com/postcss/sugarss)

`devDependencies` are ready:

- [x] [`postcss-import`](https://github.com/postcss/postcss-import)

---

Update won't be easy. We need to update custom syntaxes: `@stylelint/postcss-css-in-js`, `@stylelint/postcss-markdown`. And we probably need to move into stylelint organization and update `postcss-html` and `postcss-syntax`.

---

After all that we can start updating stylelint itself.

### PR DESCRIPTION
**Pull request by jeddy3**
> Which issue, if any, is this issue related to?

Closes #4942
Closes #5276

> Is there anything in the PR that needs further explanation?

This is the long-lived branch to be merged in `v14`.

### CODE REVIEW

**Comment by hudochenkov** [comment]
Here's how we can temporarily silence plugin warnings in Jest:

```js
const originalWarn = console.warn.bind(console.warn);

beforeAll(() => {
  console.warn = (message?, ...optionalParams) => {
    if (message.toString().includes('postcss.plugin was deprecated. Migration guide')) {
      return;
    }

    originalWarn(message, ...optionalParams);
  };
});

afterAll(() => {
  console.warn = originalWarn;
});
```

We probably could put it js-file for [`setupFilesAfterEnv`](https://jestjs.io/docs/configuration#setupfilesafterenv-array).

**Comment by jeddy3** [comment]
Sounds good. It'll clean up the output while we work on fixing the failing tests.

Do you want to push a commit to this branch for it?

**Comment by hudochenkov** [comment]
This code doesn't work ¯﻿\﻿_﻿(﻿ツ﻿)﻿_﻿/﻿¯ Neither in `setupFilesAfterEnv` or in test file itself. I think it's due jest-preset and `testRule`. Because I used this code in regular Jest setup to suppress warnings.

**Comment by jeddy3** [comment]
I believe this is now ready for review.

**Review by hudochenkov — APPROVED** [review]

**Review by alexander-akait — APPROVED** [review]

**Pull request merged**
