### PR TITLE
no-descending-specificity rule comparing numbers as strings

### PR DESCRIPTION
**Pull request by keeganstreet**
Hi guys,

There is a minor issue in the `isLowerSpecificity` utility function used by the "no-descending-specificity" rule. It is comparing the specificity parts as strings instead of converting them to numbers. So it is saying that "12" < "2".

Earlier this week we merged in https://github.com/stylelint/stylelint/pull/1497 for the "selector-max-specificity" bug fix. As a part of that change, the specificity calculator module was updated. The new version of this module returns a `specificityArray` which is an array of numbers. Previously you had to split the `specificity` string into an array and then convert the parts to numbers. But by using `specificityArray` you can avoid that step and fix this bug.

The new version of this module also includes a "compare" function which effectively achieves the same thing as `isLowerSpecificity`. So I have removed the `isLowerSpecificity` function as a simplification. If you'd prefer to keep that function I can update this PR to just add the unit test and `specificityArray` change.

I don't think there would be any performance impact. I'm not seeing much change in the report. Before:

```
MacBook:stylelint keegan$ npm run benchmark-rule -- no-descending-specificity true

> stylelint@6.7.0 benchmark-rule /Users/keegan/Projects/Tools/stylelint
> babel-node scripts/benchmark-rule.js "no-descending-specificity" "true"

Warnings: 4397
Mean: 566.0871832857144 ms
Deviation: 195.58274858245966 ms
```

After:

```
MacBook:stylelint keegan$ npm run benchmark-rule -- no-descending-specificity true

> stylelint@6.7.0 benchmark-rule /Users/keegan/Projects/Tools/stylelint
> babel-node scripts/benchmark-rule.js "no-descending-specificity" "true"

Warnings: 4397
Mean: 508.7208617333333 ms
Deviation: 124.05085001225196 ms
```

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@keeganstreet Thanks for helping.

**Comment by jeddy3** [comment]
>  So I have removed the isLowerSpecificity function as a simplification. 

SGTM. Happy to see this in the `specificity` module.

The PR looks great. Do we need a changelog item for this? 

I'll squash the commits on merge (once a 2nd pair of eyes have looked this over), so don't worry about that at your end.

**Comment by davidtheclark** [comment]
Looks great. Yeah, I think we should add a bug fix note to the changelog.

**Comment by jeddy3** [comment]
Changelog done in https://github.com/stylelint/stylelint/commit/d937d7262b5f78e350741da9c35c746271185754

**Pull request merged**
