### PR TITLE
PostCSS-Less 0.14.0

### PR DESCRIPTION
**Pull request by ntwb**
See https://github.com/stylelint/stylelint/issues/1409#issuecomment-230714400

### CODE REVIEW

**Comment by ntwb** [comment]
Travis CI - NodeJS 0.12.xx failure
AppVeyor job has been restarted.

**Comment by jeddy3** [comment]
Fingers crossed this fixes https://github.com/stylelint/stylelint/issues/1409 and https://github.com/stylelint/stylelint/issues/1389

**Comment by evilebottnawi** [comment]
@jeddy3 i think be cool ask guys about all works is correctly

**Comment by ntwb** [comment]
I've asked the original reports in #1409 and #1389 to test PostCSS-Less `0.14.0`

**Pull request merged**
