### PR TITLE
Added supports for sass syntax

### PR DESCRIPTION
**Pull request by AleshaOleg**

### CODE REVIEW

**Comment by davidtheclark** [comment]
As far as I know, this is waiting on resolution to the discussion in #2486 about whether the parser is ready for stylelint-prime-time or not — right?

**Comment by jeddy3** [comment]
> about whether the parser is ready for stylelint-prime-time or not — right?

Yep, I think we'll need to, in #2486: 

1. Assess the parsers compatibility with the core rules. So we can determine much work is required to add any missing compatibility.
2. Try to gauge whether the parser will have maintainer support in long term. So we can determine how to balance the overall health of the project with making the tool useful to a new user base.

**Comment by ntwb** [comment]
It looks like this now has some tests been added, updating to _needs review_ again

**Comment by gucong3000** [comment]
https://github.com/stylelint/stylelint/blob/master/lib/standalone.js#L274

@AleshaOleg here need a `CssSyntaxError` for syntax error.

**Comment by AleshaOleg** [comment]
@gucong3000 but i can't say where is parse error. Or i'm wrong? Because in `postcss-sass` i'm just using [gonzales-pe](https://github.com/tonyganch/gonzales-pe) to parse Sass and then simply transform their AST to PostCSS AST format.

Also, I will glad if somebody will help me to test `map`, `list` (like this kind of syntax: https://github.com/AleshaOleg/postcss-sass/blob/development/__tests__/sass/map2comment.sass) which i recently added. I plan to release `0.3.0` asap. But I still need more tests to do this.

**Comment by gucong3000** [comment]
blocked:
https://github.com/AleshaOleg/postcss-sass/pull/22
https://github.com/AleshaOleg/postcss-sass/pull/23

**Comment by AleshaOleg** [comment]
@gucong3000 sorry for too long response:)
I finally merged your changes to `postcss-sass`! Now I think it's ready to be released as 0.3.0 version. Is any things do I need to support in `postcss-sass` to make it works with `stylelint`?

**Comment by AleshaOleg** [comment]
Happy, holidays 🎉 🎅 🍾

**Comment by AleshaOleg** [comment]
@gucong3000 invited you to collaborators in `postcss-sass`. Feel free to make any changes! Again, thanks, for pr's

**Comment by gucong3000** [comment]
@AleshaOleg
Thank you for your trust.

**Comment by gucong3000** [comment]
blocked: https://github.com/AleshaOleg/postcss-sass/issues/38

**Comment by AleshaOleg** [comment]
@gucong3000 fixed for now.

**Comment by AleshaOleg** [comment]
@gucong3000 do we need everything to make a `stylelint` support sass files?

**Comment by gucong3000** [comment]
I think this PR is ready for the merge.

**Comment by ntwb** [comment]
Changelog : https://github.com/stylelint/stylelint/commit/793dd73fc59b2be4c0bf1fa74680f20a126813a5
> -   Added: (experimental) support for [SASS](http://sass-lang.com/) syntax ([#2503](https://github.com/stylelint/stylelint/pull/2503)).

**Pull request merged**
