### PR TITLE
Verbose formatter for CLI and improved invalid option warnings; close…

### PR DESCRIPTION
**Pull request by davidtheclark**
…s #703

Please give this a spin and look for bugs before merging.

### CODE REVIEW

**Comment by jeddy3** [comment]
Looking really good!

What works flawlessly (both in functionality and in formatter presentation) for:

- `-v` and `--verbose` CLI flags
- `{ formatter: "verbose" }` node API option.
- `{ code: "a{b:c;}", "verbose" }` node API options.
- invalid options (both string formatter and verbose one)
- "sources checked..." total (verbose)
- "problems found..." total (verbose)
- "problems found" stats (verbose) - nicely laid out :)

Questions and suggestions:

```shell
./node_modules/.bin/stylelint -v
```

Gives:

```shell
1 source checked
<input css 1>
0 problem found
```

Just checking that we expect as it's checking stdin, right?

---

If there are no problems the verbose reporter states: `0 problem found`. Should that be `0 problems found`? It behaves correctly for 1 and more than 1 errors e.g. `1 problem found` and `2 problems found`.

---

Is it possible to have relative paths for the list of checked sources, as to match those in the list of warnings? e.g.

```shell
css/correct.css
```

Rather than:

```shell
/Users/jeddy3/Projects/stylelint-test/css/correct.css
```

---

If I were to add a deprecation warning to a rule, where should I put it? I tried placing one in the rule itself and the warning appeared once for each file checked. Would it be possible to get it at the top and only displayed once (as with the invalid option warnings)?  I guess we could achieve this by placing the check outside the rule, but this might be more difficult for something like a deprecated option.

--- 

Invalid option and deprecation warnings have slightly different styling i.e. the whole of the deprecation warning is coloured yellow, whereas only the title (">> Invalid Option:") is coloured red for invalid option warnings. Is is possible to make them consistent? I think either style works.

---

**Comment by davidtheclark** [comment]
> ./node_modules/.bin/stylelint -v

We could have a more graceful message if there's no input. Something like "No input". Very graceful.

> If there are no problems the verbose reporter states: 0 problem found.

Will fix.

> Is it possible to have relative paths for the list of checked sources, as to match those in the list of warnings?

I figured that since this is the "verbose" option, we should be verbose and provide the absolute path so there is no ambiguity.

> Would it be possible to get it at the top and only displayed once (as with the invalid option warnings)?

I will see if I can figure out something better for deprecation warnings.

> Is is possible to make them consistent? 

I'll change the deprecation warning so only the heading is colored.

**Comment by davidtheclark** [comment]
> We could have a more graceful message if there's no input. Something like "No input". Very graceful.

I take that back. I think this is good for the verbose option.

**Comment by davidtheclark** [comment]
@jeddy3 : Pushed some changes to deprecation warnings and the pluralization. Please try again.

**Comment by jeddy3** [comment]
Changes looks good to me!

> I figured that since this is the "verbose" option, we should be verbose and provide the absolute path so there is no ambiguity.

Agreed.

**Pull request merged**
