### PR TITLE
Convert absolute documentation urls to relative urls

### LINKED ISSUE #944: Broken documentation links on stylelint.io
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug. Some of the links on stylelint.io are broken. For examples see `The CHANGELOG`, `The list of rules` and `The example config` listed here: http://stylelint.io/developer-guide/rules/#wire-up-the-rule

> What did you expect to happen?

The links should navigate to the relevant page on stylelint.io.

> What actually happened (e.g. what warnings or errors you are getting)?

The links navigate to a 404 page on github.com.

I'm posting the issue here as I believe the broken urls can be fixed by converting internal documentation links from absolute urls to relative urls. They would then be correctly processed by stylelint.io's `processLinks` function.

e.g. in https://raw.githubusercontent.com/stylelint/stylelint/ba56363/docs/developer-guide/rules.md the url `https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md` would become `../../CHANGELOG.md`

### PR DESCRIPTION
**Pull request by m-allanson**
Fixes #944

I used the regex `/stylelint/stylelint((\/[\w\-]+)*)\.md` to find urls that needed updating.

### CODE REVIEW

**Comment by jeddy3** [comment]
Ha, I was just about to start working on this one Mike! :) 

I'm just going to pull down your branch and try to generate a local copy of the site.

**Comment by jeddy3** [comment]
@davidtheclark Any objections if I had @m-allanson as a contributor so that he can work off the main repo?

**Comment by jeddy3** [comment]
@m-allanson Can you convert these URLs to domain-less absolute ones please? You'll see examples of this in the other docs e.g. https://raw.githubusercontent.com/stylelint/stylelint/master/docs/developer-guide.md

Because we convert the likes of `user-guide/rules.md` to `user-guide/rules/index.html` for the website, relative paths won't work.

**Comment by davidtheclark** [comment]
> @davidtheclark Any objections if I add @m-allanson as a contributor so that he can work off the main repo?

No way! All your contributions have been fantastic, @m-allanson.

**Comment by jeddy3** [comment]
> All your contributions have been fantastic,

Good stuff! I've sent an invite. Feel free to clone this repo (and kill your fork) once this PR is in.

**Comment by m-allanson** [comment]
Thanks @jeddy3 and @davidtheclark!

I've updated these urls.

**Comment by jeddy3** [comment]
Thanks!

**Pull request merged**
