### PR TITLE
Add `eslint-plugin-node` using `"recommended" config

### PR DESCRIPTION
**Pull request by ntwb**
Ref: https://github.com/stylelint/stylelint/pull/2977#issuecomment-337961524

Here's an initial pass at adding `eslint-plugin-node` using the "recommended" config.

• https://github.com/mysticatea/eslint-plugin-node

Here's the 19 errors reported:

```shell
❯ npm run lint:js

> stylelint@8.2.0 lint:js /Users/netweb/dev/stylelint/stylelint
> eslint . --cache


/Users/netweb/dev/stylelint/stylelint/lib/__tests__/fixtures/postcss-html-syntax.js
  3:26  error  "postcss-html" is not published  node/no-unpublished-require

/Users/netweb/dev/stylelint/stylelint/lib/__tests__/ignoreDisables.test.js
  5:29  error  "common-tags" is not published  node/no-unpublished-require

/Users/netweb/dev/stylelint/stylelint/lib/__tests__/needlessDisables.test.js
  6:29  error  "common-tags" is not published  node/no-unpublished-require

/Users/netweb/dev/stylelint/stylelint/lib/__tests__/standalone-cache.test.js
  11:24  error  "cp-file" is not published              node/no-unpublished-require
  12:28  error  "file-exists-promise" is not published  node/no-unpublished-require

/Users/netweb/dev/stylelint/stylelint/lib/__tests__/standalone-formatter.test.js
  6:27  error  "strip-ansi" is not published  node/no-unpublished-require

/Users/netweb/dev/stylelint/stylelint/lib/__tests__/standalone-syntax.test.js
  10:27  error  "strip-ansi" is not published  node/no-unpublished-require

/Users/netweb/dev/stylelint/stylelint/lib/cli.js
  3:1  error  This file needs no shebang  node/shebang

/Users/netweb/dev/stylelint/stylelint/lib/formatters/__tests__/needlessDisablesStringFormatter.test.js
  4:27  error  "strip-ansi" is not published   node/no-unpublished-require
  5:29  error  "common-tags" is not published  node/no-unpublished-require

/Users/netweb/dev/stylelint/stylelint/lib/formatters/__tests__/prepareFormatterOutput.js
  3:27  error  "strip-ansi" is not published  node/no-unpublished-require

/Users/netweb/dev/stylelint/stylelint/lib/formatters/__tests__/stringFormatter.test.js
  5:29  error  "common-tags" is not published  node/no-unpublished-require

/Users/netweb/dev/stylelint/stylelint/lib/formatters/__tests__/verboseFormatter.test.js
  4:29  error  "common-tags" is not published  node/no-unpublished-require

/Users/netweb/dev/stylelint/stylelint/lib/rules/at-rule-empty-line-before/__tests__/index.js
  8:29  error  "common-tags" is not published  node/no-unpublished-require

/Users/netweb/dev/stylelint/stylelint/lib/rules/no-duplicate-selectors/__tests__/index.js
  6:31  error  "postcss-import" is not published  node/no-unpublished-require

/Users/netweb/dev/stylelint/stylelint/lib/rules/selector-nested-pattern/__tests__/index.js
  8:29  error  "common-tags" is not published  node/no-unpublished-require

/Users/netweb/dev/stylelint/stylelint/lib/utils/__tests__/nodeContextLookup.test.js
  6:31  error  "postcss-import" is not published  node/no-unpublished-require

/Users/netweb/dev/stylelint/stylelint/scripts/benchmark-rule.js
  32:30  error  Spread operators are not supported yet on Node 4.2.1  node/no-unsupported-features

/Users/netweb/dev/stylelint/stylelint/system-tests/004/stylelint.config.js
  2:26  error  "./someUnknownFile.js" is not found  node/no-missing-require

✖ 19 problems (19 errors, 0 warnings)
  1 error, 0 warnings potentially fixable with the `--fix` option.

```

The 4 rules from above:
  -  16 x [no-unpublished-require](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unpublished-require.md) - Disallow `require()` expressions which import unpublished files/modules 
  - 1 x [no-missing-require](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-missing-require.md) - Disallow `require()`s for files that don't exist
  - 1 x [no-unsupported-features](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unsupported-features.md) - Disallow unsupported ECMAScript features on the specified version 
  - 1 x [shebang](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/shebang.md) - Suggest correct usage of shebang

Personally I'm not a fan of the `no-unpublished-require` and `no-missing-require` rules and I believe they should most likely be disabled from the _recommended_ config, I've raised my concerns with the first of these rules previously in https://github.com/mysticatea/eslint-plugin-node/issues/47

That leaves us 2 errors detected the use of _spread operator_ in `scripts/benchmark-rule.js` and the removal of the _shebang_ in `lib/cli.js`

### CODE REVIEW

**Comment by Aladdin-ADD** [comment]
> Personally I'm not a fan of the no-unpublished-require and no-missing-require rules and I believe they should most likely be disabled from the recommended config.

I'm afraid I don't think so -- it can catch some possible errors.
e.g. some packages were in devdeps, but should be in deps. (it can pass the ci, but not working when a user install from npm.)

**Comment by Aladdin-ADD** [comment]
hmm.. interesting! IMHO, these errors should not be reported, since `__tests__` was excluded in `files`. see here: https://github.com/stylelint/stylelint/blob/adb9158b9d928017a4c5ae92b367482f0a72b026/package.json#L34

there might be something wrong in this rule. cc @mysticatea

**Comment by jeddy3** [comment]
SGTM. The [`no-unsupported-features`](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unsupported-features.md) looks especially useful.

> hmm.. interesting! IMHO, these errors should not be reported, since __tests__ was excluded in files. see here:

Yep, after reading that rule's README I believe these errors shouldn't be reported. On a few occasions, we've published with something as a dev dependency instead of a normal one... this rule will hopefully catch those.

> 1 x no-missing-require - Disallow require()s for files that don't exist

This rule seems to be working well. We'll just need to turn it off using comments for that one line as we're intentionally requiring a non-existent file for a test.

> Add `eslint-plugin-node` using `"recommended" config

Should we move this over to `eslint-config-stylelint` as it's seems useful to have across all the repos?

**Comment by mysticatea** [comment]
> there might be something wrong in this rule. cc @mysticatea

Hi. Thank you for the cc.
The rule seems to have a problem; the rule does not recognize the negative pattern (`!` prefix). I confirmed that the negative pattern in `files` field is valid. I will fix it.

**Comment by mysticatea** [comment]
I fixed it. Please check `eslint-plugin-node@4.2.1`.

**Comment by jeddy3** [comment]
> I fixed it. Please check `eslint-plugin-node@4.2.1`.

That's awesome thanks! 

@ntwb I think we can roll this into `eslint-config-stylelint` now.

**Comment by ntwb** [comment]
> @ntwb I think we can roll this into eslint-config-stylelint now.

SGTM

For reference, after bumping to 5.2.1:
```shell
/Users/netweb/dev/stylelint/stylelint/lib/cli.js
  3:1  error  This file needs no shebang  node/shebang

/Users/netweb/dev/stylelint/stylelint/scripts/benchmark-rule.js
  32:30  error  Spread operators are not supported yet on Node 4.2.1  node/no-unsupported-features

/Users/netweb/dev/stylelint/stylelint/system-tests/004/stylelint.config.js
  2:26  error  "./someUnknownFile.js" is not found  node/no-missing-require
```

**Pull request closed without merging**
