### PR TITLE
Fix rule-properties-order handling of nested blocks; closes #653

### LINKED ISSUE #653: rule-properties-order with media query
```scss
.item {
        @media (min-width: $screen-sm-min) {
            margin-left: 74px;
            min-height: 64px;
        }

        @media (min-width: $screen-md-min) {
            margin-left: 106px;
            min-height: 96px;
        }

        @media (min-width: $screen-lg-min) {
            margin-left: 138px;
            min-height: 128px;
        }

        position: relative;
        margin-bottom: $margin-base;
        margin-left: 42px;
        border: 1px solid $gray-light;
        border-radius: 4px;
        box-shadow: 0 1px 1px rgba(0, 0, 0, .05);
        background-color: #fff;
        padding: 10px;
}
```
Output:
```
17:5	⚠  Expected property "position" to come before property "min-height" (rule-properties-order) [stylelint]
```
I think order in media queries and outside do not crossed. Separately check order in the media query and outside. Or maybe add option for this behaviour. What do you think?

### PR DESCRIPTION
**Pull request by davidtheclark**

### CODE REVIEW

**Comment by jeddy3** [comment]
Nice!

Shall I update the changelog and get a release out with the two fixes in?

**Comment by davidtheclark** [comment]
Let's wait until the end of the weekend. I planned to take some time later to try to check the CLI issues that @MoOx was having.

**Comment by jeddy3** [comment]
Groovy. I'll leave the release to you this time because of the time zone difference.

FYI, `npm run release` should be working now. So, just bump the `package.json` and changelog version, and then release :)

**Comment by MoOx** [comment]
Bump version in package.json & CHANGELOG, **commit**, then run "npm run release"

**Comment by jeddy3** [comment]
Oops, yep commit too! Thanks @MoOx 

Do we need to push the commit too? I've always done that, but wasn't sure if it was necessary or not...

**Comment by MoOx** [comment]
Not necessary. The command push + push tags.

**Pull request merged**
