### PR TITLE
Change emptyLineBefore to take a never option

### PR DESCRIPTION
**Pull request by dan-gamble**
I have 355/355 tests passing at https://github.com/dan-gamble/stylelint/tree/feature/578

I basically duplicated every `emptyLineBefore` test i found and changed the option to `never` and then made the tests pass from there.

### CODE REVIEW

**Comment by dan-gamble** [comment]
I've got far too many commits in here (Richard's ones) because i rebased upstream, not too sure how to PR without them. What's the process for that?

**Comment by davidtheclark** [comment]
Can you try rebasing against master?

**Comment by davidtheclark** [comment]
Not sure how familiar you are with this stuff, but `git checkout master`, `git pull`, `git checkout this-branch`, `git rebase master`.

**Comment by dan-gamble** [comment]
I've tried that and i get:

```
~/Workspace/stylelint feature/578
❯ g checkout master                                                                                                                                                                                                                                            (env: phixflow)
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.

~/Workspace/stylelint master
❯ g pull                                                                                                                                                                                                                                                       (env: phixflow)
Current branch master is up to date.

~/Workspace/stylelint master
❯ g cb                                                                                                                                                                                                                                                         (env: phixflow)
Switched to branch 'feature/578'
Your branch is up-to-date with 'origin/feature/578'.

~/Workspace/stylelint feature/578
❯ g rebase master                                                                                                                                                                                                                                              (env: phixflow)
Current branch feature/578 is up to date.
```

**Comment by davidtheclark** [comment]
Ok. Not sure exactly how screwy things got. Probably the easiest thing to do is to start a new clean branch from master and just copy-paste the files you've modified into that, then make a single nice commit. Does that make sense?

**Comment by dan-gamble** [comment]
Gonna try an interactive rebase and see if i can cherry pick them and remove the others, if not i'll go that route

**Comment by davidtheclark** [comment]
Ok, godspeed to you.

**Comment by dan-gamble** [comment]
I godspeeded so hard until AppVeyor :(

**Comment by dan-gamble** [comment]
:metal: :grin:

**Comment by dan-gamble** [comment]
Just updated the `README` then i think it's okay unless theres something else i've missed

**Comment by jeddy3** [comment]
@dan-gamble Thanks for tackling this one! I'll let David review it as he's a lot more familiar with this rule than I. 

I had one thing query though; is this going to be a deprecation or a breaking change? If it's a deprecation, then you'll probably want to adapt this PR to still accept the old option, but throw a warning if it's used. Much like how David deprecated the `"always"` option for `font-weight-notation` over in https://github.com/stylelint/stylelint/pull/812/files#diff-7f3dad09cd27a5064ffae8fe6422484dR42

**Comment by dan-gamble** [comment]
Sounds good to me, i think deprecated is the better way to go for now. I'll add that tonight :) Can remove it in a future breaking version maybe `5.x`

**Comment by jeddy3** [comment]
> Can remove it in a future breaking version maybe `5.x`

That's the plan :)

We're tracking the deprecated features in https://github.com/stylelint/stylelint/issues/802

**Comment by dan-gamble** [comment]
:+1: 

Will add the deprecation notice in tonight

**Comment by davidtheclark** [comment]
This looks good to me. Glad you worked it out, @dan-gamble. We can merge when the deprecation notice is in later.

**Comment by dan-gamble** [comment]
Sweet, genuinely surprised i managed to work that rule out, so much going on, i'm sorry for my initial request :D

**Comment by dan-gamble** [comment]
Added the deprecation warning i believe :+1: On to #803 now!

**Comment by jeddy3** [comment]
> Added the deprecation warning i believe

Good stuff! 

I think we'll need to include the old functionality as well as the warning. Am I right in thinking that it'll currently just show the warning and not function as it did before?

**Comment by dan-gamble** [comment]
Ah wasn't aware if you added deprecation and removed functionality. Will add the functionaility back in (easy fix) potentially tonight but i'm round my girlfriend so may be tomorrow morning

**Comment by davidtheclark** [comment]
I finished this up. I made `emptyLineBefore: true` work again and cleaned up a couple of things. Please review commit https://github.com/stylelint/stylelint/commit/88c0976fedf57d9df4fb8091f9b77ba8ddf66a4d for details.

**Comment by davidtheclark** [comment]
Thanks @dan-gamble! It's awesome that you took on such a complicated rule.

**Comment by dan-gamble** [comment]
Awesome thanks @davidtheclark i had a busy weekend sorry :) Will attempt #752 this week as well!

**Pull request merged**
