### PR TITLE
Expose available formatters in the Node API

### PR DESCRIPTION
**Pull request by jwilsson**
> Which issue, if any, is this issue related to?

#2181

> Is there anything in the PR that needs further explanation?

Not really, I added a basic test. Let me know if you want something more.

### CODE REVIEW

**Comment by jeddy3** [comment]
@jwilsson Thanks!

Do you think it's worth documenting this? Perhaps at the bottom of the [Formatters doc](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/formatters.md) within the developer guide:

## `stylelint.formatters`

stylelint's internal formatters are exposed publicly in `stylelint.formatters`.

**Comment by jwilsson** [comment]
@jeddy3 Sounds like a good idea, I'll add it!

**Comment by davidtheclark** [comment]
Thanks @jwilsson!

**Comment by davidtheclark** [comment]
Changelog note added:

> -   Added: `stylelint.formatters` exposed in public Node API ([#2190](https://github.com/stylelint/stylelint/pull/2190)).

**Pull request merged**
