### PR TITLE
support logical combinations

### PR DESCRIPTION
**Pull request by vankop**
> Which issue, if any, is this issue related to?

closes https://github.com/stylelint/stylelint/issues/2657

> Is there anything in the PR that needs further explanation?

nothing

### CODE REVIEW

**Comment by vankop** [comment]
> Looks good, can we add test with nested with multiple `body:not(div):not(span) {}` ?

which rule? or every `selector-pseudo-class-*` ?

**Comment by evilebottnawi** [comment]
Any, just ensure this case also covered

**Comment by vankop** [comment]
> Looks good, can we add test with nested with multiple `body:not(div):not(span) {}` ?

done

**Comment by hudochenkov** [comment]
> -   Added: `selector-*` support for all logical combinations (:matches, :has) ([#4179](https://github.com/stylelint/stylelint/pull/4179)).

**Comment by jeddy3** [comment]
@vankop It's great to see some old issues being addressed! Thank you for your work on all your recent pull requests.

**Pull request merged**
