### PR TITLE
Chore: correction stylistic errors.

### PR DESCRIPTION
**Pull request by evilebottnawi**
It would be good to add `no-multi-spaces` in `eslint-config-stylelint`.

### CODE REVIEW

**Comment by davidtheclark** [comment]
@evilebottnawi Fine by me. Want to make that part of this PR?

**Comment by evilebottnawi** [comment]
@davidtheclark listen @jeddy3 ?

**Comment by davidtheclark** [comment]
Oh that's right, forgot about the separate config.

**Comment by jeddy3** [comment]
> add new rule in `eslint-config-stylelint`

Sgtm.

**Pull request merged**
