### PR TITLE
Nesting support to rule-properties-order

### PR DESCRIPTION
**Pull request by jeddy3**

### CODE REVIEW

**Comment by MoOx** [comment]
Maybe instead we should test w3c draft syntax ? (which use 2 braces). Should not change implementation tho.

**Comment by jeddy3** [comment]
It already did e.g. `tr.ok("a { top: 0; { &:hover { color: red; } } }")`, but I've just added an extra nesting test without a first-level property e.g. tr.ok("a {{ &:hover { color: red; top: 0; } } }") for completeness.

There are a couple of `postcss-nested` syntax tests too, mainly to test at-rule bubbling (e.g. `tr.ok("a { color: red; width: 0; @media print { color: red; top: 0; } }")` as that isn't in the spec. 

It's a tricky one as that means we're supporting and testing for un-specced behaviour.

**Comment by MoOx** [comment]
Not a big deal I think.

**Comment by davidtheclark** [comment]
I think we can currently try to support both styles of nesting -- it might not be a problem. So let's just merge now and see how it works.

**Pull request merged**
