### PR TITLE
Config overrides function

### PR DESCRIPTION
**Pull request by shawnbot**
This implements the proposal in #4374. TL;DR: `configOverrides` can be a function that takes a fully resolved config and either modifies it in place and/or returns a new one:

```js
const anymatch = require('anymatch')
module.exports = {
  extends: ['some-other-config'],
  configOverrides: config => {
    // modify, add, or remove plugins config.rules and config.plugins
  }
}
```

### `--rules` CLI option
As a demonstration of how this works, I've also implemented a fix for #4331 with a new CLI flag: `--rules <comma-separated-list>` adds an config override that filters the configuration's `rules` object to include only the named rules in the list.

I haven't added docs for this yet, but I wanted to be sure that this change was welcome before doing so. I think it's super useful and would love not to have to maintain [stylelint-only](https://github.com/shawnbot/stylelint-only). 😁 

### File filters?
This _might_ pave the way for a solution to #3128, but I'm honestly not sure where in stylelint's configuration "lifecycle" the configuration is augmented, and it's entirely possible that this happens before the config is applied to individual files. If so, a follow-up would need to be necessary to either:

1. Apply `configOverrides()` for each file, and pass the file information to it; or
2. Use this function under the hood to implement one of the declarative file override patterns proposed in #3128.

Either way, this mechanism is only available in JS configs, and won't work in JSON or YAML.

### CODE REVIEW

**Comment by vankop** [comment]
@shawnbot Thanks for PR, looks good! I think we need to support "smart" merge, too. (maybe in another PR) Could you please create test case with `.stylelintrc` file? We need to support it as well.

@hudochenkov new problem with Windows in CI =( Maybe our previous hack (with commands chaining) is unnecessary now

**Comment by vankop** [comment]
> 1. Apply `configOverrides()` for each file, and pass the file information to it

I think this is more useful

> 2. Use this function under the hood to implement one of the declarative file override patterns proposed in #3128.

I think this is not possible in current stylelint design since stylelint runs with one syntax only (Does not determine syntax for each file). As I can see we can use babel approach here. Something like:
```
{
    ...
   overrides: {
           include: "../components",
           syntax: "css-in-js",
           ...
   }
}
```

So under the hood we can create `overrides` function and call it for each file using first approach API

**Comment by vankop** [comment]
I was meaning to use `mergeConfigs` option https://github.com/stylelint/stylelint/blob/master/lib/augmentConfig.js#L244 , since this feature available only for Node.js API I think it will be enough to just provide this function in public API. Code usage:
```
const configSCSS = require('./config.scss');
const {mergeConfigs} = require('stylelint');
module.exports = {
  extends: ['some-other-config'],
  configOverrides: config => {
    config = mergeConfigs(config, configSCSS)
  }
}
```

**Comment by hudochenkov** [comment]
Thank you for investigating possibilities.

We should discuss `configOverrides` proposal in https://github.com/stylelint/stylelint/issues/4374 first.

Proposed new flag is not discussed yet. https://github.com/stylelint/stylelint/issues/4331

**Pull request closed without merging**
