### PR TITLE
fix CssSyntaxError when config processors is a empty array

### PR DESCRIPTION
**Pull request by gucong3000**
> Which issue, if any, is this issue related to?

#3327

> Is there anything in the PR that needs further explanation?

No, it's self explanatory.

### CODE REVIEW

**Comment by gucong3000** [comment]
Closes: #3327

**Comment by hudochenkov** [comment]
Is it possible to write a test for this case?

**Comment by evilebottnawi** [comment]
Yep need tests for avoid regressions in future :+1:

**Comment by jeddy3** [comment]
Was there a CHANGELOG update to accompany this merge?

**Pull request merged**
