### PR TITLE
Add Node.js 9 to Travis CI

### PR DESCRIPTION
**Pull request by hudochenkov**
> Which issue, if any, is this issue related to?

None. But #2998 a little bit related.

> Is there anything in the PR that needs further explanation?

Added Node.js 9, as it the latest Node.js since yesterday. Keeping `pretest` and `coverage` on Node.js 8 as it more stable for now. `coverage` has higher priority because it takes more time (the sooner it starts, the sooner it finishes).

### CODE REVIEW

**Comment by hudochenkov** [comment]
> npm WARN npm npm does not support Node.js v9.0.0
> npm WARN npm You should probably upgrade to a newer version of node as we
> npm WARN npm can't make any promises that npm will work with this version.
> npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8.
> npm WARN npm You can find the latest version at https://nodejs.org/

¯﻿\﻿_﻿(﻿ツ﻿)﻿_﻿/﻿¯ We'll wait then until new npm version released.

**Comment by ntwb** [comment]
Thanks for the references @hudochenkov, saved me hunting them down for my other projects 😂 

I agree lets wait until npm release a compatible update

**Comment by Arcanemagus** [comment]
@gucong3000 `npm` still doesn't have a compatible release published, so I'm not sure why you removed the `PR: Blocked` label.

**Comment by hudochenkov** [comment]
@gucong3000 I wouldn't make Node.js 9 a default runner for our tests (including pretest and coverage) as it's not stable and not production ready. Please, revert this change back.

**Comment by gucong3000** [comment]
> npm still doesn't have a compatible release published, so I'm not sure why you removed the PR: Blocked label.

If we do not reinstall `npm` for node v9, build will success on Travis CI

**Comment by gucong3000** [comment]
@gucong3000 has been revised as you wish.

**Comment by ntwb** [comment]
Lets wait for an official solution from the Node.js and npm teams.

**Comment by hudochenkov** [comment]
With [`npm@5.6.0`](https://github.com/npm/npm/releases/tag/v5.6.0) it's green!

> Previously, it turns out npm broke on the latest Node, `node@9`. We went ahead and fixed it up so y'all should be able to use the latest npm again!

**Comment by ntwb** [comment]
Thanks everyone for your patience on this 😄

**Pull request merged**
