### PR TITLE
Remove VSCode extension from the list of tools

### PR DESCRIPTION
**Pull request by shinnn**
> Which issue, if any, is this issue related to?

None.

> Is there anything in the PR that needs further explanation?

I've halted to maintain it as I'm now mainly working as an Android dev and no longer have much interest in stylelint.

Thanks for including my plugin to this list for a long time.

### CODE REVIEW

**Comment by hudochenkov** [comment]
@shinnn is it possible to add me as a contributor to all relevant to VS Code plugin repositories, please? I would like to use this plugin in future, and make changes to keep it alive.

**Comment by ntwb** [comment]
@shinnn @hudochenkov Likewise, happy to help contribute to this plugin for VS Code

**Comment by ntwb** [comment]
@shinnn Have you deleted the repo, or just archived it and made it private?

**Comment by zhanba** [comment]
@shinnn  why delete the repo ?

**Comment by shinnn** [comment]
It would be better for you to reimplement the editor extension from scratch, because lots of users expect it to load stylelint from a local `node_modules` folder instead of the one bundled in the extension as my implementation does. That's why I thought the existing repo no longer need to exist.

Anyway, feel free to just copy and paste any code from the original vscode-stylelint without any credit to me, the original author. You can find many forks online, for example https://github.com/patsissons/vscode-stylelint.

**Comment by ntwb** [comment]
Thanks @shinnn for the update, it's unfortunate we couldn't take over the existing extension and user base as it also appears to have been removed from the VS Code marketplace.

Anyway, thanks for your contributions to the the stylelint community, they have been of great value, good luck in your future endeavours :)

**Comment by thibaudcolas** [comment]
@shinnn could you make the latest version of the repository / source code available again in a read-only / archived repository, or in a ZIP file? Even if lots of users might want a different implementation, for me at least I was very happy with how this extension worked as it was, so don’t really see value in reimplementing it from scratch. There are forks, but they tend to be out-of-date, and for future maintenance it would be valuable to have the commit history even if you wanted it anonymised to no longer be associated with it.

**Comment by BPScott** [comment]
Heya there folks,

I've been taking an interest in the stylelint plugin recently (thanks to looking into autofix support following the prettier extension reworking how they support stylelint integration). So I've got a biiiit of context that might be handy.

I believe https://marketplace.visualstudio.com/items?itemName=hex-ci.stylelint-plus is the most up-to date fork of @shinnn's excellent work. This was forked on June 10th 2019 after release 0.51.0 (from reading the [commit history](https://github.com/hex-ci/vscode-stylelint-plus/commits/master)). Checking my VScode extensions folder (with `ls $HOME/.vscode/extensions`) I can see that 0.51.0 is the version of `shinnn.stylelint` I have installed locally, so I'm pretty confident that's the last version before Shinnn yanked the extension. The GH repo for hex-ci.stylelint-plus is https://github.com/hex-ci/vscode-stylelint-plus.

As a small silver lining that fork does support autofixing, which Shinnn's version did not (IIRC they had concerns about its stability as https://stylelint.io/user-guide/cli#autofixing-errors still claims it is an experimental feature).

It might be worth reaching out to @hex-ci to see if they want to move their work into the stylelint org.

**Comment by hudochenkov** [comment]
Thanks for investigation, @BPScott!

**Comment by songololo** [comment]
Would it be possible for those developing / redeveloping this extension to keep this thread updated with any new developments? (Or updates on where such discussion has moved?)

Thanks.

**Comment by ntwb** [comment]
We are actively discusing this internally, work has already begun even 😏 

We will post an update here early next week 🎉

**Comment by ntwb** [comment]
We've moved the extension from @thibaudcolas repo to the stylelint org

https://github.com/stylelint/vscode-stylelint

I'll get this published to the VS Code marketplace later today

Thanks again for kicking this off @thibaudcolas 💯

**Comment by cagross** [comment]
@ntwb I'm just seeing that @shinnn's stylelint for VSCode extension has been removed (I know, I'm late to the party).  So am I correct that the extension by @thibaudcolas ([this extension](https://github.com/stylelint/vscode-stylelint)) is your recommended replacement?  Or are there still some behind-the-scenes things you need to do before making it an official suggestion?

**Comment by ntwb** [comment]
VS Code - stylelint v0.60.0 published 🎉

https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint

**Comment by cagross** [comment]
@ntwb Great thanks.

**Pull request merged**
