### PR TITLE
Rename trailing semicolon rule

### PR DESCRIPTION
**Pull request by jeddy3**
Ref: #664

### CODE REVIEW

**Comment by davidtheclark** [comment]
Looks good. Just needs a rebase/merge to catch up and fix the stupid changelog conflicts, then feel free to merge.

**Comment by jeddy3** [comment]
> Just needs a rebase/merge to catch up and fix the stupid changelog conflicts

This did not go well for me last time I tried... should 

> `git checkout master`, `git pull`, `git checkout this-branch`, `git rebase master`.

be enough?

**Comment by davidtheclark** [comment]
Yes, that should work & guide you through steps to fix the conflict.

An easier option is to merge master into this branch, fix the conflicts and commit.

`git checkout master`, `git pull`, `git checkout this-branch`, `git merge master`, fix conflicts and for each fixed conflict `git add the/file/you/fixed`, `git commit`.

**Comment by davidtheclark** [comment]
You can read about the difference between merge/rebase if you want. I think the long and short of it is that rebase is more likely to cause problems but will arguably give you a "cleaner" history.

**Comment by jeddy3** [comment]
Ummm. I don't think that worked as expected.

I've read up on rebase/merging. I also follow the instructions step by step, but something always goes wrong. 

Is this PR going to trash things, or can I merge and pretend nothing happened? :)

**Comment by davidtheclark** [comment]
Yeah this looks pretty messy. I'll look into it later. :)

**Comment by jeddy3** [comment]
> Yeah this looks pretty messy. I'll look into it later.

Sorry about that... :) 

I was convinced it'd worked this time as each step seem to go so well.

**Comment by davidtheclark** [comment]
@jeddy3: I've gone through plenty of git pains myself, so I understand.

**Pull request closed without merging**
