### PR TITLE
Use eslint@1.0.0 and eslint-config-stylelint

### PR DESCRIPTION
**Pull request by jeddy3**
I wanted to quickly brush up on the changes in eslint@1.0.0, so I created a shared config.

The only additional thing it caught was `expectedLevel` being used before it's declared in `indentation`. I shifted the declaration up a bit and the tests still pass - ok with you?

It still uses the `eslint:recommended` config, but a few of the additional rules we are using have been deprecated or renamed. I've fixed those.

I just noticed that doing a `npm i --save-dev` alphabetically orders all the properties in `package.json` - sorry about the noise... I can clean it up if it's a problem.

### CODE REVIEW

**Comment by MoOx** [comment]
ok for me.
Weird that npm order all fields now. It doesn't make sense for scripts...

**Comment by TrySound** [comment]
Edit release notes. The last is false.

**Comment by TrySound** [comment]
Globs apply in order. In your version negative to nothing and then positive to all.

**Comment by jeddy3** [comment]
On it.

**Comment by jeddy3** [comment]
Sorry guys. My bad. I messed up that last release.

I've corrected the release notes:

* `0.6.1` just contains the atrule fixes for `rule-no-duplicate-properties` and `rule-properties-order`
* `0.6.2` contains the smaller npm package fix that got hammered in this PR.

Sorry about that.

**Comment by jeddy3** [comment]
FYI, it turns out the the sorting of all the fields isn't the intended behaviour of npm and the bug has been fixed in https://github.com/npm/npm/pull/9068

**Pull request merged**
