### PR TITLE
Test for Node.js 20 on CI

### PR DESCRIPTION
**Pull request by ybiquitous**
> Which issue, if any, is this issue related to?

Ref: #6794

> Is there anything in the PR that needs further explanation?

~~Tests for Node.js 20 are still unstable. We can restore it if they become stable.~~

~~Note: CI statuses are different by each environment:~~

- ❌ ~~ubuntu~~
- ❌ ~~windows~~
- ✅ ~~macos~~

➡️ All green thanks to Jest's `--workerIdleMemoryLimit` option! 🎉

### CODE REVIEW

**Comment by ybiquitous** [comment]
Are the failures due to Jest instead of Node.js...? 🤔

**Comment by alexander-akait** [comment]
Funny:
> Test Suites: 360 passed, 360 total

**Comment by ybiquitous** [comment]
Trying Jest's [`--detectOpenHandles`](https://jestjs.io/docs/cli#--detectopenhandles) option via f7a261f2

**Comment by ybiquitous** [comment]
[`--workerIdleMemoryLimit`](https://jestjs.io/docs/configuration/#workeridlememorylimit-numberstring) can resolve failures (8d507135)! 🎉 

I know the option from this issue: 👇🏼 

- https://github.com/jestjs/jest/issues/11956

**Comment by ybiquitous** [comment]
CI is now green ✅

**Review by ntwb — APPROVED** [review]

**Pull request merged**
