### PR TITLE
Handle spaceless multiplication in unit-* rules

### PR DESCRIPTION
**Pull request by CAYdenberg**
> Which issue, if any, is this issue related to?

#2875 

> Is there anything in the PR that needs further explanation?

Wrote failing tests but haven't implemented fixes yet.

### CODE REVIEW

**Comment by jeddy3** [comment]
Tests look good.

**Comment by jeddy3** [comment]
@CAYdenberg Is this ready for review now?

**Comment by CAYdenberg** [comment]
Yes!

**Comment by jeddy3** [comment]
Is there value in creating a `parseValue` util that houses this in one place, like we do for [`parseSelector`](https://github.com/stylelint/stylelint/blob/master/lib/utils/parseSelector.js)?

**Comment by CAYdenberg** [comment]
I thought about that. We really want the postcss-value-parser to handle `*` as a separator, and it doesn't. So the work around is just to replace it, but we probably only want to make this replacement in unit rules for fear of breaking something else.

If I look at the four `unit-*` rules, most of the code is duplicated. I thought about creating some kind unit analyzer utility - maybe walkUnits? So that the individual rules could just recieve units as a callback when found, then check them. Or they could pass a "checking" function into the utility.

This would be a bigger change though, so I think this option is OK since it's just one additional line of code that's duplicated between all four files (although one that doesn't make sense without explanation/comment). I'll happily implement it though if you think it's warranted and have some feedback on how it should be designed.

**Comment by jeddy3** [comment]
> This would be a bigger change though, so I think this option is OK 

Agreed. Thanks for the write-up too. I think we're OK to go with this, as we can always revisit this if we're so inclined and/or have more time on our hands.

**Comment by jeddy3** [comment]
> -   Fixed: `unit-*` false positives for spaceless multiplication ([#2948](https://github.com/stylelint/stylelint/issues/2948)).

After two approvals, anyone can merge a PR... including the original PR author. So, feel free to merge if you noticed an unmerged PR when you check-in on stylelint. I just did this one as I generally catch-up on stylelint around this time of day.

**Pull request merged**
