### PR TITLE
block-opening-brace-before and rule-testing functions

### PR DESCRIPTION
**Pull request by davidtheclark**
Maybe ignore all the rambling in https://github.com/stylelint/stylelint/issues/32 and instead look at this PR :)

There are a bunch of things going on:

1. Add `block-opening-brace-before` rule.
2. Create a couple of utility functions (you may notice that I ended up not using `isSingleLineString()` because of https://github.com/stylelint/stylelint/issues/18#issuecomment-100569173 --- but I kept in there because other rules with almost certainly need it).
3. Create `ruleTester()`, which realizes the ideas in #32, and apply it to existing tests.

The goal of `ruleTester()` is to provide a super easy and standardized way to write the kinds of tests that we will have to write thousands of in the course of creating all these rules. **Notice, for example how the `declaration-block-trailing-semicolon` tests have 13 additions and *145 deletions***. So the `ruleTester()` indeed makes writing these tests much, much easier and faster.

What do you think?

### CODE REVIEW

**Comment by MoOx** [comment]
This looks good, my only concern is about clarity of each tests messages like said in https://github.com/stylelint/stylelint/issues/32#issuecomment-100582762

**Comment by davidtheclark** [comment]
So just to clarify the discussion -- right now we'll get TAP output like this:

```
# DECLARATION-NO-IMPORTANT: true
# pass: a { color: pink; }
ok 41 no warnings
# fail: a { color: pink !important; }
ok 42 one warning
ok 43 correct warning message
# DECLARATION-NO-IMPORTANT: false
# pass: a { color: pink; }
ok 44 no warnings
# pass: a { color: pink !important; }
ok 45 no warnings
```

This keeps the messages succinct, but it's only clear what the assertions apply to if you look at their context. One advantage of having a wrapper test function like this is that we could easily change the messages to another standardized form without having to manually enforce that style in everybody's JS files. So, yeah, if people would prefer longer messages, where each assertion names the rule and options, that seems fine with me.

One thing I do contend with, though, is that I prefer printing out the CSS string to having to write out a sentence-long description of what that particular CSS string represents. Especially when *quantity is really important in these kinds of tests*, and many tests might have essentially the same description, making test writing slower and more redundant. You know what I mean?

Maybe it would clear things up if you took the output above and wrote out how you would like it to appear?

**Comment by MoOx** [comment]
If you are happy with that output right now, let's go with it. I don't have so much to say since I didn't write yet any tests ;)
When I'll write tests I will have the right to express myself (if I thing we can improve that).

That said I would go for something like

```
# BLOCK-OPENING-BRACE-BEFORE: "space"
# pass: a { color: pink; }
ok 1 valid declaration block should not report anything
# pass: @media print { a { color: pink; } }
ok 2 valid block in should not report anything
# fail: a{ color: pink; }
ok 3 selector collapsed to declaration block should report {MESSAGE HERE}
# fail: a  { color: pink; }
ok 5 selector with multiples spaces before declaration block should report {MESSAGE HERE}
# fail: a\t{ color: pink; }
ok 7 selector with tab before declaration block should report {MESSAGE HERE}
# fail: a\n{ color: pink; }
ok 9 selector with new lines before declaration block should report {MESSAGE HERE}
# fail: @media print\n{ a { color: pink; } }
ok 11 selector with tab before block should report {MESSAGE HERE}
# fail: @media print { a\n{ color: pink; } }
ok 13 selector in block with newline before declaration block should report {MESSAGE HERE}
```

I think having clear sentence about what a test is about is a good way to understand what the error is about if you broke a test.

**Comment by davidtheclark** [comment]
With minimal API modification to `ruleTester()` I got it to report like this:

```
TAP version 13
# DECLARATION-BLOCK-TRAILING-SEMICOLON: true
# pass: a { color: pink; }
ok 1 single-line declaration block with trailing semicolon should pass
# pass: a { background: orange; color: pink; }
ok 2 multi-line declaration block with trailing semicolon should pass
# fail: a { color: pink }
ok 3 single-line declaration block without trailing semicolon should warn
ok 4 single-line declaration block without trailing semicolon should report "Expected a trailing semicolon (declaration-block-trailing-semicolon)"
# fail: a { background: orange; color: pink }
ok 5 multi-line declaration block without trailing semicolon should warn
ok 6 multi-line declaration block without trailing semicolon should report "Expected a trailing semicolon (declaration-block-trailing-semicolon)"
# DECLARATION-BLOCK-TRAILING-SEMICOLON: false
# pass: a { color: pink }
ok 7 single-line declaration block without trailing semicolon should pass
# pass: a { background: orange; color: pink }
ok 8 multi-line declaration block without trailing semicolon should pass
# fail: a { color: pink; }
ok 9 single-line declaration block with trailing semicolon should warn
ok 10 single-line declaration block with trailing semicolon should report "Expected no trailing semicolon (declaration-block-trailing-semicolon)"
# fail: a { background: orange; color: pink; }
ok 11 multi-line declaration block with trailing semicolon should warn
ok 12 multi-line declaration block with trailing semicolon should report "Expected no trailing semicolon (declaration-block-trailing-semicolon)"

1..12
# tests 12
# pass  12

# ok
```

Way more verbose ... Do you like that @MoOx enough that I should go with it?

**Comment by MoOx** [comment]
lgtm !

**Comment by davidtheclark** [comment]
Ok, just committed with those changes.

**Comment by davidtheclark** [comment]
If we like this, next time I sit down to write I'll be able to do a lot more rules, a lot less infrastructure :)

**Comment by MoOx** [comment]
It looks really great ! You did some awesome work here. Thanks a ton.

**Comment by tunnckoCore** [comment]
other than the question in comment, lgtm! :)

**Comment by jeddy3** [comment]
lgtm. The TAP output is totally fine with me.

Absolutely fantastic stuff. Thanks! :)

**Pull request merged**
