### PR TITLE
Ignore package-lock.json

### PR DESCRIPTION
**Pull request by hudochenkov**
> Which issue, if any, is this issue related to?

Kind of related to https://github.com/stylelint/stylelint/issues/2061#issuecomment-303603179

> Is there anything in the PR that needs further explanation?

It's uncomfortable to work with stylelint repository when npm@5 is installed. Because npm@5 automatically creates `package-lock.json`. So this file should be constantly manually deleted when switching branches or rebase. It's tedious. While we haven't decided to use `package-lock.json` we could ignore it.

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@hudochenkov no `package-lock.json` before https://github.com/npm/npm/issues/16866 was resolved, each update your should run `rm package-lock.json` and run `npm install/update`, it is hell :disappointed:

**Comment by hudochenkov** [comment]
@evilebottnawi thanks for heads up! Than my PR has even more sense :)

P. S. Do you think it's better to stick to npm@3 on local machine for now? (I've never used npm@4)

**Comment by evilebottnawi** [comment]
@hudochenkov we now use v4, they are very stable and good, local i am use npm v5, someone must find problems :smile:

**Comment by ntwb** [comment]
I ❤️ with npm 5, but all that love doesn't help here if you are using npm 3 or 4 😢 

I see two options:

1. The proposed adding `package-lock.json` to `.gitignore` which alleviates the problem for the repo, it won't alleviate the issue that @evilebottnawi pointing out above at npm when the `package.json` file is updated and `package-lock.json` is not you'll still need to delete the `package-lock.json` file.

2. Add an `.npmrc` file containing `package-lock=false` for now, I'm trying to find if this is backward compatible for npm 3 and 4 though.

**Comment by ntwb** [comment]
https://twitter.com/netweb/status/877661984677781506
> _"@npm_support Is `package-lock.json` compatible with either npm 3 or 4, if I add a `package-lock.json` can npm 3 or 4 benefit from this?"

https://twitter.com/npm_support/status/877671112028684289
> _"@netweb the `package-lock.json` is not compatible"_

https://twitter.com/netweb/status/877671436281757696
> _"@npm_support Thanks, so if I commit it to a repo and a user checks it out using npm 3 or 4 there won't be any explosions, simply ignored?"_

https://twitter.com/npm_support/status/877672905987043330
> _"@netweb npm3 or npm4 will ignore the package-lock.json files"_

Based on that I think we should go ahead and add a `package-lock.json` file this will benefit npm 5 users and npm 3 and npm 4 users will be unaffected.

**Comment by hudochenkov** [comment]
There more issues I found frustrating in npm@5:

- Installing subdep as toplevel dep causes unmet deps (https://github.com/npm/npm/issues/16741)
- --save-dev is removing installed deps (https://github.com/npm/npm/issues/16794)
- npm does not generate full lockfile unless a full install is run, first (https://github.com/npm/npm/issues/16893)
- Missing dependencies after running `npm install` a second time (https://github.com/npm/npm/issues/16839)
- npm install sometimes fails to install some dependencies on a fresh install (https://github.com/npm/npm/issues/16902) — happened to me twice yesterday

I don't mind `package-lock.json` available in our repo. But how to update it if I update dependency and don't have npm@5 installed?

**Comment by ntwb** [comment]
Per the last tweet in my comment above: "...npm3 or npm4 will ignore the package-lock.json files"

Unless npm 5 is used `package-lock.json` can not be updated

Per your comments above @hankthewhale and mine [here](https://github.com/stylelint/stylelint/pull/2670#issuecomment-310305721) these appear to be the least of our worries, let's merge this PR and revisit once npm addresses a few of these concerns

**Pull request merged**
