### PR TITLE
Fix `no-invalid-position-at-import-rule` false positives for `@layer`

### LINKED ISSUE #6085: [no-invalid-position-at-import-rule] Should allow `@layer` to come before `@import`
### What steps are needed to reproduce the bug?

```css
/* establish a layer order up-front, from lowest to highest priority */
@layer reset, defaults, theme, patterns, components, utilities, overrides;

@import url('colors.css') layer(theme);
```

### What Stylelint configuration is needed to reproduce the bug?

```json
{
	"no-invalid-position-at-import-rule": true,
}
```

### How did you run Stylelint?

stylelint 'src/**/*.css'

### Which version of Stylelint are you using?

`14.8.2`

### What did you expect to happen?

This is valid syntax according to the spec: https://www.w3.org/TR/css-cascade-5/#layer-empty

### What actually happened?

```
 4:1  ✖  Unexpected invalid position @import rule  no-invalid-position-at-import-rule
```

### Does the bug relate to non-standard syntax?

No

### Proposal to fix the bug

The rule should be updated to allow `@layer` to come before `@import`, and the rule's docs should be updated as well to reflect this.

### PR DESCRIPTION
**Pull request by immitsu**
> Which issue, if any, is this issue related to?

Resolve #6085 

> Is there anything in the PR that needs further explanation?

No.

### CODE REVIEW

**Review by ybiquitous — CHANGES_REQUESTED** [review]
@immitsu Thanks for creating the pull request. Almost LGTM 👍🏼 

Can you please update the doc also "ignoring `@charset`"? ⬇️ 

https://github.com/stylelint/stylelint/blob/a08312b80efa011f9302fb94d1f4de017754a19f/lib/rules/no-invalid-position-at-import-rule/README.md?plain=1#L13

**Comment by immitsu** [comment]
@ybiquitous Done!

**Review by ybiquitous — APPROVED** [review]
Thank you!

**Comment by ybiquitous** [comment]
Changelog entry added:

> Fixed: `no-invalid-position-at-import-rule` false positives for `@layer` ([#6094](https://github.com/stylelint/stylelint/pull/6094)).

**Pull request merged**
