### PR TITLE
Add failing tests for #2018

### PR DESCRIPTION
**Pull request by mxstbr**
> Which issue, if any, is this issue related to?

#2018

> Is there anything in the PR that needs further explanation?

This is just failing tests, not a solution. See #2018 for more information.

### CODE REVIEW

**Comment by davidtheclark** [comment]
Thanks for the tests @mxstbr. I should it be able to get to fixing it this weekend, if nobody beats me to it.

**Comment by davidtheclark** [comment]
@mxstbr Fixed the tests and merged them and the fix. Thanks again.

**Comment by davidtheclark** [comment]
Changelog entry:

> Fixed: media-feature-parentheses-space-inside handles comments within the parentheses.

**Comment by mxstbr** [comment]
Awesome, thanks @davidtheclark!

**Pull request merged**
