### PR TITLE
Auto-infer syntax from extension; closes #1154

### LINKED ISSUE #1154: Set option syntax based on file extension
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

We have many issue when people forget set syntax option, it is good to add this feature. For less and scss.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/33364816-set-option-syntax-based-on-file-extension?utm_campaign=plugin&utm_content=tracker%2F9282518&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F9282518&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by davidtheclark**
Addresses #1154.

This was easy to implement — the challenge is mostly in documenting the feature in all the right places. Please help out if you can by thinking if there's any better or additional way this should be documented :)

### CODE REVIEW

**Comment by davidtheclark** [comment]
Actually this is not ready for merging yet ... realized that I still needed to look into SugarSS a little bit more to find a syntax example that would cause a syntax error if the special parser is not applied ....

**Comment by davidtheclark** [comment]
Ok, I got some meaningful tests in there by exposing a "private" `_postcssResult`. I modified the JSON formatter to exclude any such fake-private properties — those beginning with `_`.

**Comment by davidtheclark** [comment]
Addresses #1154

**Comment by jeddy3** [comment]
Fantastic. Great to see this go in!

> Please help out if you can by thinking if there's any better or additional way this should be documented :)

All looks good to me.

**Pull request merged**
