### PR TITLE
api for third party utilities that run Stylelint to lookup configuration

### PR DESCRIPTION
**Pull request by gucong3000**
#provides api:
- `stylelint.buildConfig`
- `cosmiconfigOptions.cwd` exposed as `option.configLookup`

see #1882

### CODE REVIEW

**Comment by Arcanemagus** [comment]
The setting of `cosmiconfigOptions.cwd` is internal, not part of the API being exposed here.

**Comment by gucong3000** [comment]
@Arcanemagus
> The setting of cosmiconfigOptions.cwd is internal, not part of the API being exposed here.

In Atom `linter-stylelint`, we can lookup configuration file like this:
```javascript

stylelint.buildConfig({
	configLookup: dirname(filePath)
})
.then(config => {
	// get config for file in `filePath`
})
```
That's exactly as you wish.
> If Stylelint provided an API to return the configuration for a given path, this would mean that all of the third party utilities that run Stylelint can have a single source of getting a configuration, that is the same source used internally. This means everything using the API can be sure it is starting with the same configuration that Stylelint itself would be using.

**Comment by evilebottnawi** [comment]
@gucong3000 see https://github.com/stylelint/stylelint/pull/1886#issuecomment-245210031

**Comment by Arcanemagus** [comment]
@gucong3000 You've mixed parts of #1888 into this PR, you should make this PR isolated to the exposure of `buildConfig` like the title and description describe.

**Comment by Arcanemagus** [comment]
I don't think I like the approach this takes of exposing the _entire_ configuration builder, and adding an option. It would be much better if this just exposed a single function that takes a path as an argument and returns a configuration object.

**Comment by gucong3000** [comment]
mixed

**Pull request closed without merging**
