### PR TITLE
Add "css" option to --syntax parameter

### PR DESCRIPTION
**Pull request by hudochenkov**
> Which issue, if any, is this issue related to?

Needed to fix https://github.com/stylelint/stylelint-demo/issues/155.

> Is there anything in the PR that needs further explanation?

Currently there is no way to specify “css” syntax.

### CODE REVIEW

**Comment by ntwb** [comment]
This will be a breaking change requiring a _major_ release correct?

**Comment by evilebottnawi** [comment]
@ntwb no, should be as minor release

**Comment by hudochenkov** [comment]
@ntwb it will be a minor version. We add new option, it doesn't change automatic syntax detection.

**Comment by hudochenkov** [comment]
> -   Added: `css` syntax option ([#4315](https://github.com/stylelint/stylelint/pull/4315)).

**Pull request merged**
