### PR TITLE
Rule `shorthand-property-no-redundant-values` ignore some properties.

### PR DESCRIPTION
**Pull request by evilebottnawi**
/cc @davidtheclark @jeddy3

### CODE REVIEW

**Comment by davidtheclark** [comment]
LGTM

**Comment by evilebottnawi** [comment]
@danieldiekmeier merge and release?

**Comment by koistya** [comment]
Getting `Unexpected unknown unit "b5998"` in `6.4.0`

**Comment by evilebottnawi** [comment]
@koistya wait release `6.4.1`

**Comment by jeddy3** [comment]
@evilebottnawi @davidtheclark I'm releasing now.

**Comment by evilebottnawi** [comment]
@jeddy3 :tada:

**Comment by selvagsz** [comment]
Thanks @evilebottnawi for the quick fix

**Comment by evilebottnawi** [comment]
@selvagsz :cake:

**Comment by jeddy3** [comment]
[Done](https://github.com/stylelint/stylelint/releases/tag/6.4.1).

@evilebottnawi Thanks for the quick fixes!

**Pull request merged**
