### PR TITLE
docs(Plugins): add stylelint-rscss

### PR DESCRIPTION
**Pull request by rstacruz**
Thank you for all your work on stylelint!

https://github.com/rstacruz/stylelint-rscss
http://rscss.io

### CODE REVIEW

**Comment by ntwb** [comment]
Had never heard of rscss, until now 😄 

LGTM

**Comment by evilebottnawi** [comment]
LGTM
@rstacruz what about improve docs and promotion this project, very intresting

**Comment by rstacruz** [comment]
What sort of improvements would you like to see?

**Comment by evilebottnawi** [comment]
@rstacruz philosophy, and why should I use `rscss`, props, why i should not use less, scss and etc. And it was nice to see it on the main page, so that I could immediately understand the benefits.

**Comment by rstacruz** [comment]
Rscss.io has all info on it! You should use it with scss (or less, post
css, etc) actually.

**Comment by davidtheclark** [comment]
Thanks @rstacruz. I'm all for a good methodology!

**Pull request merged**
