### PR TITLE
feat: add v8-compile-cache

### PR DESCRIPTION
**Pull request by vankop**
> Which issue, if any, is this issue related to?

inspired by https://github.com/eslint/eslint/pull/11921 =)

> Is there anything in the PR that needs further explanation?

nothing

### CODE REVIEW

**Comment by jeddy3** [comment]
It would be good to get some before and after benchmarks ([like so](https://github.com/stylelint/stylelint/issues/2454#issuecomment-292794000)), so we know the benefit of this change.

**Comment by vankop** [comment]
Don't how it works exactly =)
For me 
```
time node -e "require('./bin/stylelint')"
```
after several runs `0.2s`    

For code in `master` after several runs `0.23s`
For latest npm package `0.3s`

**Comment by evilebottnawi** [comment]
Try to run `stylelint` multiple times with new `require` and without

**Comment by vankop** [comment]
@evilebottnawi something like that
```javascript
function measureRequire() {
  const t = process.hrtime();
  require("./bin/stylelint");
  console.log('stylelint: ' + process.hrtime(t)[1] / 1e+6);
}

const retry = fn => times => new Array(times).fill(0).forEach((_, i) => fn(i));

retry(measureRequire)(10);
```
???

**Comment by evilebottnawi** [comment]
Here example https://github.com/zertosh/v8-compile-cache/blob/master/bench/require-babel-core.js

**Comment by vankop** [comment]
Снимок экрана 2019-09-10 в 19 35 23

**Comment by jeddy3** [comment]
Are those the results from the PR branch or master?

**Comment by evilebottnawi** [comment]
@vankop just create suite WITH_CACHE (where true) and WITH_CACHE (where unspecific)

**Comment by vankop** [comment]
Sorry, did not understand at the beginning that I need to require code without `v8-compile-cache`

Снимок экрана 2019-09-10 в 19 56 15

**Comment by evilebottnawi** [comment]
Good perf on first run

**Comment by jeddy3** [comment]
Yep, better on first run. LGTM.

**Pull request merged**
