### PR TITLE
Add initial identity files

### PR DESCRIPTION
**Pull request by jeddy3**
I thought I'd get the ball rolling with #7 :)

The first icon you did @MoOx looked great! I'm more than happy if we go with that for twitter and github, but if you want to take a stab at refining it you can now version it :)

### CODE REVIEW

**Comment by MoOx** [comment]
pngs doesn't seems to work on github, weird.

**Comment by jeddy3** [comment]
Git was corrupting them. Added a marker to .gitattributes so it knows .png files are binary on windows.

**Comment by jeddy3** [comment]
I slightly decreased the size of the tux in the icon as it'd appear too close to the sides of the black box when the icon was scaled down in size.

**Comment by davidtheclark** [comment]
Nice work. I'm happy with using those if others are.

**Comment by davidtheclark** [comment]
Should I merge this? I'm unclear on the status.

**Comment by jeddy3** [comment]
I've merged them in as any revisions would be versioned anyway :)

**Comment by jeddy3** [comment]
It'd be great to get the Twitter avatar using the tux. Is that something either of you two have access too?

**Comment by MoOx** [comment]
Updated ;)
I think I am the only one with the twitter access for now.

**Comment by jeddy3** [comment]
Thanks! :)

**Pull request merged**
