### PR TITLE
Add stylelint-csstree-validator plugin

### PR DESCRIPTION
**Pull request by lahmatiy**

### CODE REVIEW

**Comment by ntwb** [comment]
Interesting, will have to take a look when I get some time, pretty busy this weekend.

Have you seen https://github.com/ben-eb/css-values, initial thoughts seems like there would be lots of goals in common.

Thoughts @stylelint/core?

**Comment by lahmatiy** [comment]
@ntwb Yep, I know `css-values` project. But it's currently supports just 70% (254 of 361) of properties from Mozilla's [Template:CSSData](https://developer.mozilla.org/en-US/docs/Template:CSSData) and not finished yet.
[csstree](https://github.com/csstree/csstree) supports for 100% Mozilla's dictionary + 80 additional properties ([441 in total](https://csstree.github.io/docs/syntax.html)) + fixes + vendor specific stuff + legacy and more is coming.
We also started testing by developers their CSS using [web interface](https://csstree.github.io/docs/validator.html) and first feedback is positive, it works well on real projects.

**Comment by evilebottnawi** [comment]
@lahmatiy very interesting, can you improve `README` in `csstree`. In fact, I support the idea of unions in one project (organization). We are all interested in the quality package. I think more good name is `declaration-no-invalid` (maybe include this rule in core, for me sgtm?). Also we require strong `semver` policy in `csstree`, not to break anything from other people. It would be nice write article on `habra` and promotion project.

**Comment by davidtheclark** [comment]
@lahmatiy How will csstree deal with non-standard syntax? Will it only be useful for standard CSS syntax users?

**Comment by lahmatiy** [comment]
@davidtheclark csstree is checking values according W3C specs and browser implementations. So it will fail on values that has non-standard syntax. But it may works fine for other syntaxes supported by PostCSS, since it using PostCSS AST to walk through declarations and parsing values only (for now).

@evilebottnawi Yes, documentation is on my way. Today I gave a talk about csstree and was focused on it.
> break anything from other people
It's not clear to me. Plugin based on PostCSS but cheking values of declarations. So users doesn't touch csstree API or its AST, just get warnings if something wrong with values. Probably I misunderstand something.

**Comment by evilebottnawi** [comment]
@lahmatiy http://semver.org/ see for more details

**Comment by lahmatiy** [comment]
@evilebottnawi I know about semver and how does it work. But I don't understand how it relates to plugin that doesn't expose any public API. Or you are talking about conditions to include csstree into core?
Anyway this PR is about adding link to plugin into docs page. What prevents to merge?

**Comment by davidtheclark** [comment]
I see no reason not to merge. Discussion about creating a core rule that uses CSS Tree or CSS Values can continue elsewhere.

**Comment by lahmatiy** [comment]
@davidtheclark Agree. This subject needs its own issue. It would be great if someone writes a vision of core rule and invite me and others for discussion.

**Comment by jeddy3** [comment]
> I see no reason not to merge.

Agreed.

**Comment by lahmatiy** [comment]
@jeddy3 Thank you!

**Pull request merged**
