### PR TITLE
Add autofix to property-case

### PR DESCRIPTION
**Pull request by hiroppy**
> Which issue, if any, is this issue related to?

N/A

> Is there anything in the PR that needs further explanation?

We enable fix option for `property-case`.

### CODE REVIEW

**Comment by hiroppy** [comment]
@jeddy3 updated;)

**Comment by hudochenkov** [comment]
> -   Added: `property-case` autofix ([#3448](https://github.com/stylelint/stylelint/pull/3448)).

**Comment by hudochenkov** [comment]
@hiroppy welcome to the @stylelint team! :)

**Comment by ntwb** [comment]
Welcome to the @stylelint organisation @hiroppy 🎉

**Comment by hiroppy** [comment]
@hudochenkov @ntwb Thank you for inviting to @stylelint org!
I will continue to improve stylelint:)

**Pull request merged**
