### PR TITLE
Contributing

### PR DESCRIPTION
**Pull request by jeddy3**
Continuing to get things ready for potential new contributors.

It's a very basic start, but it's something. Is it Ok?

Ref #15

### CODE REVIEW

**Comment by MoOx** [comment]
Very nice !

**Comment by MoOx** [comment]
Maybe we should add a link to #1 somewhere ?

**Comment by jeddy3** [comment]
Added to contributing.md. Done in https://github.com/stylelint/stylelint/commit/4bf6eb95df448a7ed1f2ddf9e27b141a46870e21

**Comment by MoOx** [comment]
Awesome !

**Pull request merged**
