### PR TITLE
Reorganise standalone tests

### LINKED ISSUE #727: Improve organization of non-rule tests
Right now the organization isn't always phenomenal. Like, the testing of `ignoreFiles` all happens in `standalone-test`, but the actual implementation is not part of the standalone API: it's part of the PostCSS plugin. This and other stuff could be cleaned up. 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30781943-improve-organization-of-non-rule-tests?utm_campaign=plugin&utm_content=tracker%2F9282518&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F9282518&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jeddy3**
Closes #727

The following three files:

- `extends-test`
- `ignore-test`
- `message-test`

Are named inline with `plugins-test` and `processors-test`, as all three cross between standalone and the PostCSS Plugin (as they’re more configuration object features).

Whereas, the following three files:

- `standalone-formatter-test`
- `standalone-quiet-test`
- `standalone-syntax-test`

Are testing features found only in standalone. 

This neatly reduces the original `standalone-test` to just focus on the basic use-case and errors.

Is this what you had in mind?

### CODE REVIEW

**Comment by davidtheclark** [comment]
Awesome, thanks!

**Comment by davidtheclark** [comment]
Oops, should have merged this into master ... I might cherry pick it over.

**Comment by jeddy3** [comment]
I chose `v7` because a few things were moved around in `v7`'s `standalone-test.js` for the processor feature. I figured less conflicts down the line. Should I have picked `master`?

**Comment by davidtheclark** [comment]
It should be fine, I think. I was able to merge master into v7 just a second ago.

**Pull request merged**
