### PR TITLE
Document rules that ignore @import in Less

### PR DESCRIPTION
**Pull request by jwilsson**
> Which issue, if any, is this issue related to?

#2703

> Is there anything in the PR that needs further explanation?

I think I got all of the affected rules, but an extra set of eyes would be appreciated.

### CODE REVIEW

**Comment by ntwb** [comment]
Is it worth adding some Less syntax tests to confirm `@ignore` is ignored in each of these rules?

**Comment by jeddy3** [comment]
> Is it worth adding some Less syntax tests to confirm @import is ignored in each of these rules?

I think so.

**Comment by jwilsson** [comment]
> Is it worth adding some Less syntax tests to confirm @import is ignored in each of these rules?
>
> I think so.

Do we wanna do that in the same PR or should I just create a new one with the tests?

**Comment by ntwb** [comment]
Add them to this same PR, as doing so would also confirm the existing changes here are working as intended

**Comment by jeddy3** [comment]
LGTM. I'll resolve the conflicts.

**Pull request merged**
