### PR TITLE
Chore: javascript stylistics-error.

### PR DESCRIPTION
**Pull request by evilebottnawi**
Now out build are failed after last merge. Because we update `eslint-config-stylelint` and our code have errors. @stylelint/core May be any one of us knows how to solve this problem other repositories or it is normal?

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Maybe ***ALWAYS*** rebase and tests before merging?

**Comment by m-allanson** [comment]
LGTM

**Comment by evilebottnawi** [comment]
CI Green. Nothing important. Merge

**Comment by m-allanson** [comment]
@evilebottnawi and @stylelint/core in some of the other (private) repos I work with, GitHub displays an 'Update branch' button on a Pull Request when the PR branch is out of date from the head branch. Clicking it seems to rebase the PR branch onto the head branch. 

It looks like the functionality is briefly mentioned under 'Merging out of date pull requests' here: https://github.com/blog/2137-protected-branches-improvements

Would it be useful to enable that setting for stylelint?

**Comment by evilebottnawi** [comment]
@m-allanson sgtm, I think we should try it

**Pull request merged**
