### PR TITLE
fix issue 1173

### PR DESCRIPTION
**Pull request by evilebottnawi**
https://github.com/stylelint/stylelint/issues/1173
@jeddy3 @davidtheclark

### CODE REVIEW

**Comment by davidtheclark** [comment]
Can you confirm that this fixes the particular problem mentioned in #1173? The rewriting of the rule makes sense, but I don't see any unit tests about that particular complaint.

**Comment by evilebottnawi** [comment]
@davidtheclark tomorow i think about how best write test, standard not work in this case

**Comment by evilebottnawi** [comment]
@davidtheclark i have problems with writing test, because need two report that show correcting behaviour, help me?

**Comment by davidtheclark** [comment]
Ok. Have you tried it out and know that it *does* fix the problem? We can merge without a test I think if you've confirmed that.

**Comment by evilebottnawi** [comment]
@davidtheclark i tested this problem via cli and .stylelintrc and examples in issue, also tested with other variants, all is OK. I think we can merged.

**Comment by davidtheclark** [comment]
Great.

**Pull request merged**
