### PR TITLE
Reinstate Coveralls test code coverage

### PR DESCRIPTION
**Pull request by ntwb**
Following the removal of Coveralls code coverage due to us using two test runners (Jest & Tape) now that we're only using Jest this PR reinstates the Coveralls test code coverage.

https://coveralls.io/github/stylelint/stylelint

Notes:
* The tests take ~4x longer with coverage enabled by default
 * `npm run test` without coverage `44 seconds`, with coverage `235 seconds`
 * `npm run test:jest -- --runInBand` without coverage `83 seconds`, with coverage `235 seconds`
* Coverage only covers code in `lib/`
* Creates a new Travis CI job so that there is only a single _slow_ job, rather than 3 slow jobs

_More to commits to come getting it to work on Travis CI I suspect_

### CODE REVIEW

**Comment by ntwb** [comment]
_A couple more fixes are needed here, have ran out of time today, will revisit tomorrow_

**Comment by jeddy3** [comment]
Looking good 👍

**Comment by davidtheclark** [comment]
@ntwb Did you look into Jest's built-in coverage reporting?

**Comment by ntwb** [comment]
> Did you look into Jest's built-in coverage reporting?

Indeed, this PR uses the native coverage reporting of Jest 💥 

That said, I cannot get the Travis CI to finish, runs out of memory

https://travis-ci.org/stylelint/stylelint/jobs/181581191#L303:

```shell

 PASS  lib/rules/selector-max-specificity/__tests__/index.js (6.729s)
 PASS  lib/rules/selector-pseudo-class-parentheses-space-inside/__tests__/index.js
<--- Last few GCs --->
[3344:0x4064fe0]   169508 ms: Mark-sweep 1397.7 (1535.1) -> 1397.6 (1536.1) MB, 1520.2 / 0.0 ms  allocation failure GC in old space requested
[3344:0x4064fe0]   171472 ms: Mark-sweep 1397.6 (1536.1) -> 1397.4 (1504.1) MB, 1963.9 / 0.0 ms  last resort gc 
[3344:0x4064fe0]   173032 ms: Mark-sweep 1397.4 (1504.1) -> 1397.3 (1504.1) MB, 1559.7 / 0.0 ms  last resort gc 
<--- JS stacktrace --->
==== JS stack trace =========================================
Security context: 0x113d3afc0d31 <JS Object>
    1: slowToString [buffer.js:477] [pc=0x1ded0286d049](this=0x9d52fa22a49 <an Uint8Array with map 0x18a87b01ab49>,encoding=0x113d3afc9941 <String[4]: utf8>,start=0,end=1295533)
    2: arguments adaptor frame: 1->3
    3: toString [buffer.js:~505] [pc=0x1ded021d00e1](this=0x9d52fa22a49 <an Uint8Array with map 0x18a87b01ab49>)
    4: arguments adaptor frame: 1->0
    5: readFileSync [fs.js:511] ...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x126492c [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::Factory::NewStringFromOneByte(v8::internal::Vector<unsigned char const>, v8::internal::PretenureFlag) [node]
 7: v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector<char const>, v8::internal::PretenureFlag) [node]
 8: v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::String::NewStringType, int) [node]
 9: node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding) [node]
10: void node::Buffer::StringSlice<(node::encoding)1>(v8::FunctionCallbackInfo<v8::Value> const&) [node]
11: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
12: 0xb0917c [node]
13: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
14: 0x1decfed063a7
Aborted (core dumped)
```

**Comment by ntwb** [comment]
I've just added NodeJS v4.x, v5.x & v6.x jobs for the coverage, maybe one of these will work...

Nope, the same `process out of memory` for each job

**Comment by m-allanson** [comment]
Note the comment on Jest coverage's memory requirements here https://github.com/facebook/jest/issues/2179#issuecomment-264661386

>One thing I thought could be an issue is code coverage – that definitely requires a ton of memory and at FB we had to bump the memory that node can consume.

**Comment by ntwb** [comment]
@m-allanson Thanks, I've added a job bumping NodeJS memory to 2000MB in https://github.com/stylelint/stylelint/pull/2174/commits/119b65eecba9886794d303a7f687c76dfbd0b489, lets see how that goes...

**Comment by ntwb** [comment]
Nope, out of further ideas for today....

**Comment by davidtheclark** [comment]
I am in favor of dropping Coveralls, just having a script we can run locally to check coverage.

**Comment by evilebottnawi** [comment]
@davidtheclark not good idea, few launches coverage locally, if the issue is not critical, then I can help solve it this weekend :calendar:

**Comment by ntwb** [comment]
> I am in favor of dropping Coveralls, just having a script we can run locally to check coverage.

I'll add an NPM script command for running it locally, takes ~200 seconds here on a Mid 2014 16GB MacBook:

```shell

=============================== Coverage summary ===============================
Statements   : 93.77% ( 7175/7652 )
Branches     : 88.4% ( 3141/3553 )
Functions    : 96.52% ( 1304/1351 )
Lines        : 93.83% ( 7097/7564 )
================================================================================

Test Suites: 257 passed, 257 total
Tests:       12559 passed, 12559 total
Snapshots:   0 total
Time:        210.187s
```

**Comment by jeddy3** [comment]
There [might be](https://github.com/facebook/jest/issues/2179#issuecomment-265571960) change coming from upstream that reduces the memory requirement of gathering the coverage. There's no harm in waiting to see if that lands. 

> I am in favor of dropping Coveralls,

If it doesn't land then I'm also happy with this. I think having a better developer experience (which jest provides) is more important than testing coverage within PRs.

**Comment by ntwb** [comment]
Oh, following the update to Jest `18.0.0` on of the Travis CI jobs is now passing 🎉 

I'll take a closer look on the weekend to verify and I'll clean up this PR

**Comment by evilebottnawi** [comment]
@ntwb awesome :+1:

**Comment by davidtheclark** [comment]
@ntwb Any progress on this? Should we merge or close?

**Comment by m-allanson** [comment]
@davidtheclark @ntwb I've updated this to work with the latest `master`. As mentioned in the PR intro, for now this only covers code in `lib/`.

Hmm I just noticed that unfortunately this is duplicating some of the work in #2310, I hadn't looked at that earlier.

**Comment by ntwb** [comment]
I've just updated this and to me everythings looks good, a second pair of eyes would be great 👀 

Coveralls now reappears alongside AppVeyor and Travis CI checks above:
> `coverage/coveralls — First build on jest-coverage at 93.179%`

Also at: https://coveralls.io/github/stylelint/stylelint?branch=jest-coverage

**Comment by davidtheclark** [comment]
Thanks @ntwb!

**Pull request merged**
