### PR TITLE
Fix false positives with `:nth-child` in `selector-max-specificity` rule

### LINKED ISSUE #6139: Fix TypeError regression for nth-child in selector-max-specificity
### What steps are needed to reproduce the bug?

Reproduction repo: https://github.com/Hypnosphi/stylelint-nth-child

### What Stylelint configuration is needed to reproduce the bug?

```js
module.exports = {
    rules: {
        'selector-max-specificity': ['0,2,0'],
    }
}
```

### How did you run Stylelint?

stylelint index.css

### Which version of Stylelint are you using?

`14.9.0`

### What did you expect to happen?

No errors

### What actually happened?

```
index.css
 1:1  ✖  Cannot parse selector (TypeError: Cannot read property 'nodes' of undefined)  parseError
```

### Does the bug relate to non-standard syntax?

_No response_

### Proposal to fix the bug

_No response_

### PR DESCRIPTION
**Pull request by ybiquitous**
> Which issue, if any, is this issue related to?

Closes #6139

> Is there anything in the PR that needs further explanation?

This pull request aims to fix a `TypeError` raised when parsing `:nth-child` (or `:nth-last-child`) pseudo-classes without arguments in the `selector-max-specificity` rule.

Even if the `@csstools/selector-specificity` package would be updated to parse `:nth-child` without errors (see csstools/postcss-plugins#439), please note that it's necessary Stylelint may have own logic processing `:nth-child(...)`, in order to support `<complex-selector-list>` with the `ignoreSelectors` option, e.g. `:nth-child(even of .foo)`.

See also [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child#syntax):

```
:nth-child( <nth> [ of <complex-selector-list> ]? )
```

### CODE REVIEW

**Comment by ybiquitous** [comment]
I've merged the update of `@csstools/selector-specificity` (#6143) into this branch `fix-6139`. The update can resolve `TypeError` but false positives still occur:

Input:

```json
{
  "rules": {
    "selector-max-specificity": ["0,1,0"]
  }
}
```

```css
:nth-child(odd) {}
```

Output:

```
Expected ":nth-child(odd)" to have a specificity no more than "0,1,0"
```

**Review by jeddy3 — APPROVED** [review]
LGTM, thanks! Thanks also for reporting the issue upstream.

Feel free to merge and release 14.9.1.

(I'm heading offline now for 10 days or so. As always, feel free to put out releases for any Stylelint package while I'm away.)

**Comment by ybiquitous** [comment]
@jeddy3 Thank you. I'll release a patch version today or tomorrow.

**Comment by ybiquitous** [comment]
Changelog entry added:

> - Fixed: `selector-max-specificity` false positives for `:nth-child` ([#6140](https://github.com/stylelint/stylelint/pull/6140)).

**Pull request merged**
