### PR TITLE
Add at-page support to selector-pseudo-class-no-unknown

### PR DESCRIPTION
**Pull request by evilebottnawi**
> Which issue, if any, is this issue related to?

#1871

> Is there anything in the PR that needs further explanation?

No, it's self explanatory.

If the solution is appropriate, then I will add similar logic to other rules :smile:

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@jeddy3 good, in near future i add this to another rules :smile:

**Comment by davidtheclark** [comment]
👍

**Comment by jeddy3** [comment]
> good, in near future i add this to another rules 😄

@evilebottnawi Do you want to do that in this PR? Or shall we merge this one?

**Comment by evilebottnawi** [comment]
@jeddy3 How will be better? :smile:

**Comment by jeddy3** [comment]
> @jeddy3 How will be better? 😄

I guess merging this now means the PR won't linger.

We should create new issues for the other rules you intend to update.

**Comment by evilebottnawi** [comment]
@jeddy3 good

**Comment by davidtheclark** [comment]
Added to changelog: 

> -   Fixed: `selector-pseudo-class-no-unknown` now checks `@page` at-rules and supports `@page` pseudo-classes ([#2445](https://github.com/stylelint/stylelint/pull/2445)).

**Pull request merged**
