### PR TITLE
Use dashed indents in examples of custom at-rule constructs

### PR DESCRIPTION
**Pull request by sylwia-lask**
> Which issue, if any, is this issue related to?

Ref #5523 

> Is there anything in the PR that needs further explanation?

No

### CODE REVIEW

**Review by ybiquitous — COMMENTED** [review]
@sylwia-lask Thank you for creating this PR!

In addition, there are something like a *custom* at-rule in `lib/rules/max-nesting-depth/README.md`:

https://github.com/stylelint/stylelint/blob/8a16578d0044d95546380635c2c3e116405a3094/lib/rules/max-nesting-depth/README.md#L329

https://github.com/stylelint/stylelint/blob/8a16578d0044d95546380635c2c3e116405a3094/lib/rules/max-nesting-depth/README.md#L351

Do we need to fix them too?

**Comment by sylwia-lask** [comment]
> @sylwia-lask Thank you for creating this PR!
> 
> In addition, there are something like a _custom_ at-rule in `lib/rules/max-nesting-depth/README.md`:
> 
> https://github.com/stylelint/stylelint/blob/8a16578d0044d95546380635c2c3e116405a3094/lib/rules/max-nesting-depth/README.md#L329
> 
> https://github.com/stylelint/stylelint/blob/8a16578d0044d95546380635c2c3e116405a3094/lib/rules/max-nesting-depth/README.md#L351
> 
> Do we need to fix them too?

Ah, sure we need! Thanks @ybiquitous for noticing it. I'll fix it in a couple of hours.

**Review by ybiquitous — COMMENTED** [review]
Thank you for pushing the change! It seems needed to fix the rule config example below:

```diff
-["/^my-/", "media"]
+["/^--my-/", "media"]
```

https://github.com/stylelint/stylelint/blob/9422d3e35b9e9addac90e90606a74eec72ab409f/lib/rules/max-nesting-depth/README.md#L288

**Comment by sylwia-lask** [comment]
> Thank you for pushing the change! It seems needed to fix the rule config example below:
> 
> ```diff
> -["/^my-/", "media"]
> +["/^--my-/", "media"]
> ```
> 
> https://github.com/stylelint/stylelint/blob/9422d3e35b9e9addac90e90606a74eec72ab409f/lib/rules/max-nesting-depth/README.md#L288

Thanks a million, done :)

**Review by ybiquitous — APPROVED** [review]
Thank you, LGTM! 👍🏼

**Review by jeddy3 — APPROVED** [review]
Thank you! LGTM. 

Dashed-idents can be used for other constructs too, e.g.:

```css
@--my-at-rule {
  --my-selector {
    --my-property: --my-function(10--my-unit);
  }
}
```

I've updated the original issue to be an umbrella so that we can merge this pull request as is.

**Pull request merged**
