### PR TITLE
Provide installation instructions

### PR DESCRIPTION
**Pull request by ivanoats**
It wasn't immediately clear when I discovered this package how to install it. Is it an executable, a ruby gem, a python pip package or NPM? Of course, it's npm. We should probably explicitly say that.

### CODE REVIEW

**Comment by ntwb** [comment]
@ivanoats Thanks, I think this is reasonable indeed, we've got these same instructions in the [User Guide - F.A.Q](http://stylelint.io/user-guide/faq/#how-do-i-lint-from-the-command-line) but I agree adding them to the actual CLI docs is something we should do 👍  

We, the @stylelint/core team can easily miss documenting this, _we_ know it is an NPM module, but others discovering it for the first time may not. 😄

**Comment by davidtheclark** [comment]
Agreed that this should be clear. But I think maybe it should be in the main README, not in the CLI section. After all, it applies to *every* way to use stylelint. Does that make sense? Maybe right above the Quick Start section?

**Comment by ivanoats** [comment]
I'm all for putting it in the README, too. Want a P.R.?

**Comment by davidtheclark** [comment]
Yeah, if you want to modify this one or create a new one, that would be great!

**Comment by jeddy3** [comment]
@davidtheclark I was able to look through the docs with a fresh pair of eyes this week. I'll fire over some pull requests when I'm back in a little over a week's time. One of which will clear up the installation instructions. 

I'm also heading into town this Saturday (with proper internet and a borrowed laptop). So I'll be able to review your recent PR and dip into a few issues, including some thoughts on how we can go about exposing more utils to not only stylelint plugins authors, but also 3rd party linter authors who's code we wrap (e.g. stylehacks). 

I gotta dash now though.

**Comment by jeddy3** [comment]
FYI I got back from my hols this morning. I'm going to crash soon, but I hope to make a start on this over the weekend.

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint/pull/1417

**Pull request closed without merging**
