### PR TITLE
Update to this year

### PR DESCRIPTION
**Pull request by shinnn**
Just like https://github.com/stylelint/stylelint/commit/aa5f687f681ec2e809640be3806e8be2397e4c9e

### CODE REVIEW

**Comment by jeddy3** [comment]
@ntwb Gave us a crash course in copyright law [about a month ago](https://github.com/stylelint/stylelint/pull/627). Apparently the year in the licence is suppose to be year we published the first release. So, 2015 for us.

Thanks for checking through things and suggesting amends though. Please keep them coming :)

**Comment by shinnn** [comment]
Ouch! Sorry, I didn't check the existing issues and PRs enough. Closing.

**Comment by jeddy3** [comment]
Please keep the PRs coming! I'm sure there are lots of things that _do_ need updating :)

**Comment by ntwb** [comment]
Hehehe, from watching many of these pull requests around GitHub at the start of the year quite a few are using a year range, e.g. 2015-2016 which I also believe is valid.

So something to think about as we wait for the next pull request for this same change to be made as I doubt this will be the last pull request we get for this :smirk:

**Comment by jeddy3** [comment]
> 2015-2016

Works for me :)

**Comment by ntwb** [comment]
@shinnn Do you want to update the pull request to use `2015-2016` and we'll accept that pull request?

**Comment by shinnn** [comment]
:+1:

**Comment by jeddy3** [comment]
Thanks guys. Merging now.

**Pull request merged**
