### PR TITLE
Fix end positions for `declaration-block-no-*` ("Avoid errors")

### PR DESCRIPTION
**Pull request by mattxwang**
> Which issue, if any, is this issue related to?

Part of the umbrella issue #5694.

> Is there anything in the PR that needs further explanation?

This PR contains end positions for:

* `declaration-block-no-duplicate-custom-properties`
* `declaration-block-no-duplicate-properties`
* `declaration-block-no-shorthand-property-overrides`

These are all of the rules matching `declaration-block-no-*` in the "Avoid Errors" section.

I don't mind adding support for `declaration-block-no-redundant-longhand-properties` as well (in "Enforce conventions"), though I'm a bit confused about how I would implement the start/end positions for this; what should I be highlighting? The actual shorthand (ex `margin`) doesn't appear in the code itself. Would I highlight each of the longhand properties separately?

Also, I manually did all the test cases included, though some double-checking for some of them would be nice! Pretty confident that they work as intended.

### CODE REVIEW

**Review by ybiquitous — APPROVED** [review]
LGTM, thank you.

**Comment by ybiquitous** [comment]
> I don't mind adding support for `declaration-block-no-redundant-longhand-properties` as well (in "Enforce conventions"), though I'm a bit confused about how I would implement the start/end positions for this; what should I be highlighting? The actual shorthand (ex `margin`) doesn't appear in the code itself. Would I highlight each of the longhand properties separately?

IMO, it's good to follow the current behavior. Currently, the rule warns at the start column of the last property (`margin-left` in the demo below), so it seems good that the end column also follows the last property. Any thoughts?

image

[demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdilBbJATgOYCWmAtAC4QAO8KAjDQB4DcWO+xZ5BJRAC0r0ATC3bY8hUhQBGEStVz0AzOI5TuFADYwAZsJQAWdZgC+WEABoQAZwCemSkmYJwt29fARMe-m4xJdBACAFddW2D6QJwcYNgwbUIkShIfclltCDAAa3JMCF4YKFDMKCQncizMQQqochoCWhgCVJhIhBRKMJgNC3MQMyA)

**Comment by jeddy3** [comment]
> IMO, it's good to follow the current behavior. Currently, the rule warns at the start column of the last property (margin-left in the demo below), so it seems good that the end column also follows the last property. Any thoughts?

SGTM.

**Comment by jeddy3** [comment]
> - Fixed: `declaration-block-no-*` end positions that avoid errors ([#6040](https://github.com/stylelint/stylelint/pull/6040)).

**Review by jeddy3 — COMMENTED** [review]
Looks great, thank you @mattxwang.

**Pull request merged**
