### PR TITLE
Bump postcss-jsx to 0.36.4

### LINKED ISSUE #4449: Autofix changes files without offenses
> Clearly describe the bug

when running with `--fix` stylelint generates the output that is not equal to the input even when no changes where made

> Which rule, if any, is the bug related to?

generating output with postcss

> What CSS is needed to reproduce the bug?

```js
import React from 'react'

export default () => {
  const left = 0
  const top = 0

  return (
    <div
      style={{ top, left }}
    >
      Test
    </div>
  )
}

```
> What stylelint configuration is needed to reproduce the bug?

empty config

```json
{
  "rules": {
  }
}
```

> Which version of stylelint are you using?

`stylelint@12.0.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `--fix`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, CSS-in-JS

> What did you expect to happen?

the file is not changed

> What actually happened (e.g. what warnings or errors did you get)?

```js
import React from 'react'

export default () => {
  const left = 0
  const top = 0

  return (
    <div
      style={{ top:top, left:left }}
    >
      Test
    </div>
  )
}
```

### PR DESCRIPTION
**Pull request by BPScott**
> Which issue, if any, is this issue related to?

Fixes #4449

> Is there anything in the PR that needs further explanation?

Bumps dependency to include this upstream PR (which has tests): https://github.com/gucong3000/postcss-jsx/pull/67

There's a bit of extra noice in the package-lock but that's just the result of me running `npm install` - seems something was outdated previously.

### CODE REVIEW

**Comment by BPScott** [comment]
@evilebottnawi done!

**Comment by XhmikosR** [comment]
The package-lock.json changes aren't right FYI. I'm using the latest Node.js 12.x LTS which ships with npm 6.13.4 and most of the changes you have here are reverted.

You should probably make sure you are using a newer npm version.

**Comment by XhmikosR** [comment]
And they are also reverted in dependabot's PRs, see for example https://github.com/stylelint/stylelint/pull/4553/files

**Comment by ntwb** [comment]
Create a new PR updating the lock file once all these are merged sounds like a plan

**Pull request merged**
