### PR TITLE
Util `isStandardRule` now ignore Less mixins and extends.

### PR DESCRIPTION
**Pull request by evilebottnawi**
https://github.com/stylelint/stylelint/issues/1342
Now a lot of rules(especially `selector-*` rules) not correctly.
/cc @davidtheclark @jeddy3

### CODE REVIEW

**Comment by jeddy3** [comment]
When we merge this can we use the github option to rewrite the commit message to something more descriptive? I've been doing this where I can on previous Pull Requests.

@evilebottnawi Going forward, can you use more descriptive commit messages please :)

**Comment by evilebottnawi** [comment]
@jeddy3 one second :smile:

**Comment by evilebottnawi** [comment]
@jeddy3 good?

**Comment by evilebottnawi** [comment]
i think after merge we should release new version.

**Comment by jeddy3** [comment]
Just so I'm sure. Have these rules always tripped up on this Less syntax, or has `postcss-less` change recently and it's only a recent thing?

**Comment by evilebottnawi** [comment]
@jeddy3 i think always

**Comment by jeddy3** [comment]
Ok. LGTM, but lets wait for @davidtheclark's 2nd pair of eyes as changes to the `isStandard*` rules ripple through the system.

**Comment by jeddy3** [comment]
Actually @evilebottnawi, can you please add a couple of tests to rules you think are affected by this e.g. `selector-no-combinator` and a couple of others? I'd like to be sure these tests fail, before applying this fix.

**Comment by evilebottnawi** [comment]
@jeddy3 yep

**Comment by davidtheclark** [comment]
I'm fine with this once those tests are added.

I think that only the Less parser will add `params` to a `rule` node, so this shouldn't affect other syntaxes.

**Comment by evilebottnawi** [comment]
@davidtheclark i am check only less add params

**Comment by evilebottnawi** [comment]
Strange run localy, all test ok, Now try to understand

**Pull request merged**
