### PR TITLE
Case sensitive white/blacklists and ignore* options

### LINKED ISSUE #2660: Ensure consistent case sensitivity across *-list rules and ignore* options
Ref: https://github.com/stylelint/stylelint/pull/2626#issuecomment-309861380

### PR DESCRIPTION
**Pull request by jeddy3**
Closes #2660

On further my investigation, I believe my [initial suggestion](https://github.com/stylelint/stylelint/issues/2660#issuecomment-309911294) was wrong. Having whitelist, blacklists and `ignore*: []` secondary options be case insensitive by default is too much magic. It leads to problems like https://github.com/stylelint/stylelint/issues/2647 and inconsistent behaviour (see: `comment-word-blacklist` where a case insensitive would not enable to user to allows `"TODO:` while disallowing `"todo:`). Users should _explicitly_ opt into case insensitivity by using regular expressions and the `i` flag.  This approach works well because we have all the `*-case` rules. It also means the behaviour of whitelist and blacklists and `ignore*: []` options are consistent across all rules, including `max-line-length` and `comment-word-blacklist`.

This PR enables the use of the `i` flag in regular expressions, and updates the code, tests and docs of the `*-whitelist` and `*-blacklist` rules, and any rules that have an `ignore*: []` secondary option.

This also fixes the current incorrect behaviour where users are forced to use lowercase values in black/whitelists e.g. a user no longer needs to use `function-whitelist: ["translatex"]`, they can now use the more intuitive `function-whitelist: ["translateX"]`.

### CODE REVIEW

**Comment by ntwb** [comment]
Thanks @jeddy3, quite a bit involved here, thanks 👍 

I've just tested this branch with various `/i` tests and switching case for #2647, works a treat.

_`npm run watch` with Jest tests is such a great workflow 😊_

**Comment by jeddy3** [comment]
> npm run watch with Jest tests is such a great workflow 😊

Yep! It was a big time saver whilst working on this PR. After tweaking the underlying utility I ran all tests and jotted down the failing rule names. I was then able to filter by each rule as I worked through them patching up the tests.

**Comment by ntwb** [comment]
Still a thumbs up from me

**Comment by jeddy3** [comment]
`v8`:

> -   Changed: the primary options of the `*-whitelist` & `*-blacklist` rules and the `ignore* []` secondary options are now case sensitive. Use regular expressions with the `i` flag for case insensitivity ([#2709](https://github.com/stylelint/stylelint/issues/2709)).

**Pull request merged**
