### PR TITLE
Remove function-calc-no-invalid

### PR DESCRIPTION
**Pull request by jeddy3**
> Which issue, if any, is this issue related to?

Closes https://github.com/stylelint/stylelint/issues/4731

> Is there anything in the PR that needs further explanation?

Removes one of the two [code scanning](https://github.com/stylelint/stylelint/security/code-scanning) vulnerabilities. This one is found in the generated parser code used by the rule.

This is the 2nd pull request for the `v14` branch.

Once we merged this pull request and https://github.com/stylelint/stylelint/pull/5295, we'll be able to tackle https://github.com/stylelint/stylelint/issues/5289 (removing the `syntax` option). Once that is done, I believe all the other [14.0.0 release issues](https://github.com/stylelint/stylelint/issues/5205), e.g. moving to ESM and migrating to PostCSS 8, will be unblocked and can be worked on in parallel because they shouldn't conflict with each other.

### CODE REVIEW

**Comment by ybiquitous** [comment]
> Removes one of the two [code scanning](https://github.com/stylelint/stylelint/security/code-scanning) vulnerabilities. This one is found in the generated parser code used by the rule.

@jeddy3 Can we remove `lib/utils/parseCalcExpression` also via this PR? It seems to be used only by `function-calc-no-invalid`.

**Comment by ybiquitous** [comment]
One more question: should we announce the deprecation of `function-calc-no-invalid` before releasing v14.0.0?
That is, should we release some 13.x version marking this rule as *deprecated*?

**Comment by jeddy3** [comment]
> One more question: should we announce the deprecation of function-calc-no-invalid before releasing v14.0.0?

I wasn't going to bother with a deprecation cycle. It's needless work.

**Comment by ybiquitous** [comment]
> I wasn't going to bother with a deprecation cycle. It's needless work.

Make sense. Thank you for the answer. 👍🏼

**Comment by ybiquitous** [comment]
Thanks for the commit f117326. Can we also remove the following lines?

```console
$ git grep parseCalcExpression
.eslintignore:3:lib/utils/parseCalcExpression/parser.js
.prettierignore:13:lib/utils/parseCalcExpression/parser.js
package.json:78:      "!lib/utils/parseCalcExpression/parser.js"
```

**Review by ybiquitous — APPROVED** [review]
LGTM! 🙌🏼

**Comment by jeddy3** [comment]
@ybiquitous Thanks for catching all the bits I missed!

**Review by hudochenkov — APPROVED** [review]

**Comment by jeddy3** [comment]
v14 changelog:

> - Removed: `function-calc-no-invalid` ([#5296](https://github.com/stylelint/stylelint/pull/5296)).

**Pull request merged**
