### PR TITLE
Standardise wording in rule READMEs

### PR DESCRIPTION
**Pull request by jeddy3**
Ref: https://github.com/stylelint/stylelint.io/pull/14#issuecomment-227539891

### CODE REVIEW

**Comment by Nirazul** [comment]
@jeddy3 Thanks for helping on this end!

One note - For nodes that use `<p>Given:</p>` we might need to add logic that the next pre should be ignored. Else they will be tinted green/red

**Comment by jeddy3** [comment]
> One note - For nodes that use `<p>Given:</p>` we might need to add logic that the next pre should be ignored. 

I already did that in https://github.com/stylelint/stylelint.io/commit/f38a22e9a234f1a314982d56926ae6f5d172a0ce :) It treats it as a reset.

**Comment by Nirazul** [comment]
Oh, great then :)

**Comment by ntwb** [comment]
LGTM 👍

**Pull request merged**
