### PR TITLE
Format code

### PR DESCRIPTION
**Pull request by hudochenkov**
> Which issue, if any, is this issue related to?

Follow up to https://github.com/stylelint/stylelint/pull/4259 and https://github.com/stylelint/stylelint/pull/4280. Closes https://github.com/stylelint/stylelint/issues/4246.

> Is there anything in the PR that needs further explanation?

e.g. "No, it's self explanatory."

### CODE REVIEW

**Comment by jeddy3** [comment]
Um... I'm not so sure about these now that I'm looking at the diffs in GitHub. On my MacBook screen I'm getting all sorts of weird line wrappings:

- https://github.com/stylelint/stylelint/pull/4281/files#diff-1f69085782be126b5bbc8cedfb05c700
- https://github.com/stylelint/stylelint/pull/4281/files#diff-d9fadd1d7599ae2ca9a14b5a09febba2

As @m-allanson said, a casual user is unlikely to install an extension to fix this. Even I'm unlikely to as I like to keep my extensions to a minimum.

I'm still in favour of offloading all this type of decision making to the Prettier and GitHub teams and going with their defaults. However, if the other contributors believe the pros outweigh the cons of going our own way, then happy to go with the flow.

**Comment by ntwb** [comment]
I use the [Refined GitHub](https://github.com/sindresorhus/refined-github) browser extension, it _hard codes_ the _tab_ size to 4 characters:

> https://github.com/sindresorhus/refined-github/blob/3a283ed5b3b5c42cc18a70d4c58857ab699c4978/source/features/show-whitespace.css#L17-L20

Here's the view without Refined GitHub:

NoRG


Here's the view with Refined GitHub:
RG

----

I understand that casual users are unlikely to install a browser extension to address this which is a shame_ I love _tabs_ and I love _4 character indent_ of said tabs....

But to play devils advocate for a moment, does GitHub default to _8 character indent_ for a reason, does anyone know why GitHub doesn't default to 4?

p.s I cannot recommend _Refined GitHub_ highly enough, it has so many features that make working with GitHub.com daily I'm lost without it, a vast array of productivity tips ship with it out-of-the-box, if you use GitHub every day, install the extension, you will not regret it 😃

**Comment by jeddy3** [comment]
> But to play devils advocate for a moment, does GitHub default to 8 character indent for a reason, does anyone know why GitHub doesn't default to 4?

I don't.

> p.s I cannot recommend Refined GitHub highly enough

Thanks, I've installed it and will give it a go.

I noticed a few oddities in the diffs with it.

Flat indentation for some promises:

Screenshot 2019-09-16 at 06 44 59

Indentation and line wrapping combination with:

- orphan arrows
- single space wrap
- minus one tab wrap

Screenshot 2019-09-16 at 06 51 30

---

My involvement with stylelint is mostly looking through diffs when reviewing code. Most contributors probably spend more time writing code than reviewing it, so I'm happy to defer if the authoring experience is better with these settings.

I suggest we can give these new settings ago for a couple of months. We can then have a review to see how people got on when authoring code and reviewing it. We won't know unless we give the settings a try.

**Comment by ntwb** [comment]
> Flat indentation for some promises:

Nice sleuthing, I notice that the indentation is kind of correct if you look at the number or arrows displayed, lines 12 & 16 only have 1 arrow, the surrounding lines have 2

> Indentation and line wrapping combination with:

Yeah, that line wrapping hurts my head 🤕

**Comment by ntwb** [comment]
The indentation issue is a known issue for Chrome, works correctly on Firefox:
https://github.com/sindresorhus/refined-github/issues/2421

**Comment by Arcanemagus** [comment]
> But to play devils advocate for a moment, does GitHub default to 8 character indent for a reason, does anyone know why GitHub doesn't default to 4?

Like most oddities relating to typography, the tabs being 8 characters goes all the way back to old printers:
https://en.wikipedia.org/wiki/Tab_key#Tab_characters

**Pull request merged**
