### PR TITLE
Typescript config support

### LINKED ISSUE #4940: Add support for TypeScript configuration files
> What is the problem you're trying to solve?

As many projects are adopting TypeScript as their main language, I think it would be great to have TypeScript support for stylelint configuration file.

That way, developers will be able to import TypeScript files across their codebases to customize rules in stylelint.

> What solution would you like to see?

An option to have a TypeScript file as a valid configuration file along with JavaScript configuration files.

I saw that stylelint uses `cosmiconfig` for importing configuration files and there's a TypeScript file loader for that. So I can open up a PR if you think that TS configuration files are useful for stylelint users.

### PR DESCRIPTION
**Pull request by jesusbotella**
> Which issue, if any, is this issue related to?

Closes #4940. 

> Is there anything in the PR that needs further explanation?

I think it is self-explanatory, but I have two doubts:

- Don't know where to add some more documentation about TypeScript config files (e.g., how to be able to export CommonJS for stylelint if you have another export format already, and some other issues that may appear)
- Are there any tests for configuration files? I would like to add one for TypeScript

### CODE REVIEW

**Comment by vankop** [comment]
> Are there any tests for configuration files? I would like to add one for TypeScript
Maybe system tests will help you
https://github.com/stylelint/stylelint/tree/master/system-tests

**Comment by ota-meshi** [comment]
Does this change require users to install "typescript" due to "peerDependencies" of "ts-node"?

**Comment by ota-meshi** [comment]
I think we need to add "typescript" to "dependencies" to not require the user to install it.

**Comment by hudochenkov** [comment]
> Does this change require users to install "typescript" due to "peerDependencies" of "ts-node"?
> I think we need to add "typescript" to "dependencies" to not require the user to install it.

Installing TypeScript for 99.999% of users, who don't need it is bad. Also showing peer dependency warning about it. We need different solution, probably.

**Comment by ybiquitous** [comment]
I agree with @ota-meshi and @hudochenkov. So, I suggest another solution as follows:

- Dynamic require `@endemolshinegroup/cosmiconfig-typescript-loader`. The `typescriptLoader()` function is called only when a user has own `stylelint.config.ts` file.
- Move `@endemolshinegroup/cosmiconfig-typescript-loader` from `dependencies` to `peerDependencies`.
- Add the `peerDependenciesMeta` field in order to suppress an installation warning such as:
    > npm WARN stylelint@13.7.0 requires a peer of @endemolshinegroup/cosmiconfig-typescript-loader@>=3.0.2 but none is installed. You must install peer dependencies yourself.

```diff
diff --git a/lib/createStylelint.js b/lib/createStylelint.js
index 3d0b17aa..39a6c438 100644
--- a/lib/createStylelint.js
+++ b/lib/createStylelint.js
@@ -8,9 +8,13 @@ const getPostcssResult = require('./getPostcssResult');
 const isPathIgnored = require('./isPathIgnored');
 const lintSource = require('./lintSource');
 const path = require('path');
-const typescriptLoader = require('@endemolshinegroup/cosmiconfig-typescript-loader').default;
 const { cosmiconfig } = require('cosmiconfig');
 
+const typescriptLoader = (...args) => {
+	const loader = require('@endemolshinegroup/cosmiconfig-typescript-loader').default;
+	return loader(...args);
+}
+
 const IS_TEST = process.env.NODE_ENV === 'test';
 const STOP_DIR = IS_TEST ? path.resolve(__dirname, '..') : undefined;
 
diff --git a/package.json b/package.json
index 841913d6..7510b222 100644
--- a/package.json
+++ b/package.json
@@ -110,7 +110,6 @@
     ]
   },
   "dependencies": {
-    "@endemolshinegroup/cosmiconfig-typescript-loader": "^3.0.2",
     "@stylelint/postcss-css-in-js": "^0.37.2",
     "@stylelint/postcss-markdown": "^0.36.1",
     "autoprefixer": "^9.8.6",
@@ -161,6 +160,7 @@
     "write-file-atomic": "^3.0.3"
   },
   "devDependencies": {
+    "@endemolshinegroup/cosmiconfig-typescript-loader": "^3.0.2",
     "@stylelint/prettier-config": "^2.0.0",
     "@stylelint/remark-preset": "^1.0.0",
     "@types/balanced-match": "^1.0.1",
@@ -196,6 +196,14 @@
     "remark-cli": "^8.0.1",
     "typescript": "^3.9.6"
   },
+  "peerDependencies": {
+    "@endemolshinegroup/cosmiconfig-typescript-loader": ">=3.0.2"
+  },
+  "peerDependenciesMeta": {
+    "@endemolshinegroup/cosmiconfig-typescript-loader": {
+      "optional": true
+    }
+  },
   "engines": {
     "node": ">=10.13.0"
   }
```

**Comment by jesusbotella** [comment]
Thank you for your comment @ybiquitous! I have just pushed the changes, but it seems like I need to work on this a little more because some checks are failing.

**Comment by ybiquitous** [comment]
@jesusbotella I think the following ways can resolve the errors:

> Rest parameter 'args' implicitly has an 'any[]' type.

Explicitly set the missing types as follows:

```diff
--- a/lib/createStylelint.js
+++ b/lib/createStylelint.js
@@ -10,10 +10,14 @@ const lintSource = require('./lintSource');
 const path = require('path');
 const { cosmiconfig } = require('cosmiconfig');
 
-const typescriptLoader = (...args) => {
+/**
+ * @param {string} filepath
+ * @param {string} content
+ */
+const typescriptLoader = (filepath, content) => {
 	const loader = require('@endemolshinegroup/cosmiconfig-typescript-loader').default;
 
-	return loader(...args);
+	return loader(filepath, content);
 };
 
 const IS_TEST = process.env.NODE_ENV === 'test';
```

> Cannot find module '@endemolshinegroup/cosmiconfig-typescript-loader' or its corresponding type declarations.

Add the package also to `devDependencies`:

```diff
--- a/package.json
+++ b/package.json
@@ -160,6 +160,7 @@
     "write-file-atomic": "^3.0.3"
   },
   "devDependencies": {
+    "@endemolshinegroup/cosmiconfig-typescript-loader": "^3.0.2",
     "@stylelint/prettier-config": "^2.0.0",
     "@stylelint/remark-preset": "^1.0.0",
     "@types/balanced-match": "^1.0.1",
```

**Comment by jeddy3** [comment]
Closing following discussion in https://github.com/stylelint/stylelint/issues/4940 and solution prorposed in https://github.com/stylelint/stylelint/issues/4940#issuecomment-702069412

**Pull request closed without merging**
