### PR TITLE
lookup configuration from file's path

### PR DESCRIPTION
**Pull request by gucong3000**
#1881 
continues to search configuration in these places all the way down the file tree until it finds acceptable configuration

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@gucong3000 you PR change core files, it is very important and make unexpected errors (sometimes it happens), i think this related to https://github.com/davidtheclark/cosmiconfig, not to stylelint

**Comment by evilebottnawi** [comment]
@gucong3000 we don't change this logic in `stylelint`, maybe best do this in repo above, also you can reading docs about how it is works

**Comment by gucong3000** [comment]
@evilebottnawi 
I have fully analyzed the possibility of solving this problem in repo above, which would be very difficult.
I'm pretty sure this PR is very necessary. Let's talk about it in issues. #1881

**Comment by gucong3000** [comment]
@evilebottnawi 
This problem has been bothering me for a few months. I also do a lot of analysis work.
This problem will lead to all the tools that are developed based on stylelint, which must be resolved by itself to find the configuration file.
I think this is an obvious bug stylelint
Stylelint existing configuration file to find the logic is, from the process of the directory to start to find, if not, then to the directory tree search. And bug is that the starting point of the search should be the style file where the directory, not the process where the directory.

**Comment by evilebottnawi** [comment]
@gucong3000 ok, let's wait what says @danieldiekmeier and @jeddy3, btw squash your commits in one for good review

**Comment by gucong3000** [comment]
@evilebottnawi thanks a lot!
new PR for squash commits:
#1888

**Pull request closed without merging**
