### PR TITLE
Integrate coverage and coveralls

### PR DESCRIPTION
**Pull request by evilebottnawi**
1. What do you think guys, `babel-istanbul` good choice (other solution I could not find)?
2. Should we include check coverage inside `npm test` (`npm run tape` always run with `babel-istanbul`)?

/cc @davidtheclark @jeddy3

### CODE REVIEW

**Comment by davidtheclark** [comment]
How we really have 99% test coverage? That's surprising and nice.

**Comment by davidtheclark** [comment]
I'm fine with this approach. Let's wait for @jeddy3's input, though.

**Comment by evilebottnawi** [comment]
@davidtheclark yep :)

**Comment by evilebottnawi** [comment]
for public repo we don't need .coveralls.yml with repo_token

**Comment by evilebottnawi** [comment]
Strange behaviour on node 4 and below, i try to understand

**Comment by evilebottnawi** [comment]
i don't know why it is not work on v4 and below :sob:

**Comment by ntwb** [comment]
It's only 19% coverage n my WIP PR using NYC instead of Istanbul

https://github.com/stylelint/stylelint/issues/1136#issuecomment-219397968

**Comment by evilebottnawi** [comment]
New PR https://github.com/stylelint/stylelint/pull/1279

**Pull request closed without merging**
