### PR TITLE
Improve max-line-length url() handling; fixes #605

### LINKED ISSUE #605: improve handling of url() in max-line-length
With the settings:

```json
{
  "rules": {
    "declaration-colon-space-after": "always-single-line",
    "max-line-length": 100
  }
}
```

And the code:

```css
.foo {
  background-image:
      url('url-that-is-more-than-100-chars-long');
}
```

The `declaration-colon-space-after` will throw a warning here.

### PR DESCRIPTION
**Pull request by davidtheclark**

### CODE REVIEW

**Comment by jeddy3** [comment]
Neat!

**Comment by jeddy3** [comment]
Shall I release?

**Comment by davidtheclark** [comment]
Sure!

**Comment by jeddy3** [comment]
Done.

**Pull request merged**
