### PR TITLE
Fix false positives for large/small/dynamic viewport units in unit-no-unknown

### LINKED ISSUE #5965: Fix false negatives for missing viewport units in unit-no-unknown
### What is the problem you're trying to solve?

unit-no-unknown false negatives

### What solution would you like to see?

add missing units
https://caniuse.com/viewport-unit-variants

### PR DESCRIPTION
**Pull request by Mouvedia**
> Which issue, if any, is this issue related to?

- close #5965
- ~~[#5717](https://github.com/stylelint/stylelint/pull/5717#issuecomment-991833468)~~

### CODE REVIEW

**Review by jeddy3 — CHANGES_REQUESTED** [review]
Thanks for the pull request.

Let's pull the changes for the case rule into a separate pull request.

**Review by jeddy3 — APPROVED** [review]
Thanks for pulling the changes out.

LGTM.

---

It fixes positives rather than negatives. [See demo](https://stylelint.io/demo#N4Igxg9gJgpiBcICGACYKBGAbCYDWAtAM4CWAXjPCgIwAMUAbgO4DcKAvgDoB2IANCCIBPbgBckADwTgiRfuAjcAZiQDm04DxQpOIAE4BXLDCK6qm7tu26D3EqILcIBW3idNuZlKMMwtHHnYQdiA).

**Comment by Mouvedia** [comment]
> It fixes positives rather than negatives. [See demo](https://stylelint.io/demo#N4Igxg9gJgpiBcICGACYKBGAbCYDWAtAM4CWAXjPCgIwAMUAbgO4DcKAvgDoB2IANCCIBPbgBckADwTgiRfuAjcAZiQDm04DxQpOIAE4BXLDCK6qm7tu26D3EqILcIBW3idNuZlKMMwtHHnYQdiA).

Ill fix the commit message then.

**Review by ybiquitous — APPROVED** [review]
@Mouvedia Thank you. LGTM 👍🏼

**Comment by jeddy3** [comment]
> - Fixed: `unit-no-unknown` false positives for large/small/dynamic viewport units ([#5970](https://github.com/stylelint/stylelint/pull/5970)).

**Pull request merged**
