### PR TITLE
Fix value detection when a rule is of array notation

### PR DESCRIPTION
**Pull request by kangax**

### CODE REVIEW

**Comment by kangax** [comment]
Probably needs a test but I'm short on time right now

**Comment by kangax** [comment]
(the fix definitely fixes my issue though :) so... this was at least tested empirically)

**Comment by davidtheclark** [comment]
Would you mind writing down the configuration that was causing the problem, so I can write a corresponding test?

**Comment by kangax** [comment]
```js
...
'rule-properties-order': ['alphabetical', {
    message: `
      Rules should be ordered alphabetically. It improves maintainability and
      makes for better compression.
    `,
    warn: true,
  }],
...
```

**Comment by kangax** [comment]
Basically rule-properties-order rule doesn't support array notation — there is a simple string check to determine if "alphabetical" value is passed in (not accounting for value being an array)

**Comment by davidtheclark** [comment]
@kangax: Hmmm. This shouldn't be necessary. I'll look into it soon and see if there's another bug at work. If not, I'll merge the fix here.

**Comment by davidtheclark** [comment]
I have found the bug that is causing this problem and will post a PR to fix it in one second here.

**Comment by davidtheclark** [comment]
Fixed in 5f5e180d428501085dee2b2f8ed3026e876e4529

**Pull request closed without merging**
